NDLANO/editorial-frontend

src/containers/ArticlePage/components/Comment.tsx
src/containers/ArticlePage/components/InputComment.tsx

For å få kommentarer til å ligne mer på gul lapp🌝🌼

Update background color comments

---

src/containers/StructurePage/resourceComponents/GrepCodesModal.tsx

fixes https://trello.com/c/zvluWBNC/51-fiks-grep-modal-i-strukturredigering

Fix close button grep modal

---

src/containers/WelcomePage/components/Revisions.tsx
src/containers/WelcomePage/components/worklist/ConceptListTabContent.tsx
src/containers/WelcomePage/components/worklist/SubjectDropdown.tsx

fixes [https://trello.com/c/YlzfE4Fw/50-kun-vis-utg%C3%A5tte-fag-i-subject-dropdown-n%C3%A5r-det-er-eneste-tilknytning-i-taksonomi
](https://trello.com/c/YlzfE4Fw/50-kun-vis-utg%C3%A5tte-fag-i-subject-dropdown-n%C3%A5r-det-er-eneste-tilknytning-i-taksonomi)

Position archived subjects at bottom of subject dropdown

---

src/containers/ArticlePage/components/Comment.tsx
src/containers/ArticlePage/components/InputComment.tsx

- Fikser at cursor settes først i inputfelt når man klikker (firefox)
- Oppdaterer farge på Kommenter-knapp
- Oppdaterer borderfarge

Minor updates comments

---

src/containers/NodeDiff/NodeDiff.tsx
src/containers/NodeDiff/NodeDiffContainer.tsx
src/containers/NodeDiff/diffUtils.ts

Fixes https://github.com/NDLANO/Issues/issues/3538
Gunnar hadde en fungerende fix på dette første gang han så på det, måtte bare massere TS-typene til det gikk.

Show resources diff on uppermost node in diff tree

---

src/config.ts
src/server/translate.ts

Nynodata har satt opp testmiljø som vi skal gå mot i test.
Ny bruker og token i https://github.com/NDLANO/deploy/pull/491

Use test service for test

---

cypress/e2e/Editor/versions_spec.js
src/components/Accordion/FormAccordion.tsx
src/components/Accordion/FormAccordions.tsx
src/containers/ArticlePage/FrontpageArticlePage/components/FrontpageArticlePanels.tsx
src/containers/ArticlePage/LearningResourcePage/components/LearningResourcePanels.tsx
src/containers/ArticlePage/TopicArticlePage/components/TopicArticleAccordionPanels.tsx
src/containers/ArticlePage/components/CommentSection.tsx
src/containers/ArticlePage/components/InputComment.tsx
src/containers/AudioUploader/components/AudioForm.tsx
src/containers/ConceptPage/ConceptForm/ConceptForm.tsx
src/containers/EditSubjectFrontpage/components/SubjectpageAccordionPanels.tsx
src/containers/FormikForm/VersionAndNotesPanel.tsx
src/containers/ImageUploader/components/ImageForm.tsx
src/containers/NdlaFilm/components/NdlaFilmAccordionPanels.tsx
src/containers/Podcast/components/PodcastForm.tsx
src/containers/PodcastSeries/components/PodcastSeriesForm.tsx

Tar i bruk ny accordion-komponent i alle skjemaene våre. Designet er utviklet sammen med Synne. Har et visst håp om at dette er mer uu-vennlig, og kanskje til og med raskere. Tror focus-state krever litt mer arbeid, men det blir isåfall også en jobb i frontend-packages. 
Beholder gamle accordion i versjonsloggen inntil vi får nytt design på det.

Make use of new accordion in forms

---

src/containers/WelcomePage/components/Revisions.tsx
src/containers/WelcomePage/components/TableTitle.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

fixes https://trello.com/c/X71g29nM/54-info-knapp-p%C3%A5-revisjonsblokk

Info button in revision block

---

src/components/PreviewDraft/PreviewDraft.tsx

Fix initial math render.

---

src/components/Accordion/Accordion.tsx
src/containers/App/App.tsx
src/containers/Login/Login.tsx
src/containers/StructurePage/StructureContainer.tsx
src/containers/WelcomePage/WelcomePage.tsx
src/containers/WelcomePage/components/WelcomeHeader.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Oppdaterer tekst som vises på forside når man har logget ut
I tillegg til et par småfikses:
- Skjuler lagrede søk når man er logget ut
- Lar innhold fylle hele bredden også når man er logget ut (sånn at footer ikke blir liggende midt på skjermen)
- Tilpasser header på dashbord litt bedre på små skjermer

Update logged out text

---

src/components/Dropdown/asyncDropdown/AsyncDropdown.tsx
src/containers/ArticlePage/LearningResourcePage/components/LearningResourceTaxonomy.tsx
src/containers/ArticlePage/components/ResourceTypeSelect.tsx
src/containers/StructurePage/resourceComponents/AddResourceModal.tsx

Selecten i AddResourceModal fungerte ikke helt, så skrev om til å ta i bruk ny select.

Fix search resource modal select

---

src/containers/StructurePage/folderComponents/FolderItem.tsx
src/containers/StructurePage/folderComponents/SettingsMenu.tsx
src/containers/StructurePage/folderComponents/SettingsMenuDropdownType.tsx
src/containers/StructurePage/folderComponents/sharedMenuOptions/DeleteNode.tsx

Fixes https://github.com/NDLANO/Issues/issues/3536

Remove node topic from right hand side of structure when deleting it

---

src/components/Taxonomy/ActiveTopicConnection.tsx
src/containers/ArticlePage/LearningResourcePage/components/LearningResourceTaxonomy.tsx
src/containers/ArticlePage/TopicArticlePage/components/TopicArticleTaxonomy.tsx

Må bruke korrekt verdi for å vise primærkobling.

Show primary connection in list.

---

src/containers/WelcomePage/components/worklist/SubjectDropdown.tsx

Noen små-fikser på subject dropdown i arbeidsliste

Subject dropdown: add alphabetical sorting + increase page-size

---

src/config.ts
src/server/translate.ts

Remove translate tokens from config

---

cypress/fixtures/searchSubject.json
src/containers/WelcomePage/components/worklist/SubjectDropdown.tsx

Går utifra at dette skal oppdateres i testdata også

Update aggregate-paths field to contexts.rootId

---

src/containers/StructurePage/folderComponents/sharedMenuOptions/ToggleVisibility.tsx

fixes https://github.com/NDLANO/Issues/issues/3591
Oppdaget en liten bug der det visuelt ikke ble oppdatert når man endrer synlighet på subject i strukturredigering.

Invalidate node query when visibility changes

---

src/containers/Masthead/components/NavigationMenu.tsx

Gråer ut knappene som er disablet i NavigationMenu

Add disabled styling to disabled buttons in nav menu

---

src/components/Footer/Footer.tsx
src/components/ResourcePage.tsx
src/components/SlateEditor/EditorFooter.tsx
src/constants.ts
src/containers/ArticlePage/styles.ts
src/containers/Masthead/components/SubNavigation.tsx

Flytter footer-komponent til ed, legger også til samme max-bredde som brukes på innholdet, på den måten får vi utnytter plassen bedre!

Move Footer component to ed

---

src/components/SlateEditor/plugins/blockPicker/actions.tsx
src/containers/ArticlePage/LearningResourcePage/components/LearningResourceContent.tsx

Legger til grid i vanlige artikler. Kun admin i første omgang.

Grid for admin in learningresources

---

src/containers/StructurePage/plannedResource/AddExistingResource.tsx
src/containers/StructurePage/plannedResource/PlannedResourceForm.tsx

- Skjuler ResourceType-select når man har limt inn url i inputfelt
- Legger på litt spacing på bunnen av modalen

bug-fix: do not show ResourceType select when pasted url

---

src/containers/Masthead/components/NavigationMenu.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Døper om innholds-artikkel, og flytter menyvalget til nederst i lista.

Rename content-article to about-ndla-article

---

src/components/SlateEditor/plugins/related/EditRelated.tsx
src/components/SlateEditor/plugins/related/__tests__/__snapshots__/RelatedArticleBox-test.tsx.snap

Skal fikse styling bug der modal for relatert innhold ble skjult

Bug fix: Remove absolute positioned related modal

---

src/containers/ArticlePage/components/InputComment.tsx
src/containers/StructurePage/plannedResource/PlannedResourceForm.tsx

Legger til info om hvem som har opprettet kommentaren og når den ble opprettet i kommentaren når man oppretter planlagt artikkel/emne fra strukturredigering

Add comment info text when planned article/topic is created from structure edit page

---

src/containers/StructurePage/plannedResource/PlannedResourceSelect.tsx

Fixes [#3576](https://github.com/NDLANO/Issues/issues/3576)
Legger til en `searchFrom: "any"` i Select-komponentet.

Match from anywhere in string in PlannedResourceSelect

---

src/containers/WelcomePage/components/worklist/SubjectDropdown.tsx
src/containers/WelcomePage/styles.tsx

Liten styling-fix som sette en minimumsgrense på select på dashboard

Add min-width to select

---

src/containers/WelcomePage/components/worklist/SubjectDropdown.tsx
src/containers/WelcomePage/components/worklist/WorkList.tsx
src/containers/WelcomePage/components/worklist/WorkListTabContent.tsx

Henter ids fra aggs og ikkje søkeresultat. Fikser problemet til BM.

Use aggs for fetching subjects

---

src/components/HeaderWithLanguage/HeaderInformation.tsx
src/components/HeaderWithLanguage/HeaderStatusInformation.tsx
src/components/HeaderWithLanguage/HeaderWithLanguage.tsx
src/containers/PodcastSeries/components/PodcastSeriesForm.tsx
src/containers/PodcastSeries/components/PodcastSeriesMetaData.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts
src/util/audioHelpers.ts

Legger til sjekkboks til rss-feed når man lager en ny podkast-serie eller redigerer en eksisterende serie. Når man redigerer podkast-serier bestemmer det også om rss-ikonet vises.
**Eksempel:** 
https://editorial-frontend-pr-1871.ndla.sh/media/podcast-series/7/edit/nb
Endringer blir da reflektert i 
https://ndla-frontend-pr-1419.ndla.sh/podkast/7
(etter https://github.com/NDLANO/graphql-api/pull/337 er merget)

Rss feed toggle

---

src/constants.ts
src/containers/FormikForm/components/ResponsibleSelect.tsx
src/containers/SearchPage/components/form/SearchConceptForm.tsx
src/containers/SearchPage/components/form/SearchContentForm.tsx
src/containers/StructurePage/plannedResource/PlannedResourceForm.tsx
src/containers/StructurePage/resourceComponents/ResourcesContainer.tsx

Depends on https://github.com/NDLANO/deploy/pull/505

New permission to filter by

---

src/util/subjectHelpers.ts
yarn.lock

Sets mobile banner to desktop version if empty

---

.gitignore
src/config.ts
src/index.js
src/server/server.tsx
tsconfig.json
vercel.json
yarn.lock

Denne trengte en ekstra endring sammenlignet med ndla-frontend:
Måtte skru av gzip når vi kjører på vercel :shrug:
Tilsvarer https://github.com/NDLANO/ndla-frontend/pull/1434

Fix vercel deployment

---

src/components/SlateEditor/plugins/embed/EditAudio.tsx
src/components/SlateEditor/plugins/embed/EditPodcast.tsx
src/components/SlateEditor/plugins/embed/EditVideo.tsx

fixes https://github.com/NDLANO/Issues/issues/3580

remove alt-text from audio and video

---

e2e/specs/concept.spec.ts
src/containers/Masthead/SavedSearchDropdown.tsx
src/modules/draft/draftQueries.ts

Kan testes ved å sjekke nettverksloggen

Do not fetch saved searches before opening menu

---

src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Programfag ligger under et utdanningsprogram!

Change phrases to avoid confusion with other type of subject

---

src/components/SlateEditor/plugins/mathml/BlockMenu.tsx
src/components/SlateEditor/plugins/mathml/MathEditor.tsx

Fixes https://github.com/NDLANO/Issues/issues/3640

Show edit popover when clicking math once

---

src/components/MultiButton.tsx
src/components/SaveMultiButton.tsx
src/containers/SearchPage/components/results/SearchConcept/ConceptForm.tsx

Flytter MultiButton fra frontend-packages til ED. Brukes ingen andre steder.

Move MultiButton to ed

---

src/components/MultiButton.tsx
src/components/SaveMultiButton.tsx
src/containers/ConceptPage/ConceptForm/ConceptForm.tsx

fixes https://github.com/NDLANO/Issues/issues/3644
- MultiButton dropdown legger seg bak footer
- Scrollbar skjules når man åpner dropdown (på Mac)
- Disablet lagreknapp i dropdown følger oppførsel til hovedknappen
fixes https://github.com/NDLANO/Issues/issues/3641
- Lagreknapp forblir ikke grønn for forklaringer når man lagrer

Bug fixes: MultiButton styling/functionality

---

src/components/SlateEditor/plugins/blockPicker/SlateBlockPicker.tsx
src/components/SlateEditor/plugins/blogPost/SlateBlogPost.tsx
src/components/SlateEditor/plugins/campaignBlock/SlateCampaignBlock.tsx
src/components/SlateEditor/plugins/contactBlock/SlateContactBlock.tsx
src/components/SlateEditor/plugins/keyFigure/SlateKeyFigure.tsx

De fleste nye embedene fikk buttons plassert for langt ut mot høyre. Gjorde slik at de nå aligner riktig i forhold til embeden de hører til!

Buttons follow the sizing of the embed

---

src/components/SlateEditor/plugins/embed/EditImage.tsx
src/components/SlateEditor/plugins/embed/FigureInput.tsx
src/interfaces.ts
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Avhengig av https://github.com/NDLANO/backend/pull/269

Move image border option to image instead of inlining in grid

---

src/containers/SearchPage/SearchContainer.tsx
src/containers/SearchPage/components/results/SearchList.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

fixes https://github.com/NDLANO/Issues/issues/3604
Legger til feilmelding som vises når søket feiler på søkesiden, oppdaterer også ordlyden på meldingen som vises når det ikke er noen søketreff. 
**NB**: tar gjerne innspill på formuleringene

Add search error message

---

src/components/SlateEditor/plugins/embed/SlateAudio.tsx
src/components/SlateEditor/plugins/embed/SlatePodcast.tsx

fixes https://github.com/NDLANO/Issues/issues/3645

Bug fix: add podcast/audio crash on click before finish loading

---

src/containers/StructurePage/folderComponents/sharedMenuOptions/MoveExistingNode.tsx

Passer på at parents er sletta før nye opprettes. Release fra denne branchen er deploya på staging.

Make sure old parents are deleted

---

src/components/DndList.tsx
src/constants.ts
src/containers/App/App.tsx
src/containers/FrontpageEditPage/FrontpageArticleSearch.tsx
src/containers/FrontpageEditPage/FrontpageEditPage.tsx
src/containers/FrontpageEditPage/FrontpageNode.tsx
src/containers/FrontpageEditPage/FrontpageNodeList.tsx
src/containers/FrontpageEditPage/__tests__/frontpageHelpers-test.ts
src/containers/FrontpageEditPage/frontpageHelpers.ts
src/containers/FrontpageEditPage/types.ts
src/containers/Masthead/components/NavigationMenu.tsx
src/modules/article/articleApi.ts
src/modules/article/articleQueries.ts
src/modules/frontpage/frontpageApi.ts
src/modules/frontpage/frontpageMutations.ts
src/modules/frontpage/frontpageQueries.ts
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts
src/queryKeys.ts

Er nok en del phrasing- og designkritikk som jeg fortjener å høre før denne går gjennom, men funksjonaliteten skal være på plass!
Litt usikker på navngivning generelt, da endring av "Om NDLA"-struktur og forsideartikkel strengt tatt er to forskjellige domener. Synes dog at "Endre forsideartikkel og Om NDLA-meny" blir litt vel langt.

Add support for editing front page structure

---

src/components/SlateEditor/plugins/table/SlateTable.tsx

Lik https://github.com/NDLANO/frontend-packages/pull/1780
Fjerner bare font størrelsen og stylingen slik at innholdet i editoren blir likere previewen!

Added specific styling to lists in table

---

src/components/SlateEditor/PlainTextEditor.tsx
src/components/SlateEditor/RichTextEditor.tsx
src/components/SlateEditor/plugins/grid/__tests__/normalizer-test.ts
src/containers/ArticlePage/FrontpageArticlePage/components/FrontpageArticleFormContent.tsx
src/containers/ArticlePage/LearningResourcePage/components/LearningResourceContent.tsx
src/containers/ArticlePage/LearningResourcePage/components/LearningResourceForm.tsx
src/containers/ArticlePage/LearningResourcePage/components/LearningResourcePanels.tsx
src/containers/ArticlePage/TopicArticlePage/components/TopicArticleContent.tsx
src/containers/AudioUploader/components/AudioContent.tsx
src/containers/AudioUploader/components/AudioForm.tsx
src/containers/ConceptPage/ConceptForm/ConceptForm.tsx
src/containers/ConceptPage/components/ConceptContent.tsx
src/containers/EditSubjectFrontpage/components/SubjectpageAbout.tsx
src/containers/EditSubjectFrontpage/components/SubjectpageAccordionPanels.tsx
src/containers/EditSubjectFrontpage/components/SubjectpageForm.tsx
src/containers/FormikForm/IngressField.tsx
src/containers/FormikForm/TitleField.tsx
src/containers/ImageUploader/components/ImageContent.tsx
src/containers/ImageUploader/components/ImageForm.tsx
src/containers/NdlaFilm/components/NdlaFilmAccordionPanels.tsx
src/containers/NdlaFilm/components/NdlaFilmForm.tsx
src/containers/Podcast/components/PodcastForm.tsx
src/containers/PodcastSeries/components/PodcastSeriesForm.tsx
src/containers/PodcastSeries/components/PodcastSeriesMetaData.tsx

Formik er ikke bygget for å gjøre ting enkelt. Dersom et skjema ikke validerer uten feil vil et skjema aldri submittes. Vi må derfor omgå den innebygde submit-funksjonen mer eller mindre overalt.

Allow saving invalid learning resource forms

---

src/containers/Masthead/components/Navigation.tsx

Fixes https://github.com/NDLANO/Issues/issues/3694

Reload page on logo click

---

src/containers/StructurePage/folderComponents/FolderItem.tsx
src/containers/StructurePage/folderComponents/SettingsMenu.tsx
src/containers/StructurePage/resourceComponents/ResourceBanner.tsx

Oppdaterer styling til knappene for å legge til ressurs og emne, legger til tooltip på hover og at bakgrunn vises for å bedre indikere at det er knapper.
Syntes ikke det virker som at det er issues knyttet til å wrappe `ModalTrigger` med `Tooltip`, men gjerne se at det ser greit ut!

Improve button styling for add resource button and add topic button

---

src/components/SlateEditor/plugins/embed/SlateVideo.tsx
src/components/Taxonomy/ActiveTopicConnection.tsx
src/components/Taxonomy/ActiveTopicConnections.tsx

Gjør det mulig å slette siste plassering en ressurs finnes i fra taksonomiblokka. Det går ikkje an å lagre etterpå, men om artikkelen f.eks er sletta er ikkje det et problem.

Allow delete last placement

---

src/containers/AudioUploader/components/AudioForm.tsx
src/containers/FormikForm/MetaImageSearch.tsx
src/containers/ImageUploader/components/ImageForm.tsx
src/containers/Podcast/components/PodcastForm.tsx
src/containers/PodcastSeries/components/PodcastSeriesForm.tsx

Harmoniserer bredden på bokser på tvers av skjema.

Make all boxes, sans content, wider

---

src/server/contentSecurityPolicy.ts

https://github.com/NDLANO/Issues/issues/3710

Remove hotjar

---

src/components/SlateEditor/plugins/blockPicker/SlateBlockPicker.tsx
src/components/SlateEditor/plugins/table/slateHelpers.ts
src/containers/ArticlePage/FrontpageArticlePage/components/FrontpageArticleFormContent.tsx
src/containers/ArticlePage/LearningResourcePage/components/LearningResourceContent.tsx

added image as only viable selection in table header as it is in table cell

For mange blockpicker valg i header tabell

---

src/components/PreviewDraft/PreviewDraftLightboxV2.tsx

Fixes https://github.com/NDLANO/Issues/issues/3718

Set article type in preview version

---

src/containers/StructurePage/plannedResource/PlannedResourceForm.tsx

Fixes https://github.com/NDLANO/Issues/issues/3721

Create both resources types when adding new resource

---

src/containers/StructurePage/folderComponents/FolderItem.tsx
src/containers/StructurePage/resourceComponents/ResourceBanner.tsx

Fixes https://github.com/NDLANO/Issues/issues/3661

Fix focus issue in add resource modal

---

src/components/SlateEditor/plugins/blogPost/BlogPostForm.tsx
src/components/SlateEditor/plugins/campaignBlock/CampaignBlockForm.tsx
src/i18n2.ts

Må kunne sette se som språkkode på disse komponentene

Support se for frontpage-components

---

src/components/SlateEditor/plugins/related/RelatedArticleBox.tsx

https://trello.com/c/8A2GKOMK/435-endre-urler-i-relaterte-artikler-i-ed
Fixes https://github.com/NDLANO/Issues/issues/3728

Use ED links in related content embed

---

src/containers/ConceptPage/ConceptForm/ConceptForm.tsx
src/containers/ConceptPage/components/ConceptContent.tsx

Kom frem på møtet i stad at de ikke ønsker at beskrivelse skal vises for gloser

Remove gloss conceptContent 

---

src/components/SlateEditor/EditorFooter.tsx

Remove FooterLinkButton usage

---

src/containers/ConceptPage/components/ConceptContent.tsx
src/containers/FormikForm/components/VisualElementField.tsx

Kom frem på møtet i går at navngivning her skal oppdateres for gloser, vet ikke om vi burde vise `HowToHelper` for lydfil og?

Update gloss audio element naming

---

src/containers/ConceptPage/ConceptForm/ConceptForm.tsx

Fikser opp i oversettelse for når man oppretter ny forklaring/glose:

Use conceptType for ConceptCopyright translations

---

src/components/HeaderWithLanguage/HeaderStatusInformation.tsx
src/containers/SearchPage/components/results/SearchConcept/ContentView.tsx
src/containers/SearchPage/components/results/SearchContent.tsx

Fixes https://github.com/NDLANO/Issues/issues/3731

Fix undefined published links in search for content and concepts

---

src/components/HeaderWithLanguage/HeaderStatusInformation.tsx
src/components/HeaderWithLanguage/HeaderWithLanguage.tsx

Fixes https://github.com/NDLANO/Issues/issues/3743

Disable delete button in header when something is used in other articles

---

src/containers/TaxonomyVersions/TaxonomyVersionsPage.tsx

Mikrofiks. Har irritert meg over at disse ikkje er sorterte.
Test:
Sjekk sida med taksonomiversjoner og sjå at dei kjem i samme rekkefølge kvar gong, også om du endrer på en av dei.

Sorts versions based on created

---

src/components/H5PElement/H5PElement.tsx
src/components/SlateEditor/helpers.ts
src/components/SlateEditor/interfaces.ts
src/components/SlateEditor/plugins/blockPicker/SlateBlockPicker.tsx
src/components/SlateEditor/plugins/blockPicker/actions.tsx
src/components/SlateEditor/plugins/embed/SlateFigure.tsx
src/components/SlateEditor/plugins/embed/__tests__/normalizer-test.ts
src/components/SlateEditor/plugins/embed/__tests__/serializer-test.ts
src/components/SlateEditor/plugins/embed/index.tsx
src/components/SlateEditor/plugins/embed/types.ts
src/components/SlateEditor/plugins/embed/utils.ts
src/components/SlateEditor/plugins/h5p/SlateH5p.tsx
src/components/SlateEditor/plugins/h5p/index.tsx
src/components/SlateEditor/plugins/h5p/types.ts
src/components/SlateEditor/plugins/h5p/utils.ts
src/components/SlateEditor/utils/normalizationHelpers.ts
src/containers/ArticlePage/FrontpageArticlePage/components/FrontpageArticleFormContent.tsx
src/containers/ArticlePage/LearningResourcePage/components/LearningResourceContent.tsx
src/containers/VisualElement/VisualElement.tsx
src/containers/VisualElement/VisualElementMenu.tsx
src/containers/VisualElement/VisualElementPicker.tsx
src/containers/VisualElement/VisualElementSearch.tsx
src/interfaces.ts
src/modules/embed/embedApi.ts
src/modules/embed/queries.ts
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts
src/util/articleContentConverter.tsx
src/util/formHelper.ts

Fixes https://github.com/NDLANO/Issues/issues/3744
Tror det er en del mer kode som kan forsvinne, men mistenker at det er tryggere å ta det når vi er helt borte fra de gamle embed-tingene.

Use H5pEmbed in Slate

---

src/containers/StructurePage/resourceComponents/ResourceBanner.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

fixes https://github.com/NDLANO/Issues/issues/3745

Show workflow count in ResourceBanner

---

src/containers/ArticlePage/LearningResourcePage/components/LearningResourceTaxonomy.tsx
src/containers/ArticlePage/TopicArticlePage/components/TopicArticleTaxonomy.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

fixes https://github.com/NDLANO/Issues/issues/3753
Legger til advarsel i taksonomiblokk om at endringer krever delpublisering.

Add taxonomy warning

---

src/components/SlateEditor/plugins/blockPicker/SlateBlockPicker.tsx
src/components/SlateEditor/plugins/blockPicker/index.ts
src/components/SlateEditor/plugins/toolbar/ToolbarButton.tsx
src/constants.ts
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Fixes https://github.com/NDLANO/Issues/issues/3767
Burde kanskje vise frem hotkeyen et sted, men hvor? Inne i blokkvelgeren?

Add hotkey MOD+Enter to open block picker

---

package.json
yarn.lock

Kan testes ved å sjekke at `window.config` serialiseres til det samme som før

Bump serialize-javascript

---

e2e/specs/blockpicker_learning_resource.spec.ts
package.json
yarn.lock

De har gjort endringer til UI-modus som gjør det veldig mye enklere å se om en request er mocket eller ikke. Dette gjør livet mitt veldig mye enklere

Bump playwright for QoL improvements

---

e2e/specs/taxonomy.spec.ts
src/containers/Masthead/components/NavigationMenu.tsx
src/containers/StructurePage/NodeItem.tsx
src/containers/StructurePage/folderComponents/sharedMenuOptions/RequestNodePublish.tsx

Fixes NDLANO/Issues#3751
Viser ikon om at emne er bedt om delpublisering

Bruker cloud-ikon for å markere publisering

---

src/components/SlateEditor/EditorFooter.tsx

fixes https://github.com/NDLANO/Issues/issues/3770

Update prioritized toggle 

---

src/components/HeaderWithLanguage/HeaderInformation.tsx
src/components/HeaderWithLanguage/HeaderStatusInformation.tsx
src/components/HeaderWithLanguage/HeaderWithLanguage.tsx

Fixes https://github.com/NDLANO/Issues/issues/3773

Use slug for published frontpage articles

---

src/containers/PublishRequests/PublishRequestsContainer.tsx
src/containers/WelcomePage/components/LastUsedItems.tsx
src/containers/WelcomePage/components/Revisions.tsx
src/containers/WelcomePage/components/worklist/WorkList.tsx

It can be a derived value instead

Remove onSuccess and onError callbacks used for setting simple errors.

---

src/containers/FormikForm/components/ProcessedField.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Fixes https://github.com/NDLANO/Issues/issues/3779

Disable processed checkbox when origin is not set

---

src/containers/ArticlePage/LearningResourcePage/components/LearningResourceTaxonomy.tsx
src/containers/ArticlePage/LearningResourcePage/components/taxonomy/TaxonomyBlock.tsx
src/containers/ArticlePage/LearningResourcePage/components/taxonomy/TaxonomyInfo.tsx
src/containers/ArticlePage/TopicArticlePage/components/TopicArticleTaxonomy.tsx
src/containers/ArticlePage/TopicArticlePage/components/TopicTaxonomyBlock.tsx
src/modules/taxonomy/taxonomyApi.ts

Dette fikser også en feil som oppsto på koblinger når man byttet mellom forskjellige tax-versjoner.

Prepare taxonomy block for react query v5. 

---

src/containers/ConceptPage/CreateConcept.tsx
src/containers/GlossPage/CreateGloss.tsx

Så tittel vises på fanen når man oppretter ny forklaring/glose

Update HelmetWithTracker title

---

e2e/specs/rich_block_text_editor.spec.ts
src/containers/FormikForm/articleFormHooks.ts
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Reverts NDLANO/editorial-frontend#2044
Kom frem på møtet i dag at de ikke ønsker denne funksjonaliteten likevel! De vil heller fokusere på å vise dette tydeligere i strukturredigering der det er endringer og delpublisering trengs

Revert "Add warning on save when title is updated and the article is published"

---

src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

relates to https://github.com/NDLANO/backend/pull/325

Add translations for republish status

---

src/phrases/phrases-nn.ts

Ref https://trello.com/c/zEX5dXKW/436-progresjonsvisning-fag, de ønsket 'bygger' også på nynorsk, ikke 'byggjer'

Changing buildsOn nn translation

---

src/containers/AudioUploader/components/AudioCopyright.tsx
src/containers/AudioUploader/components/AudioForm.tsx
src/containers/AudioUploader/components/AudioMetaData.tsx
src/containers/FormikForm/components/ProcessedField.tsx
src/containers/ImageUploader/components/ImageCopyright.tsx

Delt opp metadatablokk for opplastning av lyd, ref https://github.com/NDLANO/Issues/issues/3796

Moved copyright-content to separate accordion and component

---

.github/workflows/ci.yml
Dockerfile
package.json

Sikkerhetsoppdatering. Funker fint å kjøre lokalt via docker.

Bump node to 18.18

---

src/containers/Masthead/SavedSearchDropdown.tsx

Fixes https://github.com/NDLANO/Issues/issues/3772

Open search with slash

---

e2e/auth.setup.ts
package.json
src/util/jwtHelper.ts
yarn.lock

Ikkke så veldig breaking. Sjekk at du får logget inn og ut.

Bump jwt-decode to 4.0

---

e2e/specs/versions.spec.ts

Ironisk at en annen test feiler her, men versjoner ser hvertfall ut til å funke

Fix version flake

---

src/components/HeaderWithLanguage/DeleteLanguageVersion.tsx
src/components/HeaderWithLanguage/HeaderActions.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

fixes https://github.com/NDLANO/Issues/issues/3774
Forslag til hvordan det kan se ut hvertfall!

Add version comparer to article header

---

src/constants.ts
src/containers/ArticlePage/articleTransformers.ts
src/containers/FormikForm/AddRevisionDateField.tsx
src/containers/WelcomePage/components/Revisions.tsx

Løser https://github.com/NDLANO/Issues/issues/3800

Add expiration icon for revisions

---

src/containers/WelcomePage/components/worklist/WorkListTabContent.tsx

Lot merke til at ikke prioritert-ikonet var sentrert i arbeidslista, denne fikser!

Center icons in worklist vertically

---

src/containers/ArticlePage/TopicArticlePage/components/TopicArticleContent.tsx

Fjerner advarsel som ble vist i konsollen på emner!

Update active styling for MarkdownButton using data attribute

---

src/containers/Podcast/components/PodcastForm.tsx

Add missing license block

---

src/components/HeaderWithLanguage/DeleteLanguageVersion.tsx

Nok en plass vi har glømt å endre sjekk på type.

Add possibility to delete gloss language

---

src/components/PreviewDraft/PreviewDraftLightboxV2.tsx

Fixes https://github.com/NDLANO/Issues/issues/3808
Aligns the content to the center, with some margin.

Better alignment when comparing article versions

---

src/components/SlateEditor/plugins/related/EditRelated.tsx

Fixes https://github.com/NDLANO/Issues/issues/3818, same way as the front page search.

Adjusting dropdown height based on window height

---

src/containers/Masthead/components/NavigationMenu.tsx

Fikser styling på Opprett læringsressurs/Opprett emne i NavigationMenu til å være disablet

Fix disabled styling in NavigationMenu

---

src/containers/Masthead/components/NavigationMenu.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Fikk avklart at disse menyvalgene nå kan fjernes

Remove unused navigation menu options to create resources

---

src/components/SlateEditor/plugins/table/matrix.ts

Vra en commit som ikke ble pusha 🥇

Needs to be greater or equal

---

src/containers/WelcomePage/components/worklist/WorkList.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

- Oppdaterer placeholder-tekst på select for å velge prioritet
- Endrer rekkefølge på faner i arbeidsliste sånn at parkerte er plassert ved siden av ressurser

Minor worklist/priority fixes

---

package.json
src/containers/FormikForm/components/ElementList.tsx
src/containers/FormikForm/components/ElementListItem.tsx
src/containers/NdlaFilm/components/NdlaFilmAccordionPanels.tsx
src/containers/NdlaFilm/components/NdlaFilmArticle.tsx
src/containers/NdlaFilm/components/NdlaFilmForm.tsx
src/containers/NdlaFilm/components/ThemeEditor.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts
src/util/ndlaFilmHelpers.ts
yarn.lock

https://github.com/NDLANO/Issues/issues/3821
Legger til støtte for å sette og fjerne ekstra informasjonsartikkel

3821 information article

---

src/components/SlateEditor/plugins/related/EditRelated.tsx

Tror vi ganske trygt kan fjerne denne scss'en snart

Replace related title scss component with heading component

---

src/components/PreviewDraft/PreviewDraft.tsx
src/containers/FormikForm/IngressField.tsx

https://trello.com/c/7mTmyox9/586-feil-i-ingress-n%C3%A5r-ingress-starter-med-nummer

Inline parse ingress fields

---

src/components/Taxonomy/TaxonomyLightbox.tsx
src/containers/StructurePage/plannedResource/AddExistingResource.tsx
src/containers/StructurePage/plannedResource/PlannedResourceForm.tsx
src/containers/StructurePage/resourceComponents/ResourceBanner.tsx

fixes https://github.com/NDLANO/Issues/issues/3847
Skriver om modal for å legge til ny ressurs i strukturredigering til å ta i bruk tabs i stedet for en lang modal med scroll!

Refactor add resource modal to use tabs instead of scroll

---

src/components/SlateEditor/plugins/footnote/render.tsx
src/containers/ArticlePage/LearningResourcePage/components/LearningResourceFootnotes.tsx

Vi rendret visst ikke fotnoter. Erstattet også klassenavn med emotion

Fix footnote rendering. Remove footnote class names

---

src/components/PreviewDraft/PreviewDraft.tsx

https://github.com/NDLANO/Issues/issues/3856

Set 'no' when article langage is 'nb' for improved accessibility

---

package.json
src/components/ControlledImageSearchAndUploader.tsx
src/containers/FormikForm/MetaImageSearch.tsx
src/containers/Podcast/components/PodcastMetaData.tsx
src/containers/PodcastSeries/components/PodcastSeriesMetaData.tsx
src/modules/image/imageApiInterfaces.ts
yarn.lock

Fixes https://github.com/NDLANO/Issues/issues/2814 (with https://github.com/NDLANO/backend/pull/351)
ToDo:
- Update backendtypes ++

Sending extra attribute to the image search for podcast pictures

---

src/containers/WelcomePage/components/LMASubjects.tsx

https://trello.com/c/ZR8931HC/646-produksjonsflyt-i-lma-fag

Filter on selected subject LMA block

---

src/constants.ts
src/containers/StructurePage/StructureBanner.tsx
src/containers/StructurePage/StructureContainer.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

fixes https://github.com/NDLANO/Issues/issues/3894

Add lma-subjects filter toggle to structure edit

---

src/constants.ts
src/containers/FormikForm/formikDraftHooks.ts
src/containers/StructurePage/plannedResource/PlannedResourceForm.tsx

Såg på slack noen som ønska å øke grensa på sist redigerte. Dette gjør det i det minste lett å endre i neste omgang.

Make last edited cutoff configurable

---

src/components/PreviewDraft/PreviewDraft.tsx
src/containers/FormikForm/IngressField.tsx

Lar markdown støtte linjeskift i ingress.

Support newlines in introduction

---

src/containers/Masthead/components/Navigation.tsx

https://trello.com/c/wOJOXHoA/112-2-lenker-inn-p%C3%A5-dashboard
Venter med å ta inn denne til jeg får dobbeltsjekket utseende med NDLA

Add links to header

---

src/components/DisplayEmbed/DisplayExternal.tsx
src/components/DisplayEmbed/__tests__/__snapshots__/DisplayExternal-test.jsx.snap
src/components/SlateEditor/plugins/audio/SlateAudio.tsx
src/components/SlateEditor/plugins/campaignBlock/SlateCampaignBlock.tsx
src/components/SlateEditor/plugins/contactBlock/SlateContactBlock.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Endrer tekster litt slik at det blir litt meir konsistent kvar vi bruker slett og fjern.

Meir konsistent plassering av redigeringsknapper i artikkel

---

src/components/SlateEditor/plugins/blockPicker/SlateBlockPicker.tsx

Forgot another one

---

src/containers/FormikForm/MetaImageSearch.tsx
src/containers/Podcast/components/PodcastMetaData.tsx
src/containers/PodcastSeries/components/PodcastSeriesMetaData.tsx

NDLANO/Issues#3914
Fjerner mulighet for å redigere alt-tekst

Disable alt-editing

---

src/containers/WelcomePage/components/ArticleStatusContent.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

fixes https://github.com/NDLANO/Issues/issues/3915

Add sum to lma/favorites block

---

src/containers/WelcomePage/components/LastUsedItems.tsx
src/containers/WelcomePage/components/Revisions.tsx
src/containers/WelcomePage/components/worklist/WorkList.tsx

Resetter page når pageSize endres

Reset page when pageSize changes

---

src/components/SlateEditor/plugins/aside/SlateRightAside.tsx

Justering Z-index

---

src/containers/NodeDiff/NodeDiffContainer.tsx

Fikser varselet vite ga oss beskjed om

Check both conditions when filtering diff nodes

---

src/components/PreviewDraft/PreviewConcept.tsx
src/components/PreviewDraft/PreviewDraft.tsx
src/containers/FormikForm/IngressField.tsx
src/util/parseMarkdown.ts

Samme oppsett som graphql-api.
Test: sjekk at /subject-matter/learning-resource/35799/edit/nb vises korrekt både med markdownknapp og forhåndsvisning.

Støtte for linjeskift men ikkje liste i ingress

---

package.json
yarn.lock

Bump typescript to 5.3

---

src/containers/WelcomePage/components/ArticleStatusContent.tsx

Liten fiks for å tilpasse kolonne-bredde litt bedre i produksjonsflyt-blokken

Better adjust ArticleStatusContent column widths

---

src/components/HeaderWithLanguage/HeaderActions.tsx

Kun nn og nb skal kunne settes på gloss.

Only norwegian for gloss

---

src/components/SlateEditor/plugins/details/index.tsx

Fixes https://github.com/NDLANO/Issues/issues/3937
Ikke nødvendigvis den riktigste måten å løse det på. Men ser ut til å fungere.

Fix language labels in detail summaries

---

src/components/HeaderWithLanguage/HeaderInformation.tsx
src/components/LastUpdatedLine/LastUpdatedLine.tsx
src/containers/ConceptPage/CreateConcept.tsx
src/containers/ConceptPage/components/ConceptContent.tsx
src/containers/SearchPage/components/results/SearchConcept.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Var visst litt kjapp med hotfixen min i går.

Skiller mellom artikkel og forklaring på sist oppdatert

---

src/containers/WelcomePage/components/worklist/ConceptListTabContent.tsx
src/containers/WelcomePage/components/worklist/WorkListTabContent.tsx
src/modules/concept/conceptApiInterfaces.ts

frontendbiten av denne: https://github.com/NDLANO/backend/pull/376
I tillegg til litt opprydning!
For å teste: Sjekk at oppførsel for forklaringer i arbeidsliste fortsatt fungerer sånn det skal/riktig data vises

Use new aggregate-paths query-param for concepts

---

package.json
src/components/HeaderWithLanguage/HeaderFavoriteStatus.tsx
src/components/HeaderWithLanguage/HeaderStatusInformation.tsx
src/containers/ArticlePage/LearningResourcePage/components/taxonomy/TaxonomyBlock.tsx
src/containers/ArticlePage/TopicArticlePage/components/TopicTaxonomyBlock.tsx
src/containers/ConceptPage/conceptTransformers.ts
src/containers/EditMarkupPage/EditMarkupPage.tsx
src/containers/StructurePage/folderComponents/topicMenuOptions/SwapTopicArticle.tsx
src/containers/StructurePage/plannedResource/PlannedResourceForm.tsx
src/containers/StructurePage/resourceComponents/GrepCodesModal.tsx
src/modules/myndla/myndlaApi.ts
src/modules/myndla/myndlaQueries.ts
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts
src/queryKeys.ts
yarn.lock

Fixes NDLANO/Issues#3943
Depends on https://github.com/NDLANO/backend/pull/391
Etter backenden har blitt litt oppdatert så måtte jeg ha med `undefined` på noen felter som tidligere var optional.
Vet ikke om vi kommer oss rundt det fra backend-siden helt ennå så tror vi må tåle litt teite `undefined` enn så lenge.

#3943: Add icon to indicate favorite-markings to HeaderStatusInformation

---

src/components/SlateEditor/plugins/toolbar/SlateToolbar.tsx
src/components/SlateEditor/plugins/toolbar/ToolbarLanguageOptions.tsx
src/components/SlateEditor/plugins/toolbar/toolbarDropdownComponents.tsx

Fixes https://github.com/NDLANO/Issues/issues/3942
Kunne kanskje håndtert noen av de nummererte verdiene bedre.

Fix language dropdown

---

src/components/SlateEditor/plugins/toolbar/ToolbarLanguageOptions.tsx

Fixes https://github.com/NDLANO/Issues/issues/3952

Fix an issue that occurred when a word that already contains a language attempts to insert a new language with a larger word selection

---

src/components/SlateEditor/plugins/toolbar/SlateToolbar.tsx

Fixes https://github.com/NDLANO/Issues/issues/3960

Reduce toolbar z-index to avoid toolbar being shown in modals

---

src/components/Accordion/FormAccordion.tsx
src/components/SlateEditor/RichTextEditor.tsx
src/components/SlateEditor/plugins/embed/EditVideo.tsx
src/components/SlateEditor/plugins/embed/SlateVideo.tsx
src/components/SlateEditor/plugins/toolbar/SlateToolbar.tsx
src/containers/FormikForm/InlineField.tsx

https://github.com/NDLANO/Issues/issues/3945
Litt redd for å se hvor bra/dårlig dette funker med kommentarer. Det er noe ordentlig herk å plassere toolbaren. 
Etter dette gjenstår egentlig bare bilde-captions, men lurer på om det er lurt å refaktorere hele image-embeden før den tid kommer.

Create an InlineField. Make Toolbar work without a portal to allow for placing it in modals

---

src/components/HeaderWithLanguage/HeaderActions.tsx
src/components/HeaderWithLanguage/util.ts
src/components/SlateEditor/EditorFooter.tsx
src/containers/ArticlePage/FrontpageArticlePage/components/FrontpageArticleForm.tsx
src/containers/ArticlePage/LearningResourcePage/components/LearningResourceForm.tsx
src/containers/ArticlePage/TopicArticlePage/components/TopicArticleForm.tsx

Fixes https://github.com/NDLANO/Issues/issues/3959

Bokmål / Nynorsk toggle in editor toolbar

---

src/components/SlateEditor/plugins/definitionList/handlers/onEnter.ts
src/components/SlateEditor/plugins/heading/index.tsx
src/components/SlateEditor/plugins/list/handlers/onEnter.ts
src/components/SlateEditor/plugins/paragraph/index.tsx
src/components/SlateEditor/plugins/paragraph/utils.ts
src/components/SlateEditor/plugins/section/__tests__/normalizer-test.ts
src/components/SlateEditor/plugins/section/index.tsx

fixes https://github.com/NDLANO/Issues/issues/3958
Ser ut som en return ble korta ned i en commit.

Return next event instead of undefined

---

src/components/SlateEditor/plugins/link/EditLink.tsx
src/components/SlateEditor/plugins/link/Link.tsx

fixes https://github.com/NDLANO/Issues/issues/3962
Tok å lånte logikk fra inlineconcept, ser ut til å fungere betre!

HandleSelectionChange now is the same as in inlineconcept

---

src/components/HeaderWithLanguage/HeaderActions.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Fixes https://github.com/NDLANO/Issues/issues/3964

Disable comparing with published version if the 2 versions are identical

---

e2e/specs/math.spec.ts
e2e/specs/toolbar.spec.ts
package.json
yarn.lock

Bumper playwright. Ser ut som at denne gjorde slik at testene kjører fint for meg igjen så tipper det gjør det for andre også!!
Hugs å oppdatere browser!!

Updated playwright and removed deprecated type usage

---

package.json
src/components/ControlledImageSearchAndUploader.tsx
src/containers/ImageUploader/components/ImageForm.tsx
yarn.lock

Greit å få inn!
Dette er egentlig bare denne commiten: https://github.com/NDLANO/editorial-frontend/pull/2259/commits/559e25d0df450addbece9d55fbefbe90f3140c7e (kunne sikkert cherry-picket den istedet, men fjerner den commiten fra den andre branchen når denne tas inn)

Bump backend types

---

src/style/form.css
src/style/index.css

Remove some unused css

---

src/components/SlateEditor/plugins/external/ExternalEmbedForm.tsx

Hvis en url matcher noe i `urlTransformers` antar vi at den er gyldig. Hvis transformasjonen feiler setter vi feltet som feil.

Account for possible url transforms when validating an external URL.

---

package.json
src/components/HeaderWithLanguage/HeaderFavoriteStatus.tsx
src/components/HeaderWithLanguage/HeaderStatusInformation.tsx
src/containers/FormikForm/components/ElementList.tsx
src/modules/myndla/myndlaApi.ts
src/modules/myndla/myndlaQueries.ts
src/util/resourceHelpers.ts
yarn.lock

- Bumper types-backend
- Oppdaterer fetch av resource stats til backend updates
- Legger til hjertemarkering for audio/images
- Fjerner bruk av learningResourceType, ref: https://github.com/NDLANO/backend/commit/de622fc12c7fb2da69ba73381d0bc20ee1fbded0

Bump types-backend + refactor resource favorites fetch

---

src/containers/ArticlePage/FrontpageArticlePage/EditFrontpageArticle.tsx
src/containers/ArticlePage/LearningResourcePage/EditLearningResource.tsx
src/containers/ArticlePage/TopicArticlePage/EditTopicArticle.tsx
src/containers/ConceptPage/EditConcept.tsx

Oversetter de nye html-variantene våre! Dette skal vel være alle feltene.

Translate HTML fields

---

src/server/translate.ts

Fixes https://github.com/NDLANO/Issues/issues/3877

Log error with bunyan when translate API fails

---

src/modules/search/searchApi.ts
src/util/searchHelpers.ts

Oppdaget at søk på Emne/Om-ndla artikkel ikke fungerer etter overgang til POST for søk, denne fikser.

Fix search for topic-article/frontpage-article

---

src/components/SlateEditor/plugins/file/SlateFile.tsx

Fixes https://github.com/NDLANO/Issues/issues/3985

Save file name when clicking save button

---

src/containers/Masthead/components/MastheadSearchForm.tsx
src/containers/StructurePage/NodeItem.tsx

Vil gjerne forenkle Icon-komponenten litt. Dette er en teit prop å ha.

Style icons normally instead of relying on icon color prop

---

src/components/Dropdown/asyncDropdown/AsyncDropdown.tsx
src/components/SlateEditor/plugins/conceptList/ConceptTagPicker.tsx
src/components/SlateEditor/plugins/contactBlock/ContactBlockForm.tsx
src/components/SlateEditor/plugins/embed/EditVideo.tsx
src/components/SlateEditor/plugins/h5p/EditMetadataModal.tsx
src/containers/ArticlePage/components/ContentLink.tsx
src/containers/FormikForm/AddNotesField.tsx
src/containers/FormikForm/AddRevisionDateField.tsx
src/containers/FormikForm/SlugField.tsx
src/containers/ImageUploader/components/ImageContent.tsx
src/containers/NdlaFilm/components/ThemeNameModal.tsx
src/containers/StructurePage/AddNodeModalContent.tsx
src/containers/StructurePage/folderComponents/sharedMenuOptions/components/SearchDropdown.tsx
src/containers/StructurePage/folderComponents/subjectMenuOptions/AddNodeTranslation.tsx
src/containers/StructurePage/folderComponents/subjectMenuOptions/ChangeNodeName.tsx
src/containers/StructurePage/plannedResource/AddExistingResource.tsx
src/containers/StructurePage/plannedResource/PlannedResourceForm.tsx
src/containers/StructurePage/plannedResource/PlannedResourceSelect.tsx
src/containers/TaxonomyVersions/components/VersionNameField.tsx

Remove all usage of Input, InputV2, TextArea and TextAreaV2

---

src/components/SlateEditor/RichTextEditor.tsx
src/components/SlateEditor/plugins/concept/inline/index.tsx
src/components/SlateEditor/plugins/concept/inline/render.tsx
src/components/SlateEditor/plugins/link/Link.tsx
src/components/SlateEditor/plugins/span/render.tsx
src/components/SlateEditor/utils/InlineBugFix.tsx

Har testet den litt rundt så ut til å fungere ganske supert.  Følger bare hva som har blitt gjort hos [slate](https://github.com/ianstormtaylor/slate/blob/d271c4be543027be2197f353d7ea61b51e9c48c6/site/examples/inlines.tsx#L77-L82). 
TLDR:
Fikser og gjør endringene jeg gjorde for 4 uker siden bedre

Fixes sluggish keyboard navigation on inlines

---

src/containers/FormikForm/IngressField.tsx
src/containers/FormikForm/TitleField.tsx

Fixer warnings i konsollet når man tabber ut av title eller ingress

Fix editor warnings

---

src/containers/ConceptPage/components/ConceptContent.tsx

Fixes https://trello.com/c/3NhWOcUr/795-deaktiver-valgmulighet-for-video-i-forklaringer

Disable video visuel element on concept

---

src/containers/ArticlePage/LearningResourcePage/components/taxonomy/TaxonomyBlock.tsx
src/containers/ArticlePage/TopicArticlePage/components/TopicTaxonomyBlock.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Fixes https://trello.com/c/mDidlbGQ/792-ta-vekk-hjelpetekst-som-handler-om-delpublisering

Remove partial publishing error message from taxonomy block

---

src/components/NynorskTranslateProvider.tsx

Fixes https://github.com/NDLANO/Issues/issues/3997

Parse and reserialize html before sending it to translate api

---

src/components/SlateEditor/plugins/link/EditLink.tsx
src/components/SlateEditor/plugins/link/Link.tsx

Om du trykker på X _(close)_ knappen når du lager en lenke så brekker hele siden i mozilla

Moved link handleRemove so its handled in radixAutoFocus

---

src/containers/FrontpageEditPage/FrontpageEditPage.tsx

Fixes https://github.com/NDLANO/Issues/issues/4007

Show selected frontpage article on page load

---

src/components/DatePicker.tsx

Fixes https://trello.com/c/3MlFV9pd/806-ed-datovelgar-p%C3%A5-lenkeblokk-har-feil-z-index

Increase z-index of DatePicker to allow for usage within modals

---

package.json
src/components/HeaderWithLanguage/HeaderFavoriteStatus.tsx
src/components/HeaderWithLanguage/HeaderStatusInformation.tsx
src/containers/SearchPage/components/results/SearchContent.tsx
src/containers/SearchPage/components/sort/SearchSort.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts
yarn.lock

fixes https://github.com/NDLANO/Issues/issues/4006
Noe sånt som var tanken med denne?
Burde favorittmarkering vises på søkeresultat for bilder/lyd og?

Show favorites search

---

src/containers/VisualElement/VisualElement.tsx

Sikkert fint å vise frem det visuelle elementet

Add video renderer to visual element block.

---

src/components/SlateEditor/plugins/link/Link.tsx

Å fjerne content link fungerte ikke på comment men det gjør det med denne fixen.

Added path on link remove

---

src/components/SlateEditor/RichTextEditor.tsx
src/components/SlateEditor/plugins/link/Link.tsx

Løser [#4005](https://github.com/orgs/NDLANO/projects/2/views/9?pane=issue&itemId=60074747). 
Tar i mot forslag på hvordan det kan løses på en penere måte

add eventlisteners for outside click and esc krey press

---

src/constants.ts
src/server/contentSecurityPolicy.ts

Støtter embed av video fra https://www.mn.uio.no/ibv/om/skolelab/ressursarkivet/instruksjonsfilmer.html

Support uio videos

---

src/containers/WelcomePage/components/SubjectViewContent.tsx

Fikser bug som beskrevet her: https://trello.com/c/3gUjW6ev/815-fagoversikt
Hvis man vil teste kan man oppdatere favorittfag i test til:
> [
>     "urn:subject:30e47341-3f0e-4f5f-9d80-b99e9d62b866",
>     "urn:subject:6309cc71-56be-4c99-90bb-4600dccb2b15",
>     "urn:subject:d7f82986-1cf1-4449-bcc2-7ee442784761",
>     "urn:subject:cccdda20-f034-4fc7-877a-f91d89c40178",
>     "urn:subject:331f077e-04a3-4340-94d7-b6a463bab9e5",
>     "urn:subject:e1265b4e-58bf-45ee-ba43-71a819f86517",
>     "urn:subject:4e633ace-a9ad-4ad1-b065-fb91ca72151e",
>     "urn:subject:9d6d7550-f6df-4157-aa21-1f161d18f771",
>     "urn:subject:dab41c7e-e8b1-4f28-8893-e360d849c270",
>     "urn:subject:6ba15509-052e-42dc-83cb-b06c1774cc74",
>     "urn:subject:4eb79eed-3527-42e8-86d8-f487aa15a0d5",
> …

Bug fix: subjectsView block 

---

src/components/Accordion/FormAccordions.tsx
src/components/Accordion/FormAccordionsWithComments.tsx
src/components/Accordion/OpenAllButton.tsx
src/components/ResourcePage.tsx
src/constants.ts
src/containers/ArticlePage/FrontpageArticlePage/FrontpageArticlePage.tsx
src/containers/ArticlePage/FrontpageArticlePage/components/FrontpageArticleForm.tsx
src/containers/ArticlePage/FrontpageArticlePage/components/FrontpageArticlePanels.tsx
src/containers/ArticlePage/LearningResourcePage/components/LearningResourceForm.tsx
src/containers/ArticlePage/LearningResourcePage/components/LearningResourcePanels.tsx
src/containers/ArticlePage/TopicArticlePage/components/TopicArticleAccordionPanels.tsx
src/containers/ArticlePage/TopicArticlePage/components/TopicArticleForm.tsx
src/containers/ArticlePage/components/CommentSection.tsx
src/containers/ArticlePage/styles.ts
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

https://trello.com/c/BD2M8DaQ/134-bryter-for-%C3%A5-sl%C3%A5-av-p%C3%A5-gule-lapper
- Legger til mulighet for å toggle visning av kommentarer i artikkel

Add switch for possibility of hiding comments in resource page

---

src/containers/WelcomePage/components/WelcomeHeader.tsx
src/modules/myndla/myndlaApi.ts
src/modules/myndla/myndlaQueries.ts
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

https://trello.com/c/434SnHSK/135-endringer-i-velkommen-banneret
depends on https://github.com/NDLANO/backend/pull/459
- viser frem siste hjertemarkerte ressurs på dashboard

Display last favorited resource on dashboard

---

src/components/PreviewDraft/PreviewConceptComponent.tsx
src/components/PreviewDraft/PreviewDraft.tsx
src/components/PreviewDraft/PreviewVersion.tsx
src/components/PreviewDraft/useTransformedArticle.ts
src/modules/article/articleGqlQueries.ts

Fixes https://github.com/NDLANO/Issues/issues/4017
Kan testes ved å se at forhåndsvisning (den i footeren) er mer tro til publisert artikkel mtp visning av publiserte forklaringer og alt-text på bilder.

Make preview closer to a published article

---

src/containers/Login/Login.tsx
src/containers/Logout/Logout.tsx
src/containers/NotFoundPage/NotFoundPage.tsx

Ser ikke ut til å påvirke noe.

Remove OneColumn css modifiers

---

src/components/Accordion/FormAccordion.tsx
src/components/PreviewDraft/PreviewDraft.tsx
src/containers/ArticlePage/FrontpageArticlePage/components/FrontpageArticlePanels.tsx
src/containers/ArticlePage/LearningResourcePage/components/LearningResourcePanels.tsx
src/containers/ArticlePage/TopicArticlePage/components/TopicArticleAccordionPanels.tsx
src/containers/AudioUploader/components/AudioForm.tsx
src/containers/EditSubjectFrontpage/components/SubjectpageAccordionPanels.tsx
src/containers/ImageUploader/components/ImageForm.tsx
src/containers/NdlaFilm/components/NdlaFilmAccordionPanels.tsx
src/containers/Podcast/components/PodcastForm.tsx
src/containers/Podcast/components/PodcastMetaData.tsx
src/containers/PodcastSeries/components/PodcastSeriesForm.tsx
src/containers/VisualElement/UrlAllowList.tsx

Lurt å kvitte oss med flest mulig utility-klasser så vi kan bevege oss vekk fra inuit.

Remove class name usage

---

src/components/SlateEditor/plugins/external/SlateExternal.tsx
src/constants.ts

Fixes https://github.com/NDLANO/Issues/issues/4027
Er ikke hundre prosent sikker på hvorfor vi gjør så fryktelig mye validering her, så test gjerne litt forskjellige caser som jeg ikke har klart å finne på.

Fix broken youtube embeds

---

src/components/SlateEditor/plugins/link/utils.ts
src/components/SlateEditor/plugins/toolbar/handleMenuClicks.ts

Fixes https://github.com/NDLANO/Issues/issues/4031

Forhindre lenke i h2

---

src/components/SlateEditor/plugins/external/SlateExternal.tsx

Gjerne sjekk at [denne](https://github.com/NDLANO/editorial-frontend/pull/2361#pullrequestreview-2040782835) feilen ikke oppstår

Do not call onClose when saving external embed form

---

.github/workflows/ci.yml
Dockerfile
README.md
package.json
yarn.lock

Fixes Snyk vulnurability https://security.snyk.io/vuln/SNYK-ALPINE318-OPENSSL-6593964

Upgrade Node to 20.13.1

---

package.json
src/components/HeaderWithLanguage/EmbedInformation/EmbedConnection.tsx
src/components/HeaderWithLanguage/LearningpathConnection.tsx
src/components/HelpIcon.tsx
src/components/HelpMessage.tsx
src/components/HowTo/HowToHelper.tsx
src/components/HowTo/MarkdownExample.tsx
src/components/HowTo/index.ts
src/components/HowTo/stories.ts
src/components/SlateEditor/plugins/blockPicker/actions.tsx
src/containers/AudioUploader/components/AudioFileInfoModal.tsx
yarn.lock

Fjernet komponent-eksempler. Beholdt markdown-beskrivelse.

Move ndla/howto into ed

---

package.json
yarn.lock

Fixes vulnurability https://security.snyk.io/vuln/SNYK-JS-HELMETCSP-469436

Bump helmet to 3.23.3

---

src/components/PreviewDraft/PreviewDraft.tsx
src/components/PreviewDraft/PreviewMarkup.tsx
src/containers/ComparePage/ComparePage.tsx
src/containers/PreviewDraftPage/PreviewDraftPage.tsx

Kun forhåndsvis skal ikkje vise alt-tekst.

Pulls previewAlt out as param to PreviewDraft component

---

src/containers/StructurePage/folderComponents/subjectMenuOptions/TaxonomyMetadataLanguageSelector.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

NDLANO/Issues#4028
Gjør det mulig å definere samiske fag som samlinger.

Redefinerer språkmetadatafeltet og legger til koder

---

src/containers/SearchPage/components/sort/SearchSort.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

https://trello.com/c/CYWzZdw1/142-kunne-finne-utdaterte-artikler
Legger til sortering for sist faglig vurdert (published), ser ut som at det var en enkel fiks!

Add sort option for published

---

src/components/SlateEditor/plugins/concept/inline/InlineWrapper.tsx

Merka at jeg ikke kunne escape modalen når du velger/redigerer concept såååå smekka inn lik løsning vi har på link 🔢

Added logic similar to link to escape edit concept modal with keyboard

---

src/components/Accordion/FormAccordion.tsx
src/components/PreviewDraft/PreviewVersion.tsx
src/containers/ArticlePage/LearningResourcePage/components/LearningResourcePanels.tsx
src/containers/ArticlePage/TopicArticlePage/components/TopicArticleAccordionPanels.tsx
src/containers/AudioUploader/components/AudioForm.tsx
src/containers/ComparePage/ComparePage.tsx
src/containers/ConceptPage/ConceptForm/ConceptForm.tsx
src/containers/EditSubjectFrontpage/components/SubjectpageAccordionPanels.tsx
src/containers/ImageUploader/components/ImageForm.tsx
src/containers/NdlaFilm/components/NdlaFilmAccordionPanels.tsx
src/containers/Podcast/components/PodcastForm.tsx
src/containers/PodcastSeries/components/PodcastSeriesForm.tsx

https://github.com/NDLANO/Issues/issues/4052

Create a variant prop for FormAccordion, to reduce className usage

---

src/containers/Login/Login.tsx
src/containers/Logout/Logout.tsx

Er bare `login/failure` som faktisk viser innhold.

Remove utility classes for login and logout

---

src/components/SlateEditor/plugins/paragraph/Paragraph.tsx

https://github.com/NDLANO/Issues/issues/4052

Use data attribute to center paragraphs in editor

---

src/components/QualityEvaluation/QualityEvaluation.tsx
src/components/QualityEvaluation/QualityEvaluationForm.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Noen små justeringer!
- Oppdaterer sånn at 1 og 5 har border for å tydeligere skille de fra de andre valgene
- Justerer fargene litt
- Oppdaterer oversettelser

Update quality evaluation scale colors + update phrases.

---

src/components/AlertModal/AlertModal.tsx
src/components/Footer/Footer.tsx
src/components/Form/FormRemainingCharacters.tsx
src/components/HeaderWithLanguage/HeaderLanguagePill.tsx
src/components/HeaderWithLanguage/HeaderSupportedLanguages.tsx
src/components/ResourcePage.tsx
src/components/SlateEditor/EditorFooter.tsx
src/components/SlateEditor/plugins/table/SlateTable.tsx
src/components/SlateEditor/utils/InlineBugFix.tsx
src/components/Taxonomy/Fade.tsx
src/components/Taxonomy/TaxonomyBlockNode.tsx
src/containers/ArticlePage/FrontpageArticlePage/FrontpageArticlePage.tsx
src/containers/ArticlePage/LearningResourcePage/LearningResourcePage.tsx
src/containers/ArticlePage/TopicArticlePage/TopicArticlePage.tsx
src/containers/ArticlePage/styles.ts
src/containers/Messages/__tests__/__snapshots__/Messages-test.tsx.snap
src/containers/NodeDiff/TreeNode.tsx
src/containers/StructurePage/NodeItem.tsx
src/containers/TaxonomyVersions/components/VersionForm.tsx
src/containers/WelcomePage/components/TableComponent.tsx
src/containers/WelcomePage/components/TableTitle.tsx

Fjerner resterende bruk av `css`-attributtet på HTML-elementer. Lar selve typescript-endringene i tsconfig ligge slik at dette ikke holder igjen noen andre PR'er, men de burde nok endres snart.

Prefer styled over css

---

src/containers/PreviewDraftPage/PreviewDraftPage.tsx
src/containers/SearchPage/components/results/SearchContent.tsx
src/containers/StructurePage/resourceComponents/Resource.tsx
src/util/resourceHelpers.ts
src/util/taxonomyHelpers.ts

Fixes NDLANO/Issues#4023
Trenger ikkje redefinere mapping som allerede finnes. Dessuten vil kun artikler+læringsstier ha contexts så gjør sjekken litt bedre.

Fiks lenker til forklaringsartikler fra søk

---

src/components/Accordion/FormAccordionsWithComments.tsx
src/components/QualityEvaluation/QualityEvaluationModal.tsx

- Flipper checked state for skjul/vis kommentarer switch
- Oppdaterer theme for redigering av kvalitetsvurdering

Flip checked state comment switch + update color theme edit quality evaluation button

---

src/constants.ts
src/server/contentSecurityPolicy.ts

https://trello.com/c/Z7DtDFFd/877-godta-flere-domener-som-embed-url

Add new embeds for maps

---

src/components/SlateEditor/plugins/toolbar/toolbarState.ts

Tenker vi slår av inline på multiblock select inntil vi finner på en smart løsning å håndtere det på. Jeg klarte ikke å finne på en mega nice måte å gjøre det på uten å skrive om ganske mye.

Added disabling on multiblock selection toolbar

---

src/components/SlateEditor/plugins/link/EditLink.tsx
src/components/SlateEditor/plugins/link/utils.ts

Rart vi ikkje har oppdaga dette før.

Support using preview url in link plugin

---

src/containers/FormikForm/components/ElementList.tsx

Fixes NDLANO/Issues#4067
Sjekk lenker på ndla-film-redigering og sammenlign med ed.test

Fixes links in ndla-film by using id if present

---

src/components/SlateEditor/utils/InlineBugFix.tsx

fixes https://github.com/NDLANO/Issues/issues/4063

Removed empty space and adjusted styling

---

src/components/SlateEditor/plugins/toolbar/toolbarState.ts
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Legger til Dari som mulighet for språkmerking.

Add dari to language codes

---

src/components/PreviewDraft/PreviewVersion.tsx

Kan testes ved å sjekke at "marker forskjeller" i "sammenlign med publisert" fungerer som det skal og at denne ikke kræsjer siden:
http://localhost:3000/subject-matter/learning-resource/37647/edit/nb

Add missing router context when rendering diffable transformed article

---

src/containers/FormikForm/GrepCodesFieldContent.tsx

Midlertidig løsning for å fjerne form-komponenter som ikke skal overføres til nye systemet.

Stop using FormPill

---

src/containers/WelcomePage/WelcomePage.tsx
src/containers/WelcomePage/components/ArticleStatusContent.tsx
src/containers/WelcomePage/components/ArticleStatuses.tsx
src/containers/WelcomePage/components/LastUsedConcepts.tsx
src/containers/WelcomePage/components/LastUsedItems.tsx
src/containers/WelcomePage/components/LastUsedResources.tsx
src/containers/WelcomePage/components/Revisions.tsx
src/containers/WelcomePage/components/SubjectView.tsx
src/containers/WelcomePage/components/SubjectViewContent.tsx
src/containers/WelcomePage/components/TableComponent.tsx
src/containers/WelcomePage/components/worklist/ConceptListTabContent.tsx
src/containers/WelcomePage/components/worklist/WorkList.tsx
src/containers/WelcomePage/components/worklist/WorkListTabContent.tsx

Use isPending instead of isLoading in worklist

---

src/components/SlateEditor/plugins/image/SlateImage.tsx

Som BM skrev på slack så kan man innimellom se feil bilde i en artikkel dersom det har blitt cachet og så endret.
Legger på en timestamp i bilde-url'en slik at vi ikke vil treffe cachen i `SlateImage`.

Add query-param to avoid cache in `SlateImage`

---

src/containers/FormikForm/formikDraftHooks.ts

Gjør som Bjørn Magne ba om på slack.
Gjør så kun det i "Innhold" panelet påvirker `lastEditedArticles` i user-data.

Only update user data when content has changed

---

src/containers/StructurePage/StructureContainer.tsx

Skjuler forklaringsfag i struktur for alle som ikkje er admin.

Hide concept subjects in structure

---

src/containers/StructurePage/StructureContainer.tsx

fixes https://github.com/NDLANO/Issues/issues/4133

Fix sticky resources container

---

src/components/QualityEvaluation/QualityEvaluationForm.tsx

Fix update of quality evaluation failure

---

src/components/QualityEvaluation/QualityEvaluationForm.tsx

Litt bedre error handling i quality evaluation form!

Try/catch for onSubmit and onDelete in quality evaluation form

---

src/containers/ArticlePage/TopicArticlePage/EditTopicArticle.tsx
src/containers/StructurePage/resourceComponents/Resource.tsx
src/containers/StructurePage/resourceComponents/ResourceBanner.tsx
src/containers/StructurePage/resourceComponents/ResourcesContainer.tsx
src/containers/StructurePage/resourceComponents/StatusIcons.tsx

Fiks som indikerer i taksonomi også om emneartikler er brukt flere steder (https://trello.com/c/XmFaldEM/900-indikere-om-emneartikler-er-brukt-flere-steder-i-taksonomi-strukturredigering)

Indicate multiple contexts for topic articles

---

src/components/QualityEvaluation/AverageQualityEvaluation.tsx
src/components/QualityEvaluation/QualityEvaluationForm.tsx
src/containers/StructurePage/NodeItem.tsx
src/containers/StructurePage/StructureContainer.tsx
src/containers/StructurePage/folderComponents/FolderItem.tsx
src/containers/StructurePage/resourceComponents/QualityEvaluationGrade.tsx
src/containers/StructurePage/resourceComponents/ResourcesContainer.tsx
src/containers/StructurePage/resourceComponents/StructureResources.tsx
src/containers/StructurePage/resourceComponents/SubjectBanner.tsx
src/containers/StructurePage/resourceComponents/TopicResourceBanner.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Fikser som BM/Johannes ønsket, i hovedsak:
- Legger til advarsel i modal som vises når man velger kvalitetsvurdering til 5
- Reintroduserer subject-banner, med mulighet for å kvalitetsvurdere fag derfra
- Viser alltid gjennomsnitt/satt vurdering av noden
- Viser alltid en desimal for gjennomsnitt
de siste tingene fikses i denne: https://github.com/NDLANO/taxonomy-api/pull/260

Quality evaluation fixes

---

src/components/QualityEvaluation/QualityEvaluationModal.tsx
src/constants.ts
src/containers/StructurePage/NodeItem.tsx
src/containers/StructurePage/RootNode.tsx
src/containers/StructurePage/StructureBanner.tsx
src/containers/StructurePage/StructureContainer.tsx
src/containers/StructurePage/resourceComponents/Resource.tsx
src/containers/StructurePage/resourceComponents/ResourceItems.tsx
src/containers/StructurePage/resourceComponents/ResourcesContainer.tsx
src/containers/StructurePage/resourceComponents/StructureResources.tsx
src/containers/StructurePage/resourceComponents/SubjectBanner.tsx
src/containers/StructurePage/resourceComponents/TopicResourceBanner.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Litt prop drilling, vurderte også å løse dette med en provider i stedet, kunne isåfall flyttet alle states knyttet til visning/skjuling av options dit, kom med innspill om dere har 🌚

Add switch for toggling quality evaluation in taxonomy

---

src/components/Accordion/FormAccordionsWithComments.tsx
src/config.ts
src/containers/StructurePage/NodeItem.tsx
src/containers/StructurePage/StructureBanner.tsx
src/containers/StructurePage/resourceComponents/Resource.tsx
src/containers/StructurePage/resourceComponents/SubjectBanner.tsx
src/containers/StructurePage/resourceComponents/TopicResourceBanner.tsx

Etter deploy i ettermiddag trengs ikkje denne lenger.

Remove flag for quality-evaluation

---

src/components/Accordion/FormAccordionsWithComments.tsx
src/components/QualityEvaluation/AverageQualityEvaluation.tsx
src/components/QualityEvaluation/QualityEvaluation.tsx
src/components/QualityEvaluation/QualityEvaluationForm.tsx
src/components/QualityEvaluation/QualityEvaluationModal.tsx
src/containers/ArticlePage/FrontpageArticlePage/components/FrontpageArticlePanels.tsx
src/containers/ArticlePage/LearningResourcePage/components/LearningResourcePanels.tsx
src/containers/ArticlePage/TopicArticlePage/components/TopicArticleAccordionPanels.tsx
src/containers/StructurePage/NodeItem.tsx
src/containers/StructurePage/resourceComponents/SubjectBanner.tsx
src/containers/StructurePage/resourceComponents/TopicResourceBanner.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

https://trello.com/c/fGCHdaEC/970-oppdateringer-kvalitetsvurdering
Kom inn noen ekstra ønsker i forbindelse med kvalitetsvurdering, vi burde kanskje cherry-pick deploye disse commitene sånn at vi får tatt det videre før redesign er klart? 🤔 
**NB**: Oppdaget i forbindelse med denne PRen at count ikke er riktig oppdatert, @jnatten ser på det, tenker vi venter med å ta denne videre til det også er fikset!

QualityEvaluation: add note when quality evaluation changes + update title/aria-label for average

---

src/containers/StructurePage/StructureBanner.tsx
src/containers/StructurePage/resourceComponents/SubjectBanner.tsx

Hide switches in programme subject banner

---

src/components/ContentTypeProvider.tsx
src/components/SlateEditor/plugins/blockquote/SlateBlockQuote.tsx
src/components/SlateEditor/plugins/blockquote/index.tsx
src/components/SlateEditor/plugins/blockquote/render.tsx
src/components/SlateEditor/plugins/framedContent/SlateFramedContent.tsx
src/components/SlateEditor/plugins/framedContent/index.tsx
src/components/SlateEditor/plugins/framedContent/utils.ts
src/containers/ArticlePage/FrontpageArticlePage/components/FrontpageArticleFormContent.tsx
src/containers/ArticlePage/LearningResourcePage/EditLearningResource.tsx
src/containers/ArticlePage/TopicArticlePage/components/TopicArticleContent.tsx
src/containers/ConceptPage/components/ConceptContent.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts
src/util/embedTagHelpers.tsx

Har ikke lagt inn støtte for forhåndsvisning ennå. Tror vi må hente mer data for å få det til :')

feat: support color variants for FramedContent and blockquote based on article content type

---

e2e/specs/taxonomy.spec.ts
package.json
src/components/Accordion/FormAccordionsWithComments.tsx
src/components/PreviewDraft/PreviewVersion.tsx
src/components/Taxonomy/ActiveTopicConnection.tsx
src/components/Taxonomy/RelevanceOption.tsx
src/components/Taxonomy/RelevanceOptionSwitch.tsx
src/components/Taxonomy/TopicConnections.tsx
src/containers/ArticlePage/LearningResourcePage/components/taxonomy/TaxonomyInfo.tsx
src/containers/ArticlePage/TopicArticlePage/components/TopicArticleConnections.tsx
src/containers/FormikForm/AddRevisionDateField.tsx
src/containers/StructurePage/StructureBanner.tsx
src/containers/StructurePage/folderComponents/sharedMenuOptions/ToggleVisibility.tsx
src/containers/StructurePage/folderComponents/subjectMenuOptions/ToggleExplanationSubject.tsx
src/containers/StructurePage/folderComponents/subjectMenuOptions/ToggleProgrammeSubject.tsx
src/containers/StructurePage/folderComponents/topicMenuOptions/GroupTopicResources.tsx
src/containers/StructurePage/resourceComponents/GroupResourcesSwitch.tsx
src/containers/WelcomePage/components/ArticleStatusContent.tsx
src/containers/WelcomePage/components/Revisions.tsx
src/containers/WelcomePage/components/worklist/WorkListTabContent.tsx
src/containers/WelcomePage/styles.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts
yarn.lock

Fjerner gammel switch. MERK: Jeg har tatt noen kreative friheter som er spesielt synlige i struktur. Sikkert lurt å gå over og sjekke at ting ser nogenlunde greit ut.

refactor: remove old switch

---

src/containers/WelcomePage/WelcomePage.tsx
src/containers/WelcomePage/components/ArticleStatuses.tsx
src/containers/WelcomePage/components/LastUsedItems.tsx
src/containers/WelcomePage/components/Revisions.tsx
src/containers/WelcomePage/components/SubjectView.tsx
src/containers/WelcomePage/components/TableComponent.tsx
src/containers/WelcomePage/components/WelcomePageTabsContent.tsx
src/containers/WelcomePage/components/worklist/WorkList.tsx
src/containers/WelcomePage/styles.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Tenker at vi beveger oss vekk fra de dynamiske grid-komponentene. Det er kanskje like greit at vi setter størrelsen direkte på komponenten.

feat: use new tabs for frontpage

---

package.json
src/components/ControlledImageSearchAndUploader.tsx
src/components/ImageSearchAndUploader.tsx
src/components/SlateEditor/plugins/concept/ConceptModalContent.tsx
src/components/SlateEditor/plugins/related/EditRelated.tsx
src/components/StyledFormComponents.tsx
src/containers/StructurePage/plannedResource/AddExistingResource.tsx
src/containers/StructurePage/plannedResource/PlannedResourceModal.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts
yarn.lock

Merk: Jeg endrer kun nok ting til at vi kan droppe `ndla/tabs`. Innholdet som ligger i tabs refaktoreres senere.

refactor: rewrite old tabs to new tabs

---

src/components/FileUploader/FileUploader.tsx
src/components/SlateEditor/plugins/file/SlateFileList.tsx
src/containers/AudioUploader/components/AudioContent.tsx
src/containers/ImageUploader/components/ImageContent.tsx
src/containers/VisualElement/VisualElementSearch.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Endrer oppførselen litt, se hva dere syntes!

FileUpload to new components

---

src/containers/FormikForm/CopyrightFieldGroup.tsx
src/containers/FormikForm/components/ContributorsField.tsx
src/containers/FormikForm/components/LicenseField.tsx
src/containers/FormikForm/components/OriginField.tsx
src/containers/FormikForm/components/ProcessedField.tsx

Begynner å lure på om vi skal koste på oss en liten abstraksjon for Select. Den er ganske slitsom å skrive :')

refactor: use new components in licenses block

---

src/components/DatePicker.tsx
src/components/LastUpdatedLine/DateEdit.tsx
src/containers/FormikForm/components/InlineDatePicker.tsx

På sikt kan vi sikkert bytte over til ark sin DatePicker. Tror vi kan spare litt bundle-size der.

refacyor: use primitives for date picker

---

src/containers/ArticlePage/components/ContentLink.tsx

Brukes f.eks til relatert innhold (ekstern lenke)

refactor: use primitives in ContentLink

---

src/components/DialogCloseButton.tsx

feat: add dialog close button component

---

src/components/SlateEditor/plugins/concept/ConceptModalContent.tsx
src/containers/SearchPage/SearchContainer.tsx

Katrine tar resten i en annen PR!

refactor:use new pagination components

---

src/components/SlateEditor/plugins/video/SlateVideo.tsx
src/containers/ArticlePage/LearningResourcePage/EditLearningResource.tsx

Får 404 i brightcove dersom &t= er med

Do not add t= to videolink

---

src/components/SlateEditor/plugins/linkBlockList/LinkBlockForm.tsx
src/components/SlateEditor/plugins/linkBlockList/SlateLinkBlockList.tsx

refactor: use primitives in SlateLinkBlock

---

src/containers/FormikForm/IngressField.tsx

Veit ikkje om dette er en god ide, men det funker i det minste.

Makes introduction larger in preview of article

---

package.json
src/components/SlateEditor/plugins/concept/ConceptModalContent.tsx
src/components/abstractions/Pagination.tsx
src/containers/SearchPage/SearchContainer.tsx
src/containers/WelcomePage/components/LastUsedConcepts.tsx
src/containers/WelcomePage/components/LastUsedResources.tsx
src/containers/WelcomePage/components/Revisions.tsx
src/containers/WelcomePage/components/SubjectViewContent.tsx
src/containers/WelcomePage/components/worklist/ConceptListTabContent.tsx
src/containers/WelcomePage/components/worklist/WorkListTabContent.tsx
yarn.lock

Flytter Pagination til /abstractions og tar den i bruk overalt

Pagination abstraction

---

src/containers/StructurePage/folderComponents/subjectMenuOptions/AddNodeTranslation.tsx
src/containers/StructurePage/folderComponents/subjectMenuOptions/ChangeNodeName.tsx

Her nøstet vi tydeligvis form-komponenter, så jeg forenklet litt!

refactor: use primitives in node name form

---

src/containers/ArticlePage/components/Comment.tsx
src/containers/ArticlePage/components/InputComment.tsx

Har ikke tatt for meg noe styling ennå. Ser ut som at designet ikke er helt klart, litt farger som mangler og sånt

refactor: use primitives in comment component

---

src/containers/ImageUploader/components/ImageContent.tsx

fixes https://github.com/NDLANO/Issues/issues/4191
Fikser også at knapp for å slette bilde ofte legger seg over bildet, ser ut som dette er en bedre posisjonering!

Fix image preview file upload not shown

---

src/components/PreviewDraft/PreviewConcept.tsx
src/components/PreviewDraft/PreviewConceptCompare.tsx

refactor: remove emotion in concept preview components.

---

package.json
src/server/api.ts
yarn.lock

Route for å kunne kjøre prompt mot Bedrock i ed.

POST route for haiku invocation

---

src/containers/ArticlePage/components/ConceptsField.tsx
src/containers/ArticlePage/components/ContentField.tsx
src/containers/ConceptPage/components/ConceptArticles.tsx
src/containers/EditSubjectFrontpage/components/SubjectpageArticles.tsx
src/containers/NdlaFilm/components/ThemeMovies.tsx

Fikser så dette blir semantisk riktig html igjen! 😅

Wrap dnd resource item lists in ul-element

---

src/containers/ArticlePage/components/ConceptsField.tsx

Gjort noen små refaktoreringer, men har beholdt FormikField inntil videre. Derfor combobox-label ser så stort ut :')

feat: use combobox in ConceptsField

---

src/containers/ConceptPage/components/ConceptMetaData.tsx

Er nok lurt å teste denne litt nøye etter å ha lest gjennom koden

refactor: use primitives for selecting concept subjects

---

src/containers/FrontpageEditPage/FrontpageArticleSearch.tsx
src/containers/FrontpageEditPage/FrontpageEditPage.tsx
src/containers/FrontpageEditPage/FrontpageNode.tsx

Litt merkelig komposisjon med popover, så ender opp med å se sånn her ut!

refactor: use combobox in Frontpage node menu

---

src/components/SlateEditor/plugins/uuDisclaimer/DisclaimerForm.tsx
src/containers/ArticlePage/components/ConceptsField.tsx
src/containers/FrontpageEditPage/FrontpageArticleSearch.tsx
src/containers/NdlaFilm/components/NdlaFilmArticle.tsx
src/containers/Podcast/components/PodcastSeries.tsx
src/util/usePaginatedQuery.ts

Reset page state when a mismatch is found in data and page

feat: introduce a delayed query helper and use it in combobox queries.

---

src/containers/SearchPage/components/results/SearchContent.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Viser alert-ikon dersom fleire kontekster

Show alert on more than one tax context

---

src/containers/SearchPage/components/sort/SearchSort.tsx

Skriver om selects for sortering/rekkefølge til ny select! gjør det veldig enkelt designmessig, også får vi heller tilpasse senere

Sort and order selects to new select

---

src/components/SlateEditor/plugins/heading/__tests__/normalizer-test.ts
src/components/SlateEditor/plugins/heading/index.tsx
src/components/SlateEditor/plugins/span/index.tsx
src/components/SlateEditor/plugins/toolbar/__tests__/toolbarState-test.ts
src/components/SlateEditor/plugins/toolbar/toolbarState.ts

Forhindrer bruk av bold i h2-h4

No bold in title

---

src/components/SlateEditor/plugins/video/EditVideo.tsx
src/components/SlateEditor/plugins/video/SlateVideo.tsx

Med ny dialog så blir labels satt til ny fontweight, tok et midlertidig designvalg å gjorde begge labels til label tag og dermed fikk de samme design

Added new dialog items slate video

---

src/components/SlateEditor/plugins/details/Details.tsx

fixes https://github.com/NDLANO/Issues/issues/4197

Do not center details content

---

src/containers/StructurePage/StructureContainer.tsx
src/containers/StructurePage/resourceComponents/ResourcesContainer.tsx
src/containers/StructurePage/resourceComponents/StructureResources.tsx
src/containers/StructurePage/resourceComponents/SubjectBanner.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

https://trello.com/c/QyiNgmtm/1069-vise-lma-desk-spr%C3%A5k-p%C3%A5-fagheader-i-struktur

Show subject responsibles in subject banner

---

src/util/searchHelpers.ts

Tar contextTypes fra søket videre dersom det er spesifisert.
Fixes NDLANO/Issues#4200

Passthrough context type from search

---

src/components/Form/FormRemainingCharacters.tsx
src/components/SlateEditor/plugins/campaignBlock/CampaignBlockForm.tsx

Stjeler egentlig bare det Lars allerede hadde gjort i FormikField

feat: properly support slate values in FormRemainingCharacters

---

src/components/SlateEditor/plugins/image/SlateImage.tsx
src/components/SlateEditor/plugins/video/SlateVideo.tsx

Lærte om de portalene etter disse :^) Nå erre mulig å lagre igjen

Learned about the need of wrapping dialogcontent i portal after these

---

src/containers/EditSubjectFrontpage/components/SubjectpageAccordionPanels.tsx
src/containers/EditSubjectFrontpage/components/SubjectpageSubjectlinks.tsx
src/containers/EditSubjectFrontpage/components/nodes/NodeList.tsx
src/containers/EditSubjectFrontpage/components/nodes/NodeSearchDropdown.tsx
src/containers/EditSubjectFrontpage/components/nodes/index.ts

Det gamle fungerte dårlig, dette fungerer litt bedre. Misbruker multi-select for å få til en litt bedre arbeidsflyt enn det en gang var. Prøver også å hente litt mindre data, så ting ikke hopper like mye!

refactor: use combobox in subject page links

---

e2e/specs/blockpicker_learning_resource.spec.ts
src/components/SlateEditor/plugins/codeBlock/CodeBlock.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Det funker men jeg trenger nok hjelp om hvordan vi skal gjøre det mer finere?

Refactored to new dialog. Adjusted tests to new dialog

---

src/components/HowTo/HowToHelper.tsx
src/components/SlateEditor/plugins/blockPicker/SlateBlockPicker.tsx

Skrev om blockpicker til nye komponenter.

Blockpicker new components

---

src/containers/WelcomePage/components/worklist/SubjectCombobox.tsx

Vi ønsker ikke å filtrere i items basert på valgt element

SubjectCombobox: selectionBehavior to preserve

---

src/containers/ArticlePage/components/ConceptsField.tsx

guarantee that it's listed in items.
Fixes https://github.com/NDLANO/Issues/issues/4202

fix: do not use multiselect when working with external list items

---

src/containers/FormikForm/GrepCodesField.tsx

samme oppførsel som: https://github.com/NDLANO/editorial-frontend/pull/2577/commits/4bf8b43e51a31ad43079a83db48054c6aaa8ba8c

GrepCodes combobox: Fix combobox selection behaviour

---

src/containers/EditSubjectFrontpage/components/SubjectpageSubjectlinks.tsx
src/containers/EditSubjectFrontpage/components/nodes/NodeList.tsx
src/containers/EditSubjectFrontpage/components/nodes/NodeSearchDropdown.tsx

- Fikser opp i selection-logikk
- Fjerner bruk av ListResource i NodeList, tenker den komponenten er unødvendig å bruke når vi alltid rendrer fallback-bilde

NodeSearchDropdown: selection fix

---

src/containers/StructurePage/plannedResource/AddExistingResource.tsx

MERK: Det er forskjeller på fetching av læringsstier her og i gammel implementasjon. Tenkte en åpenbar forenkling var å kun bruke søk uavhengig av om vi skulle hente ut læringsstier eller "vanlige" artikler. En sjapp sjekk med API'et viser dog at vi returnerer et ulikt antall ressurser på tvers av de to API'ene. `CREATED_BY_NDLA` er heller ikke mulig å bruke fra søke-API'et, men den brukes vel ikke i søket i ndla-frontend heller?

refactor: Use Combobox in AddExistingResource

---

src/components/HeaderWithLanguage/DeleteLanguageVersion.tsx
src/components/HeaderWithLanguage/HeaderActions.tsx

DeleteLanguageVersion to new Button component 

---

src/components/HowTo/stories.ts
src/containers/ConceptPage/components/InlineImageSearch.tsx
src/containers/FormikForm/MetaImageSearch.tsx

https://trello.com/c/J1QqBl2g/1114-fjerne-infoknapp-p%C3%A5-metabilde-i-ed

Remove meta image helper

---

src/containers/ImageUploader/components/ImageContent.tsx

https://trello.com/c/0B6dSJhZ/1112-dynamiske-tekst-felt-bilde-api

Use TextArea in ImageContent form content

---

src/components/ControlledImageSearchAndUploader.tsx
src/components/ImageSearchAndUploader.tsx

På sikt burde nok disse to være en komponent!

refactor: use primitives in ImageSearchAndUploader

---

src/components/SlateEditor/plugins/framedContent/SlateFramedContent.tsx

depends on https://github.com/NDLANO/editorial-frontend/pull/2585

FramedContent new styled

---

src/containers/StructurePage/folderComponents/sharedMenuOptions/MoveExistingNode.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Gjør det litt lettere å skjønne kva som kan gjøres her.
https://trello.com/c/4Gp2vyLo/1110-flytt-eksisternede-emne-hit-for-standardbruker

Less room for misunderstanding

---

src/components/HeaderWithLanguage/HeaderStatusInformation.tsx
src/components/SlateEditor/plugins/concept/block/BlockWrapper.tsx
src/components/SlateEditor/plugins/concept/inline/InlineWrapper.tsx
src/containers/SearchPage/components/results/SearchContent.tsx
src/containers/StructurePage/resourceComponents/StatusIcons.tsx

Etter design-oppdatering! Denne varianten skal brukes overalt i ed for warnings

Use ErrorWarningFill for warnings

---

src/containers/FormikForm/components/ContributorsField.tsx

https://trello.com/c/4DMHNyeD/1119-justere-tekstfeltene-i-lisensmodalen-til-tekst-i-ramme

Fix grid columns spacing in ContributorsField

---

src/containers/SearchPage/components/results/SearchList.tsx

fix: do not deduplicate users in search. After all, we rely on actual

---

src/components/DndList.tsx
src/components/DraggableItem.tsx
src/containers/ArticlePage/FrontpageArticlePage/components/FrontpageArticleFormContent.tsx
src/containers/FormikForm/components/MetaImageField.tsx
src/containers/Podcast/components/PodcastSeries.tsx
src/containers/SearchPage/components/form/SearchTag.tsx
src/containers/StructurePage/folderComponents/SettingsMenu.tsx
src/containers/StructurePage/folderComponents/sharedMenuOptions/EditGrepCodes.tsx

rører ikke Navigation, SavedSearchItem, AlertModal, Version for å unngå konflikter!

Remove IconButtonV2 usage

---

src/components/SlateEditor/plugins/concept/SearchConceptResults.tsx

Hermer litt etter stylingen på søkesiden.

refactor: use panda in SearchConceptResults

---

src/components/Accordion/FormAccordions.tsx
src/components/Accordion/OpenAllButton.tsx

Accordions med kommentar er litt kjipt, så lar det ligge litt!

refactor: panda for regular form accordions

---

src/containers/StructurePage/folderComponents/SettingsMenuDropdownType.tsx
src/containers/StructurePage/folderComponents/sharedMenuOptions/ConnectExistingNode.tsx
src/containers/StructurePage/folderComponents/topicMenuOptions/CopyNodeResources.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Separate placeholders for kopiering og kloning

---

src/components/SaveButton.tsx
src/components/SaveMultiButton.tsx
src/containers/ArticlePage/LearningResourcePage/components/taxonomy/TaxonomyBlock.tsx
src/containers/ArticlePage/TopicArticlePage/components/TopicTaxonomyBlock.tsx
src/containers/AudioUploader/components/AudioForm.tsx
src/containers/ConceptPage/ConceptForm/ConceptFormFooter.tsx
src/containers/EditMarkupPage/EditMarkupPage.tsx
src/containers/EditSubjectFrontpage/components/SubjectpageForm.tsx
src/containers/FrontpageEditPage/FrontpageEditPage.tsx
src/containers/ImageUploader/components/ImageForm.tsx
src/containers/NdlaFilm/components/NdlaFilmForm.tsx
src/containers/Podcast/components/PodcastForm.tsx
src/containers/PodcastSeries/components/PodcastSeriesForm.tsx
src/containers/SearchPage/SearchSaveButton.tsx
src/containers/StructurePage/folderComponents/subjectMenuOptions/ChangeNodeName.tsx
src/containers/TaxonomyVersions/components/VersionForm.tsx

Tok knappene ved siden av en `SaveButton` i samme slengen.

refactor: SaveButton to new Button

---

src/containers/Messages/Messages.tsx
src/containers/Messages/__tests__/__snapshots__/Messages-test.tsx.snap

Har en liten mistanke om at vi ikke egentlig trenger dette lenger

refactor: drop alert overlay in Messages

---

src/containers/StructurePage/StructureContainer.tsx
src/containers/StructurePage/folderComponents/topicMenuOptions/GroupTopicResources.tsx
src/containers/StructurePage/resourceComponents/ResourcesContainer.tsx
src/containers/StructurePage/resourceComponents/StructureResources.tsx
src/containers/StructurePage/resourceComponents/TopicResourceBanner.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Denne skulle visst tilbake! Dette er kun å legge tilbake gammel kode som ble fjernet i refactor av taksonomi

Add switch to toggle grouped resources in topic banner

---

src/components/SlateEditor/plugins/comment/inline/index.tsx
src/components/SlateEditor/plugins/concept/inline/index.tsx

Forklaring fjernes dersom du bruker backspace på siste bokstav, men ikkje ved bruk av delete. Dette fikser dette.

Unwrap concept on delete

---

src/components/SlateEditor/plugins/audio/index.tsx
src/components/SlateEditor/plugins/blockquote/index.tsx
src/components/SlateEditor/plugins/campaignBlock/index.tsx
src/components/SlateEditor/plugins/codeBlock/index.tsx
src/components/SlateEditor/plugins/comment/block/index.tsx
src/components/SlateEditor/plugins/comment/inline/index.tsx
src/components/SlateEditor/plugins/concept/block/index.tsx
src/components/SlateEditor/plugins/concept/inline/index.tsx
src/components/SlateEditor/plugins/contactBlock/index.tsx
src/components/SlateEditor/plugins/copyright/index.ts
src/components/SlateEditor/plugins/embed/index.tsx
src/components/SlateEditor/plugins/external/index.ts
src/components/SlateEditor/plugins/file/index.tsx
src/components/SlateEditor/plugins/footnote/index.tsx
src/components/SlateEditor/plugins/framedContent/index.tsx
src/components/SlateEditor/plugins/h5p/index.tsx
src/components/SlateEditor/plugins/image/index.ts
src/components/SlateEditor/plugins/keyFigure/index.tsx
src/components/SlateEditor/plugins/linkBlockList/index.tsx
src/components/SlateEditor/plugins/pitch/index.tsx
src/components/SlateEditor/plugins/related/index.tsx
src/components/SlateEditor/plugins/uuDisclaimer/index.ts
src/components/SlateEditor/plugins/video/index.ts
src/util/__tests__/embedTagHelpers-test.ts
src/util/articleContentConverter.tsx
src/util/embedTagHelpers.tsx

Kan sees i artikler med fil-lister, relatert innhold og lenkeblokker.

Fix react unique key warnings in slate plugins

---

src/components/NodeIconType.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Skal vi gidde å legge inn et spesielt ikon for utdanningsprogram?

refactor: use new icons in NodeIconType

---

src/components/Layout/MastheadLayout.tsx
src/components/Layout/PageLayout.tsx
src/components/Page/Layout.tsx
src/containers/App/App.tsx
src/containers/H5PPage/H5PPage.tsx

Gjort i all hovedsak for å fjerne `PageContainer` fra `@ndla/ui`, men kan godt hende at det hjelper litt på ytelse også! Trooor alle sidene skal rendre likt som før.

refactor: do not render any components in App

---

src/components/SlateEditor/plugins/mathml/EditMath.tsx

Bjarne vil ha lagring på taborder 3 og ikkje 4.

Change tab order for save

---

src/components/AlertDialog/AlertDialog.tsx
src/components/QualityEvaluation/AverageQualityEvaluation.tsx
src/components/SlateEditor/EditorFooter.tsx
src/components/SlateEditor/plugins/blockPicker/SlateBlockPicker.tsx
src/components/SlateEditor/plugins/comment/inline/index.tsx
src/components/SlateEditor/plugins/comment/inline/utils.ts
src/components/SlateEditor/plugins/concept/inline/index.tsx
src/components/SlateEditor/plugins/copyright/index.ts
src/components/SlateEditor/plugins/file/index.tsx
src/components/SlateEditor/plugins/heading/index.tsx
src/components/SlateEditor/plugins/table/index.tsx
src/components/SlateEditor/plugins/table/matrixHelpers.ts
src/components/SlateEditor/plugins/video/EditVideo.tsx
src/containers/ArticlePage/components/CommentSection.tsx
src/containers/ArticlePage/components/RevisionNotes.tsx
src/containers/EditSubjectFrontpage/components/SubjectpageSubjectlinks.tsx
src/containers/FormikForm/GrepCodesField.tsx
src/containers/FormikForm/components/MetaImageField.tsx
src/containers/GlossPage/components/ExamplesFieldArray.tsx
src/containers/NdlaFilm/components/NdlaFilmArticle.tsx
src/containers/NdlaFilm/components/ThemeEditor.tsx
src/containers/PodcastSeries/components/PodcastEpisodes.tsx
src/containers/StructurePage/AddNodeModalContent.tsx
src/containers/StructurePage/folderComponents/sharedMenuOptions/DeleteNode.tsx
src/containers/StructurePage/folderComponents/subjectMenuOptions/ChangeNodeName.tsx
src/containers/StructurePage/folderComponents/topicMenuOptions/PublishChildNodeResources.tsx
src/containers/StructurePage/plannedResource/AddExistingResource.tsx
src/containers/StructurePage/plannedResource/PlannedResourceForm.tsx
src/modules/embed/embedApi.ts
src/modules/embed/queries.ts

chore: remove unused imports and variable declarations

---

src/components/HeaderWithLanguage/EmbedInformation/EmbedConnection.tsx
src/components/HeaderWithLanguage/HeaderInformation.tsx
src/components/SlateEditor/plugins/blockPicker/SlateBlockPicker.tsx
src/components/SlateEditor/plugins/footnote/index.tsx
src/components/SlateEditor/plugins/uuDisclaimer/DisclaimerForm.tsx
src/components/SlateEditor/plugins/uuDisclaimer/SlateDisclaimer.tsx
src/containers/Podcast/components/PodcastForm.tsx
src/containers/SearchPage/SearchSaveButton.tsx
src/containers/WelcomePage/hooks/storedFilterHooks.tsx

refactor: reduce ternary logic usage

---

src/components/Taxonomy/TopicConnections.tsx
src/containers/ArticlePage/LearningResourcePage/components/taxonomy/TaxonomyBlock.tsx
src/containers/ArticlePage/LearningResourcePage/components/taxonomy/TaxonomyInfo.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Remove FieldHeader usage in TaxonomyBlock

---

src/components/SlateEditor/EditorFooter.tsx
src/containers/ArticlePage/FrontpageArticlePage/components/FrontpageArticleForm.tsx
src/containers/ArticlePage/LearningResourcePage/components/LearningResourceForm.tsx
src/containers/ArticlePage/TopicArticlePage/components/TopicArticleForm.tsx

Finnes vel ikke lenger. Beholdt funksjon i tilfelle det plutselig skal inn igjen i fremtiden. Gjerne si fra om dere er uenige i det!

chore: remove validation traces

---

src/containers/Session/SessionProvider.tsx
src/containers/StructurePage/folderComponents/subjectMenuOptions/ChangeNodeName.tsx

Er dette egentlig noe vi vil ha der?

chore: ignore console.log warnings

---

src/components/HeaderWithLanguage/DeleteLanguageVersion.tsx

chore: add default case when deleting language version

---

src/containers/EditSubjectFrontpage/components/SubjectpageAbout.tsx
src/containers/FormikForm/components/VisualElementField.tsx

Forslag til håndtering av spacing!

SubjectPageAbout: Use FormContent + replace FormikField with FormField

---

src/containers/ArticlePage/FrontpageArticlePage/components/FrontpageArticleFormContent.tsx
src/containers/ArticlePage/LearningResourcePage/components/LearningResourceContent.tsx
src/containers/ArticlePage/TopicArticlePage/components/TopicArticleAccordionPanels.tsx
src/containers/ArticlePage/TopicArticlePage/components/TopicArticleContent.tsx
src/containers/ConceptPage/components/ConceptContent.tsx
src/containers/FormikForm/IngressField.tsx

Skriver om alle stedene med Ingress

Use FormContent + replace FormikField with FormField

---

src/components/H5PElement/h5pApi.ts
src/components/SlateEditor/plugins/h5p/SlateH5p.tsx
src/config.ts
src/modules/h5p/h5pMutations.ts
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Får en 403 på selve embeden etter at den er kopiert. Usikker på om det er noe jeg gjør galt eller om det er noe h5p finner på?

feat: add support for copying h5p embeds

---

src/containers/AudioUploader/components/AudioContent.tsx
src/containers/AudioUploader/components/AudioForm.tsx
src/containers/Podcast/components/PodcastForm.tsx

Lurer på om det er like greit dette blir en p? var h2 tidligere, men det er nok lurt å gå bort ifra, eventuelt kunne det vært label, men vanskelig å riktig få knyttet den til input 😅

Remove FieldHeader in AudioContent

---

src/components/Form/SegmentHeader.tsx
src/containers/ArticlePage/FrontpageArticlePage/components/FrontpageArticleFormContent.tsx
src/containers/ArticlePage/LearningResourcePage/components/LearningResourceContent.tsx
src/containers/ArticlePage/TopicArticlePage/components/TopicArticleContent.tsx
src/containers/FormikForm/components/VisualElementField.tsx

Remove FieldHeader usage

---

src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Språkfolka ber om endring i formulering.

HTML i editor - oppdatert varsel

---

src/containers/ArticlePage/FrontpageArticlePage/components/FrontpageArticlePanels.tsx
src/containers/ArticlePage/LearningResourcePage/components/LearningResourcePanels.tsx
src/containers/ArticlePage/TopicArticlePage/components/TopicArticleAccordionPanels.tsx
src/containers/ArticlePage/components/CommentSection.tsx

Fikser opp i: editorial-frontend-master.vercel.app/subject-matter/learning-resource/38782/edit/nb

Fix overflow issue by removing auto column sizing

---

src/components/HeaderWithLanguage/HeaderFavoriteStatus.tsx
src/containers/Masthead/components/MastheadDrawer.tsx
src/containers/Masthead/components/MastheadSearch.tsx
src/modules/draft/draftApi.ts
src/util/__tests__/htmlHelpers-test.ts
src/util/htmlHelpers.ts
src/util/routeHelpers.ts

Støtter innliming av urler til utdanningsprogram og fag.

Handle urlpaste for subject and programme

---

src/containers/ArticlePage/components/RevisionNotes.tsx

Button alignment at start

---

src/containers/Masthead/components/MastheadSearch.tsx
src/util/routeHelpers.ts

Korte urler til læringsstier må også kunne limes inn

Add support for pasting learningpaths

---

src/components/DraggableItem.tsx
src/components/abstractions/Combobox.tsx
src/containers/FrontpageEditPage/FrontpageArticleSearch.tsx
src/containers/FrontpageEditPage/FrontpageEditPage.tsx
src/containers/FrontpageEditPage/FrontpageNode.tsx
src/containers/FrontpageEditPage/FrontpageNodeList.tsx

Improvisert designet, syntes det ble litt mer oversiktlig enn det var! men lov å komme med innspill 🤓

Frontpage refactor

---

src/constants.ts
src/containers/Masthead/components/SubNavigation.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Prøvde å holde ting relativt likt

refactor: use primitives in SubNavigation

---

src/containers/SearchPage/components/form/SearchContentForm.tsx

Make FieldRoot take full width at tabletDown breakpoint

---

src/containers/FrontpageEditPage/FrontpageArticleSearch.tsx
src/containers/FrontpageEditPage/FrontpageEditPage.tsx

Gir ikkje meining at du ikkje skal kunne legge til i menyen.

Make it possible to add copyrighted articles to frontpage menu

---

src/modules/taxonomy/taxonomyApi.ts

Fixes https://github.com/NDLANO/Issues/issues/4237
Såvidt jeg vet blir nye emner opprettet i struktur automatisk usynlige

fix: default visibility to false when creating new topic articles

---

package.json
src/components/Transcribe/helpers.ts
src/config.ts
src/server/api.ts
yarn.lock

Transcribe endepunkter for å kunne få tekst fra en lydfil på s3 og kunne polle for å sjekke status på transkriberingen. 
Transkribering tar litt tid så deler derfor i to endepunkter.

Transcribe endpoints

---

src/components/SlateEditor/plugins/span/index.tsx
src/components/SlateEditor/plugins/span/render.tsx
src/components/SlateEditor/plugins/toolbar/ToolbarLanguageOptions.tsx

https://github.com/NDLANO/Issues/issues/4205
Vi må nok migrere litt i backend også

feat: automatically set direction when language is ar

---

src/components/Taxonomy/NodeItem.tsx
src/containers/NodeDiff/TreeNode.tsx
src/containers/StructurePage/NodeItem.tsx

Prøvd å ikke gjøre altfor mye 😅

Tree node refactor

---

src/containers/FormikForm/GrepCodesField.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

fixes https://github.com/NDLANO/Issues/issues/4243
For å få paginering blandt annet! Ser ingen grunn til at dette ikke skal være GenericSearchCombobox nå 🤔

Use GenericSearchCombobox for grepCodes

---

.github/workflows/ci.yml
.github/workflows/release.yml

Bump actions/cache to v4

---

src/components/SlateEditor/plugins/related/EditRelated.tsx

Fikser at dialog lukker seg når man prøver å legge til relatert innhold

Wrap combobox in FieldRoot to not inherit editor field

---

src/components/SlateEditor/plugins/comment/CommentPopoverPortal.tsx

fixes https://github.com/NDLANO/Issues/issues/4261

Fix inline comments behaviour after upgrading to React 19

---

src/components/Taxonomy/RelevanceOption.tsx
src/components/Taxonomy/types.ts
src/containers/StructurePage/NodeItem.tsx
src/containers/StructurePage/folderComponents/NodeControls.tsx
src/containers/StructurePage/folderComponents/SettingsMenu.tsx
src/containers/StructurePage/folderComponents/SettingsMenuDropdownType.tsx
src/containers/StructurePage/folderComponents/StructureErrorIcon.tsx
src/containers/StructurePage/plannedResource/PlannedResourceForm.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

https://trello.com/c/AMVczWMe/1185-kunne-sette-kjernestoff-tilleggstoff-p%C3%A5-emner-i-struktur-via-redigerings-menyen
Legger til mulighet for å styre kjernestoff/tilleggstoff for emner i struktur!

Add possibility to update relevance for topics in strucuture

---

src/components/SlateEditor/plugins/comment/CommentPopoverPortal.tsx
src/components/SlateEditor/plugins/comment/inline/SlateCommentInline.tsx

Fix issue with inline comments introduced when upgrading to React 19

---

src/components/SlateEditor/plugins/comment/block/SlateCommentBlock.tsx
src/components/SlateEditor/plugins/comment/inline/SlateCommentInline.tsx

https://trello.com/c/MusOK5Hp/1181-for-svak-gulfarge-p%C3%A5-merknad-i-tekst-i-ed

Update inline + block comment color

---

src/components/SlateEditor/plugins/details/render.tsx

fixes https://github.com/NDLANO/Issues/issues/4251

Fix link and comment inlines in details summary

---

.github/workflows/release.yml

Henter versjoner fra variabler på organisasjonen

Use vars for versions

---

src/util/diffHTML.ts

Dette gjør at diff-visninga ikkje knekker.
https://trello.com/c/90zPeWIW/1201-fikse-feil-i-marker-forskjeller

Use innerHtml for diff-view

---

src/components/PreviewDraft/TransformedPreviewDraft.tsx

Oppdatering i henhold til design!

Disclaimer in article as dialog

---

src/containers/StructurePage/folderComponents/subjectMenuOptions/ToggleExplanationSubject.tsx

Disable setting forklaringsfag

---

src/components/SlateEditor/plugins/concept/SearchConceptForm.tsx
src/containers/FormikForm/components/ResponsibleSelect.tsx
src/containers/SearchPage/components/form/SearchContentForm.tsx
src/containers/SearchPage/components/form/SearchForm.tsx
src/containers/SearchPage/components/form/SearchImageForm.tsx
src/containers/StructurePage/folderComponents/subjectMenuOptions/SubjectCustomFieldSelector.tsx
src/containers/StructurePage/plannedResource/PlannedResourceForm.tsx
src/server/auth.ts

Fixes https://github.com/NDLANO/Issues/issues/4277
Kall meg frontend-jonas

Add users filtering to `SearchImageForm`

---

src/components/HeaderWithLanguage/HeaderInformation.tsx
src/components/HeaderWithLanguage/HeaderWithLanguage.tsx

https://trello.com/c/b0iTLJlF/1239-innholdstype-blir-konsekvent-vist-som-fagstoff-i-toppen-av-ressurser

Show content type in badge from taxonomy on resources

---

src/containers/ConceptPage/components/ConceptMetaData.tsx
src/containers/FormikForm/MetaDataField.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Rename to tags

---

src/components/validators.ts

fixes https://github.com/NDLANO/Issues/issues/4288

Add if block for NOOP validation in isEmpty

---

src/components/PreviewDraft/PreviewDraft.tsx
src/components/PreviewDraft/useTransformedArticle.ts

Fikser korrekt farge for denne https://trello.com/c/XrulHWyQ/1238-forh%C3%A5ndsvisning-i-ed-viser-ikke-farge-p%C3%A5-tekstboks-hvis-denne-er-satt

Send contenttype to transform to get correct color for variants.

---

src/components/validators.ts

Ser ut som valideringen var litt for streng. Denne løsern litt mer opp 🤠

Fix validation on noops so its not too strict

---

src/components/SlateEditor/plugins/external/ExternalEmbedForm.tsx
src/components/SlateEditor/plugins/external/SlateExternal.tsx
src/constants.ts
src/server/contentSecurityPolicy.ts

Støtter to nye embeds. Fikser også at eksterne ressurser ikkje tolkes som H5P på mouseover på redigering og sletting

Support new urls. Fix edit labels.

---

src/containers/FormikForm/GrepCodesField.tsx

Gjør det (kanskje) litt lettere å huske at du kan søke på læreplankode også.

Display laereplan in grep-search

---

src/components/SlateEditor/EditorFooter.tsx
src/containers/ArticlePage/FrontpageArticlePage/components/FrontpageArticleForm.tsx
src/containers/ArticlePage/LearningResourcePage/components/LearningResourceForm.tsx
src/containers/ArticlePage/TopicArticlePage/components/TopicArticleForm.tsx
src/containers/ConceptPage/ConceptForm/ConceptForm.tsx
src/containers/ConceptPage/ConceptForm/ConceptFormFooter.tsx
src/containers/ConceptPage/conceptTransformers.ts
src/containers/FormikForm/components/ResponsibleSelect.tsx
src/containers/FormikForm/components/StatusSelect.tsx
src/containers/GlossPage/components/GlossForm.tsx

Prøver å fjerne så mye redundant state-logikk som mulig og tar heller i bruk formik-values! Lurt å være litt nøye på testingen her tror jeg 😄

Simplify EditorFooter logic 

---

src/components/SlateEditor/RichTextEditor.tsx
src/components/SlateEditor/plugins/blockPicker/SlateBlockPicker.tsx

fix: ensure block picker shows up when it should

---

src/containers/FormikForm/GrepCodesField.tsx

Litt dumt at mulighet for å fjerne flere grep-koder på enter forsvant, denne fikser!

Add grep codes on enter click

---

src/components/AlertDialog/AlertDialog.tsx
src/components/SlateEditor/EditorFooter.tsx
src/containers/ArticlePage/FrontpageArticlePage/components/FrontpageArticleForm.tsx
src/containers/ArticlePage/LearningResourcePage/components/LearningResourceForm.tsx
src/containers/ArticlePage/TopicArticlePage/components/TopicArticleForm.tsx
src/containers/FormikForm/utils.ts
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

fixes https://github.com/NDLANO/Issues/issues/4291

Show alert dialog when publishing article with unpublished concepts

---

src/containers/StructurePage/folderComponents/SettingsMenuDropdownType.tsx

Hide visibility and diff if not tax-admin in settings menu

---

package.json
src/config.ts
src/containers/StructurePage/StructureBanner.tsx
src/containers/StructurePage/StructureContainer.tsx
src/containers/StructurePage/resourceComponents/MatomoStats.tsx
src/containers/StructurePage/resourceComponents/Resource.tsx
src/containers/StructurePage/resourceComponents/ResourceItems.tsx
src/containers/StructurePage/resourceComponents/ResourcesContainer.tsx
src/containers/StructurePage/resourceComponents/StatusIcons.tsx
src/containers/StructurePage/resourceComponents/StructureResources.tsx
src/containers/StructurePage/resourceComponents/TopicResourceBanner.tsx
src/containers/StructurePage/utils.ts
src/modules/matomo/matomoApi.ts
src/modules/matomo/matomoQueries.ts
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts
src/queryKeys.ts
src/server/api.ts
src/server/httpCodes.ts
src/server/matomo.ts
src/util/apiHelpers.ts
yarn.lock

fixes https://github.com/NDLANO/Issues/issues/4296
Jeg er litt usikker på hvordan dataen burde vises frem i struktur, så gjerne kom med innspill!

Fetch data from matomo

---

src/components/SlateEditor/RichTextEditor.tsx

Fixes https://github.com/NDLANO/Issues/issues/4319
Har gjenskapt kommentarene her: http://localhost:3000/subject-matter/learning-resource/42492/edit/nb

perf: only typeset mathjax if math exists in the article

---

src/components/SlateEditor/RichTextEditor.tsx

Ser egentlig ingen grunn til at vi har dette. Editoren blir raskere dersom vi fjerner det.

chore: drop tab handling in editor. It's too expensive to calculate for the benefit it brings

---

src/containers/ArticlePage/components/commentToolbarUtils.ts

Rendrer paragraf i paragraf i kommentar

fix: use divRenderer in comment, avoiding p in p

---

src/containers/ConceptPage/ConceptForm/ConceptForm.tsx
src/containers/ConceptPage/components/ConceptMetaData.tsx
src/containers/ConceptPage/conceptTransformers.ts

Fjerner håndtering av metabide for forklaring.

Ignore metaimage for concept. To be removed.

---

src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Me hentar nb_hits, nb_visits og avg_time_on_page.
Det kan me oversette til besøk, sidevisingar og gjennomsnittleg tid på sida. Endra på nokre formuleringar. ../index.php?module=API&method=Actions.getPageUrls&idSite=3&period=year&date=last1&format=JSON&showColumns=nb_visits,nb_hits,avg_time_on_page&token_auth=TOKEN&flat=1&filter_pattern=fe71c65f0c%24

Omformuleringar

---

src/containers/StructurePage/LeftColumn.tsx
src/containers/StructurePage/NodeItem.tsx
src/containers/StructurePage/PreferencesProvider.tsx
src/containers/StructurePage/RootNode.tsx
src/containers/StructurePage/StructureBanner.tsx
src/containers/StructurePage/StructureContainer.tsx
src/containers/StructurePage/resourceComponents/StructureResources.tsx
src/containers/StructurePage/resourceComponents/SubjectBanner.tsx

Prop-drillingen begynte å bli litt voldsom i struktur 😅

Structure preferences to provider

---

src/config.ts
src/containers/StructurePage/StructureBanner.tsx

Add config flag to turn on or off matomodata

---

src/components/SlateEditor/plugins/toolbar/ToolbarLanguageOptions.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

https://trello.com/c/SHi7jyjx/1330-endring-p%C3%A5-formateringsmenyen

Make languageselect clearable

---

src/config.ts
src/containers/App/App.tsx
src/containers/Masthead/components/MastheadDrawer.tsx
src/containers/UpdateCodes/UpdateCodesPage.tsx
src/modules/draft/draftApi.ts
src/modules/draft/draftMutations.ts
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts
src/util/routeHelpers.ts

fixes https://github.com/NDLANO/Issues/issues/4332

Add page for updating grep codes

---

src/components/LastUpdatedLine/DateEdit.tsx

DateEdit trigger button as tertiary

---

src/components/SlateEditor/plugins/image/ImageEmbedForm.tsx

fixes https://github.com/NDLANO/Issues/issues/4337
Dette vil kun gi oppførselen ved nyproduksjon som står i trellokortet!

Remove caption for decorative images

---

src/components/HeaderWithLanguage/CloneImageDialog.tsx
src/containers/ImageUploader/components/ImageUploadFormElement.tsx

Fix cloning of images with SVG filetype

---

src/components/ContentTypeProvider.tsx
src/components/NynorskTranslateProvider.tsx
src/components/PreviewDraft/PreviewVersion.tsx
src/components/SlateEditor/ArticleLanguageProvider.tsx
src/components/SlateEditor/IsNewArticleLanguageProvider.tsx
src/components/SlateEditor/SlateContext.tsx
src/components/SlateEditor/plugins/grid/GridContext.tsx
src/components/ToastProvider.tsx
src/components/WideArticleEditorProvider.tsx
src/containers/Messages/MessagesProvider.tsx
src/containers/Session/SessionProvider.tsx
src/containers/StructurePage/PreferencesProvider.tsx
src/containers/StructureVersion/TaxonomyVersionProvider.tsx

Kommer til å bli deprecated etterhvert!
https://react.dev/blog/2024/12/05/react-19#context-as-a-provider

Context as provider

---

src/components/Form/SearchSaveButton.tsx
src/components/Form/SearchTagGroup.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

fikser feks: https://ed.test.ndla.no/search/content?exclude-revision-log=false&fallback=false&filter-inactive=true&include-other-statuses=false&includeCopyrighted=true&page=1&page-size=10&query=%22test%22&sort=-lastUpdated

Fix i18n escaping of values in search query

---

src/components/SlateEditor/plugins/framedContent/SlateFramedContent.tsx
src/components/SlateEditor/plugins/rephrase/Rephrase.tsx
src/containers/FormikForm/MetaDataField.tsx
src/containers/ImageUploader/components/ImageContent.tsx
src/modules/llm/llmApiTypes.ts
src/modules/llm/llmMutations.ts

Forenkler forhåpentligvis koden litt 😄

Generic AI mutation

---

src/components/SlateEditor/plugins/campaignBlock/index.tsx
src/components/SlateEditor/plugins/codeBlock/index.tsx
src/components/SlateEditor/plugins/comment/block/index.tsx
src/components/SlateEditor/plugins/concept/block/index.tsx
src/components/SlateEditor/plugins/external/index.ts
src/components/SlateEditor/plugins/grid/index.tsx
src/components/SlateEditor/plugins/h5p/index.tsx
src/components/SlateEditor/plugins/uuDisclaimer/index.ts

Vi kan ikke gå helt over ennå, men vi nærmer oss!

chore: use editor imports where possible

---

src/containers/StructurePage/resourceComponents/ResourceItems.tsx

https://trello.com/c/d1lM4jKZ/1340-sortering-struktur-vurdere-evt-forbedring

Invalidare queries on drag end

---

src/components/FileUploader/FileUploader.tsx

https://trello.com/c/7GjRt0fw/1337-filer-i-ed 
+ fikser at man kan lagre flere om man trykker fort på lagre-knapp

Remove required on FileUploader FieldRoot + disable save button when submitting

---

src/components/SlateEditor/plugins/table/render.tsx
src/components/SlateEditor/plugins/table/slateActions.ts

fixes https://github.com/NDLANO/Issues/issues/4348
Tror dette skal være nok! (?)

Properly align cell header in table

---

src/components/SlateEditor/interfaces.ts
src/components/SlateEditor/plugins/break/index.tsx
src/components/SlateEditor/plugins/div/index.tsx
src/components/SlateEditor/plugins/div/queries.ts
src/components/SlateEditor/plugins/div/render.tsx
src/components/SlateEditor/plugins/div/types.ts
src/containers/ArticlePage/components/InputComment.tsx
src/containers/StructurePage/plannedResource/PlannedResourceForm.tsx

refactor: build div plugin on top of new plugin system

---

src/containers/StructurePage/NodeItem.tsx
src/containers/StructurePage/SafeLinkWithQuery.tsx
src/containers/StructurePage/StructureBanner.tsx
src/containers/StructurePage/resourceComponents/Resource.tsx
src/containers/StructurePage/resourceComponents/ResourceItems.tsx
src/containers/StructurePage/resourceComponents/ResourcesContainer.tsx
src/containers/StructurePage/resourceComponents/TopicResourceBanner.tsx
src/containers/StructurePage/resourceComponents/isVisibleHook.ts
src/containers/StructurePage/utils.ts
src/modules/matomo/matomoApi.ts
src/modules/matomo/matomoQueries.ts
src/server/api.ts
src/server/matomo.ts

https://trello.com/c/vFGFMCxc/1277-vise-data-fra-matomo-i-struktur-i-ed
Ser at dette hvertfall tar ca halvparten av tiden for emner med mange ressurser (~400), så det er jo hvertfall lovende!
NB: Har enda ikke testet dette mot Matomo i prod, kun i test

Update Matomo fetch: performance optimizations

---

src/components/SlateEditor/plugins/concept/inline/InlineWrapper.tsx

https://trello.com/c/Pe8gEFMZ/1338-for-svak-markering-av-forklaringer-i-editor

Update concepts color in editor

---

src/components/SlateEditor/plugins/toolbar/SlateToolbar.tsx

Dette ser også ut til å fikse et problem som Amandus møtte på i dialog i dialog i dialog x 300.
Test at toolbaren funker akkurat som før med tanke på åpning og lukking, spesielt når en flytter seg fra en editor til en annen.

perf: reduce the amount of times we check to see whether the popover should be open/closed

---

src/containers/StructurePage/resourceComponents/MatomoStats.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

https://trello.com/c/vFGFMCxc/1277-vise-data-fra-matomo-i-struktur-i-ed#comment-681891fdf854e7670bc86b80

fix: always show matomo button if enabled, regardless of data

---

src/containers/StructurePage/resourceComponents/MatomoStats.tsx

Mer justeringsønsker fra BM og Guttorm! Ligger på toppen av det som er i prod.

hotfix: display hits instead of visits

---

src/components/SlateEditor/plugins/table/__tests__/caption-normalizer-test.ts
src/components/SlateEditor/plugins/table/__tests__/cell-normalizer-test.ts
src/components/SlateEditor/plugins/table/__tests__/container-normalizer-test.ts
src/components/SlateEditor/plugins/table/__tests__/row-normalizer-test.ts
src/components/SlateEditor/plugins/table/__tests__/table-normalizer-test.ts
src/components/SlateEditor/plugins/table/__tests__/tableTestHelpers.ts

Det er en del som allerede er dekket i `normalizer-test`, men tenker det er greit å ha duplikater i første omgang.

chore: add more table tests

---

src/server/matomo.ts

Litt fleire urler sjekkes mot matomo

Also check en and se for numbers

---

src/components/SlateEditor/plugins/toolbar/ToolbarLanguageOptions.tsx

Display values with less padding

---

src/containers/FormikForm/articleFormHooks.ts

Fixes https://github.com/ndlano/issues/issues/4368

fix: return early if already saving

---

src/components/SlateEditor/interfaces.ts
src/components/SlateEditor/plugins/toolbar/SlateToolbar.tsx
src/components/SlateEditor/plugins/toolbar/index.ts

Fixes https://trello.com/c/mn4Utyfv/1384-bildebug-2-i-ed
Fixes https://github.com/ndlano/issues/issues/4378

fix: do not assume that the toolbar plugin exists

---

src/util/audioHelpers.ts

Fixes https://github.com/NDLANO/Issues/issues/4379

fix: initialize hasRSS as boolean when loading series form

---

src/modules/audio/audioApi.ts
src/modules/image/imageApi.ts

Fixes https://github.com/ndlano/issues/issues/4377
Fixes https://trello.com/c/k2k2nc2C/1383-bildebug-i-ed
Samme bug gjaldt også lyd og podkastserier. Er det noen andre steder vi kan ha gått på samme smellen?

fix: do not parse JSON when deleting language versions

---

src/containers/WelcomePage/components/WelcomeHeader.tsx

https://trello.com/c/l6RxVlX0/1392-feil-lenke-til-siste-hjertemarkerte-ressurs-p%C3%A5-dashboard
Læringsstier blir linka feil

Link recent learningpath to learningpath

---

.github/workflows/ci.yml

ved nærmere ettertanke så trenger vi vel ikke å logge inn i docker her?

remove docker logins on ci

---

src/containers/App/SearchPage.tsx
src/containers/SearchPage/AudioSearch.tsx
src/containers/SearchPage/ContentSearch.tsx
src/containers/SearchPage/ImageSearch.tsx
src/containers/SearchPage/PodcastSeriesSearch.tsx
src/containers/SearchPage/SearchContainer.tsx
src/containers/SearchPage/SearchPageHeader.tsx

Legger til rette for at man kan lazy-loade kun de søkesidene man trenger!

refactor: do not generate search pages dynamically

---

src/components/SlateEditor/plugins/singleLine/__tests__/normalizer-test.ts
src/components/SlateEditor/plugins/singleLine/index.ts
src/components/SlateEditor/plugins/singleLine/types.ts
src/containers/FormikForm/TitleField.tsx

Prøver igjen! Tar nå hensyn til at man kan ha flere barn, så lenge ingen av de er blokk-elementer!

feat: add single line plugin

---

src/containers/FormikForm/GrepCodesField.tsx

Skal også legge inn søk på koden.

Displays kv-code in grepsearchresult

---

src/config.ts

Funker ikkje å logge inn i dag om du kjørere med NDLA_ENVIRONMENT=local

Make login work with local env

---

src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Rename private status in ed

---

src/containers/LearningpathPage/LearningpathForm.tsx
src/containers/LearningpathPage/components/LearningpathTextEditor.tsx
src/containers/LearningpathPage/learningpathFormUtils.ts
src/containers/LearningpathPage/metadata/LearningpathMetaFormPart.tsx
src/containers/LearningpathPage/steps/ExternalStepForm.tsx
src/containers/LearningpathPage/steps/ResourceStepForm.tsx
src/containers/LearningpathPage/steps/TextStepForm.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts
src/util/formHelper.ts

Fixes https://github.com/NDLANO/Issues/issues/4413

feat: add learningpath introduction

---

src/containers/StructurePage/resourceComponents/GrepCodesDialog.tsx
src/containers/StructurePage/resourceComponents/Resource.tsx
src/containers/StructurePage/resourceComponents/ResourceItems.tsx
src/containers/StructurePage/resourceComponents/ResourcesContainer.tsx
src/containers/StructurePage/resourceComponents/TopicResourceBanner.tsx

Fixes https://github.com/NDLANO/Issues/issues/4419
Fixes https://trello.com/c/LDHCZdEs/1445-kompetansem%C3%A5l-vise-kompetansem%C3%A5lsett-p%C3%A5-dialog-i-struktur
Justerte littegrann på forslaget fra Trello. Tror det de foreslår har en relativt høy sjanse for å overflowe.

feat: display kv in grep dialog

---

src/config.ts
src/containers/Masthead/components/MastheadDrawer.tsx
src/containers/SearchPage/components/form/SearchContentForm.tsx
src/containers/StructurePage/plannedResource/PlannedResourceForm.tsx
src/routes.tsx
src/util/routeHelpers.ts

Drop config flags and menu point
