src/containers/Login/LoginProviders.js
In addition to remove Facebook as a login option, `LoginProviders` is refactored so that it returns an array instead of tags wrapped in a div.
=> Removes facebook as login option #1071

src/util/__tests__/__snapshots__/slateHelpers-test.js.snap, src/util/slateHelpers.js
resolves https://github.com/NDLANO/Issues/issues/1085
Fixes rendering of saved footnote in editor
- Shows pound sign (#) inline in a learning resource
=> Fixed broken footnote

src/components/DisplayEmbedTag/DisplayExternal.jsx
`providerName` for H5P-s changed case in response
Test procedure:
- Check that edit button (pencil) appears on articles with H5P
- Check that edit button (pencil) appears when adding new H5Ps to articles
=> fix: upper case H5P name fix

src/server/Auth0SilentCallback.js
resolves https://github.com/NDLANO/Issues/issues/1345
Auth0 error when renewing token causing client to logout.
Test case:
=> fix: silent callback auth renew causing error and logouts

src/config.js
=> Fixes learningpath frontend domain url in prod #1369

src/components/SlateEditor/plugins/pasteHandler/__tests__/__snapshots__/pasteHandler-test.js.snap, src/components/SlateEditor/plugins/pasteHandler/__tests__/pasteHandler-test.js, src/components/SlateEditor/plugins/pasteHandler/index.js
resolves https://github.com/NDLANO/Issues/issues/1352
Converts to paragraph when pasting into editor content
Test case:
=> fix: handles line type blocks on paste

src/containers/SearchPage/components/results/SearchContent.jsx, src/containers/SearchPage/components/results/SearchContentLanguage.jsx, src/phrases/phrases-en.js, src/phrases/phrases-nb.js, src/phrases/phrases-nn.js, src/style/search.css, src/util/resourceHelpers.js
Resolves 1385
This pullrequest adds alternative URLs for results in the search on different languages. The fix should support the following:
=> Adds other language urls in the search #1385

src/components/SlateEditor/plugins/embed/FigureButtons.jsx
Knappene i WarningModal fungerer ikke når man skal slette et bilde. Foreslår uansett å fjerne WarningModal i dette tilfelle, da vi uansett kan angre med ctrl-z. Vi har heller ikke warning modal for andre slettinger i editoren.
=> Remove warning modal

src/containers/AudioUploader/components/AudioContent.jsx
Resolves https://github.com/NDLANO/Issues/issues/1446
Test Procedure:
=> fix: Disable upload input field if audio id exists

src/components/PreviewDraft/PreviewDraftLightbox.jsx, src/containers/LearningResourcePage/components/LearningResourceForm.jsx, src/containers/TopicArticlePage/components/TopicArticleForm.jsx
revert refactoring to only use transformArticleToApiVersion in previewDraft calls. Other calls to draft-api fails if you use transformArticleToApiVersion
=> Only transform article in previewDraft

src/components/RichTextField.jsx, src/containers/TopicArticlePage/components/TopicArticleContent.jsx
- Fix that slate Editor only renders once on input, and that ingress does not trigger content Editor to re-render
- Reuse ingress component from learning resource
=> Fix topicarticle rendering

src/components/SlateEditor/plugins/embed/index.js
Fixes issue 1621 by inserting empty paragraph after embeds if next block is not a paragraph or heading
=> Always add empty paragraph after embeds

src/containers/LearningResourcePage/components/LearningResourceTaxonomy.jsx
• Endringer i taxonomy ble ikke alltid registrert før de lastes inn på nytt 
• Fikset ved å legge til en liten delay ved lagring før laste inn ny data
• Vise Spinneren når man trykker på lagre
Trello:
https://trello.com/c/XKrbDn2h/145-matematikk-knytte-fagstoff-til-emne-med-samme-navn
=> Delay reloading taxonomy after save

package.json, yarn.lock
Fixes https://trello.com/c/VpLTscvF/129-lang-lastetid-matte
Removes schema rule that alle cell content must be block. We anyway control what we can add to the table elsewhere. 
Includes this commit from ndla-slate-edit-table: https://github.com/NDLANO/slate-edit-table/commit/0af304b5aee7a5793d02ce95ef98b6fc1e2fcde3
=> Fix table slowness

src/components/DisplayEmbed/DisplayExternal.jsx, src/components/DisplayEmbed/DisplayExternalVisualElement.jsx
=> Fixes bug with h5p edit button saves form #1712

src/components/SlateEditor/plugins/SlateToolbar/SlateToolbar.jsx, src/components/SlateEditor/plugins/mathml/MathEditor.js
=> Fixes bug with matheditor not opening from toolbar

package.json, razzle.config.js, yarn.lock
Removes BundleAnalyzerPlugin since it is never used by anyone. Add if needed on a later stage.
=> Removes BundleAnalyzerPlugin

src/util/authHelpers.js
=> #1788: Tell auth0 to always show account selection on authorize()

src/containers/AudioUploader/components/AudioPlayer.jsx
Redigering eller bruk av lyder fører til feilmeldinga "i.pause is not a function". Testa lokalt og ser at ved å kommentere disse ut får vi likevel til å spille av lyder i editoren. Sikkert ikkje blivende løsning, men det må ryddes opp i.
=> Disable effects

src/components/HeaderWithLanguage/DeleteLanguageVersion.jsx, src/modules/concept/conceptApi.js
Litt midlertidig løsning, såå den burde kanskje endres sånn at det blir mer generelt og ikke tilpasset kun for article og concept.
=> Implemented support for delete language version on frontend

src/components/formikValidationSchema.js, src/containers/LearningResourcePage/components/LearningResourceTaxonomy.jsx, src/containers/LearningResourcePage/components/taxonomy/TopicConnections.jsx, src/containers/TopicArticlePage/components/TopicArticleTaxonomy.jsx, src/util/retriveBreadCrumbs.js, src/util/retriveBreadCrumbs.ts
Fix taxonomy changes seemingly failing when saving, because timeout was not big enough
- Don't refetch taxonomy on topicArticles, just calculate new state based on returned path
- Silently refetch taxonomy in learning resources, and increase timeout to 5secs. State should then be updated until next time save is pressed
- Some other bug fixes and refactoring
Check that
=> Fix article taxonomy saving

src/util/__tests__/embedTagHelpers-test.js, src/util/embedTagHelpers.js
Ikke merge denne før det er fikset i backend ref Issue 1867, da vil det ikke funke å opprette drafts uten visuelt element.
=> Make visual element return empty string

src/containers/StructurePage/resourceComponents/AddResourceModal.jsx
Fixes error when pasting url into add resource modal. Still fails though, taxonomy-api returns 409 conflict when adding whatever resource, I think this is something they have changed on their end?
=> fix read from paths when pasting

src/containers/FormikForm/VersionAndNotesPanel.jsx
Saving after reset from article-api fails due to missing statuses.
=> Keep status if article fetched from article-api.

src/containers/NdlaFilm/NdlaFilmEditor.jsx
Løsningen burde nok vært skrevet om slik at den ikke er avhengig av en liste av alle tilgjengelige filmer.  Det blir for tidkrevende i denne omgang. Det er uansett p.t. bare ca 250 filmer.
=> Increase query-limit in search-editor

src/containers/WelcomePage/WelcomePage.tsx
[Issue #2020](https://github.com/NDLANO/Issues/issues/2020)
NDLA ønsker at mine siste artikler må fungere litt anderledes enn det gjør i dag. Vi må derfor skjule funksjonaliteten inntil dei har fått beskreve korleis dei vil ha det. Vi treng ikkje slette noko, berre legge til et flagg som skjuler søket fra forsida.
=> #2020 Hide last used from dashboard

src/containers/FormikForm/FormikMetaImageSearch.jsx
Opplastning av bilde sender et event som både FormikMetaImageSearch _og_ VisualElementSearch bruker.
Det gjør at meta panelet er rendret (åpent) så vil den fange eventet og endre metabilde basert på det opplastede bildet.
=> #2033: Only trigger metaImageUpload when metaImage dialog is showing

scripts/checkArticles/index.js, src/config.js, src/util/diffHTML.js, src/util/slateHelpers.js
cleanUpHtml fjerner innslag av </tag><tag> for f.eks strong.
Men allowStrongRemoval sjekka på <tag/><tag> altså det motsatte.
Fiksen er altså at allowStrongRemoval snus til å sjekke på samme som fjernes i cleanUpHtml.
Er dette en forståelig fiks?
=> Fixing diffing of articles

src/components/PreviewDraft/PreviewDraft.tsx, src/containers/FormikForm/FormikIngress.jsx
Fixes NDLANO/Issues#2141
Skrur på breaks i remarkable for at \n skal rendres som br i visninga.
Forhåndsvisninga i ingress-editor fungerer ikkje optimalt fordi field.value.document.text henter ut teksten fra feltet slått sammen til en lang tekststreng uten separatorer. Har sjekka kva som finnes av verdier i field.value men har ikkje funne bedre måte å gjøre det på.
=> Enable br in markdown in introduction

src/components/SlateEditor/plugins/mathml/MathEditor.js
Redigering av matte feiler om lagra matte ikkje har `<math>` som ytterste ledd. Dette har tidligerere blitt fjerna av vår kode, så endringa må med for at både gamle og nye formler skal virke.
=> Make sure all math is wrapped in math-tag before edit.

src/components/Dropdown/asyncDropdown/AsyncDropdown.jsx, src/containers/FormikForm/articleFormHooks.js, src/containers/FormikForm/formikDraftHooks.js
Dette er litt prøving og feiling, men ser ut til å være et stykke på vei.
Feilen blei innført med oppgradering til formik 2, og det ser ut som om endra resetForm er grunnen til at det feiler. I [migreringsoppskrifta](https://jaredpalmer.com/formik/docs/migrating-v2) står det 
> Because we introduced initialErrors, initialTouched, initialStatus props, resetForm's signature has changed. It now accepts the next initial state of Formik (instead of just the next initial values).
Parameter til resetForm er av type [FormikState](https://github.com/formik/formik/blob/master/packages/formik/src/types.tsx#L39) så eg testa å sette inn formik som parameter i og med at den såg ut til å dekke interfacet. Uten parameter til funksjonen blei formik satt tilbake til staten den hadde ved starten på …
=> Fixing resetting form at save

src/containers/WelcomePage/components/SavedSearch.tsx, src/phrases/phrases-en.js, src/phrases/phrases-nb.js, src/phrases/phrases-nn.js
Fixes NDLANO/Issues#2213
Does not show "ingen søketekst" for saved searches. Found simple code to remove undefineds from array.
=> Hides empty search params

cypress/integration/Taxonomy/topic_spec.js, src/containers/StructurePage/folderComponents/menuOptions/AddExistingToSubjectTopic.jsx, src/containers/StructurePage/folderComponents/menuOptions/AddExistingToTopic.jsx
Fixes NDLANO/Issues#2230
For å unngå problematikk rundt filter ved flytting av emner mellom fag, begrenser dette at emner kun kan flyttes innad i fag.
Alle emner kan flyttes til toppnivå i fag. Men emner kan ikkje flyttes til et underemne av seg sjølv, fordi dette vil føre til en sirkulæravhengighet som vi ikkje får rydda opp i.
Skulle helst ha brukt funksjon for å hente emner i et fag, men det endepunktet returnerer ikkje paths, og det er så vidt eg kan hugse fremdeles mulig at et emne kan ha fleire paths. Når det er endelig rydda opp i kan vi også endre endepunkt.
=> Only allow moving topics within subject

src/containers/App/App.jsx, src/containers/NdlaFilm/components/ElementList.jsx, src/containers/NdlaFilm/components/ElementListItem.tsx, src/interfaces.ts
Lenkene som skulle peke til Learningpaths pekte til LearningResources og articles. Nu er det fikset.
Dobbeltsjekk her: `/subjectpage/urn:subject:34/14/edit/nb`
Under `Artikler`, elementet "Overslagsregning og hoderegning" er en Learningpath, sjekk at lenken sender til siden: https://stier.test.ndla.no/learningpaths/398/step/2978
og at andre lenker linker til artikler ellers.
=> Fix link to learningpath

src/components/SlateEditor/plugins/pastehandler/index.js, src/containers/LearningResourcePage/components/LearningResourceContent.jsx
Om du kopierer tekst fra tekst i ramme og limer inn i samme ramma får du ei ny ramme inni den gamle. For å unngå dette sjekker denne pastehandleren om kor lang path det er fram til plassen der markøren står. Dersom det er mindre enn 4 er du på toppnivået (document > section > markør) og kan la slate håndtere innliminga. Men dersom pathen er lengre er du inni en komponent og då limes berre inn teksten du har kopiert.
PR kan testes ved å kopiere tekst fra kor som helst i dokumentet og lime inn i enten tekst i ramme eller ekspanderboks. Men du skal også kunne kopiere en heil artikkel og lime innholdet inn i en ny artikkel og få med alt av formatering.
=> Only paste text if inside component

src/components/SlateEditor/editorSchema.jsx
Oppdaga en uheldig konsekvens av pastehandler som lar deg paste inn med formatering. Det var et hull i reglene som gjorde at section fra kopiert dokument kunne havne inni en p eller en section. Det forhindres her ved at det sjekkes at en section har en document som parent, og om den ikkje har det så unwrappes sectionen og problemet forsvinner.
Test: 
I ed-test kan du kopiere tekst fra en boks og lime inn i en tom p på rotnivå. Då får du en ny boks med kopiert tekst, men om du ser i html-editoren så ser du at det har havna en section rundt boksen. Lagreknappen blir heller ikkje grønn etter lagring.
I pr skal lagreknappen bli grønn og section skal bli borte fra html-koden.
=> Unwrap if node if section within section.

src/components/SlateEditor/plugins/details/index.tsx, src/util/slateHelpers.js
Eg har irritert meg over at dersom du fjerner en mateformel så settes det inn m i steden for formelen. Denne endringa setter inn tekstverdien til html-elementet, så dersom formelen var 2+2=4 så er det faktisk det som settes inn i teksten.
=> Unwrap math with text content in stead of 'm'

src/components/SlateEditor/plugins/concept/EditSlateConcept.jsx
https://github.com/NDLANO/Issues/issues/2295 
Legger til data-type inline til nye forklaringer som legges til i editoren.
Er det mer enn dette som skal til? Var så lite kode.
Dette er da at den defaulter til 'inline', så blir det egen pr på å velge type (inline eller expanded/ plakat).
=> #2295 add data-type to concept

src/components/SlateEditor/plugins/details/index.tsx, src/components/SlateEditor/utils/schemaHelpers.js
Vi må støtte å rendre embeds og kode inni bokser.  Dette fordi dei med html-tilgang kopierer bilder og slikt inn i boksene. Det er mange bokser som har dette i seg allerde.
=> Add possibility to render code and embed in boxes

src/components/SlateEditor/plugins/codeBlock/CodeBlock.tsx
Lagring av html i kodeblokk funker ikkje fordi validator i draft-api plukker det opp som ugyldig kode. Vi må encode og decode det som lagres for at dette skal fungere. Lagra html blir litt rar med masse `&lt;` og slikt men det må nesten bli slik.
Test: 
Lag en kodeblokk og legg inn html eller faktisk berre en <. Det skal fungere å lagre artikkelen,
=> Using he for encoding and decoding tags

src/components/SlateEditor/RichBlockTextEditor.jsx, src/components/SlateEditor/plugins/mathml/EditMath.js, src/components/SlateEditor/plugins/mathml/MathML.js
Vi la til for mange mathjax-loadings og det gjør sida supertreig.
Denne artikkelen lar seg ikkje åpne https://ed.test.ndla.no/subject-matter/learning-resource/22679/edit men samme i pr-installasjon skal funke.
=> Fixing superslow math loading

src/components/PreviewDraft/PreviewDraft.tsx, src/components/SlateEditor/plugins/mathml/EditMathModal.js, src/components/SlateEditor/plugins/mathml/MathEditor.js
Gjør matte like raskt å laste første gong. Krever at det klikkes på en matteformel for at den skal rendres etter endring.
Test:
Matte rendres fullt ved åpning av artikkel.
Ved redigering av matte må du klikke på Forhåndsvis-knapp for å rendre forhåndsvisninga.
Etter å ha lagra matteendringer må du klikke på formelen for å rendre den på nytt.
Etter å ha lagra artikkelen må du klikke på en tilfeldig matteformel for å rendre all matte i sida på nytt.
=> Forsøker å fikse matterendering uten at det går alt for masse på bekostning av ytelse.

src/util/diffHTML.js, src/util/slateHelpers.js
Basert på kommentar i ndla-slack. Det fungerer ikkje å kopiere tekst fra ingress og lime inn i artikkel. Det er fordi ingress er en slate-editor uten skjema og derfor håndteres linjer som block av type line. Denne håndterer vi ikkje i vårt skjema, men vi kan serialisere det til p-tags.
I tillegg er det lov å ha br-tags inni code-tags så enabler dette. Har sett eksempel på artikler i prod der knappen ikkje blir blå fordi dette ikkje godtas i editoren.
Test: Rediger en artikkel og kopier inn tekst fra ingress inn i artikkelen. Dette skal gå bra og ikkje feile. Sammenlign gjerne med test.
=> Serialize line to paragraph. Enable br in code.

src/components/HeaderWithLanguage/HeaderStatusInformation.jsx, src/components/HeaderWithLanguage/HeaderWithLanguage.jsx
Viser berre lenke til ndla.no for artikler og ikkje for forklaringer, som er det som skjer no.
Test:
Publiserte forklaringer skal vise grønt ikon men det skal ikkje være klikkbart.
=> Only show link for articles

src/components/HeaderWithLanguage/HeaderStatusInformation.jsx, src/components/SlateEditor/plugins/link/EditLink.jsx, src/components/SlateEditor/plugins/link/Link.jsx, src/components/SlateEditor/plugins/link/LinkForm.jsx, src/config.js, src/containers/StructurePage/resourceComponents/ResourceItemLink.jsx, src/phrases/phrases-en.js, src/phrases/phrases-nb.js, src/phrases/phrases-nn.js, src/util/resourceHelpers.js, src/util/routeHelpers.js
I dag går det ikkje an å lime inn lenker til ndla.no artikler med ?filter= i urlen.
Test; 
Sett inn lenke i artikkel med adressa https://test.ndla.no/subjects/subject:33/topic:2:1:165344/resource:1:124037?filters=urn:filter:b100450f-c0bd-4b73-b924-44ab6baf4777
=> Ignore parameters in pasted ndla-url

src/containers/StructurePage/folderComponents/menuOptions/DeleteTopic.jsx
NDLANO/Issues#2361
Vi har arkivert emneartikkel ved sletting av emne, men det går ikkje dersom artikkelen er brukt i fleire emner.
Test:
Emneartikkel som kun er brukt i et emne skal arkiveres ved sletting av emnet i taksonomi. Emneartikkel som er brukt i fleire emner skal ikkje arkiveres ved sletting av emnet.
=> Do not archive if article is used in multiple topics

src/containers/PreviewDraftPage/PreviewDraftPage.jsx, src/containers/WelcomePage/WelcomePage.tsx
jeg har irritert meg over at jeg ikke får scrollet på WelcomePage/ hjem-siden på ed, spesielt om jeg har åpen konsollen. 
Så her er et forlag til å legge til  `overflow: auto;` som gjør at vi kan scrolle på denne siden nå som den har litt content. 
pluss:
> Kan du fikse det samme på PreviewDraft? Feks på https://ed.test.ndla.no/preview/22663/nb så ser du ikkje alt om du ekspanderer forklaringa under hallo.
=> allow scroll on WelcomePage

src/components/SlateEditor/plugins/embed/EditImage.tsx, src/components/SlateEditor/plugins/embed/SlateImage.tsx, src/containers/ImageEditor/ImageAlignButton.jsx, src/containers/ImageEditor/ImageEditor.tsx
Fixes NDLANO/Issues#2374
Endringene av bildestørrelse i editor skal nå gjenspeile det som vises i forhåndsvisning. 
Det dukker opp noen feilmeldinger i article-converter og det ser ut som størrelsesnavnene som brukes her er forskjellige og behandles på en annen måte.  Slik det er nå fører dette til at både "medium" og "stort" produserer et bilde med størrelse "medium".
=> 2374 image editor size consistency

src/components/PreviewConcept/PreviewConcept.tsx
Ref:  https://trello.com/c/0ZAFA5qW/720-sammenligning-av-spr%C3%A5kversjoner#comment-5fe07cd9b4e3b77edc478340
Vi skal alltid vise liste og fag sjølv om dei er tomme.
Eks: https://editorial-frontend-pr-850.ndla.sh/concept/717/edit/nb skal vise `Liste og filter:` uten noko etter :
=> Always show list and subject

src/components/PreviewConcept/PreviewConcept.tsx, src/containers/ConceptPage/components/ConceptContent.jsx, src/containers/FormikForm/FormikIngress.jsx
Ref https://trello.com/c/M9nkpu9A/816-bug-i-ed-med-visning-av-markdown-ved-bruk-av-%C3%B8ye-ikonet
Lar forklaringer vise lister men ikkje artikkelingress.
=> Allow lists for concepts but not articles.

src/components/SlateEditor/plugins/link/EditLink.jsx, src/components/SlateEditor/plugins/link/__tests__/EditLink-test.js
Etter at vi fjerna /subjects fra ndla-urler fungerer ikkje lenger automatisk oversettelse fra ndla-urler til lenkeembeds.
Test:
Gå til test.ndla.no og finn en vilkårlig artikkel med taksonomiurl. Kopier urlen.
Rediger en artikkel og sett inn ei lenke og bruk urlen som du kopierte. Lagre artikkelen.
Klikk på lenka og sjå at lenka som vises er på formatet ed.test.ndla.no/*.
Sjekk html-editoren for artikkelen og sjekk at det er satt inn en embed av type article og med data-content-id.
=> Fix ndla url link

src/components/HeaderWithLanguage/HeaderActions.jsx, src/containers/ConceptPage/components/ConceptArticles.tsx, src/containers/ConceptPage/components/ConceptForm.jsx, src/containers/ConceptPage/components/ConceptMetaData.jsx, src/containers/FormikForm/formikConceptHooks.jsx, src/containers/FormikForm/subjectpageFormHooks.ts, src/phrases/phrases-en.js, src/phrases/phrases-nb.js, src/phrases/phrases-nn.js, src/server/contentSecurityPolicy.js, src/shapes.js, src/util/__tests__/__snapshots__/conceptUtil-test.js.snap, src/util/conceptUtil.js
Fixes NDLANO/Issues#2376
1. https://editorial-frontend-pr-851.ndla.sh/
2. Følgende skal fungere
- Opprette ny forklaring
- Legge til artikkel til forklaring
- Fjerne artikkel fra forklaring
- Fjerne alle artikler fra forklaring
- Bytte rekkefølge på artikler i eksisterende forklaring
~Se også PR for concept-api:
https://github.com/NDLANO/concept-api/pull/71~
=> 2376-legge-til-flere-artikler-i-forklaring

src/components/DisplayEmbed/DisplayExternal.jsx, src/components/DisplayEmbed/__tests__/DisplayExternal-test.jsx, src/components/DisplayEmbed/__tests__/__snapshots__/DisplayExternal-test.jsx.snap
Fixes NDLANO/Issues#2346
Tidligere har oembeds som ikke fetches ikke blitt vist i ed (ref. øverst i ed.test.ndla.no/subject-matter/learning-resource/22729/edit/nb). Har lagt til `EditorErrorMessage` som placeholder for å vise feilmelding. Test i samme artikkel som over: https://editorial-frontend-pr-859.ndla.sh/subject-matter/learning-resource/22729/edit/nb
Erroren gir ikke veldig spesifikk info om hvorfor det er error, bør det spesifiseres?
=> Vise placeholder med error når oembeds ikke hentes 

src/components/SlateEditor/plugins/related/EditRelated.jsx, src/components/SlateEditor/plugins/related/RelatedArticleBox.jsx, src/phrases/phrases-en.js, src/phrases/phrases-nb.js, src/phrases/phrases-nn.js
**Sortering av relaterte artikler**
Endrer "items" til "articles" for mer lesbar kode
Lager en "updateArticles" funksjon i stedet for "removeArticles" som kan brukes til både sletting og flytting.
Forsøker å legge til et forklarende paragraf for den nye funksjonaliteten
Legger til en aria-label på knappen som sletter alle relaterte artikler
=> Legger til Droppable seksjon og Draggable wrappers

public/h5p-custom-css.css, src/components/DisplayEmbed/DisplayExternal.jsx, src/util/apiHelpers.js
Issue NDLANO/Issues#2300
Trello https://trello.com/c/u9KIMobD/760-knowit-ed-sjekk-dialogkort-i-fagpresentasjon-den-er-altfor-h%C3%B8y
PR i article-converter: https://github.com/NDLANO/article-converter/pull/215
Legger til custom css fil fra ndla og sender denne inn til custom. Har brukt denne artikkelen for testing: https://ed.test.ndla.no/subject-matter/learning-resource/22726/edit/nb
Det som skal være endret: 
* mindre luft rundt tekst i dialogboks (de hvite boksene inni h5p)
* venstrestilt tekst i lister i dialogboks
=> 2300 custom for css tilpasset visning av h5p

src/components/PreviewConcept/PreviewConceptLightbox.tsx, src/containers/ConceptPage/components/ConceptContent.jsx, src/containers/ConceptPage/components/ConceptForm.jsx, src/containers/FormikForm/formikConceptHooks.tsx, src/containers/LearningResourcePage/components/LearningResourceForm.jsx, src/interfaces.ts, src/modules/concept/conceptApiInterfaces.ts, src/shapes.js, src/util/__tests__/__snapshots__/conceptUtil-test.js.snap, src/util/__tests__/conceptMocks.js, src/util/__tests__/conceptUtil-test.js, src/util/conceptUtil.ts, src/util/formHelper.js
Fixes NDLANO/Issues#2385
Fixes NDLANO/Issues#2412
Et problem i artikkel/forklaring-form gjorde at metabilde alt-tekst forsvant dersom man endret status to ganger på rad. Det eksisterte fortsatt i databasen og dukket opp igjen ved refresh. Dette er nå løst ved at parseImageUrl returnerer imageId som en fallback dersom url'en allerede har blitt parset.
Denne PRen fikser også feil nevnt i NDLANO/Issues#2412. Det skal nå være mulig å opprette forklaring igjen.
How to test:
1. Sjekk at metabilde kan legges til, redigeres og fjernes.
2. Sjekk at metabilde alt-tekst ikke forsvinner dersom du endre status to ganger på rad.
3. Sjekk at andre felter fortsatt fungerer både å opprette ved ny forklaring og endring/fjerning av felt på eksisterende forklaring.
4. Forklaring skal kunne opprettes.
Sider …
=> 2385 bugfix article meta image alt text disappear

src/components/SlateEditor/plugins/embed/FigureButtons.tsx, src/phrases/phrases-en.js, src/phrases/phrases-nb.js, src/phrases/phrases-nn.js
Fixes NDLANO/Issues#2415 
Legger på lenke til brightcove for redigering av video.
Tst:
Lag eller rediger artikkel. Legg til video og velg en video fra brightcove. Lagre artikkelen.
Videoen skal ha et lenke-ikon under slett-ikonet og når du klikker på det skal du komme til brightcove.
=> Add link to brightcove. Some languagelaundry.

src/components/SlateEditor/plugins/pastehandler/index.js
Fixes NDLANO/Issues#2401
Skriver om pasteHandler til å strippe vekk formatering og bare lime inn ren-tekst for consistency.
Hvordan teste:
Prøv å paste tekst fra forskjellige kilder (tabelller, bokser, etc) inn i ed elementer (tekstfelt, ekspanderende boks, tabell, etc) og sjekk at det bare pastes ren tekst og ikke formateringer.
=> Stripping formatting on paste and pasting plain text

src/containers/ConceptPage/CreateConcept.jsx
Fixes NDLANO/Issues#2379 (forhåpentlig vis)
Fikser slik at `CreateConcept` sjekker om man har lokale verdier i `concept` slik at det ikke sendes inn `initialConcept` ved rerender om man har gjort endringer.
=> 2379: Fixing bug where CreateConcept always sends initialConcept to ConceptForm

src/containers/SearchPage/components/results/SearchImage.jsx
Alt-tekst på bilder i bildesøk blir vist som `"[Object, object]"`. Bruker image-api nå og ikke search-api og alt-tekst er visst strukturert noe annerledes.
Test:
1. Gjør et bildesøk /search/image?page=1&page-size=10&sort=-relevance
2. Se at bildene har fått satt en streng som alt-tekst og ikke object.
=> Bugfix: Alt text for image search results

src/containers/EditSubjectFrontpage/components/SubjectpageAbout.tsx, src/containers/EditSubjectFrontpage/components/SubjectpageAccordionPanels.tsx, src/containers/EditSubjectFrontpage/components/SubjectpageForm.tsx, src/containers/EditSubjectFrontpage/components/SubjectpageMetadata.tsx, src/containers/FormikForm/FormikMetadata.jsx, src/containers/LearningResourcePage/components/LearningResourceForm.jsx, src/containers/NdlaFilm/components/NdlaFilmAccordionPanels.tsx, src/containers/NdlaFilm/components/NdlaFilmForm.tsx, src/containers/TopicArticlePage/components/TopicArticleForm.jsx
Etter å ha skreve tekst i metadescription går det ikkje an å klikke utenfor. Fikser dette ved å sende formikprops nedover i treet og legger på onBlur. 
Merk:  Dette er fremdeles feil for ndla-film og fagforsider! Men der vil det være kjappere for en med bedre typescript-fu enn meg å fikse.
=> Fix focus traps for metadata.

src/containers/SearchPage/components/results/SearchConcept/ContentView.jsx, src/containers/SearchPage/components/results/SearchConcept/SearchStyles.jsx
Fixes NDLANO/Issues#2440
Test:
* https://editorial-frontend-pr-892.ndla.sh/search/concept?page=1&page-size=10&sort=-lastUpdated
* Lisenstekst skal være byttet ut med ikoner. Se at dette ser riktig ut
=> Replace license text with icons

src/containers/SearchPage/SearchContainer.jsx
Fixes NDLANO/Issues#2458
Det finnes ikke statusfelt for lyd/bilde å vise fram på samme måte som for artikkel/forklaring så vidt jeg kan se. Har derfor ikke implementert dette.
Har lagt til sortingsvalg i bildesøk og lydsøk. 
How to test:
1. https://editorial-frontend-pr-899.ndla.sh/
2. Prøv forskjellige kombinasjoner av "sortering" og "rekkefølge" i bildesøk og lydsøk.
=> Add Sort options to image and audio search

src/containers/FormikForm/FormikMetadata.jsx
Fikser fokuslås på metadata. Dette er en patch fra master-versjonen som blei deploya i går. Eg lager en release av brancen og legger i staging og ber om deploy.
Test:
Åpne metadata-boks på artikkel og klikk i metabeskrivelse. Sjekk at du kan klikke i nøkkelord etterpå.
=> Fix focus steal

src/containers/EditMarkupPage/EditMarkupPage.jsx, src/containers/FormikForm/FormikMetadata.jsx
Fixes NDLANO/Issues#2474 and NDLANO/Issues#2475
Laster inn svar fra server ved lagring i html-editor, samt bruker SaveButton for å få grønn lagreknapp. 
Test:
HTML: Åpne artikkel i html-editor. Gjør en endring og sjekk at Lagreknappen blir grønn etter lagring og at innholdet oppfriskes.
=> 2474 load changes after save

src/server/server.jsx
Fikser slik at alle kall på ed.ff redirectes til ed.
Test: Kjør opp ed lokalt og skriv i terminal: `curl -I -H 'Host: ed.ff.ndla.no' localhost:3000` og sjå at du får en 302 redirect til ed.ndla.no.
=> Fix redirect

src/containers/EditMarkupPage/EditMarkupPage.jsx
Fixes NDLANO/Issues#2335
Ved lagring av artikkel i HTML-editor dukket det opp nye tags ved lagring. Dette skjedde spesielt når brukeren la inn linjeskift i koden.
Hvordan er problemet løst: Trimmer hver linje for whitespaces og fjerner alle linjeskift. 
Ved noen tilfeller dukker det fortsatt opp `<p>`-tag rundt tekst. Dette skjer i følgende tilfelle:
`<section><p>noe tekst</p>tekst uten p</section>` -> `<section><p>noe tekst</p><p>tekst uten p</p></section>`
men ikke i dette tilfellet:
`<section>noe tekst</section>` -> `<section>noe tekst</section>`
Hvordan teste:
1. PR-installasjon
2. Åpne en artikkel i HTML-editor
3. Prøv å lagre linjeskift og andre endringer på koden. Resultatet skal være likt bortsett fra at det slås sammen til én linje.
=> 2335 bugfix html editor changes code

src/components/SlateEditor/plugins/SlateToolbar/handleMenuClicks.js
Fixes NDLANO/Issues#2485
Ref https://trello.com/c/ZbnXGcEw/970-mellomrom-i-formateringsfunksjoner
Stripper space fra kantene av valgt tekst for å unngå windowsproblematikk rundt valg av ord med dobbelklikk.
Test:
På windows: rediger en artikkel og dobbeltklikk på et ord og sjå at mellomrommet er valgt. klikk på feks **<>** i toolbar og sjekk at kun ordet får bakgrunnsfarge.
Alle os: rediger en artikkel og marker tekst som starter med eller slutter med mellomrom og klikk på et valg i toolbar. Mellomromma skal forsvinne etter klikket.
=> Fjerner space fra start og slutten av selektert tekst

src/constants.js, src/containers/VisualElement/visualElementApi.js
Legger til at embeds fra geogebra kan vises i ed.
Fjerner også at cors-anywhere brukes på test.
Test:
Denne artikkelen skal vise med geogebra: https://editorial-frontend-pr-922.ndla.sh/subject-matter/learning-resource/59218/edit/nb
=> Add support for showing geogebra. Do not use cors-url for test

package.json, src/components/MonacoEditor/MonacoEditor.jsx, src/containers/EditMarkupPage/EditMarkupPage.jsx, yarn.lock
Fixes NDLANO/Issues#2460
Oppgradert monaco-editor til siste versjon.
To endringer har blitt gjort i koden for å få dette til å fungere:
- F1-shortcut var tidligere importert som ´quickCommand´. Importeres nå som `standaloneCommandsQuickAccess`.
- monaco er ikke lenger tilgjengelig global som default. La til `globalApi: true` i `window.MonacoEnvironment` som beskrevet i changelogen til monaco-editor. Denne kodeblokken måtte også flyttes for at den skulle fungere.
Hvordan teste:
1. https://editorial-frontend-pr-927.ndla.sh/
2. Åpne en artikkel og sjekk at funksjonalitet i HTML-editor fungerer som normalt.
=> 2460 upgrade monaco editor

cypress/integration/Search/search_spec.js, src/containers/SearchPage/components/form/SearchContentForm.jsx, src/containers/SearchPage/components/form/SearchForm.jsx
Fikser søk etter status igjen.
Test
Søk etter innhold og filtrer på status og sjekk at antall treff oppdateres. Endring av søketerm skal ikkje nullstille statusen. 
Søk etter forklaring og sjekk at du også der kan filtrere på status.
=> Use correct parameter for content search

src/components/SlateEditor/slateRendering.jsx
Wrapper tabell-rendering med egen div slik at tabeller vises likt som i frontend.
Test.
Rediger artikkel og legg inn en tabell. Sammenlign artikkelen med forhåndsvisninga og sjekk at dei ser like ut. Breie tabeller med masse tekst skal kunne bli like breie som bilder og kodeblokker.
=> Wrap table-render with custom div

src/modules/translate/translateApi.js
Oversettelsestjenesten har en bug som fjerner whitespace i payloaden. Ved å legge på paramter x:true forteller vi tjenesten å bruke en anna html-parser.
Test
Rediger en artikkel på bokmål og sett inn en forklaring inni en setning. Oversett til nynorsk med tjenesten og sjekk at formateringa ser korrekt ut. Uten ekstra parameter vil mellomrom rundt forklaringa bli sletta.
=> Removing cors proxy and adding magical param.

src/components/MoveContentButton.tsx, src/components/SlateEditor/plugins/aside/SlateFactAside.jsx, src/components/SlateEditor/plugins/bodybox/SlateBodyBox.jsx, src/components/SlateEditor/plugins/details/Details.tsx
Fixes NDLANO/Issues#2500
Depends on https://github.com/NDLANO/frontend-packages/pull/773
Test:
Sjekk at går an å fjerne boks, men beholde innhold fra "faktaboks" og "ekspanderende boks" på samme måte som med "tekst i ramme"
=> 2500 unwrap boxes

src/containers/LearningResourcePage/components/LearningResourcePanels.jsx, src/containers/TopicArticlePage/components/TopicArticleAccordionPanels.jsx
Branch fra versjonen som ligger i staging.
Legger på sjekk om bruker har draft-admin før nytt panel for relatert innhold vises. Må på plass før vi deployer ed i prod. Lager uansett release av denne branchen.
Test: For alle oss skal det sjå som vanlig ut, men alle som ikkje har draft-admin skal ikkje sjå feltet.
=> Hide panel for mere mortals

package.json, src/util/slateHelpers.jsx
Matte som ligger direkte inni en li, div eller aside vises ikkje. Det er fordi det i disse tilfeller tolkes som block. Det kan ha fungert i en tidligere versjon av slate, men med skillet mellom inline og block som finnes i slate i dag så funker ikkje det.
Artikkelen https://ed.test.ndla.no/subject-matter/learning-resource/59231/edit/nb har matte i det andre listepunktet men det vises ikkje på grunn av denne regelen. 
Test
Tilsvarende [artikkel i pr-installasjon](https://editorial-frontend-pr-939.ndla.sh/subject-matter/learning-resource/59231/edit/nb) skal vise matte korrekt. Lagreknappen kan være blå fordi matten wrappes i p ved lagring. Ikkje lagre artikkelen.
=> Math should always be inline

src/containers/EditMarkupPage/EditMarkupPage.tsx
Fixes NDLANO/Issues#2519
Marc rapporterte at linjeskift i kodeblokk forsvinner ved lagring av html. Dette er på grunn av håndteringa av formatert html der vi stripper bort nettopp \n. oppdatere koden litt slik at kun linjeskift rett etter en > blir fjerna.
Test.
Lag en kodeblokk med mange linjer i en artikkel. Rediger html og gjør en liten endring slik at du får lagra. Kodeblokken skal ha fått beholde linjeskifta sine.
=> Preventing \n in codeblock to be stripped from html

src/containers/ArticlePage/LearningResourcePage/CreateLearningResource.jsx, src/containers/ArticlePage/LearningResourcePage/EditLearningResource.jsx, src/containers/ArticlePage/LearningResourcePage/EditResourceRedirect.tsx, src/containers/ArticlePage/LearningResourcePage/LearningResourcePage.jsx, src/containers/ArticlePage/TopicArticlePage/CreateTopicArticle.jsx, src/containers/ArticlePage/TopicArticlePage/EditArticleRedirect.tsx, src/containers/ArticlePage/TopicArticlePage/TopicArticlePage.jsx
Fikk en feilmelding om changing state i render 
`Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.`
Tror denne redirecten vil få til det samme som history.push, bare med bruk av react router Redirect
Når vi henter fra backend så vil den finne en mulig språk fallback automatisk tror jeg? vi behøver ikke finne den før vi kommer inn
=> Alternativ løsning for redirect

src/modules/translate/translateApi.js
Omgår feil i oversettelsestjeneste der æøå gjøres om til html entitieter.
Test:
Lag en artikkel med æøå i ingress. Lagre og bruk knapp Oversett til nynorsk. Ny variant skal ha æøå i ingress fremdeles.
=> Do not convert å to &aring;

cypress/integration/Editor/full_resource_spec.js, cypress/integration/Editor/topic_article_spec.js, src/components/EditMarkupLink.jsx, src/containers/ArticlePage/LearningResourcePage/LearningResourcePage.jsx, src/containers/ArticlePage/TopicArticlePage/TopicArticlePage.jsx
userAccess forsvant fra props til artikkelredigering så måtte legge det inn igjen for å få html-tilgang.
Test: Sjekk at du har html-lenka tilgjengelig på en tilfeldig artikkel.
=> Reinstating missing html-edit link.

src/phrases/phrases-en.ts, src/phrases/phrases-nb.ts, src/phrases/phrases-nn.ts
Endrer navn på statuser. Det som tidligere var Arkivert er no Sletta for å skille tydeligere på forskjellen mellom sletta artikler og arkivløsning som kjem etter kvart.
Test:
Søk etter artikler med status Slettet. Disse skal kun dukke opp i dette søket. Statusendringer skal bruke navnet Slett.
=> Changing label on two statuses

src/containers/SearchPage/components/results/SearchHighlight.tsx, src/phrases/phrases-en.ts, src/phrases/phrases-nb.ts, src/phrases/phrases-nn.ts
Fixes NDLANO/Issues#2540
Viser også søketreff fra notes.
Test: Søk etter artikler med feks ordet Oppdatert. Dersom det ikkje er andre treff, skal det vises "Søketreff fra versjonslogg"
=> 2540 Displaying search hits from notes

src/containers/ArticlePage/LearningResourcePage/components/LearningResourceForm.jsx
Det at vi setter origin til '' gjør at det er forskjell på det som sendes inn og det som er lagra for nesten alle artikler. Det vil sei at disse får ny versjon i apiet sjølv om det kun er metadata som endres.
Test:
Alt skal fungere som vanlig. Artikler som ikkje har origin skal kunne oppdateres med metadata uten at status endres.
=> Do not send origin

cypress/integration/Editor/slate_block_picker_spec.js, src/components/DisplayEmbed/helpers/DisplayExternalModal.jsx, src/components/H5PElement/H5PElement.tsx, src/components/Lightbox.jsx, src/components/SlateEditor/plugins/blockPicker/SlateVisualElementPicker.jsx, src/containers/VisualElement/VisualElementModalWrapper.tsx, src/containers/VisualElement/VisualElementSearch.jsx, src/containers/VisualElement/VisualElementSelectField.jsx
fixes NDLANO/issues#2543
Ved opprettelse og redigering av h5p vises nå headeren med lukkeknapp kun når henting av h5p-editoren feiler. For andre visuelle elementer skal headeren fortsatt vises. Har også overskrevet stylingen på `<h2>` (som blir brukt i video- og h5p-opplasteren) i Modal for disse komponentene for å redusere på mengden luft øverst i modalen. Så nå skal h5p-editoren ha mer plass i modalen den brukes i.
Testing:
- [Artikkel med h5p](https://editorial-frontend-pr-971.ndla.sh/subject-matter/learning-resource/59271/edit/nb)
=> 2543 skjule modalheader for h5p

src/components/SlateEditor/plugins/details/DetailsBox.tsx
Fixes NDLANO/Issues#2498
Ser ut som den beste løsningen på sikt er å skrive om tittel-feltet til å være redigerbart inline, men det blir dobbelt arbeid om det skal gjøres nå siden slate oppgraderes.
Har løst problemet her med scrolling, men man ser at den blinker til toppen av nettsiden et kort øyeblikk før scroll går tilbake til riktig posisjon.
=> 2498 fix expanding box title with scroll

src/containers/ArticlePage/LearningResourcePage/components/LearningResourceForm.jsx, src/containers/ArticlePage/TopicArticlePage/components/TopicArticleForm.jsx
Fixes NDLANO/Issues#2557
Fikser slik at klona artikler åpnes i editoren etter kloning.
Test:
Åpne en artikkel og klikk på Kopier artikkel i toppen. Editoren skal oppdateres til å ha ny artikkel.
=> Adding history-parameter to open cloned article

src/components/ControlledImageSearchAndUploader.tsx, src/containers/ArticlePage/LearningResourcePage/CreateLearningResource.jsx, src/containers/ArticlePage/LearningResourcePage/components/LearningResourceForm.jsx, src/containers/ArticlePage/TopicArticlePage/CreateTopicArticle.jsx, src/containers/ArticlePage/TopicArticlePage/TopicArticlePage.jsx, src/containers/ArticlePage/TopicArticlePage/components/TopicArticleForm.jsx, src/containers/FormikForm/articleFormHooks.js
Hadde litt tid på tampen av dagen så småfiksa litt på noen av de feilmeldingene som Anders har nevnt.
- Tabs i ImageSearchUploader krever content for hver av tabsene, så i stedet for å returnere `null` hvis man ikke har `licenses` la jeg til en errorMessage.
- Fant en feilmelding i TopicArticle- og LearningResourceForm som kom av at state prøvde å oppdatere seg før formik var rendra, men kunne gjøre den stateoppdateringen direkte i `useArticleFormHooks` i stedet, så gjorde det.
- Sender med prop history fra CreateTopicArticle og -LearningResource inn i formsene
=> 2512 Småfiksing på feilmeldinger i console

src/components/Lightbox.jsx
Fixes NDLANO/Issues#2560
Forhåndsvisning av gamle versjoner vises etter kvarandre og ikkje ved siden av kvarandre.
=> Removing flex-direction to fix preview of old versions.

src/components/PreviewDraft/PreviewDraft.tsx, src/components/PreviewDraft/PreviewDraftLightbox.jsx, src/components/PreviewDraft/PreviewProduction.jsx, src/containers/PreviewDraftPage/PreviewDraftPage.jsx
Article må ha locale for å rendre labels i audoplayer korrekt. 
Test.
Åpne en artikkel med lyd/podkast. Forhåndsvis artikkelen. Om du hovrer over knappene i lydavspilleren skal det vises tekster og ikkje phrase-ider.
=> Adding language to Article to fix labels.

src/containers/AudioUploader/EditAudio.tsx, src/containers/Podcast/EditPodcast.tsx
Virker litt forvirrende at skjema for audio ikkje endres ved bytte mellom språk. La til spinner for å gjøre det litt meir tydelig.
test: Finn lyd/podcast og bytt mellom språkversjoner. Dette skal trigge spinner.
=> Add spinner when changing between language version

src/components/SlateEditor/plugins/embed/AudioPlayerMounter.tsx, src/containers/Podcast/components/PodcastForm.tsx, src/containers/Podcast/components/PodcastMetaData.tsx
Skjuler header i podcast. Viser kvadratisk podcast-bilde. Krever oppdatert AudioPlayer for å fikse css.
Test:
* Header-feltet er skjult fordi det ikkje trengs. Slettes i seinare versjon. https://trello.com/c/i5ZULnWd/1087-fjerne-overskrift-feltet-i-podcast
* Introduksjon har maks 1000 tegn, med validering. https://trello.com/c/P7uDI9lV/1086-max-1000-karakterer-p%C3%A5-podcast-vis-mer-lenke
* Krav om opphaver er fjerna. https://trello.com/c/mj8p3nHW/1088-ta-bort-krav-om-opphavsperson-p%C3%A5-podcast
=> Skjuler header fra podcast-skjema

src/components/SlateEditor/plugins/embed/AudioPlayerMounter.tsx, src/containers/AudioUploader/components/AudioContent.tsx, src/containers/AudioUploader/components/AudioForm.tsx, src/containers/Podcast/components/PodcastForm.tsx, src/containers/Podcast/components/PodcastMetaData.tsx, src/modules/audio/audioApiInterfaces.ts, src/phrases/phrases-en.ts, src/phrases/phrases-nb.ts, src/phrases/phrases-nn.ts, src/util/audioHelpers.ts
Det funker å lagre tekstversjon på vanlige audios, men for podcast kjem melding `Cannot specify podcastMeta fields for audioType other than 'podcast'`. Det må fikses i audio-api.
=> Flytter tekstversjon til audioform.

src/components/SlateEditor/plugins/toolbar/SlateToolbar.tsx, src/components/SlateEditor/plugins/toolbar/ToolbarButton.jsx, src/style/toolbar.css
Avventer https://github.com/NDLANO/editorial-frontend/pull/1034
Oppdatert styling av toolbar som dukker opp ved markering av tekst. Hver knapp er nå adskilt av en border og aktive knapper får mørkere bakgrunn og border.
Hvordan teste:
1. Åpne PR-installasjon
2. Åpne eller opprett en artikkel
3. Marker tekst og trykk på noen av knappene.
4. Sjekk at:
- Aktiverte knapper har blå bakgrunn og en noe mørkere border.
- Ingen knapper har dobbel eller manglende border
- Eventuelt andre kommentarer på styling
=> Slate upgrade toolbar styling

src/modules/translate/translateApi.js
Fixes NDLANO/Issues#2607
Legger på ekstra parameter på oversettelsestjenesten. Har laga en artikkel som har mesteparten av tinga som kan spesifiseres.
http://localhost:3000/subject-matter/learning-resource/31108/edit/nb
Test:
* Forsøk å oversette artikkel til nynorsk.
Merk. Det ser ut til å være en feil i oversettelsestjenesten som ikkje behandler "vi" korrekt. Det er tjenesten sin feil og ikkje vår.
=> Adding extra parameters to translate service.

src/containers/App/App.tsx
Fixes https://github.com/NDLANO/Issues/issues/2637
Problemet kan se ut til å henge sammen med emotion. En forskjell fra H5PPage i forhold til andre komponenter i ed er at det brukes @emotion/react. I andre komponenter brukes @emotion/css eller styled eller core. Det kan være en årsak til feilen. 
En løsning på feilen kunne ha vært å inkludere chunkExtractor (se https://emotion.sh/docs/ssr), men tror det er nå mer jobb enn det man får ut. Fikk samme resultat fra lighthouse med og uten h5ppage som chunk nå, og den utgjør bare 6 kb. 
Edit: Ser at emotion/core har blitt renamet til emotion/react. Så skal undersøke forskjeller mer. (se https://emotion.sh/docs/emotion-11#package-renaming)
=> Revert loadable h5ppage

src/containers/ConceptPage/conceptUtil.ts, src/modules/concept/conceptApiInterfaces.ts
Fixes https://github.com/NDLANO/Issues/issues/2628
Bugen oppsto fordi `metaImage` ble satt til undefined istedenfor null.
=> Fixed deletion of concept metadata images.

src/containers/AudioUploader/EditAudio.tsx, src/containers/ConceptPage/EditConcept.jsx, src/containers/FormikForm/formikConceptHooks.tsx, src/containers/ImageUploader/EditImage.tsx, src/containers/PodcastSeries/EditPodcastSeries.tsx, src/util/audioHelpers.ts, src/util/resolveJsonOrRejectWithError.js
Fixes https://github.com/NDLANO/Issues/issues/2641
Lagt til notfoundpage ved manglende id på hver av ressursene. Screenshot av ressurser;
Kan testes ved å trykke inn på en ressurs og legge til en random id, e.g. http://localhost:3000/media/podcast-series/344444/edit/nb 
Kræsjet lokalt ved uhåndtert promise ved status 404, så la til resolve ved `src/util/resolveJsonOrRejectWithError.js `. Tar gjerne feedback på om det er gjort riktig.
=> Show notfoundpage if no data

src/components/SlateEditor/plugins/footnote/EditFootnote.tsx, src/components/SlateEditor/plugins/footnote/FootnoteForm.jsx, src/components/SlateEditor/plugins/link/EditLink.tsx
Tittelen i modal for redigering av lenke og fotnote var tidligere plassert til venstre for skjemaet. Denne PRen fikser det så tittelen er plassert ovenfor.
Hvordan teste:
- Åpne PR-installasjon
- Opprett/åpne artikkel
- Legg til fotnote og lenke. Se at tittel er plassert riktig.
=> Slate upgrade dialog styling

src/components/SlateEditor/RichTextEditor.tsx, src/components/SlateEditor/interfaces.ts, src/components/SlateEditor/plugins/break/index.tsx, src/components/SlateEditor/plugins/details/index.tsx, src/components/SlateEditor/plugins/table/index.tsx, src/components/SlateEditor/utils/normalizationHelpers.ts
Lagt til placeholder for tittel i ekspanderende boks. 
Hvordan teste:
- Åpne PR-installasjon.
- Åpne eller lag en ny artikkel.
- Sjekk blant annet at:
- Placeholder vises i tittelfeltet i ekspanderende boks
- Lagring og redigering fungerer
- Markør plasseres og vises riktig
=> Slate: Show placeholder for title in Details box

src/constants.ts, src/server/contentSecurityPolicy.ts
Fixes https://github.com/NDLANO/Issues/issues/2625
Måtte legge til ebok i contentsecuritypolicy og whitelist. reader.pubfront.com ser ut til å bli brukt av ebok for embedded code, så det måtte også bli lagt til i contentsecuritypolicy. 
Istedenfor å hente ut full embeded code fra gratis utdrag (se eksempelbok https://ebok.no/ebok/hvem-sa-hva_helene-uri-2/), hentes heller src-lenken fra iframe i embedded code.
**Kan testes ved å:**
- gå inn på pr-instansen
- gå inn på artikkel
- legg til innhold: Ressurs som lenke
- lim inn lenke fra iframe src , for eksempel `https://ebok.no/market/sample/1419092/
`
Bilde fra hvordan innholdet bør vises:
=> Add ebok as valid domain

src/containers/ImageUploader/EditImage.tsx, src/containers/ImageUploader/components/ImageForm.tsx
Fixes https://github.com/NDLANO/Issues/issues/2650
- Siden et bilde som ikke er opplastet ennå ikke vil ha `imagedata`, vil ikke opplastning av bilde fungere. Fjernet derfor `notfoundpage` hvis ingen `imagedata`. 
- Forventet at den eksisterende importen av `headerwithlanguage` fungerte siden den har export default i fila `index.js` i samme mappe, men den fungerte ikke. Oppdaterte importen til å peke mer spesifikt. 
- Benyttet isSaving i SaveButton for å klargjøre når bildet lastes opp
=> Fix import and remove notfoundpage if no data

src/components/H5PElement/H5PElement.tsx
Fixes https://github.com/NDLANO/Issues/issues/2661
Virker som det er ekvivalent å benytte useCallback og dependency array i useEffect med tom dependency array (https://stackoverflow.com/questions/55840294/how-to-fix-missing-dependency-warning-when-using-useeffect-react-hook). Men i dette tilfellet fungerte det ikke med useCallback, så byttet til tomt array og fjernet useCallbacks.
=> Fix h5p extra reload

src/components/SlateEditor/plugins/concept/ConceptModal.jsx
Problemet som er løst:
Ved innsetting av forklaring i editor (via inline toolbar) så åpnes en modal. Søkefeltet fungerer dårlig når man skriver raskt. Trenger delay etter hvert trykk slik at man kan skrive ferdig ordet før den søker.
Løste det ved å legge inn debounce for å utsette søk til 400ms etter man er ferdig med å skrive
Hvordan teste:
- Åpne artikkel
- Skriv noe tekst, marker den og velg "forklaring" i toolbar (eller ctrl+alt+c).
- Søk etter forklaring i feltet og bekreft at du kan skrive ordet ferdig før den gjør et søk.
=> Slate: Add debounce to concept plugin modal

src/components/FileUploader/FileUploader.tsx, src/phrases/phrases-en.ts, src/phrases/phrases-nb.ts, src/phrases/phrases-nn.ts
Fixes https://github.com/NDLANO/Issues/issues/2601
Deployet [fix i draft-api](https://github.com/NDLANO/draft-api/pull/272), og da fungerte det å laste opp f3d i ed. Trengte ikke å legge til .f3d i `src/components/FileUploader/FileUploader.tsx` for å få det til å fungere, så jeg vet ikke hva `allowedFiles` her egentlig gjør. 
Gjerne dobbeltsjekk at filopplastning av typen .f3d fungerer i ed.
Lagt til manglende oversettelser.
=> Add missing translations for files

src/components/SlateEditor/interfaces.ts, src/components/SlateEditor/plugins/aside/index.tsx, src/components/SlateEditor/plugins/blockquote/index.tsx, src/components/SlateEditor/plugins/bodybox/index.tsx, src/components/SlateEditor/plugins/codeBlock/index.tsx, src/components/SlateEditor/plugins/details/index.tsx, src/components/SlateEditor/plugins/div/index.tsx, src/components/SlateEditor/plugins/heading/index.tsx, src/components/SlateEditor/plugins/link/index.tsx, src/components/SlateEditor/plugins/list/handlers/onEnter.ts, src/components/SlateEditor/plugins/list/index.tsx, src/components/SlateEditor/plugins/paragraph/index.tsx, src/components/SlateEditor/plugins/section/index.tsx, src/components/SlateEditor/plugins/table/index.tsx, src/util/articleContentConverter.tsx
Dersom man har markøren som plassert i bildet og trykker enter, så skal man hoppe til neste linje hvor det opprettes et nytt liste-element. Tidligere ble hoppet den heller ut av listen i en tom paragraf.
=> Slate: onEnter, only unwrap list when list-item is empty

src/containers/StructurePage/resourceComponents/ResourceGroup.jsx
Bugen er live i test. Man kan teste den ved å legge til en ressurs i en tom ressursgruppe i struktur. Den oppstår fordi det passeres inn et tomt objekt til `ResourceGroup` i `StructureResources`.
=> Fixed a bug where adding a resource to an empty resource group would crash the app

src/containers/PodcastSeries/components/PodcastSeriesForm.tsx
Fixes NDLANO/Issues#2667
Kan testes ved å forsøke å lagre en podcast serie uten metabilde.
=> #2667: Fix non-null assertion where there can be a `undefined` value

src/components/SlateEditor/plugins/related/EditRelated.jsx, src/components/Taxonomy/TaxonomyLightbox.tsx, src/containers/ArticlePage/components/ContentField.tsx, src/containers/ArticlePage/components/ContentLink.tsx, src/phrases/phrases-en.ts, src/phrases/phrases-nb.ts, src/phrases/phrases-nn.ts
Fixes NDLANO/Issues#2666
Legger til validering når man setter inn relatert, ekstern artikkel i en artikkel. Endrer også på modalen som brukes når man gjør det samme under "Relatert innhold" tabben til å være lik den som brukes i editoren.
Test:
* Åpne blockpicker og velg Relatert innhold
* Trykk "Legg til ekstern artikkel"
* Det skal ikke gå an å lagre med en ugyldig url
=> 2666 external link url validation

src/containers/StructurePage/StructureContainer.jsx, src/phrases/phrases-nb.ts, src/phrases/phrases-nn.ts
Fixes NDLANO/Issues#2658
Forrige fiks fjerna muligheten for å sortere på første nivå. Dette fikser det, men er kanskje ikkje mest elegant.
Test: 
Det skal gå an å sortere emner på alle nivå i strukturredigeringa.
=> Fikser slik at det går an å sortere også på første nivå.

src/components/HeaderWithLanguage/HeaderActions.jsx, src/containers/AudioUploader/EditAudio.tsx, src/containers/AudioUploader/components/AudioForm.tsx
Fixes NDLANO/Issues#2681
Oversetter lyd-manuskript .
Test:
Finn en lydfil med bokmål og ikkje nynorsk. Skriv gjerne inn tekst i tekstversjonfeltet. Klikk på Oversett til nynorsk. Sjekk at både tittel og tekstversjon oversettes.
=> Added translating of audio from bokmål to nynorsk.

src/util/audioHelpers.ts
Fixes NDLANO/Issues#2694
Ved henting av lyd fjernes duplikate tags.
Hvordan teste:
- Åpne PR-instans
- Åpne feks /media/audio-upload/1275/edit/sma (denne innholder per dette tidspunkt duplikater)
- Om du ser i requesten så vil en lydfil med duplikate tags kun vise fram unike tags.
=> Remove duplicates from tags in fetched audio

src/phrases/phrases-nb.ts
Fixes https://github.com/NDLANO/Issues/issues/2711
Etterslep fra injectT -> i18next. Problemet oppsto fordi de to løsningene bruker forskjellige interpolation-løsninger.
=> Fix faulty validation message on minItems validation

src/components/SlateEditor/plugins/codeBlock/CodeBlock.tsx
Fikser en feil som ble oppdaget i beta. Ved lukking av kodeblokk ble fokus ofte satt i starten av editor.
Dette er løst ved å sette fokus i editor og plassere selection etterpå med en timeout.
Hvordan teste:
- Åpne / lag artikkel
- Sett inn kodevisning og forsøk alle metoder for å lukke modalen. Fokus skal alltid settes etter kodevisningen.
=> Slate: Set focus correctly after closing code block editor

src/config.ts, src/constants.ts, src/containers/VisualElement/UrlAllowList.tsx, src/containers/VisualElement/VisualElementUrlPreview.jsx, src/containers/VisualElement/__tests__/transformUrlIfNeeded-test.js, src/phrases/phrases-en.ts, src/phrases/phrases-nb.ts, src/phrases/phrases-nn.ts
Fixes NDLANO/Issues#2707
Har lagt til en modal som viser en tabell over gyldige url-er. Denne finner man ved å redigere artikkel og legge til "Ressurs fra lenke" via legg-til-knappen.
Hvordan teste:
1. Åpne PR-instans
2. Åpne/lag artikkel
3. Legg til ressurs fra lenke
4. Det skal vises en ny knapp med tekst "gyldige domener".
5. Ting å sjekke
- Modalen fungerer som forventet
- Tabellen som vises
- Translations
- Styling
=> Add button to show a modal with whitelisted urls in external url embed

src/containers/ImageUploader/components/ImageMetaData.tsx, src/containers/SearchPage/components/form/SearchImageForm.tsx, src/phrases/phrases-en.ts, src/phrases/phrases-nb.ts, src/phrases/phrases-nn.ts
Fixes NDLANO/Issues#2719
Kan testes ved å lage/oppdatere bilder og sjekke at modellklarering funker som det skal.
NB: Denne er branchet fra versjonen som kjører i staging (`1c9fa85`)
=> #2719: Adds options for handling not-set value for modelReleased images

src/containers/VisualElement/VisualElementUrlPreview.jsx, src/containers/VisualElement/__tests__/__snapshots__/transformUrlIfNeeded-test.js.snap, src/containers/VisualElement/__tests__/transformUrlIfNeeded-test.js, src/containers/VisualElement/urlTransformers.ts
Fixes NDLANO/Issues#2716
Avhengig av https://github.com/NDLANO/editorial-frontend/pull/1146
Legger til oversetting av kahoot-lenker.
Hvordan teste:
1. Åpne artikkel
2. Legg til ressurs fra lenke via +-knapp.
3. Lim inn en lenke på formatet `create.kahoot.it/<valgfritt>/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`
4. Denne skal transformeres til `embed.kahoot.it/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`
5. Forhåndsvisning skal fungere
=> 2716 kahoot url transform

src/components/ControlledImageSearchAndUploader.tsx, src/containers/FormikForm/MetaImageSearch.tsx, src/containers/ImageUploader/EditImage.tsx, src/containers/ImageUploader/components/ImageForm.tsx, src/containers/VisualElement/VisualElementSearch.jsx
Opplastning av bilde feilet fordi `modelRelease`-verdien var undefined by default og fordi `inModal` alltid var false, selv om den skal være true. Satt `modelRelease` til å være `not-set` by default. 
Den evige innlastingen kom av en endring som tok til høyde for innlasting av bilder når man skulle redigere et eksisterende bilde. Har fjernet sjekken inntil videre, uten noen synlige bivirkninger.
=> 2730 Fixed infinite loading and image upload failure for learning resources

src/containers/AudioUploader/components/AudioContent.tsx, src/containers/AudioUploader/components/AudioCopyInfo.tsx, src/containers/AudioUploader/components/AudioFileInfoModal.tsx, src/containers/AudioUploader/components/AudioForm.tsx, src/containers/AudioUploader/components/AudioFormInfo.tsx, src/phrases/phrases-en.ts, src/phrases/phrases-nb.ts, src/phrases/phrases-nn.ts
Fixes NDLANO/Issues#2723
Har lagt til informasjon to steder i AudioForm.
1. Header-felt over lydfil med klikkbart ikon som åpner modal.
2. Ved opprettelse av ny språkversjon legges det informasjon under lydfilen om hvor den er hentet fra.
Hvordan teste:
- Åpne PR-instans
- Åpne lydfil
- Forsøk å lage ny språkversjon og se om (2) fungerer. Dette skal kun dukke opp i dette tilfellet.
- Sjekk at modal fungerer som forventet.
- Se gjennom styling, oversettinger og innhold.
=> 2723 audiofile info

src/containers/StructurePage/StructureContainer.tsx, src/containers/StructurePage/__tests__/__snapshots__/StructurePage-test.jsx.snap, src/containers/StructurePage/folderComponents/FolderItem.tsx, src/containers/StructurePage/resourceComponents/StructureResources.tsx
La til muligheten til å disable "hopp til ressurser"-knappen i struktur inntil ressurser har blitt hentet. 
Fikset også en bug som oppsto når henting av topic resources feilet. I nåværende tilstand vil ressursene til forrige topic fortsette å bli vist. Valgte istedenfor å nullstille ressursene i slike tilfeller.
=> Add disable option in jump to resources button. Fixed structure resource fetching bug.

src/containers/FormikForm/formikDraftHooks.ts
Alle steder updateUserData brukes sendes det inn `number`, fjernet derfor `string` som mulig input. 
Ellers er feilen rettet ved at stringId brukes ved filtrering og ikke articleId som er number.
Hvordan teste:
- Åpne en artikkel
- Lagre flere ganger
- Bekreftet at artikkelen kun er oppført én gang på forsiden.
=> Duplicate articles will now be removed when updating last edited articles

src/containers/ArticlePage/LearningResourcePage/components/LearningResourceContent.tsx, src/containers/ArticlePage/LearningResourcePage/components/LearningResourcePanels.tsx, src/containers/FormikForm/articleFormHooks.ts
Feil som dukket opp som følge av at RichBlockTextEditor er javascript og ikke ga feilmelding på at type til handleSubmit ble endret. Reverserer derfor så vi går tilbake til slik strukturen var før.
Hvordan teste:
- Åpne artikkel og test at lagring med knapp / ctrl+s fungerer i alle felter.
- ~Sjekk også at liste over sist redigerte artikler på forsiden ikke inneholder duplikater~. Løses i https://github.com/NDLANO/editorial-frontend/pull/1167
=> Save using ctrl+s now works in articles

src/containers/App/SearchPage.tsx, src/containers/FormikForm/formikDraftHooks.ts, src/containers/Masthead/MastheadSearch.jsx, src/containers/SearchPage/SearchSaveButton.tsx, src/containers/SearchPage/components/form/SearchContentForm.tsx, src/phrases/phrases-en.ts, src/phrases/phrases-nb.ts, src/phrases/phrases-nn.ts
Fixes NDLANO/Issues#2736
Ting som er gjort:
- Lagring av søk på søkesiden lar deg nå ikke lagre det samme søket flere ganger. Dersom det skjer viser den også en feilmelding. Knappen indikerer nå også dersom søket allerede er lagret.
- Fikset litt uoverensstemmelser mellom søk i masthead og søkesiden:
- Dersom man allerede er på søkesiden og søker via masthead, så vil søket og søkeskjemaet nå oppdatere seg. Det er kun query-feltet som skal endres, ingen andre parametre i url skal endres/fjernes/legges til.
- Ved bytte til innholds-søk fra en av de andre søketypene legges nå `fallback=false&include-other-statuses=false` til i url. Dette er default for innholdssøk når man går dit via masthead.
Hvordan teste lagring av søk:
- Prøv ulike søk.
- Se at lagret søk vises på forsiden og at …
=> 2736 no multiple save search

src/containers/AudioUploader/components/AudioContent.tsx, src/containers/AudioUploader/components/AudioFileInfoModal.tsx, src/phrases/phrases-en.ts, src/phrases/phrases-nb.ts, src/phrases/phrases-nn.ts
NDLANO/Issues#2724
Har lagt til en linje om sletting av filer i informasjons-modalen i audio form. Oversettelser er også omformulert.
Hvordan teste:
- Åpne eller lag lydfil og sjekk at oversettelser vises riktig. Det skal nå være fire punkter.
- Se over phrases.
=> 2724 deletion of audio files

src/components/SlateEditor/EditorFooter.tsx
Fixes https://github.com/NDLANO/Issues/issues/2748.
Det hadde å gjøre med en type guard som var feildefinert, slik at valideringsfunksjonen returnerte tidlig.
=> Fixed faulty type guard for EditorFooter

src/components/SlateEditor/plugins/embed/SlateVideo.tsx
Tok bare i bruk feil variabel. 
Kan testes ut ved å redigere en video-caption i en artikkel. Se at endringene kommer opp i artikkelen med en gang du har klikket på "lagre video".
=> Changed the variable used to render markdown when slate video is not currently being edited

src/components/SlateEditor/plugins/blockPicker/SlateVisualElementPicker.jsx, src/containers/ConceptPage/conceptUtil.ts, src/containers/VisualElement/VisualElementSelectField.jsx
Oppdaget en feil da jeg arbeidet med slate-oppgradering.
Boksen for å huke av om man vil sette et bilde som metabilde er synlig ved valg av visuelt element i ndla film. Denne PRen fikser dette.
Hvordan teste:
1. Bekreft at metabilde kan settes med checkbox ved innsetting av bilde i læringsressurs.
2. Bekreft at metabilde kan settes med checkbox ved valg av visuelt element i forklaring og emne.
3. Bekreft at metabilde ikke kan settes ved valg av visuelt element i ndla film.
=> Bugfix hide metaimage checkbox in ndla film

src/components/PreviewDraft/PreviewDraft.tsx
Legger til h5p-resizer til forhåndsvisning av artikkel.
H5p i artikler som vises i ed blir ikkje resiza korrekt i forhåndsvisning. Fikser det ved å importere helperfil i previewdraft.
Test:
* Artikkel med høg h5p skal vises med h5p ekspandert til å ikkje ha scrollbars. Både i slate og i forhåndsvisning.
=> Add h5p resizer to preview page

src/components/DisplayEmbed/DisplayExternal.jsx, src/containers/VisualElement/VisualElementSearch.jsx
https://github.com/NDLANO/Issues/issues/2690
onEditEmbed hadde en bug som gjorde at if setningen alltid var true fordi den sjekket
properties.url !== embed.url, men properties.url er alltid undefined
Dette førte også til at url ble satt til undefined, er ikke helt sikker på hva den originale ideen var
=> ignorere ny path når man oppdaterer h5p

src/components/Taxonomy/ActiveTopicConnection.tsx, src/components/Taxonomy/ActiveTopicConnections.tsx, src/components/Taxonomy/SharedTopicConnections.tsx, src/components/Taxonomy/TopicConnections.tsx, src/containers/ArticlePage/LearningResourcePage/components/LearningResourceTaxonomy.tsx, src/containers/ArticlePage/TopicArticlePage/components/TopicArticleConnections.tsx, src/containers/ArticlePage/TopicArticlePage/components/TopicArticleTaxonomy.tsx, src/modules/taxonomy/taxonomyApiInterfaces.ts, src/util/taxonomyHelpers.ts
Fixes NDLANO/Issues#2779
Test:
* Gå inn på en læringsressurs
* Åpne taksonomitaben
* Breadcrumbs skal dukke opp med en gang (sammenlign med ed.test)
Tilsvarende test kan gjøres for emneplassering i emne artikkel. Her vistes spinneren helt til all data var hentet fra før, men dette skal nå gå raskere.
Koden for å legge til en emnetilknyttning er også endret på. Dette skal fungere som før.
=> 2779 fix blank topic connections

src/containers/EditSubjectFrontpage/components/SubjectpageForm.tsx, src/containers/FormikForm/subjectpageFormHooks.ts
Fixes https://github.com/NDLANO/Issues/issues/2787
Feilen kom av at `TFunction` ble passert inn istedenfor oppdateringsfunksjonen. Hvordan det ikke ble plukket opp av TypeScript er jeg litt usikker på.
Hvordan teste:
1. Gå til en subjectpage som allerede finnes.
2. Endre metabeskrivelse.
3. Trykk lagre.
4. Refresh siden og sjekk at metabeskrivelsen er oppdatert.
=> Fixed updating subject pages

src/components/SlateEditor/plugins/embed/AudioPlayerMounter.tsx
https://github.com/NDLANO/Issues/issues/2782
Knappen gjør ingenting i editoren, men det er mer innlysende enn å kun ha en tom knapp. Alternativt kan vi endre `LicenseByLine` i frontend-packages slik at man kan omitte knappen.
=> Added a reuse label to Audio FigureCaptions.

src/components/PreviewDraft/PreviewDraft.tsx
Fixes NDLANO/Issues#2791
Ved bytting av språkversjon i sammenlikning eller forhåndsvisning av språkversjon i ed vil Mathjax ikke rendres lenger dersom det finnes i innholdet.
Hvordan teste:
1. https://ed.test.ndla.no/subject-matter/learning-resource/31044/edit/nb. Bytting mellom språk ved forhåndsvisning/sammenlikning vil få mathjax til å slutte å vises riktig.
2. Gjør det samme i PR-instans, men nå skal mathjax vises riktig selv etter bytting.
=> Trigger Mathjax script when preview content changes

src/components/SlateEditor/plugins/embed/AudioPlayerMounter.tsx, src/components/SlateEditor/plugins/embed/EditAudio.tsx, src/components/SlateEditor/plugins/embed/SlateAudio.tsx
Fikser delvis https://github.com/NDLANO/Issues/issues/2783
Fikser fullstendig sammen med https://github.com/NDLANO/frontend-packages/pull/889
Kallene til i18next i ed er unødvendige. Dette kallet trenger kun å brukes dersom man mottar en artikkel fra article-converter. Der den ble brukt i ED var innholdet allerede dynamisk.
=> Removed all calls to initAudioPlayers

src/components/PreviewConcept/PreviewConcept.tsx
En liten fiks på styling relatert til svg-er i visuelt element som blir rendret i størrelse 0*0px.
Forhåndsvisning av https://editorial-frontend-pr-1202.ndla.sh/concept/1197/edit/nn skal nå vise bilde i full bredde.
=> Concept visual element will be centered when not full width

cypress/integration/Editor/toolbar_spec.js, src/components/SlateEditor/plugins/embed/AudioPlayerMounter.tsx, src/components/SlateEditor/plugins/link/__tests__/normalizer-test.ts, src/components/SlateEditor/plugins/link/index.tsx
Fixes NDLANO/Issues#2805
Avventer https://github.com/NDLANO/editorial-frontend/pull/1217
Når man trykker backspace i en lenke skal den nå forsvinne når den er tom. Tidligere dukket den opp igjen etter lagring.
=> 2805 delete link with backspace

src/components/Dropdown/asyncDropdown/AsyncDropdown.tsx
Fixes NDLANO/Issues#2841
Retter en feil der asyncdropdown krasjer ved trykk på esc etter valg av element.
Hvordan teste:
1. Åpne PR-instans.
2. Åpne tilfeldig artikkel
3. Åpne seksjonen "Relatert innhold"
4. Skriv i "Forklaringer"-feltet og trykk på en vilkårlig forklaring.
5. Trykk på escape. I test vil dette krasje. I PR-instans skal dette gå fint.
=> Prevent async dropdown from crashing on esc-click

src/containers/ImageEditor/ImageEditor.tsx, src/containers/ImageEditor/ImageSizeButton.tsx, src/containers/ImageEditor/ShowBylineButton.tsx
Fixes NDLANO/Issues#2851
Fikser en feil der nettsiden krasjet ved forsøk på å redigere visuelt element. Dette gjaldt spesielt denne:
https://ed.test.ndla.no/subjectpage/urn:subject:1:8bfd0a97-d456-448d-8b5f-3bc49e445b37/78/edit/nn.
Hvordan teste:
1. https://editorial-frontend-pr-1264.ndla.sh
2. Åpne forklaring/emne/ndla-film eller emnet nevnt over.
3. Trykk visuelt element for å redigere (dersom det er et bilde)
4. Sjekk at siden ikke krasjer og at bilde kan redigeres og lagres som før.
=> Visual element without size and alt text no longer crashes on click

src/containers/FormikForm/components/ElementList.jsx
Fixes NDLANO/Issues#2853
Viser korrekt språk i lenke til læringssti.
Test:
* Åpne artikkel 5148 i pr-installasjon og i test. 
* Klikk på ikon for bruk i læringssti.
* I test er det undefined i urlen, men i pr-installasjon er det locale fra i18n.
=> Using correct prop

src/components/SlateEditor/plugins/concept/EditSlateConcept.tsx
Lenke til redigering av forklaring er feil. Det brukes et løpenummer for forklaringene i artikkelen, og det har sneket seg inn i lenka. Ser ingen umiddelbare problemer med dette, men @haattis har vel hatt en grunn for å gjøre det slik?
=> Bruker korrekt id for redigeringslenke

src/components/SlateEditor/plugins/embed/SlateImage.tsx
Fixes NDLANO/Issues#2869
Paragrafer i Slate skal ikke lenger dekke for hitboxen til bilder. Feilen kan sees her: https://ed.test.ndla.no/subject-matter/learning-resource/31293/edit/nb. Der er ikke hele bildet som er plassert ved siden av tekst klikkbart.
Hvordan teste:
1. Åpne den samme artikkelen i PR-instans.
2. Sjekk at hele bildet er klikkbart og åpner redigering ved klikk.
=> Slate: Place side aligned image above paragraphs to allow clicking it

src/components/DisplayEmbed/DisplayExternal.jsx
Redigerign av h5p skal oppdatere artikkelen slik som tidligere. Dette blei fiksa tidligere men forsvant i merge.
Test
* Rediger h5p i artikkel og sjekk at lagreknapp blir blå etter at du har lagra h5p.
=> Reverter endring som forsvant i merge av slate.

src/modules/taxonomy/topicresouces/index.ts
Fixes NDLANO/Issues#2873
Legger på ekstra parameter for å ta vare på relevance.
Test:
* Åpne en ressurs-artikkel og legg den under et emne i taksonomi.
* Velg at ressursen skal være tilleggstoff og klikk "Lagre taksonomi"
* Lukk og åpne taksonomiblokk og sjekk at ressursen er tilleggstoff.
=> Adding relevanceId as param to create topic-resource

src/containers/App/App.tsx, src/util/authHelpers.ts
Fixes https://github.com/NDLANO/Issues/issues/2872
Feilen kom av at AuthInitializer ble kjørt flere ganger. Fikset det ved å legge inn et flagg som sørget for at createMessage kunne bli satt, men at renewal ikke ble gjort. Dette reduserer auth0-kallene fra uendelig til 2-3 kall hver gang man fokuserer en fane.
=> Add option to ignore scheduled renewal of auth token

src/style/index.css
Plusser på 1px padding for å unngå at formler barberes i topp og bunn.
Matte som forhåndsvises i ed blir litt anderledes enn i frontend. Dette gjør at ting blir likere.
Test:
* Åpne artikkel med matte som også er publisert.
* Klikk på grønt ikon i toppen for å sjå artikkel på test.ndla.no
* Klikk på forhåndsvisning og sammenlig utseende på artikkelen i dei to fanene.
Artikkel 31308 kan brukes til test.
=> Setter samme utseende på matte som i frontend.

src/containers/SearchPage/SearchContainer.tsx
Fixes NDLANO/Issues#2879
Ved endring av sortering på søkeside ble alle andre parametre tilbakestilt. Denne PRen sørger for at parametrene ikke blir tilbakestilt lenger.
Hvordan teste:
- Åpne søkeside
- Gjør et søk med noe tekst og parametre
- Endre sortering og bekreft at antallet resultater er likt og at parametre ikke blir tilbakestilt.
=> Preserve search object on updating sort options

src/components/HeaderWithLanguage/EmbedInformation/EmbedConnection.tsx, src/components/HeaderWithLanguage/HeaderStatusInformation.tsx, src/phrases/phrases-en.ts, src/phrases/phrases-nb.ts, src/phrases/phrases-nn.ts
NDLA ønsker at ikon kun skal vises dersom det faktisk er bruk av innholdet.
Test:
* Ikon for at artikkel/bilde/lyd er brukt av andre skal kun vises dersom det faktisk er i bruk.
=> Viser ikon for bruk av innhold kun dersom dersom bruk.

src/components/PreviewDraft/PreviewProduction.tsx, src/phrases/phrases-en.ts, src/phrases/phrases-nb.ts, src/phrases/phrases-nn.ts
Viser andre headers for versjoner.
Test:
Om du sammenligner med gamle versjoner skal det no stå revisjonsnummeret i header.
=> Viser meir korrekte overskrifter på sammenligning av versjoner.

src/components/SlateEditor/plugins/paragraph/utils.ts, src/components/SlateEditor/plugins/table/index.tsx
Fixes NDLANO/Issues#2903
Fikser en feil der mathml som ligger direkte i `<td>` blir fjernet i normalisering.
Hvordan teste:
1. Åpne /subject-matter/learning-resource/31330/edit/nb i PR-instans. Alle matteformler skal vises.
- Lagreknappen blir aktivert, men det er fordi det mangler en celle i andre rad som automatisk blir lagt til.
=> 2903 bugfix deletion of mathml in table cells

src/components/SlateEditor/PlainTextEditor.tsx, src/components/SlateEditor/RichTextEditor.tsx, src/containers/ArticlePage/LearningResourcePage/components/LearningResourceContent.tsx, src/containers/ArticlePage/LearningResourcePage/components/LearningResourcePanels.tsx, src/containers/ArticlePage/TopicArticlePage/components/TopicArticleAccordionPanels.tsx, src/containers/ArticlePage/TopicArticlePage/components/TopicArticleContent.tsx, src/containers/FormikForm/VersionAndNotesPanel.tsx, src/containers/FormikForm/articleFormHooks.ts
Fixes NDLANO/Issues#2892
Slate editors vil nå endre seg ved tilbakestilling til en eldre versjon i læringsressurs. Da vil alle slate-felter oppdatere seg med verdiene fra den gamle versjonen.
Hvordan teste:
1. Åpne en læringsressurs.
2. Tilbakestill til en eldre versjon i versjonsloggen.
3. Alle felter i formen skal oppdateres til verdiene som er i den tilbakestilte versjonen.
=> Update slate content on reverting article version

src/components/SlateEditor/plugins/table/index.tsx
Fikser en feil der redigering av matte i tabell feiler. Enten ved lukking av matte-editor eller lagring av matte-editor.
Hvordan teste:
- Åpne /subject-matter/learning-resource/31330/edit/nb i PR-instans. Rediger en av matteformlene i tabellen (ikke formelen på første rad). Siden skal ikke krasje ved lagring/lukking av matte-editor.
=> Fix mathml edit crashing in tables

package.json, src/components/ControlledImageSearchAndUploader.tsx, src/components/ImageSearchAndUploader.tsx, src/components/SlateEditor/VisualElementEditor.tsx, src/components/SlateEditor/plugins/blockPicker/SlateVisualElementPicker.jsx, src/components/SlateEditor/plugins/concept/ConceptModal.tsx, src/containers/ArticlePage/TopicArticlePage/components/TopicArticleAccordionPanels.tsx, src/containers/ConceptPage/ConceptForm/ConceptForm.tsx, src/containers/ConceptPage/CreateConcept.tsx, src/containers/ConceptPage/EditConcept.tsx, src/containers/ConceptPage/components/ConceptMetaData.tsx, src/containers/FormikForm/MetaDataField.jsx, src/containers/FormikForm/MetaImageSearch.tsx, src/containers/FormikForm/formikConceptHooks.tsx, src/containers/FormikForm/utils.ts, src/containers/VisualElement/VisualElementSearch.jsx, src/containers/VisualElement/VisualElementSelectField.jsx, src/phrases/phrases-en.ts, src/phrases/phrases-nb.ts, src/phrases/phrases-nn.ts, yarn.lock
Fixes NDLANO/Issues#2770
Avventer https://github.com/NDLANO/frontend-packages/pull/929.
Hva er fikset:
- Forklarings-skjema viste delvis feil tilstand etter lagring. Feilen kan framprovoseres i test ved å velge et nytt visuelt element og deretter lagre. Visuelt element viser da gammelt innhold fram til man klikker hvor som helst i skjemaet, da endrer visuelt element seg til ny verdi. Dette er nå fikset.
- Har lagt til checkbox ved valg av metabilde i forklaring. Visuelt element settes til det samme dersom denne er markert.
=> 2770 sync concept meta and visual

src/components/SlateEditor/plugins/embed/SlateVideo.tsx
NDLANO/Issues#2688
Sjekker at relatert id er et tall før det brukes.
Test:
* Artikkel 31334 i test har to videoer med verdi i related-feltet. Kun den første er synstolka og skal ha knapp.
=> Checks if is number before using value for alternative video

src/containers/ArticlePage/LearningResourcePage/components/LearningResourceForm.tsx, src/containers/ArticlePage/TopicArticlePage/components/TopicArticleForm.tsx, src/containers/FormikForm/articleFormHooks.ts, src/containers/GrepCodes/GrepCodesForm.tsx
Fixes NDLANO/Issues#2885
Bruk av state setter oppdaterer ikkje verdien før etter render, så det som sendes inn tas ikkje hensyn til. Gjorde det enkelt og sender inn en verdi som defaulter til false.
Dagens oppførsel er at dersom du bruker lagre som ny så lagres det vanlig, men neste lagring vil uansett lagre som ny fordi flagget er satt og ikkje tilbakestillt.
Test:
* Valget lagre som ny skal fungere som det skal.
=> Make save as new work again

src/containers/SearchPage/SearchSaveButton.tsx
Fixes NDLANO/Issues#2913
Lagring av søk fra søkesiden feilet tidligere dersom dataen i databasen ikke eksisterte enda. Dette er nå fikset.
Hvordan teste:
1. Brukeren din i ed er nødt til å ikke ha lagret søk før.
2. Åpne søkesiden og forsøk å lagre et søk. Knappen skal indikere at søket er lagret og det skal bli synlig på søkesiden.
=> Bugfix: Save search now works when list is undefined

src/components/SlateEditor/plugins/mathml/MathEditor.tsx
Fixes NDLANO/Issues#2907
Forbedrer hvordan mathml-plugin håndterer fokus i Slate. Først og fremst skal den nå holde fokus ved mathml etter lukking av matte-editor uten å flytte fokus til toppen av nettsiden.
Test følgende i artikkel/emne:
1. Fokus skal settes ved mathml ved lagring, fjerning og lukking.
=> 2907 mathml UI improvements

src/containers/StructurePage/folderComponents/menuOptions/CopyResources.tsx
Fixes NDLANO/Issues#2914
Ikkje bruk emner uten path.
Test:
* Åpne pr og gå til strukturredigering
* Velg et emne og klikk på tannhjulet
* Velg menyvalg for kopiering eller kloning av ressurser fra anna emne
* Søk etter feks HMS. Alle treff skal ha en breadcrumb, som viser at den finnes i strukturen. I test får du opp emner uten dette.
=> Check if path before returning topics

src/components/HeaderWithLanguage/DeleteLanguageVersion.tsx, src/components/HeaderWithLanguage/HeaderActions.tsx, src/components/HeaderWithLanguage/HeaderInformation.tsx, src/components/HeaderWithLanguage/HeaderStatusInformation.tsx, src/components/HeaderWithLanguage/HeaderWithLanguage.tsx, src/components/StyledFilledButton/StyledFilledButton.jsx
Fixes https://github.com/NDLANO/Issues/issues/2911
Forsøkte først å legge til en tooltip, men det ser ut som at `@ndla/tooltip` ikke fungerer særlig bra på knapper som er disabled. Flere av ressursene (emneartikkel, læringsressurs, konsept) skjuler allerede slett språkversjon-knappen fullstendig dersom en ressurs kun har en språkversjon igjen. For andre typer så jeg på det som mer hensiktsmessig å bare disable den, men kan også fint endre det til å oppføre seg likt som de tidligere nevnte ressursene.
=> 2911 Disable delete language button when resource only has one language version and is in use elsewhere

package.json, src/components/SaveMultiButton.tsx, yarn.lock
Fixes NDLANO/Issues#2902
Denne PRen bruker alpha-pakker fra https://github.com/NDLANO/frontend-packages/pull/952
Har oppdatert MultiButton til å støtte overstyring av disabled-parameter for secondary-button og buttons i tilhørende dropdown. 
Dropdown er per nå tilgjengelig når lagreknapp er grå. Ikke når knappen er grønn/lagret.
Alternativt kunne man byttet ut MultiDropdown med to separate knapper, en for lagring og en for lagring av ny versjon.
Hvordan teste:
- Åpne en artikkel.
- Dropdown på lagreknapp skal være tilgjengelig selv om ingen endringer er gjort eller den er markert som grønn/lagret.
- MultiButton brukes også i redigering av forklaring fra søkesiden. Se at den fungerer fint der også.
=> Secondary button on SaveMultiButton can be enable with override

src/components/Taxonomy/ActiveTopicConnection.tsx
Fixes https://github.com/NDLANO/Issues/issues/2921
Hvordan teste:
1. Gå inn på en læringsressurs som inneholder en eller flere emnetilknytninger. Primærtilknytning-knappen skal vises.
2. Fjern taxonomy:admin-scopet fra brukeren din.
3. Logg ut og inn av brukeren din.
4. Gå inn på samme læringsressurs. Primærtilknytning-knappen skal ikke vises.
=> Only show primary connection button when user has taxonomy admin scope

src/components/PreviewDraft/PreviewDraftLightbox.tsx, src/components/PreviewDraft/PreviewLightboxContent.tsx, src/components/PreviewDraft/PreviewProduction.tsx
Fixes https://github.com/NDLANO/Issues/issues/2878
Synderen var hverken bilder eller H5P, men HTML! 
Forskjellen kan testes ved å se på forskjellen på [denne](https://ed.test.ndla.no/nn/subject-matter/learning-resource/31359/edit/nb) i test og i PR-instansen ved sammenligning av språk, i versjonshistorien og på forhåndsvisningssiden.
=> Fixed preview render bugs when an article included a CodeDiv

src/components/SlateEditor/plugins/related/EditRelated.tsx, src/components/SlateEditor/plugins/related/__tests__/__snapshots__/RelatedArticleBox-test.tsx.snap
Fixes https://github.com/NDLANO/Issues/issues/2932
Kan testes ved å gjenskape bildet i linket issue.
=> Added z-index to EditRelated in order to be above SlateImage when active

src/containers/FormikForm/AlertModalWrapper.tsx
Fixes NDLANO/Issues#2917
Fikser en feil der AlertModal i artikkel-editor redirecter deg til annet språk etter lagring.
Hvordan reprodusere i test:
1. Gjør en endring i bokmål.
2. Trykk på nynorsk versjon i header.
3. Trykk avbryt så du forblir på bokmål-versjon
4. Lagre deretter artikkel
5. Du skal nå ha blitt redirected til nynorsk, men artikkelen har blitt lagret som forventet.
i PR-instans skal du i steg 5 forbli på bokmål.
=> Reset AlertModalWrapper nextLocation on cancel

src/components/PreviewConcept/PreviewConcept.tsx, src/components/SlateEditor/plugins/concept/EditSlateConcept.tsx, src/components/SlateEditor/plugins/concept/SlateConceptPreview.tsx
Fixes https://github.com/NDLANO/Issues/issues/2933
Er det noen flere steder dette kan oppstå? Det virker som at article-converter allerede håndterer forklaringer i artikler.
=> Allow one to open image in new tab when viewing a slate concept or when previewing a concept

src/components/SlateEditor/plugins/list/utils/toggleList.ts
Fixes NDLANO/Issues#2942
Ved trippelklikk på en paragraf, slik at hele paragrafen blir markert + et ekstra mellomrom på høyre side, fikk man en rar interaksjon. Spesielt om den markerte paragrafen var siste element i en liste. Dette skjer fordi Slate har et konsept om at siste punkt på en linje tilsvarere første punkt på neste. 
Ved toggling av liste på siste paragraf i en boks endte slate derfor opp med å toggle liste _etter_ boksen heller.
Hvordan teste:
1. Åpne en artikkel og sett inn en av boks-typene.
2. Trippel-klikk siste paragraf på linja slik at du markerer alt + det ekstra "usynlige" mellomrommet på høyre side.
3. Toggle liste
4. Lista skal nå toggles inni boksen og ikke utenfor.
=> Unhang range when toggling list items

src/components/SlateEditor/plugins/concept/EditSlateConcept.tsx
Det skal alltid vises kva status forklaringa har. No vises dette kun dersom forklaringa er eller har vore publisert.
Test:
* Sett kladd-forklaring inn i artikkel og sjekk at status vises.
=> Viser alltid status for forklaring i artikkel.

src/components/MonacoEditor/editorActions.js, src/containers/EditMarkupPage/EditMarkupPage.tsx, src/phrases/phrases-en.ts, src/phrases/phrases-nb.ts, src/phrases/phrases-nn.ts
Feilen ble introdusert i https://github.com/NDLANO/editorial-frontend/pull/1284, og kommer antageligvis av endringen fra klassekomponent til funksjonskomponent. Jeg er ikke helt sikker på hva feilen er, men det virker som at funksjonen som passeres inn til Monaco tar i bruk state-verdiene den innehar når Monaco-instansen blir opprettet. 
`draft`-verdien i `EditMarkupPage` sin state er riktig helt inntil den kalles på inne i `saveChanges`. Derfor mente jeg den mest logiske løsningen var å heller la Monaco håndtere denne staten i størst mulig grad. Den brukes dog fortsatt for å oppnå lagring ved knappetrykk. 
Fikset også en oversettelse som ser ut til å ha falt bort for en stund siden. La inn en ny nøkkel for å fikse det.
=> Fixed the ability to save in the html editor by pressing MOD+S

cypress/integration/Editor/editorRoutes.js
Fikser forhåpentligvis den flaky cypress-testing i full_resource_spec.
=> Mock out call to search-api

src/containers/ArticlePage/articleTransformers.ts
Fixes https://github.com/NDLANO/Issues/issues/2962
Hvordan teste: Legg til en læreplankobling på en topic-article. Etter lagring og refreshing av siden skal grepCoden forbli.
=> 2962 Add grepCodes field when converting TopicArticleFormType to UpdatedDraftApiType

src/components/SlateEditor/helpers.ts, src/components/SlateEditor/interfaces.ts, src/components/SlateEditor/plugins/span/__tests__/normalizer-test.ts, src/components/SlateEditor/plugins/span/__tests__/serializer-test.ts, src/components/SlateEditor/plugins/span/index.tsx, src/containers/ArticlePage/LearningResourcePage/components/LearningResourceContent.tsx, src/containers/ArticlePage/TopicArticlePage/components/TopicArticleContent.tsx, src/util/articleContentConverter.tsx
Fixes NDLANO/Issues#2963
Opprettet en ny plugin for å håndtere spans med language. Feks `<span lang="en">some English text</span>`
Hvordan teste:
1. Åpne en artikkel
2. Legg til en span tilsvarende den over i html-editor. Feks `<p>Engelsk tekst: <span lang="en">some English text</span></p>`
3. Lagre.
4. Gjør noen endring i slate-editor og lagre.
5. Gå tilbake til html-editor og sjekk at span med lang-attributt fortsatt finnes.
=> Add span plugin to handle span with language attribute

cypress/integration/Editor/slate_block_picker_spec.js, src/containers/VisualElement/VisualElementSearch.tsx
Fixes https://github.com/NDLANO/Issues/issues/2972
`audioType` er ikke et parameter til API'et, så det har tidligere blitt slettet fra query-objektet. Da defaulter AudioSearch til standard. Gått over til å beholde `audioType` i query-objektet, og istedenfor transformere det til riktig form.
=> Don't delete audioType from audio query type

src/components/SlateEditor/plugins/embed/EditAudio.tsx, src/components/SlateEditor/plugins/embed/SlateAudio.tsx, src/components/SlateEditor/plugins/embed/SlatePodcast.tsx, src/containers/VisualElement/VisualElementSearch.tsx, src/interfaces.ts
Fixes NDLANO/Issues#2975
Fjerner input-felt fra caption i slate. Dataen vil likevel aldri forsvinne fra eksisterende embeds med mindre det slettes i html-editor eller at det lages en ny migrasjon.
Det går an å skrive om Slate til å bli strengere og ikke ta med uønskede attributter, men det vil føre til at lagreknappen blir blå i alle artikler som har `data-caption`-feltet per nå. Noen tanker?
Hvordan teste:
- Legg inn Lyd i artikkel.
- Trykk på den etterpå for å redigere. Det skal ikke lenger finnes et felt for lydtekst.
=> 2975 remove audioembed caption

src/components/SlateEditor/helpers.ts, src/components/SlateEditor/plugins/aside/__tests__/serializer-test.ts, src/components/SlateEditor/plugins/bodybox/__tests__/serializer-test.ts, src/components/SlateEditor/plugins/codeBlock/__tests__/serializer-test.ts, src/components/SlateEditor/plugins/concept/__tests__/serializer-test.ts, src/components/SlateEditor/plugins/details/__tests__/serializer-test.ts, src/components/SlateEditor/plugins/embed/__tests__/serializer-test.ts, src/components/SlateEditor/plugins/file/__tests__/serializer-test.ts, src/components/SlateEditor/plugins/footnote/__tests__/serializer-test.ts, src/components/SlateEditor/plugins/link/__tests__/serializer-test.ts, src/components/SlateEditor/plugins/mathml/__tests__/serializer-test.ts, src/components/SlateEditor/plugins/noEmbed/__tests__/serializer-test.ts, src/components/SlateEditor/plugins/related/__tests__/serializer-test.ts, src/components/SlateEditor/plugins/span/__tests__/serializer-test.ts, src/components/SlateEditor/plugins/table/__tests__/serializer-test.ts, src/components/SlateEditor/plugins/table/index.tsx, src/containers/ArticlePage/LearningResourcePage/components/LearningResourceForm.tsx, src/containers/ArticlePage/TopicArticlePage/components/TopicArticleForm.tsx, src/style/table.css, src/util/convertFromHTML.ts, src/util/formHelper.ts
Forbedrer ytelsen på slate med et par endringer:
- Ved konvertering av html til Slate gjøres det samtidig noe manuell normalisering nå. Tomme tekstfragmenter settes inn rundt inline-elementer (linker, matte osv) og tomme paragrafer settes ut rundt blokker (bilder, video osv). Dersom dette gjøres av Slate sin innebygde normalisering blir prosessen mye tyngre.
- Memoiserer html-en av originalartikkel. Dette reduserer tiden det tar å diffe htmlen med ca 50%. (Fra 90-110ms til 40-50ms)
- Fikset samtidig css på tabeller inni ekspanderende boks/faktaboks/tekstboks. Brede tabeller kunne tidligere flyte over sidene av boksen. Dette gjelder kun stylingen i slate.
=> Slate performance improvements

src/containers/ArticlePage/TopicArticlePage/components/TopicArticleTaxonomy.tsx
Fixes NDLANO/Issues#2980
Gjør alltid nye emner usynlige i taksonomi.
Test:
* Plasser et emne på en ny plass og lagre. Emnet skal være markert som usynlig.
=> Always set metadata invisible for new topic.

src/constants.ts, src/containers/VisualElement/__tests__/transformUrlIfNeeded-test.js, src/containers/VisualElement/urlTransformers.ts, src/server/contentSecurityPolicy.ts
Fixes NDLANO/Issues#3013
Legger til støtte for sketchup embeds.
Test
* Sjekk at du kan legge til feks https://3dwarehouse.sketchup.com/model/eb498ef3-3de5-42ca-a621-34ea29cc08c4/Oppbygging-av-ringmur og at dette lagres med embed-url uten tittel.
=> Adds support for sketchup urls

src/containers/VisualElement/VisualElementUrlPreview.tsx, src/interfaces.ts
Legger til lagring av type iframe for iframe-embeds for å være klar når https://github.com/NDLANO/backend/pull/33 deployes.
Test:
* Når du setter inn ressurs fra lenke så sendes data-type=iframe i payload.
* I test vil propertyen ignoreres og fjernes
* Om du kjører mot versjon fra pr så lagres det og returneres.
Neste steg er å utvide ressurs fra lenke til å kunne spesifisere tittel, caption og bilde.
=> Add type-property to iframe embed.

src/containers/SearchPage/components/results/SearchConcept/ContentView.tsx, src/util/routeHelpers.ts
Fixes NDLANO/Issues#3041
Unngår å få ukjente språkvarianter for forklaringer fra søkeresultatet.
=> Removes lang from toEditConcept

src/containers/StructurePageBeta/NodeItem.tsx, src/containers/StructurePageBeta/RootNode.tsx, src/containers/StructurePageBeta/StructureContainer.tsx
Vet ikke om dette kan kalles prematurt, men jeg synes det blir veldig overkill å rerendre hvert eneste item i struktur hver gang man klikker på noe. Denne PR'en sørger for at det kun er treet til den nåværende og den forrige rotnoden som rerendres. For å få til dette endret jeg også på måten vi håndterer favoritter på, slik at man enkelt bare kan passere en boolean ned til rotnoden.
=> Added memoization for root nodes

src/containers/StructurePageBeta/folderComponents/SettingsMenuDropdownType.tsx, src/containers/StructurePageBeta/folderComponents/sharedMenuOptions/EditGrepCodes.tsx, src/containers/StructurePageBeta/folderComponents/sharedMenuOptions/components/MenuItemEditField.tsx, src/modules/grep/grepApiInterfaces.ts, src/modules/grep/grepQueries.ts, src/modules/nodes/nodeMutations.ts, src/queryKeys.ts, src/util/queryUtils.ts
Her la jeg også inn en endring som påvirker endring av synlighet, gruppering av ressurser og endring av `customFields`. Ser ikke ut til å ha påvirket noe, men gjerne sjekk at endringer holder seg selv etter at du har klikket deg rundt til andre noder. Sjekk også at det ikke går an å møte på en race condition når du sletter flere grep-koder rett etter hverandre.
=> Re-added grep-codes to both root and child nodes

src/containers/StructurePageBeta/resourceComponents/GrepCodesForm.tsx, src/containers/StructurePageBeta/resourceComponents/GrepCodesModal.tsx, src/containers/StructurePageBeta/resourceComponents/Resource.tsx, src/modules/draft/draftMutations.ts
Denne må endres dersom vi velger å ta inn https://github.com/NDLANO/editorial-frontend/pull/1402
Sjekk at grep-koder på ressurser blir oppdatert når du går ut av grepkode-modalen. Sjekk også at formet ikke blir dirty dersom du "går tilbake" til forrige `initialValues`-state.
Skulle gjerne tatt for meg `GrepCodesField`-komponenten også, men det virker som en større oppgave som heller kan tas senere. Virker som at `AsyncDropdown` helt fint kunne blitt erstattet med en React Query-ekvivalent for et bedre resultat.
=> Added back ability to add grep codes to structure resources

src/containers/StructurePageBeta/RootNode.tsx, src/containers/StructurePageBeta/StructureContainer.tsx, src/containers/StructurePageBeta/folderComponents/sharedMenuOptions/EditGrepCodes.tsx, src/containers/StructurePageBeta/folderComponents/sharedMenuOptions/ToggleVisibility.tsx, src/containers/StructurePageBeta/folderComponents/sharedMenuOptions/components/MenuItemCustomField.tsx, src/containers/StructurePageBeta/folderComponents/subjectMenuOptions/ChangeNodeName.tsx, src/containers/StructurePageBeta/folderComponents/topicMenuOptions/GroupTopicResources.tsx, src/containers/StructurePageBeta/resourceComponents/AddResourceModal.tsx, src/containers/StructurePageBeta/resourceComponents/Resource.tsx, src/containers/StructurePageBeta/resourceComponents/ResourceItems.tsx, src/containers/StructurePageBeta/resourceComponents/StructureResources.tsx, src/containers/StructureVersion/TaxonomyVersionProvider.tsx, src/interfaces.ts, src/modules/nodes/nodeApi.ts, src/modules/nodes/nodeMutations.ts, src/modules/nodes/nodeQueries.ts, src/util/apiHelpers.ts
Det er ikke sjans i havet at dette går uten at hvertfall en ting brekker. 
Bestemte meg for å ikke inkludere `taxonomyVersion` i `react-query`-kallene sin cache; Hvis vi først endrer taxonomy-versjon kan vi likesågodt invalidere hele cachen.
=> Added taxonomyVersion parameter to every node api call

src/constants.ts, src/containers/SearchPage/components/results/SearchConcept/ConceptForm.tsx
NDLANO/Issues#3047
Fikser sånn at kun admin kan publisere forklaring fra inline-skjema.
Test:
* Må nesten testes lokalt. Endre på konstant CONCEPT_ADMIN_SCOPE og sjekk at du ikkje lenger har lov å lagre og publisere fra inlineredigering.
=> Hide save and publish for non admins.

src/util/articleContentConverter.tsx
Fixes NDLANO/Issues#3061
Emneartikler som har mer enn én seksjon skal nå vise alle seksjonene i ed. Har samtidig redusert mengden kode litt da flere av funksjonene var veldig like.
Hvordan teste:
1. Åpne eller lag artikkel med flere seksjoner. Feks /nn/subject-matter/topic-article/25555/edit/nn.
2. Redigering og lagring av flere seksjoner skal fungere. Sletting av seksjoner skal også fungere.
=> 3061 multi section in topic

src/components/SlateEditor/RichTextEditor.tsx
Oppdaget en feil da jeg testet kopiering av matte som fører til at matte ikke blir reinitialisert riktig ved lagring.
Feilen kan fraprovoseres på test ved å lagre en artikkel med matte to ganger. Da vil formateringen forsvinne.
Gjør det samme i PR-instans og det vil gå å lagre mange ganger etter hverandre uten at formatering forsvinner.
=> Mathjax will reinitialize properly on save

src/containers/ArticlePage/LearningResourcePage/EditLearningResource.tsx, src/containers/ArticlePage/TopicArticlePage/EditTopicArticle.tsx, src/containers/AudioUploader/EditAudio.tsx, src/containers/ConceptPage/EditConcept.tsx, src/containers/FormikForm/translateFormHooks.ts, src/containers/Podcast/EditPodcast.tsx
Som ønska på https://trello.com/c/G01BVAuK/1422-metadata-om-listeoppf%C3%B8ring-nynorsk-bokm%C3%A5l-p%C3%A5-forklaring-m%C3%A5-samkj%C3%B8res
Støtter oversettelse av nøkkelord.
Test:
* Lag artikkel og legg inn nøkkelord som vil være forskjellig på bokmål og nynorsk
* Oversett artikkel til nn og sjekk at nøkkelord også er oversatt.
=> Litt hårete, men støtter nynorskoversettelse av nøkkeord.

src/components/SlateEditor/RichTextEditor.tsx, src/components/SlateEditor/plugins/blockPicker/SlateBlockPicker.tsx, src/components/SlateEditor/plugins/blockPicker/options.ts, src/components/SlateEditor/plugins/paragraph/Paragraph.tsx, src/containers/ArticlePage/LearningResourcePage/components/LearningResourceContent.tsx, src/containers/ArticlePage/TopicArticlePage/components/TopicArticleContent.tsx
Ble nødvendig å skrive om pluss-menyen i Slate til å plasseres absolutt i en Portal i stedet for som en del av paragrafer. Pluss-menyen skal nå være tilgjengelig i tabeller og siden tabeller har overflow: hidden fungerer ikke nåværende løsning lenger. Litt synd, for portaler og manuell oppdatering av position skaper flere bugs 🤷 Uansett, det ser ut som at dette fungerer bra, men måtte bruke en setTimeout på 0ms for å unngå rare posisjoner på menyen. Visning i tabell kommer i en senere PR.
Hvordan teste:
1. Åpne en artikkel.
2. Forsøk diverse innsettinger fra menyen, åpning, lukking og trykk på diverse annet i editoren. Målet er at alt skal fungere likt som før.
=> Slate blockpicker in root

src/components/SlateEditor/plugins/concept/inline/InlineConcept.tsx, src/components/SlateEditor/plugins/concept/inline/SlateNotion.tsx
Fixes NDLANO/Issues#2965
Navigering med piltaster i Notion har vært veldig buggy til nå. Grunnen er at Slate har problemer med å håndtere tekst i `<button>`-elementer. Derfor har jeg laget en Slate-variant av Notion som ikke bruker `<button>`.
Hvordan teste:
1. Åpne en artikkel som har flere inline-forklaringer (settes inn fra toolbar ved markering av tekst eller ctrl+alt+c). Bruk gjerne /nn/subject-matter/learning-resource/31329/edit/nb
2. Naviger gjennom forklaringene med piltaster, spesielt trykk på opp/ned når du har markøren inni forklaringen.
3. Sjekk også at åpning av modal og fjern-knapp i modal fungerer som før.
=> 2965 inline notion bugfix

package.json, src/components/SlateEditor/plugins/mathml/MathEditor.tsx, yarn.lock
Fant ikke ut nøyaktig når dette har brukket, for det så ut som fokus etter lukking av modal har vært trøblete en stund. Uansett: problemet med fokus er løst (som alltid når Slate er vrang) med setTimeout på 0ms. 
Oppdaget samtidig at Slate har en bug introdusert med versjon 0.77.2 relatert til inline-voids plassert på slutten av en linje. Gjør det umulig å bruke piltast til å plassere markøren etter feks Mathml. Bruker derfor versjon 0.77.0 inntil videre og har subscribed til issue på github.
Hvordan teste:
1. Opprett mathml og lagre. Markøren skal plasseres rett etter mathml.
2. Åpne eksisterende mathml og avbryt. Markøren skal her også plasseres rett etter mathml.
3. Marker en mathml som er i slutten av en paragraf. Sjekk at pil til høyre plasserer markør til høyre for mathml. Samme for …
=> Bugfix mathml

src/containers/StructurePageBeta/NodeItem.tsx, src/containers/StructurePageBeta/folderComponents/FolderItem.tsx, src/containers/StructurePageBeta/folderComponents/SettingsMenu.tsx, src/containers/StructurePageBeta/folderComponents/SettingsMenuDropdownType.tsx, src/containers/StructurePageBeta/folderComponents/sharedMenuOptions/DeleteNode.tsx, src/interfaces.ts, src/modules/nodes/nodeApi.ts, src/modules/nodes/nodeMutations.ts, src/phrases/phrases-en.ts, src/phrases/phrases-nb.ts, src/phrases/phrases-nn.ts
Legger inn støtte for å slette noder i struktur-beta. I tidligere versjon måtte man behandle subject, subject-topic og topic-subtopic forskjellig. I denne versjonen differensierer man kun mellom rotnode og barnenode. Hvis en barnenode slettes vil også connection slettes, samt at emnebeskrivelsen slettes hvis den kun brukes her. 
Kan testes ved å legge til en ny rotnode, for deretter å legge minst to nivåer med barn inn under den. Slett deretter hele treet fra blad-nivå og oppover.
=> Added options for deleting nodes in structure beta

src/components/HeaderWithLanguage/HeaderStatusInformation.tsx, src/phrases/phrases-en.ts, src/phrases/phrases-nb.ts, src/phrases/phrases-nn.ts
Viser feed-ikon i header på podkastserie.
Test:
* Sjekk at det vises url til feed i header på serier.
=> Add feed-icon to series page.

package.json, src/containers/TaxonomyVersions/components/Version.tsx, src/containers/TaxonomyVersions/components/VersionForm.tsx, src/modules/taxonomy/versions/versionQueries.ts, yarn.lock
Relatert til https://github.com/NDLANO/Issues/issues/3076.
Prøver å splitte denne opp, og dette virket som et greit sted å starte.
Denne PR'en inneholder to endringer, der den første ikke har noe med issuet å gjøre. Jeg bumpet react-query for å fikse query key-tekstfargen slik at det ikke lenger er hvit tekst på hvit bakgrunn.
Den andre, og store endringen er at jeg har laget et nytt system for hvordan man oppretter en query key. En query key er en nøkkel som forbindes med en spesifikk API-spørring. Dersom man spør etter data fra samme query key to ganger på rad vil react-query bruke cache og returnere umiddelbart, før den eventuelt returnerer oppdatert data fra API'et. Vår gamle løsning baserte seg på at utvikleren hadde en grei kunnskap om hvordan en spesifikk nøkkel var bygget opp i …
=> Add a more sustainable way to invalidate queries

src/containers/SearchPage/components/form/SearchContentForm.tsx, src/containers/StructurePageBeta/resourceComponents/StructureResources.tsx, src/modules/taxonomy/resourcetypes/resourceTypesQueries.ts
Relatert til https://github.com/NDLANO/editorial-frontend/pull/1442
I samme stil som https://github.com/NDLANO/editorial-frontend/pull/1442
Sjekk at ressurstyper fungerer på lagrede søk, på søkesiden og på ressursvisningen i struktur-beta. Gjøres ingen invalidering på dette direkte, så burde være greit.
=> New query keys for resource types

src/containers/ConceptPage/conceptTransformers.ts
Fixes NDLANO/Issues#3086
Det går ikkje an å lagre forklaringer med status PUBLISHED fordi endring av status fungerer ikkje når du sender inn gjeldende status med update. Kunne sikkert løst dette i concept-api også men dette var en raskere fiks.
Test:
* Sjekk at det går an å lagre forklaringer som er publiserte og at status endres til kladd.
=> Do not send status with update

src/components/ResourcePage.tsx, src/containers/App/SubjectMatterPage.tsx, src/containers/StructurePageBeta/resourceComponents/GrepCodesModal.tsx, src/containers/WelcomePage/components/LastUsedContent.tsx, src/modules/audio/audioQueries.ts, src/modules/concept/conceptQueries.ts, src/modules/draft/draftQueries.ts, src/modules/image/imageQueries.ts
Måtte ta dette sammen for å unngå feil. Dette går i all hovedsak på søkesidene og form-sidene. Kan derfor testes ved å sjekke at søk og navigering til alle ressurser fungerer som før. Sjekk også forsiden, da den tar i bruk draft-queries.
=> Added query key functions to search and single-resource query functions

src/components/SlateEditor/plugins/concept/block/BlockConcept.tsx, src/components/SlateEditor/plugins/concept/block/BlockConceptPreview.tsx, src/components/SlateEditor/plugins/concept/inline/InlineConceptPreview.tsx, src/components/SlateEditor/plugins/concept/inline/SlateNotion.tsx
Inline-forklaring i slate fikk feil visning i modal etter feilrettinger jeg gjorde tidligere. Den fikk det nye blokk-visningsformatet, men skal fortsatt vises som tidligere. Har rettet dette opp ved å lage to separate preview-types, en for inline og en for blokk-visning.
Hvordan teste:
1. Åpne en artikkel.
2. Sett inn en forklaring
3. Modalen som åpnes skal ha "gammel" visning med visuelt element på toppen og tekst under.
=> Separate previews for inline and block concept

src/components/SlateEditor/plugins/embed/EditImage.tsx
Oppdaget et problem med bilder av små størrelse der bilderedigerings-modal ble veldig smal og dermed gjøre det vanskelig å redigere bilde. Feilen kan framprovoseres i test ved å sette inn et bilde av størrelse "frimerke" (må høyre eller venstrestilles først) og deretter trykke på det igjen for å åpne editoren.
Dette er nå løst ved at modalen alltid har samme bredde som slate-editoren.
Hvordan teste:
1. Åpne artikkel.
2. Sett inn bilde og trykk på det etterpå.
3. Høyre eller venstre-juster og sett størrelse til frimerke. Lagre bilde.
4. Trykk på bildet igjen. Bredden på editoren skal fortsatt være stor.
=> Slate image editor always have full width

src/containers/StructurePage/folderComponents/menuOptions/CopyResources.tsx, src/containers/StructurePageBeta/folderComponents/SettingsMenuDropdownType.tsx, src/containers/StructurePageBeta/folderComponents/topicMenuOptions/CopyNodeResources.tsx, src/interfaces.ts, src/modules/nodes/nodeApi.ts, src/modules/nodes/nodeMutations.ts, src/modules/taxonomy/resources/index.ts, src/phrases/phrases-en.ts, src/phrases/phrases-nb.ts, src/phrases/phrases-nn.ts
Med denne PR'en merget inn er struktur-beta feature-complete!!
Jeg er litt usikker på hvordan man skal få testet feilhåndtering her; Har inntil videre ikke kommet på en god måte å fremprovosere feil på, annet enn å endre på URL'en man treffer. 
Happy-pathen kan testes ved å få oversikt over hvilke ressurser som eksisterer på et emne. Etter at man har navigert seg til et annet emne kan man deretter sjekke at `kopier`-knappen legger ressursene under den nyvalgte noden. Det samme kan også gjøres for kloning, men da er det også greit å sjekke at det er har blitt opprettet nye versjoner av selve ressursene også.
=> Add copy and clone resources functionality for structure beta

src/containers/AudioUploader/components/AudioContent.tsx, src/containers/AudioUploader/components/AudioForm.tsx, src/containers/AudioUploader/components/AudioMetaData.tsx, src/containers/Podcast/components/PodcastForm.tsx
Dette gjelder AudioMeta og AudioContent i lyd- og podkast-skjemaer. Klassene passeres inn, men brukes ikke til noe.
=> Remove unneeded BEM classes for audio content and audio meta

src/components/SlateEditor/plugins/mathml/MathEditor.tsx
Et par feilrettinger på mathml i slate. I alle disse tilfellene skal markør plasseres etter matte:
- Innsetting av matte ved markering av tekst
- Innsetting av matte ved umarkert tekst og trykk på ctrl+m 
- Lagring av eksisterende matte
Forklaring av kodeendringene: Vet ikke. Fokus er weird. Virker likevel som om dette er litt mindre forutsigbart enn andre ting i Slate da mathml også re-rendrer seg asynkront.
=> Always set focus after mathml when editing

now.json, src/components/SlateEditor/plugins/concept/block/BlockConceptPreview.tsx, src/components/SlateEditor/plugins/concept/inline/InlineConceptPreview.tsx
Legger til status-ikon på blokkforklaring. Følger samme mal som i inline-forklaring.
Hvordan teste:
- Sett inn blokkforklaring fra plussmeny. Sjekk at forklaring markeres med grønt/grått ikon avhengig av publiseringsstatus.
=> Add status icon to block concept

src/components/SlateEditor/plugins/mathml/MathML.tsx
Dette er en feil som er fikset i ndla frontend og forhåndsvisning av artikkel i ed. Absoluttverdi-wrapping i mathml forsvinner i en del tilfeller.
Legger på samme styling i matte i slate.
Hvordan teste:
- Åpne /subject-matter/learning-resource/31044/edit/nb (skal være mathml der nå)
- Endre skalering på nettsiden større/mindre og se at absoluttverdi-wrapping forblir der hele tiden.
=> Prevent pipes in mathml for disappearing

src/components/SlateEditor/plugins/mark/index.tsx, src/style/code.css, src/style/index.css
Med mindre Slate finner på noe lurt ser jeg ingen grunn til at dette ikke skal være likt.
=> Move c-inline__code to Styled Component

src/components/HeaderWithLanguage/HeaderStatusInformation.tsx, src/config.ts, src/containers/ArticlePage/LearningResourcePage/components/LearningResourcePanels.tsx, src/containers/ArticlePage/TopicArticlePage/components/TopicArticleAccordionPanels.tsx, src/containers/SearchPage/components/form/SearchContentForm.tsx, src/containers/StructurePageBeta/folderComponents/SettingsMenuDropdownType.tsx
NDLA trenger litt meir tid for å lande revisjoner. Legger til miljøvariabel for å skru på enn så lenge.
I denne pr-installasjonen er verdien ikkje satt, så derfor er det nok å sjekke at Revisjoner er borte fra artikkel, at klokke-ikon ikkje vises i artikkel/søkeresultat, og at valg for å sette revisjonsdato på barn i struktur er borte.
=> Skjuler revisjoner så lenge det ikkje er eksplisitt skrudd på.

src/components/SlateEditor/plugins/aside/SlateRightAside.tsx
Keep classNames to get css from ndla-ui.
Denne er verken pen eller vakker, men sikkert greit å støtte den uansett. 
Kan sammenligne utseendet på https://ed.test.ndla.no/subject-matter/learning-resource/31473/edit/nb med PR-instans for å teste.
=> Convert SlateRightAside ED css to emotion. 

src/containers/PreviewDraftPage/PreviewDraftPage.tsx
Var et enkelt overflow problem.
*For å gjenskape:* 
I innhold, klikk på ordet som har forklaring
*Her fungerer det ikke:*
https://ed.test.ndla.no/preview/31480/nb
*Her fungerer det:*
https://editorial-frontend-pr-1514.ndla.sh/preview/31480/nb
Closes NDLANO/Issues#3090
=> Fikset avkuttet forklaringsmodal

src/containers/FormikForm/AddRevisionDateField.tsx, src/containers/NodeDiff/DiffOptions.tsx, src/containers/SearchPage/components/form/SearchContentForm.tsx, src/containers/StructurePageBeta/folderComponents/SettingsMenuDropdownType.tsx, src/phrases/phrases-en.ts, src/phrases/phrases-nb.ts, src/phrases/phrases-nn.ts
Fixes NDLANO/Issues#3145
Menyvalg for å kopiere revisjonsdato skjules. Funksjonaliteten blir liggende i apiet, så sletter ikkje komponenten i tilfelle den skal inn igjen.
Endrer størrelse på et par søkefelt for å få litt bedre flyt for dersom revisjonsdato er skrudd av. Dette vil fjernes etter kvart.
Fikser en feil label i diff-visning av nodetrær.
=> 3145 hide clone revisions

src/components/Lightbox.tsx, src/containers/Messages/__tests__/__snapshots__/Messages-test.tsx.snap, src/containers/StructurePage/__tests__/__snapshots__/AddResourceModal-test.tsx.snap
Super kjapp fix av bredde-problem på sammenlikning av språkversjoner. Er ikke veldig kjent med hvor komponenten brukes utover her, så hadde vært fint om noen kunne peke meg i riktig retning dersom dette brekker design på andre steder.
**Eksempel:**
> Klikk på sammenlign språkversjoner
**Før:** https://ed.test.ndla.no/subject-matter/learning-resource/31469/edit/nb
**Etter:** https://editorial-frontend-pr-1521.ndla.sh/subject-matter/learning-resource/31469/edit/nb
---
Closes NDLANO/Issues#3125
=> Fix article width bug

src/components/SlateEditor/plugins/embed/EditImage.tsx
Kan sammenlignes med f.eks; https://ed.test.ndla.no/subject-matter/learning-resource/31044/edit/nb der det ikke funker. Hvis man oppretter ny forklaring på et ord og deretter velger bilde og forsøker å redigere det - vil siden krasje.
Etter å ha fikset at siden ikke krasjet når man skal redigere bildet, måtte det fikses at bilderedigeringsmodalen ikke havnet bak forklaringsmodalen.
Closes https://github.com/NDLANO/Issues/issues/3156
=> Prevent error when editing image in concept modal

src/components/SlateEditor/plugins/concept/ConceptModal.tsx
Closes https://github.com/NDLANO/Issues/issues/3168
_Det som var feil:_ Dersom man skulle bla gjennom flere sider av forklaringer i forklaringsmodal, ble innholdet på siden oppdatert, men ikke sidetallet. Da kunne man ikke bla bakover fordi uansett hvilken side man var på så stod sidetallet som 1. 
Nå funker det å navigere seg gjennom sidene og sidetallet oppdateres riktig.
=> Update page number in pager

cypress/integration/Editor/slate_block_picker_spec.js, src/components/ControlledImageSearchAndUploader.tsx, src/components/ImageSearchAndUploader.tsx, src/containers/FormikForm/MetaImageSearch.tsx, src/containers/VisualElement/VisualElementSearch.tsx, src/containers/VisualElement/VisualElementUrlPreview.tsx
Legger til ekstra parameter language i tillegg til locale for bildesøk, slik at det går an å sende inn artikkelspråk for å få korrekt bildetreff. Det hadde ikkje holdt å bruke locale for då vil du få samme visning uavhengig av artikkelspråket.
Test:
* Lag en artikkel med både bokmål og nynorskversjon. 
* Sett inn bilde i artikkel og søk på 54559. Du skal få forskjellig bilde avhengig av språk fordi denne id-en har forskjellige bildefiler for nynorsk og bokmål.
=> Legger til mulighet for å sende inn artikkelspråk til bildesøk.

src/containers/StructurePage/folderComponents/menuOptions/DeleteTopic.tsx
Fixes NDLANO/Issues#3184
Det var en logisk brist i koden. Fordi sletting av emner først er sletting av koblingsobjekt, så vil emnet du sletter faktisk bli filtrert ut fordi path er borte. Så det er kun når lengda på emner uten path er 0 at du faktisk kan arkivere artikkelen.
=> Sletter emneartikler dersom ingen emner bruker artikkelen.

src/containers/ConceptPage/ConceptForm/ConceptForm.tsx, src/containers/ConceptPage/components/ConceptMetaData.tsx, src/containers/FormikForm/MetaDataField.tsx, src/containers/FormikForm/MetaImageSearch.tsx, src/containers/Podcast/components/PodcastForm.tsx, src/containers/Podcast/components/PodcastMetaData.tsx, src/containers/PodcastSeries/components/PodcastSeriesForm.tsx, src/containers/PodcastSeries/components/PodcastSeriesMetaData.tsx, src/containers/SearchPage/components/results/SearchConcept/SearchConcept.tsx, src/containers/SearchPage/components/results/SearchContent.tsx
Fixes NDLANO/Issues#3171
Bruker innholdsspråk for å vise metabilde.
Test:
* Endre metabilde for innhold med språkvariant nn og nb og bruk bildeid 54599
* Alle plasser der dette bildet brukes skal forskjellig variant vises.
=> Use content language to fetch image.

src/config.ts, src/containers/FormikForm/formikSubjectpageHooks.ts
Fixes https://github.com/NDLANO/Issues/issues/3181
Kan testes ved å navigere mellom forskjellige språkversjoner av en fagforside der innholdet varierer basert på språket man er på. Kan også testes ved å lagre og bytte språkversjon flere ganger.
=> Remove stored subjectpage when switching languages to fix bug with PlainTextEditor

src/config.ts, src/containers/VisualElement/VisualElementSearch.tsx
Fixes NDLANO/Issues#3194
Test:
* Sett inn video med opphavsrett og sjekk at videoid wWQ015NyI lagres. (Vercel og deploy er oppdatert med ny variabel)
=> Use separate playerid for copyrighted videos.

package.json, src/components/SlateEditor/plugins/concept/inline/InlineConcept.tsx, src/components/SlateEditor/plugins/concept/inline/utils.ts, yarn.lock
Fixes NDLANO/Issues#3188
Ved innsetting av forklaring vil nå spaces i start/slutt av ord ikke markeres. Slate har ingen direkte støtte for dette så vidt jeg kunne se, så må manuelt telle spaces og redusere det markerte området. Oppdaterer også Slate til siste versjon.
Hvordan teste:
- Åpne artikkel og skriv et par ord.
- Marker rundt et ord inkludert mellomrom.
- Sett inn forklaring via toolbar eller ctrl+alt+c
- Forklaringen som ble satt inn skal nå være uten de opprinnelig markerte mellomrommene.
=> Ignore whitespaces when inserting inline concept

src/containers/StructurePageBeta/resourceComponents/StructureResources.tsx, src/util/taxonomyHelpers.ts
Fixes https://github.com/NDLANO/Issues/issues/3205
Ikke testet ordentlig ennå, annet enn at den spytter ut samme output som nåværende løsning. Skal erstatte `groupSortResourceTypesFromNodeResources`.
=> Write new algorithm that accounts for orphaned resource types

src/containers/StructurePage/RootNode.tsx, src/containers/StructurePage/StructureContainer.tsx
Fixes https://github.com/NDLANO/Issues/issues/3249
Gikk gjennom en merkelig reise for å finne ut av dette. Feilen har egentlig ingenting å gjøre med react-query, men heller måten jeg har valgt å memoisere nodetrær på. I nåværende løsning vil en rotnode og dens barn kun rendres på nytt dersom den åpnes/lukkes, hvis dens favorittstatus endres eller hvis noden har ny data. Dette kolliderer med toggleFavorite-funksjonen, da nye versjoner av den vil ignoreres. Vi vil med andre ord brukt utdaterte versjoner av funksjonen inntil favoritt-statusen til den nåværende noden endres. Det blir feil. 
Her var det to mulig løsninger. Den første var å ta hensyn til toggleFavorites-funksjonen i memoiseringen. Dette ville dog rerendre hele nodetreet hver gang man la til en ny favoritt, og skapte merkbar …
=> Fix issue with toggling favorite subjects caused by root node memoization

src/components/SlateEditor/plugins/mathml/EditMath.jsx
Det viser seg at wiris vil ha 'no' for å vise matte-editor på norsk.
Test:
* Legg inn matte i en artikkel og sjekk at hjelpetekster i wiris er på norsk.
=> Use valid language code for wiris

src/containers/ImageUploader/components/ImageContent.tsx
Legger til et timestamp i bilde-editoren for å unngå å bruke cachet bilde etter oppdatering.
Kan testes ved å se at å erstatte en bildefil for et bilde ikke gjør at det gamle bildet henger igjen frem til refresh.
=> Avoid using cached image in image-editor

src/containers/StructurePage/resourceComponents/Resource.tsx
Regner med at dette har å gjøre med en oppdatering i taksonomi? I nye struktur er det ingenting annet som eksplisitt tar hensyn til topic-subtopic og subject-topic, så jeg regner med at alt skal være i orden etter dette.
=> Separate between node connections and resource connections by node-connection

src/components/SlateEditor/plugins/table/TableActions.tsx, src/util/articleContentConverter.tsx
Fikser to unique key feil i editoren.
Kan testes ved å sjekke at vi ikke får unique key errors i konsollen i editoren. Den ene oppstod kun om det fantes tabeller, mens den andre oppstod i alle (tror jeg) slate elementer.
=> Fix unique key errors in editor

src/components/HeaderWithLanguage/HeaderActions.tsx
Jeg kan ikke forklare hvorfor denne typeguarden lagde den warningen, men dette fikser det.
Jeg ser også at `createReturnTypeGuard` faktisk kaller på funksjonen vi typeguarder (som kanskje er eneste måte?), men det føles ut som en veldig dårlig ide, spesielt om funksjonen har sideeffekter sånn som denne har.
Jeg elsker ikke casts, men vet ikke helt hvordan vi kommer rundt det i typescript uten å gjøre noe annet skittent 😕
=> Fix unique key warning in lightboxpreview

src/constants.ts, src/containers/VisualElement/urlTransformers.ts, src/server/contentSecurityPolicy.ts
Gjør det mulig å embedde facebook og sketchfab. Legger også til nytt navn på tv2skole.
Test:
* Du kan legge inn facebook-videourler fra embedkode
* Du kan legge inn sketchfab urler fra embedkode
* Du kan legge inn sketchfab modell-urler, og disse blir oversatt til embed urler
Merk at du ikkje kan lagre før backend er oppdatert.
=> Add new embeds

src/components/HeaderWithLanguage/DeleteLanguageVersion.tsx, src/components/SlateEditor/EditorFooter.tsx, src/containers/EditMarkupPage/EditMarkupPage.tsx, src/containers/EditSubjectFrontpage/components/SubjectpageForm.tsx, src/containers/FormikForm/articleFormHooks.ts, src/containers/FormikForm/ndlaFilmFormHooks.ts, src/containers/Messages/MessagesProvider.tsx, src/phrases/phrases-en.ts, src/phrases/phrases-nb.ts, src/phrases/phrases-nn.ts, src/util/apiHelpers.ts
Fixes https://github.com/NDLANO/Issues/issues/3303
Legger til en ekstra feilmelding i `articleFormHooks` for 500 error.
Legger også til en fallback feilmelding så `applicationError` alltid vil gi en eller annen feilmelding. Enten en som den finner i exceptionen, eller en fallback generisk en om den ikke finner noen.
=> Improve error handling

src/components/HeaderWithLanguage/HeaderStatusInformation.tsx
Kan testes ved å se at "publisert" ikke lenger legger seg over tooltip dersom man holder over publisert-ikonet i et skjema for lenge.
=> Remove svg titles to avoid 'double tooltip' for svgs

src/containers/ArticlePage/articleTransformers.ts, src/containers/ConceptPage/conceptTransformers.ts, src/containers/ImageUploader/imageTransformers.ts, src/util/audioHelpers.ts
Gamle bilder kunne lagres uten å ha satt en lisenstype. Da returnerer backenden de som "unknown". Skjemaet tolker dette som at en verdi er satt, og velger automatisk den første lisensen når den ikke finner "unknown". Denne PR'en sørger for at unknown ikke settes som default-verdi.
=> Transform unknown licenses to undefined for initial form values to trigger proper form errors

src/containers/VisualElement/urlTransformers.ts
La til automatisk transformering til embed av Jeopardylabs url'er. 
Sikkert ikke den fineste måten, kan virke irriterende når brukerne prøver å slette deler av `?embed=1` så vil det trigge en rerender som appender en ny `?embed=1` på slutten. Vil ikke breake linken da siste query vil ta presedens.   En løsning kan være å skrive om til regex matching på deler av stringen men ser ikke helt behovet om det ikke blir veldig irriterende for brukerne.
=> Added url transformer for Jeopardylabs

src/containers/WelcomePage/hooks/savedSearchHook.ts
fixes https://github.com/NDLANO/Issues/issues/3431
Gjør dette kallet conditional på om subjects inneholder `,` eller ikke, om den har komma vil den ikke fungere og vil da være søket `Mine favoritter`.
=> Ignoring comma separeted lists in taxonomyquery for savedsearch

src/phrases/phrases-en.ts, src/phrases/phrases-nb.ts, src/phrases/phrases-nn.ts, src/util/formHelper.ts
fixes https://github.com/NDLANO/Issues/issues/3434
La til ny varsling i topic-article skjema om visuelt element ikke er bilde
=> Added test to check if visual element is image

src/containers/StructurePage/resourceComponents/Resource.tsx, src/modules/nodes/nodeQueries.ts
Fixes https://github.com/NDLANO/Issues/issues/3421
Dette tvinger frem noen hundre milisekunder med rød statustekst, men det er vanskelig å fikse opp i uten videre. Kan testes ved å legge til en ressurs på et emne, og se at metadata hentes automatisk.
=> Automatically fetch meta data and update resource list when adding a new resource

src/components/SlateEditor/VisualElementEditor.tsx
Er et tryktbar felt under visueltelement picker. Editor var satt til `readOnly=false` ved å bytte til true ble buggen borte og funksjonaliteten vedvarer. 
Måte å teste:
Gå inn på en emne artikkel og prøv å trykke under visueltelement picker, dette skal da ikke fungere.
=> Writeable field below visualelementpciker

src/components/DisplayEmbed/helpers/DisplayExternalModal.tsx, src/components/H5PElement/H5PElement.tsx, src/components/SlateEditor/plugins/blockPicker/SlateVisualElementPicker.tsx, src/containers/VisualElement/VisualElementModalWrapper.tsx, src/containers/VisualElement/VisualElementSearch.tsx
Fjerner også litt error-håndtering som fjernet litt styling og skjuler lukkeknapp, da man kan lukke ModalV2 både ved esc og ved å klikke utenfor modalen.
=> Rewrite h5p view to use modal v2

src/containers/StructurePage/resourceComponents/StructureResources.tsx
Fikser kanskje til og med https://github.com/NDLANO/Issues/issues/3407?
Kan testes ved å sammenligne https://ed.test.ndla.no/structure/urn:subject:b1c2d3e8-4f32-4a00-9291-d944602842b6/urn:topic:890be79b-0b35-4783-b891-723519a56abb/urn:topic:1f2172af-0d33-4be4-9550-1b24605e07fb på test og i PR-instansen.
=> Enable node resource meta query when no resources are available, but the child node has a contentUri

src/server/server.tsx
Meir korrekt å bruke permissions fordi disse settes fra rolla i auth0. Scope settes fra en rule som vi har laga sjølv, men den bør egentlig fases ut.
=> Bruker permissions og ikkje scope for tilgangssjekk

src/containers/NodeDiff/NodeDiff.tsx, src/modules/nodes/nodeQueries.ts
fixes https://github.com/NDLANO/Issues/issues/3476
Noen kommentarer:
1. Prøvde også en løsning der jeg brukte paginering i draft-api (page-size/page parametre), men dette ga fortsatt 431 i respons når id'er nådde en visst nivå, tror uansett det er lurt å begrense størrelsen på id'er som legges med spørringen, så landet derfor på nåværende løsning
2. Ser at lignende fetching av mange drafts gjøres i blant annet `fetchNodeResourceMetas` i nodeQueries, burde denne typen logikk innføres der og kanskje? eventuelt om logikken burde være implementert i fetchDrafts direkte? (Litt usikker på om det blir rotete, derfor jeg unngikk det i første omgang .. )
=> Limit ids fetched at once draft-api

src/containers/FormikForm/MetaImageSearch.tsx, src/containers/FormikForm/components/MetaImageField.tsx, src/containers/ImageUploader/components/ImageContent.tsx, src/containers/Podcast/components/PodcastForm.tsx, src/containers/Podcast/components/PodcastMetaData.tsx, src/containers/PodcastSeries/components/PodcastSeriesForm.tsx, src/containers/PodcastSeries/components/PodcastSeriesMetaData.tsx
Problemet her var at om eg satte width på henting av bilde, så blei valideringa feil fordi bildet som blei henta var mindre enn faktisk størrelse. Dette sjekker dimensjonene som er lagra og ikkje størrelsen på bildet som hentes.
Viser også litt mindre bilder i ed. Trenger ikkje vise full størrelse i skjema.
=> Bruker image-dimensions for å validere podkastbilde.

src/components/H5PElement/H5PElement.tsx, src/components/H5PElement/h5pApi.ts
Bruker nytt info-endepunkt for å hente tittel på h5p.
Test:
* Sett inn h5p i artikkel. Sjekk med html-editor i etterkant at du har fått data-title satt på ndlaembed. Det skal du få sjølv om h5p ikkje har satt lisens. Det ser du på h5p om den har ikon for gjenbruk nederst i iframe.
=> Bruker nytt info-endepunkt for å hente tittel

src/containers/NodeDiff/NodeDiffContainer.tsx, src/containers/PublishRequests/PublishRequestsContainer.tsx
Viser publiseringsforespørsler i alfabetisk rekkefølge. Litt overraska over at eg ikkje måtte putte resultatet av sort inn i en const.
Test: 
* Gå til side for publiseringsforespørsler, og sjekk at lista er sortert alfabetisk på brødsmulesti.
* Klikk på knapp for sammenligning, og sjekk at brødsmulesti også vises der.
=> Sorts requests by breadcrumbs

src/components/HeaderWithLanguage/HeaderStatusInformation.tsx, src/containers/StructurePage/resourceComponents/ApproachingRevisionDate.tsx, src/containers/StructurePage/resourceComponents/StatusIcons.tsx, src/phrases/phrases-en.ts, src/phrases/phrases-nb.ts, src/phrases/phrases-nn.ts
Liten refakturering der vi heller gjenbruker samme klokke-ikon som brukes inne på artikler sånn at de vil være samme farge, oppdaterer også fargen for 'warn' etter ønske fra NDLA.
kan f.eks testes her: /structure/urn:subject:da2379d0-3c91-4e4d-94d7-fc42f69593d2/urn:topic:3ce397d1-4939-474d-8242-15faaa0a06e6
=> Reuse approaching revision component at structure edit page

src/components/HeaderWithLanguage/HeaderStatusInformation.tsx, src/components/HeaderWithLanguage/LearningpathConnection.tsx, src/containers/EditSubjectFrontpage/components/SubjectpageAccordionPanels.tsx, src/containers/EditSubjectFrontpage/components/SubjectpageArticles.tsx, src/containers/EditSubjectFrontpage/components/SubjectpageForm.tsx, src/containers/NdlaFilm/components/DropdownSearch.tsx, src/containers/StructurePage/folderComponents/topicMenuOptions/PublishChildNodeResources.tsx, src/containers/StructurePage/resourceComponents/AddResourceModal.tsx
Dersom vi oppgraderer pakker vil CI feile på grunn av typefeil. Dette er fordi vi ender opp med types-learningpath som en dev-dep fra nåværende pakker, men det er fjernet i den nyeste versjonen.
=> Remove more old type references

src/components/SlateEditor/plugins/concept/__tests__/serializer-test.ts, src/components/SlateEditor/plugins/concept/block/BlockConcept.tsx, src/components/SlateEditor/plugins/concept/block/index.tsx, src/components/SlateEditor/plugins/concept/block/interfaces.ts, src/components/SlateEditor/plugins/concept/inline/InlineConcept.tsx, src/components/SlateEditor/plugins/concept/inline/index.tsx, src/components/SlateEditor/plugins/concept/inline/interfaces.ts, src/util/__tests__/__snapshots__/embedTagHelpers-test.js.snap, src/util/__tests__/embedTagHelpers-test.js, src/util/embedTagHelpers.tsx
Helper-funksjonene er dratt ut fra https://github.com/NDLANO/editorial-frontend/pull/176.
Jeg mener at dette er ett steg nærmere bedre typesikkerhet i ED, samt at vi får slått sammen typene i ED og i types-embed. Tar en plugin om gangen for å gjøre det enklere å verifisere at ting går som det skal. Har et par til lokalt som er klare hvis denne går inn.
Har blitt en del strengere på hva som kan sendes inn til helper-funksjonene. I fremtiden håper jeg at vi kun skal ta i mot strings, i og med at alle attributtene skal bli strings til slutt. Selv om React til slutt klarer å serialisere ting riktig mener jeg dette kan hjelpe oss med å skrive embed-typer som er enklere å serialisere.
=> Extract new serializers and deserializers. Convert concepts as a POC

src/components/SlateEditor/plugins/concept/block/BlockConcept.tsx, src/components/SlateEditor/plugins/concept/inline/InlineConcept.tsx
Fikser feilen jeg nettopp innførte i ED. Vi filtrerer nå ut alt av attributter som ikke er strenger, og da ble ikke conceptId med. Bruker nå ordentlige typer så vi er sikre på at vi sender inn riktig data.
=> Send concept embed data as strings. Use proper types for both block and inline concepts

src/containers/WelcomePage/components/Revisions.tsx, src/containers/WelcomePage/components/worklist/ConceptListTabContent.tsx, src/containers/WelcomePage/components/worklist/WorkList.tsx, src/containers/WelcomePage/components/worklist/WorkListTabContent.tsx
Kan testes ved å sjekke at status-sortering fungerer for artikler, forklaringer og revisjoner på dashboard
=> Add status as sortable field in worklist

src/containers/WelcomePage/components/LastUsedItems.tsx, src/containers/WelcomePage/components/TableComponent.tsx
Noen små styling-updates:
- Fixed høyde på boksene på dashboard
- Legger til pager til Sist redigert-boks for likt utseende
- Legger til bedre overflow-handling i tabell-titler (**NB**: Burde vi gjøre dette på en annen måte? Nå vil titler deles midt i ord ved overflow, Men det er kanskje fortsatt bedre enn å kutte deler av tittelen .. se bilder under for sammenligning)
=> Styling updates WelcomePage

src/components/SlateEditor/plugins/link/EditLink.tsx, src/components/SlateEditor/plugins/link/Link.tsx, src/components/SlateEditor/plugins/link/__tests__/normalizer-test.ts, src/components/SlateEditor/plugins/link/__tests__/serializer-test.ts, src/components/SlateEditor/plugins/link/index.tsx, src/util/__tests__/slateMockValues.js
Verdiene i `SlateMockValues` er litt... ish. I ED serialiserer vi barna til content-link til vanlig HTML, som deretter legges i `data-link-text` i GQL. Skal vi endre det, eller skal vi bare beholde det?
=> Content link to new embed type

src/containers/NodeDiff/__tests__/diffTestData.ts, src/containers/NodeDiff/diffUtils.ts, src/modules/nodes/nodeApiTypes.ts, src/modules/nodes/nodeMutations.ts
Uten denne vil diff-visninga vise at ting som er like egentlig er forskellig. 
Kan testes på http://localhost:3000/nodeDiff/urn:subject:e474cd73-5b8a-42cf-b0f1-b027e522057c?originalHash=2276&otherHash=default og sammenligne med https://ed.staging.ndla.no/nodeDiff/urn:subject:e474cd73-5b8a-42cf-b0f1-b027e522057c?originalHash=2276&otherHash=default
Merk at dette er staging.
=> Legger til minimal context-type i ed for å kunne unnta fra diff.

src/containers/VisualElement/VisualElementUrlPreview.tsx
Embeds via oembed-proxy skal være external.
=> If oembed-fetch is success, use external

src/components/SlateEditor/plugins/concept/inline/InlineConceptPreview.tsx, src/components/SlateEditor/plugins/conceptList/ConceptSearchResult.tsx, src/components/SlateEditor/plugins/embed/SlateVideo.tsx, src/config.ts, src/containers/VisualElement/VisualElementSearch.tsx, src/modules/video/brightcoveApi.ts
Fixes NDLANO/Issues#3516
Depends on https://github.com/NDLANO/deploy/pull/489
Bruker egen avspiller i slate.
Test:
* Legg til video i en artikkel og sjå at den viser tittel  ~og beskrivelse~ i ed, men ikkje i forhåndsvisning.
=> Use ed-player for editing.

src/containers/ArticlePage/components/InputComment.tsx
fixes [https://trello.com/c/RdlbTvEd/61-innhold-i-gul-lapp-nullstilles-n%C3%A5r-man-klikker-ut](https://trello.com/c/RdlbTvEd/61-innhold-i-gul-lapp-nullstilles-n%C3%A5r-man-klikker-ut)
Fikser bug der det man har startet å skrive i øverste inputboks for kommentarer ble nullstilt når man klikket ut for så å klikke inn igjen.
=> Fix input field comment being reset when click outside

src/containers/EditMarkupPage/EditMarkupPage.tsx
Fikser slik at monaco-editor tar opp den plassen den skal ha.
Test: Åpne html-editor og sammenlign med test og staging. Bredda skal være tilsvarende som staging.
=> Sets width for monaco editor

src/components/H5PElement/H5PElement.tsx, src/containers/H5PPage/H5PPage.tsx
Bruker flex for å la h5p-iframe ta opp resten av skjermen.
Test: Etter å ha logga inn, klikk på "Rediger H5P" i menyen og sjekk at edlib tar opp alt av skjermbilde under header.
=> Øker størrelsen på h5p-iframe.

.gitignore, cypress/e2e/Taxonomy/subject_spec.js, cypress/e2e/Taxonomy/topic_spec.js, src/containers/StructurePage/StructureContainer.tsx
Når vi legger inn støtte for programfag så vil disse ligge _over_ subjects. Så dagens struktur-verktøy må tilpasses då. Enn så lenge gir det meining at det er fag som redigeres her.
=> Only fetch subjects for structure-page

src/containers/WelcomePage/components/LastUsedItems.tsx, src/containers/WelcomePage/components/Revisions.tsx, src/containers/WelcomePage/components/worklist/ConceptListTabContent.tsx, src/containers/WelcomePage/components/worklist/WorkListTabContent.tsx, src/phrases/phrases-en.ts, src/phrases/phrases-nb.ts, src/phrases/phrases-nn.ts
Artikler og forklaringer har titler og ikkje navn. Endrer tabeller på forsida til å være meir i henhold til dette.
=> Use title in welcome-page tables for more consistency

src/containers/WelcomePage/WelcomePage.tsx, src/containers/WelcomePage/components/Revisions.tsx, src/containers/WelcomePage/styles.tsx, src/phrases/phrases-en.ts, src/phrases/phrases-nb.ts, src/phrases/phrases-nn.ts
fixes https://trello.com/c/Dn1pxrim/63-revisjonsblokka-kunne-filtrere-p%C3%A5-prim%C3%A6rkobling
Legger til toggle for å filtrere på kun artikler med primærkobling til favorittfag i revisjonsblokka
=> Add toggle for resources with primary connection in revision block

src/containers/SearchPage/components/form/SearchContentForm.tsx
fixes https://github.com/NDLANO/Issues/issues/3605
Fikser sånn at draft-status også nullstilles når man tømmer filtre på søkesiden
=> Bug fix: Draft status reset in SearchContentForm

src/containers/WelcomePage/components/Revisions.tsx
- Legger på alfabetisk sortering på fag i dropdown i revisjonsblokk (På samme måte som i arbeidsliste)
- Gjør også tittel-kolonne litt bredere
=> Sort subjects in dropdown in revisions alphabetically

src/containers/SearchPage/components/form/SearchConceptForm.tsx, src/containers/SearchPage/components/form/SearchContentForm.tsx, src/modules/auth0/auth0Api.ts, src/modules/auth0/auth0Queries.ts, src/modules/draft/draftQueries.ts, src/server/auth.ts, src/server/server.tsx
Depends on https://github.com/NDLANO/deploy/pull/521
Endrer til å bruke `app_metadata.isOrWasEdUser` for å søke authors i auth0.
Dette lar oss fortsette å oppdatere `permissions` objektet på samme måte i deploy, men vi kan fremdeles søke på folk som ikke lenger har tilganger.
=> Use `app_metadata.isOrWasEdUser` when searching for auth0 editors

src/components/ResourcePage.tsx, src/constants.ts, src/containers/ArticlePage/FrontpageArticlePage/FrontpageArticlePage.tsx, src/containers/ArticlePage/styles.ts
Remove unecessary css in maincontent. Added new size for default frontpage-articles.
Om ndla artikler skal ha størrelse `773px` når vi ikke er i `wide-view` som er på `1100px`.
=> Frontpage article sizing

src/components/SlateEditor/plugins/embed/SlateVideo.tsx, src/containers/WelcomePage/components/worklist/WorkListTabContent.tsx
Viser om en artikkel er om-ndla-artikkel og ikkje berre emne.
Fant også ut at knapp for redigering av video hadde feil tekst.
Test:
* Sett deg som ansvarlig på en om-ndla-artikkel og sjekk at den har artikkeltype på forsida
* Finn artikkel med brightcove og sjå at blyantknapp har title Rediger video.
=> Replace hardcoded value with article-type

src/components/SlateEditor/RichTextEditor.tsx
Fixes https://github.com/NDLANO/Issues/issues/3656
Editor skal nå bevare fokus der det var dersom du lagrer med MOD+s, men ikke når du klikker på lagreknappen. Dette sørger for at fokus ikke plasseres først i editoren når du lagrer med knapp. Slenger med en liten forklaring på hvorfor dette skjer:
`RichTextEditor` fokuserte alltid react-editoren, og satt deretter cursor basert på `lastSelection`, en custom-attributt som vi setter når man trykker på lagre-hotkeyen (MOD+s). Dersom `lastSelection` ikke er satt fokuserer man første elementet i slate-editoren, altså helt øverst i content-feltet. Det er ikke kjempelett å få Slate til å vite om at man har klikket på lagre-knappen, og derfor også ganske vanskelig å sette `lastSelection` basert på når man klikker på lagreknappen. Man kan eventuelt …
=> Only restore focus to slate when saving an article with save hotkey

src/components/HeaderWithLanguage/HeaderStatusInformation.tsx
Vi har begynt å vise lenke til artikkel med samme id i concept på grunn av omskriving av header.
=> show link to published concept in concept-form

src/components/SlateEditor/plugins/table/index.tsx
Merket at tall på tomme celler var veldig treigt plutselig legger til return i normaliseringen som vi gjør på andre celler normaliseringer.
=> Added return when normalizing alignment numbers

src/components/SlateEditor/plugins/contactBlock/ContactBlockForm.tsx, src/components/formikValidationSchema.ts, src/phrases/phrases-en.ts, src/phrases/phrases-nb.ts, src/phrases/phrases-nn.ts
https://trello.com/c/5HTPtGn2/414-kontaktperson-blokk-mangler-validering-av-epost-adresse
Kan sikkert krangle i all evighet om hvilken epost-regex man skal bruke. Jeg valgte denne.
Edit: Lars slo meg visst.
=> Add email validation for contact block

src/components/SlateEditor/PlainTextEditor.tsx, src/containers/AudioUploader/components/AudioManuscript.tsx
Fixes https://github.com/NDLANO/Issues/issues/3666, tror jeg? Stjålet stylingen fra frontend-packages. Har også fikset en feil der vi ikke sendte ID videre til Editable, som førte til at labelet ikke var knyttet opp mot selve inputet.
=> Make audio manuscript editor look more like ndla-frontend

src/components/SlateEditor/plugins/table/__tests__/normalizer-test.ts, src/components/SlateEditor/plugins/table/__tests__/serializer-test.ts, src/components/SlateEditor/plugins/table/defaultBlocks.ts, src/components/SlateEditor/plugins/table/index.tsx, src/components/SlateEditor/plugins/table/interfaces.ts, src/components/SlateEditor/plugins/table/matrixNormalizer.ts, src/components/SlateEditor/plugins/table/slateHelpers.ts
Removing isHeader from table as it now isn't necessary with the usage of th.
Kan sikkert være lurt å teste den litt, jeg klarte ikke å brekke den
=> Removing isHeader data from cells as it escapes into tests

src/components/SlateEditor/plugins/blockPicker/SlateBlockPicker.tsx, src/components/SlateEditor/plugins/blockPicker/actions.tsx, src/containers/ArticlePage/LearningResourcePage/components/LearningResourceContent.tsx
Ser vi har dobbelt opp med grid i blockpicker i OmNDLA artikkelene våre. Fjerner den i frontpage actions da vi allerede har den i common.  Kan testes ut ved å åpne blockpicker i de ulike editorene vi har.
=> Removes grid from frontpageActions since in commonActions

src/containers/Masthead/SavedSearchDropdown.tsx
Liten oppdatering av denne: https://github.com/NDLANO/editorial-frontend/pull/1907
Endrer sånn at vi ikke refetcher hver gang man åpner menyen, dette fører til færre nettverkskall og bedre brukeropplevelse da man slipper loading hver gang lagret søk åpnes. Venter fortsatt med å fetche lagret søk til man åpner menyen første gang.
=> Saved search optimalization: Do not refetch saved search data when menuOpen changes

src/containers/WelcomePage/components/worklist/ConceptListTabContent.tsx
Oppdaterer bredde på kolonner i arbeidsliste for forklaringer etter at innholdstype ble lagt til for å bedre tilpasse til mindre skjermer.
=> Fix worklist concept column widths

src/components/AlertModal/AlertModal.tsx, src/containers/Messages/__tests__/__snapshots__/Messages-test.tsx.snap
Fant litt rar styling i AlertModal, så her er noen oppdateringer:
- Tar i bruk farger fra colors
- Den hvite teksten på warning-modalen får veldig liten kontrast mot bakgrunnen, så oppdaterte denne til å være `text.primary`
- Fikser opp i at Heading og CloseButton på info-modalen ikke ble vist pga de hadde samme farge som bakgrunnen
Den hvite teksten på success-modalen har også litt liten kontrast, men jeg har ikke gjort noe med den ...
=> Fix styling bugs in AlertModal

src/components/SlateEditor/plugins/related/EditRelated.tsx, src/components/SlateEditor/plugins/related/__tests__/RelatedArticleBox-test.tsx
Emner som settes inn som relatert innhold blir uansett ikkje vist korrekt i artikkelen.
=> Remove search for topics

src/components/ResourcePage.tsx, src/containers/StructurePage/folderComponents/sharedMenuOptions/components/SearchDropdown.tsx, src/modules/article/articleGqlQueries.ts, src/modules/article/articleQueries.ts, src/modules/audio/audioQueries.ts, src/modules/auth0/auth0Queries.ts, src/modules/concept/conceptQueries.ts, src/modules/draft/draftMutations.ts, src/modules/draft/draftQueries.ts, src/modules/embed/queries.ts, src/modules/frontpage/filmMutations.ts, src/modules/frontpage/filmQueries.ts, src/modules/frontpage/frontpageMutations.ts, src/modules/frontpage/frontpageQueries.ts, src/modules/image/imageQueries.ts, src/modules/nodes/nodeMutations.ts, src/modules/nodes/nodeQueries.ts, src/modules/search/searchQueries.ts, src/modules/taxonomy/resourcetypes/resourceTypesQueries.ts, src/modules/taxonomy/taxonomyMutations.ts, src/modules/taxonomy/versions/versionMutations.ts, src/modules/taxonomy/versions/versionQueries.ts
Runde 2 med arbeid mot React Query 5. Den eneste tillate syntaxen for `useQuery` vil være objekt-syntax. Dette medfører at `UseQueryOptions` nå krever at man sender inn både `queryKey` og `queryFn`. Kommer rundt dette ved å sette de til partial.
=> Make internal hooks use object syntax

src/components/SlateEditor/PlainTextEditor.tsx
fixes https://github.com/NDLANO/Issues/issues/3705
Fikser opp i en styling-bug i placeholder i form i Safari
Se forskjell her:
=> Fix placeholder styling bug in Safari

src/containers/NdlaFilm/components/ThemeEditor.tsx, src/containers/NdlaFilm/components/ThemeNameModal.tsx, src/util/ndlaFilmHelpers.ts
Dette er vel den eneste film-relaterte komponenten som brukes fra `@ndla/editor`. Har ikke forbedret koden noe særlig, flytter den bare ut av frontend-packages.
=> Move ThemeEditorModal over from frontend-packages

src/components/SlateEditor/plugins/file/FileList.tsx, src/components/SlateEditor/plugins/file/FileListEditor.tsx, src/components/SlateEditor/plugins/file/FileNameInput.tsx
Dette er en blåkopi av det som ligger i frontend-packages. Den er ikke UU-vennlig, og jeg ser heller ikke for meg at dette er noe som kommer til å brukes i ndla-frontend. Den burde sikkert refaktoreres, men det kan vi ordne senere.
=> Move FileListEditor from frontend-packages to ED.

src/components/Dropdown/asyncDropdown/AsyncDropdown.tsx, src/containers/StructurePage/folderComponents/sharedMenuOptions/components/SearchDropdown.tsx
Attributtet heter `maxRender` i frontend-packages, så jeg har videreført det med samme navn (for consistency, selv om jeg var frista te å kalle det pageSize). DropdownMenu brukes også flere steder enn AsyncDropdown, bl.a. i søkefelteltene for noder (som brukes til bl.a. faglenker) så jeg har også lagt den til der i tilfelle det ønskes endra seinere.
=> Added maxRender with default value

src/components/Dropdown/asyncDropdown/AsyncDropdown.tsx, src/containers/FrontpageEditPage/FrontpageArticleSearch.tsx
DropdownMenu hadde et `menuHeight` attributt som kan brukes til å sette en max-height. Er sikkert mer elegante måter å gjøre det på, men etter litt testing så det ut til at 30 % av skjermhøyden gjør den ganske lik som i dag ved fullskjerm, men resizing vil dynamisk oppdatere nedtrekksmenyen slik at pagination blir synlig også på lavere skjermer (til den når et visst punkt, men da trur jeg man er langt utafor range hvor det er et problem)
=> Dynamic updates dropdown height based on screen height

src/components/SlateEditor/plugins/blogPost/BlogPostForm.tsx, src/components/SlateEditor/plugins/campaignBlock/CampaignBlockForm.tsx, src/components/SlateEditor/plugins/campaignBlock/SlateCampaignBlock.tsx, src/components/SlateEditor/plugins/keyFigure/KeyFigureForm.tsx, src/containers/ConceptPage/components/InlineImageSearch.tsx, src/containers/FormikForm/components/MetaImageField.tsx
Kom frem et ønske her: https://trello.com/c/KfJFfEgd/447-alt-tekst-p%C3%A5-bloggpost-og-kampanjeblokk om lik oppførsel som for alt tekst på metabilde!
Endringer i BlogPost, CampaignBlock og KeyFigure:
- Alt tekst fra bildet brukes som default
- Skjuler alt-tekst inputfelt/isDecorative så lenge metabilde ikke er valgt
=> Update alt text logic for BlogPost, CampaignBlock and KeyFigure

src/components/SlateEditor/plugins/concept/SearchConceptResults.tsx, src/phrases/phrases-en.ts, src/phrases/phrases-nb.ts, src/phrases/phrases-nn.ts
Når man går via toolbar og skal legge til glose eller forklaring, stod det Velg forklaring selv om resultatet var en glose. Har sattknappeteksten til å conditionally bruke forklaring- eller glosetekst.
Det var også en oversettelsestekst for remove, ikke bare choose. Jeg så ikke at den var i bruk p.t., men la til oversettelser også for remove under gloss.
=> Conditional concept / gloss button text

src/components/SlateEditor/plugins/span/LanguageButton.tsx, src/components/SlateEditor/plugins/span/LanguageSelector.tsx, src/components/SlateEditor/plugins/span/Span.tsx, src/components/SlateEditor/plugins/toolbar/SlateToolbar.tsx, src/components/SlateEditor/plugins/toolbar/handleMenuClicks.ts
Når jeg eksperimenterte, fant jeg også en feil som gjorde at teksten på språk-knappene ble wrappet vertikalt ved grid-visning; som også ble rettet. Det er ikke sikkert at den lenger er helt strengt tatt nødvendig når jeg gikk en annen vei med løsning, men det er allikevel en fin sikkerhet at den er der, så har latt den stå.
=> Place LanguageSelector in SlateToolbar

src/containers/NdlaFilm/components/NdlaFilmArticle.tsx
https://github.com/NDLANO/Issues/issues/3821
Liten tweak etter at https://github.com/NDLANO/editorial-frontend/pull/2130 ble merget inn. Dersom en artikkel allerede er satt, blir ikke initial search kjørt og feltet blir ikke automatisk åpnet.
=> Making article field dependant on value having been set or not

src/components/SlateEditor/plugins/h5p/SlateH5p.tsx, src/config.ts, src/util/resourceHelpers.ts
Inntil ndla har bestemt korleis dei skal håndtere dette, så vil dei skjule det.
Test:
Du har ikkje lenger mulighet til å redigere alt/meta for h5p.
I tillegg kan du velge kinesisk som språk i søk.
=> Disable h5p-meta for now

src/containers/Podcast/components/PodcastForm.tsx, src/containers/PodcastSeries/components/PodcastSeriesForm.tsx
Alt-tekst på metabilder for podkast skal være frivillig i og med at det er for det meste dekorativt. Endringa gjør at du kan legge til bilde på både podkast og serie uten å sette alt-tekst.
=> Alt tekst for serie og podkast skal være frivillig.

src/components/SlateEditor/plugins/link/utils.ts
Fixes NDLANO/Issues#3876
Dagens kode tar med for masse tekst.
Test: 
Sett inn lenke til https://test.ndla.no/subject:1:6951e039-c23e-483f-94bf-2194a1fb197d/topic:c12f7a1f-4a4d-4e39-b362-48fc931df908/topic:46b003a6-5182-4afa-b809-913645c7a707/resource:1:180650 eller https://stier.test.ndla.no/learningpaths/723/step/5344 og sjå at ting lagres korrekt med kun id i data-content-id.
=> Only uses id for learningpath

src/components/SlateEditor/plugins/link/EditLink.tsx, src/components/SlateEditor/plugins/link/Link.tsx
fixes https://github.com/NDLANO/Issues/issues/3883
Lukking av modal ville få react/slate til å kræsje. 
Løsningen var å flytte `Reacteditor.focus()` til et tidligere punkt i koden før man gjorde endringer på teksten. 
Tok også tak i litt opprydning for å få props destructa når vi tar de imot istedenfor overalt i koden!
=> Refactor link plugin code. Fix onClose problems

src/components/HeaderWithLanguage/HeaderActions.tsx, src/components/PreviewDraft/PreviewDraftLightboxV2.tsx, src/phrases/phrases-en.ts, src/phrases/phrases-nb.ts, src/phrases/phrases-nn.ts
https://trello.com/c/MsQWIPJR/651-sammenlign-med-publisert-tuning
Fikser:
- Fikser liten bug der sammenlign med publisert knappen på artikler ble vist når artikkelen ikke har en publisert versjon, men kun er lagret som ny versjon. 
- Oppdaterer tittel på publisert versjon
=> Only show compare with published if published version exists

src/components/FormField.tsx
Legger til tre komponenter som på sikt kan erstatte `FormikField`, og som vil tillatte oss større fleksibilitet i hvordan vi bygger skjemafelter. De er også ganske så mye mer UU-vennlige, selv om det ikke har vært et stort fokus i ED.
Dette er formålet med komponentene:
* __FormField__: En tynn wrapper rundt Formik sin `useField`. Tanken er at vi kan sikt ganske enkelt kan bytte den ut med `react-hook-form` sin `Controller`-komponent.
* __FormControl__: En tynn wrapper rundt `FormControl` fra frontend-packages. Den sørger for at vi slipper å lage ID'er for formfeltene våre selv. Denne eksisterer kun fordi vi ikke kan bruke `useId` i frontend-packages, da den krever react 18.
* __FormRemainingCharacters__: En wrapper rundt `FieldHelper` som viser hvor mange karakterer en har igjen i et …
=> Add wrapper components for using formik, FormControl and RemainingCharacters

src/containers/ArticlePage/components/Comment.tsx, src/containers/ArticlePage/components/CommentSection.tsx
Oppdaget litt buggy oppførsel på å toggle kommentarer mellom åpen/lukket, feks. når man oppretter kommentarer så var det ikke mulig å åpne/lukke.
Denne fikser opp i det og gjør koden litt ryddigere!
=> Fix and simplify logic for opening/closing comments

src/containers/ImageEditor/ImageAlignButton.tsx, src/containers/ImageEditor/ImageEditor.tsx, src/containers/ImageEditor/ImageEditorButton.tsx
Gjør det umulig (vanskelig) å venstrejustere bilder fra ed.
Test: sjekk at du ikkje lenger kan venstrejustere bilder i artikler. Allerede venstrejusterte bilder kan fremdeles finnes og redigeres.
=> Disable left align button

src/containers/ArticlePage/LearningResourcePage/components/LearningResourceForm.tsx, src/containers/ArticlePage/TopicArticlePage/components/TopicArticleForm.tsx
Legger til unntak til validering for å kunne slette/avpublisere uten taksonomi
Sjekk at du kan endre status på artikkel til enten sletta eller avpublisert på artikkel uten taksonomi.
=> Gjør det mulig å avpublisere uten taksonomi

.github/workflows/ci.yml, package.json, yarn.lock
Preventivt satt yarn te v4.1.0 for både bygg og packet manager for å unngå samme feil som oppstid i ed og frontend packages.
=> Yarn 4.1.0

src/containers/ArticlePage/components/Comment.tsx
fixes https://trello.com/c/1L260TBp/692-fikse-at-ikke-hele-kommetaren-ble-vist-etter-lukking
TextareaV3 fungerer ikke særlig bra med ekspanderbare input-felter, reverterer derfor til å bruke textareaV2 for kommentarer inntil vi finner en annen løsning på det i TextareaV3.
For å teste:
- Opprett ny kommentar, lukk kommentaren og lagre artikkelen
- Åpne kommentaren ved å bruke toggle-knapp eller å trykke direkte i input-felt, sjekk at man ser hele kommentaren
=> Bug fix: Revert usage of textareaV3 in comments

src/components/SlateEditor/plugins/aside/SlateRightAside.tsx
Fixes https://github.com/NDLANO/Issues/issues/3935
Burde kanskje ikke fjerna denne helt. Halv-høye verdier gjorde at det delvis overskrev forklaringer i teksten. Fjerne dem helt gjorde altså at knappene ikke lenger var klikkbare. Satt en minimal verdi nå, slik at de igjen kan trykkes på.
=> Fix right aside buttons

src/components/HeaderWithLanguage/HeaderLanguagePicker.tsx, src/components/Overlay.tsx, src/containers/Masthead/components/Navigation.tsx, src/containers/Masthead/components/SessionContainer.tsx, src/containers/StructurePage/folderComponents/SettingsMenu.tsx
Kan snart droppe focus-trap-react som dep. Dette sørger også for at overlay dekker hele skjermen.
=> Use our own dropdown menus instead of focus-trap-react for most dropdowns.

e2e/specs/toolbar.spec.ts, package.json, src/components/SlateEditor/ArticleLanguageProvider.tsx, src/components/SlateEditor/PlainTextEditor.tsx, src/components/SlateEditor/RichTextEditor.tsx, src/components/SlateEditor/VisualElementEditor.tsx, src/components/SlateEditor/plugins/audio/SlateAudio.tsx, src/components/SlateEditor/plugins/audio/render.tsx, src/components/SlateEditor/plugins/concept/block/BlockWrapper.tsx, src/components/SlateEditor/plugins/concept/block/render.tsx, src/components/SlateEditor/plugins/concept/inline/InlineWrapper.tsx, src/components/SlateEditor/plugins/concept/inline/render.tsx, src/components/SlateEditor/plugins/conceptList/ConceptList.tsx, src/components/SlateEditor/plugins/conceptList/render.tsx, src/components/SlateEditor/plugins/embed/SlateFigure.tsx, src/components/SlateEditor/plugins/embed/render.tsx, src/components/SlateEditor/plugins/h5p/SlateH5p.tsx, src/components/SlateEditor/plugins/h5p/render.tsx, src/components/SlateEditor/plugins/link/Link.tsx, src/components/SlateEditor/plugins/link/render.tsx, src/containers/ArticlePage/FrontpageArticlePage/components/FrontpageArticleFormContent.tsx, src/containers/ArticlePage/FrontpageArticlePage/components/frontpageRenderers.ts, src/containers/ArticlePage/LearningResourcePage/components/LearningResourceContent.tsx, src/containers/ArticlePage/LearningResourcePage/components/learningResourceRenderers.ts, src/containers/ArticlePage/TopicArticlePage/components/TopicArticleContent.tsx, src/containers/ArticlePage/TopicArticlePage/components/topicArticleRenderers.ts, src/containers/VisualElement/VisualElement.tsx, yarn.lock
This also fixes a bug when hot-reloading the editor during development
=> Pass article language into a context instead of passing it directly to plugins.

src/components/SlateEditor/plugins/link/Link.tsx
Fixes https://github.com/NDLANO/Issues/issues/3956
The editor.selection can be reset when Slate loses focus, causing both the popover and the modal to disappear.
=> Do not rely on editor.selection to display the link modal/popover.

src/containers/WelcomePage/components/Revisions.tsx
https://trello.com/c/NXbPeBnc/123-revisonsblokka-fjerne-de-oransje-klokkene
Oransje klokker skal ikke lenger vises i revisjons-blokk
=> Hide orange clock indicator from revision block

src/components/Accordion/FormAccordion.tsx, src/components/HeaderWithLanguage/HeaderActions.tsx, src/components/HeaderWithLanguage/HeaderWithLanguage.tsx, src/containers/ArticlePage/FrontpageArticlePage/EditFrontpageArticle.tsx, src/containers/ArticlePage/FrontpageArticlePage/components/FrontpageArticleForm.tsx, src/containers/ArticlePage/FrontpageArticlePage/components/FrontpageArticlePanels.tsx, src/containers/ArticlePage/LearningResourcePage/EditLearningResource.tsx, src/containers/ArticlePage/LearningResourcePage/components/LearningResourceForm.tsx, src/containers/ArticlePage/LearningResourcePage/components/LearningResourcePanels.tsx, src/containers/ArticlePage/TopicArticlePage/EditTopicArticle.tsx, src/containers/ArticlePage/TopicArticlePage/components/TopicArticleAccordionPanels.tsx, src/containers/ArticlePage/TopicArticlePage/components/TopicArticleForm.tsx, src/containers/ArticlePage/components/PanelTitle.tsx, src/containers/ArticlePage/components/PanelTitleWithChangeIndicator.tsx, src/containers/FormikForm/VersionAndNotesPanel.tsx, src/containers/FormikForm/articleFormHooks.ts, src/containers/FormikForm/formikDraftHooks.ts, src/modules/draft/draftQueries.ts, src/phrases/phrases-en.ts, src/phrases/phrases-nb.ts, src/phrases/phrases-nn.ts, src/queryKeys.ts
Fixes https://github.com/NDLANO/Issues/issues/3963
- Refaktorerer sånn at vi ikke gjør flere kall på `/draft-api/v1/drafts/123/history`
- Legger til indikatorer i accordion blocks om innholdet har endret seg
=> Indicate changes since last publication in accordion blocks

src/util/formHelper.ts
Fikser opp i preview visning av kommentarer i arbeidsliste:
=> Fix comment content stripping for tooltip in preview comment

src/components/SlateEditor/plugins/external/SlateExternal.tsx, src/constants.ts
Ref https://trello.com/c/FEmxc8Mq/724-godkjenne-brightcove-p%C3%A5-ressurs-fra-lenke-for-%C3%A5-fjerne-h5p-iframe
Gjør det mulig å sette inn https://players.brightcove.net/4806596774001/experience_618457388771de00248efb67/index.html via ressurs fra lenke. Dette er en spilleliste og trengs for å slutte å bruke h5p iframe-type.
=> Enable brightcove to support playlists

src/components/FormField.tsx, src/containers/FormikForm/TitleField.tsx, src/containers/ImageUploader/components/ImageForm.tsx
Fixes https://github.com/NDLANO/Issues/issues/3983
Det er et par andre felter der dette _kan_ være et problem:
* Origin?
* Contributors?
* Gloser?
=> Add language warnings to the title and image caption fields when creating a new language version of an article

src/containers/FormikForm/components/ContributorsField.tsx
Man vil ikke klare å "gå tilbake" til `Originator`, men verdien parses ordentlig.
=> Lowercase contributor type in select to account for uppercased db values

src/phrases/phrases-en.ts, src/phrases/phrases-nb.ts, src/phrases/phrases-nn.ts
Fixes https://trello.com/c/EI6si56P/778-ed-l%C3%A6ringssti-med-status-privat-viser-formstatusprivate
=> Add missing "PRIVATE" translation for private learningpaths

src/components/SlateEditor/plugins/link/Link.tsx
Fixes https://github.com/NDLANO/Issues/issues/3984
Makan til vanskelig fokus er å jobbe med. Det er en liten delay før cursor flytter seg når man lukker dialogen med ESC, men cursor plasserer seg riktig til slutt.
=> Do not automatically close Link popover when editor loses focus

src/components/SlateEditor/plugins/blockPicker/SlateBlockPicker.tsx, src/components/SlateEditor/plugins/blogPost/utils.ts, src/components/SlateEditor/plugins/campaignBlock/utils.ts, src/components/SlateEditor/plugins/contactBlock/utils.ts, src/components/SlateEditor/plugins/external/utils.ts
Disse 4 gir feilmelding dersom man bruker tastaturnavigasjon til å legge dem til (Ctr+Enter, tabtabtabtabtabtabtba, Enter):
- Ressurs fra lenke
- Bloggpost
- Kontaktblokk
- Kampanjeblokk
Denne fikser det.
=> Bugfix for keyboard navigation in blockpicker

src/util/formHelper.ts
Fixes https://github.com/NDLANO/Issues/issues/4001
Kan testes ved å bytte visuelt element på enten forklaring eller emneartikkel.
`inlineContentToHTML` har aldri klart å parse ´ndlaembed`. Vi har tidligere jobbet rundt dette ved å opprettholde en liste med slate-felter, men gikk vekk fra dette da det ikke fungerte bra nok med f.eks HTML-captions. Tipper det var da feilen oppsto. 
Eneste konsekvensen jeg kan se for meg at dette vil ha er at vi tar en liten hit i ytelse, men gjerne test det litt på forskjellige felter.
=> Always calculate slate form differences with blockContentToHTML

src/components/SlateEditor/plugins/toolbar/toolbarState.ts
Fixes https://trello.com/c/wuz2fBoI/807-deaktivere-headingvalg-i-tabell-p%C3%A5-ed
=> Disable text option in toolbar when in table

src/components/NynorskTranslateProvider.tsx, src/containers/Podcast/EditPodcast.tsx, src/containers/Podcast/components/PodcastForm.tsx
Handle translation cases where we pass a HTML string containing several HTML elements. The nynorsk translates automatically exits once a top-level element has been properly parsed. By passing in a body element, we guarantee that there's always a shared top level element that we can remove once the translation has passed
=> Fikse nynorsk oversettelse av podkaster

src/containers/ComparePage/ComparePage.tsx
fixes https://github.com/NDLANO/Issues/issues/4018
Viser språkmerking på side for å sammenligne språkversjoner.
Testes: [https://editorial-frontend-pr-2354.vercel.app/nb/compare/38620/nb](https://editorial-frontend-pr-2354.vercel.app/nb/compare/38620/nb)
**NB:** Denne løsningen er ikke heelt 100% uu-messig, siden nå vil også språket leses opp for skjermlesere. Jeg har sett på litt ulike måter å løse det på, blant annet å legge til tom alt tekst i content-feltet ved å bruke '/' ([w3](https://www.w3.org/TR/css-content-3/#alt)), men dette er dessverre ikke støttet i firefox og safari. Bare å komme med forslag til andre løsninger hvis noen har!
=> Indicate lang attribute in compare language page

src/components/SlateEditor/plugins/campaignBlock/CampaignBlockForm.tsx
Liten styling fiks, fikser opp i avstanden her i kampanjeblokkform:
=> Small styling fix campaign block form

package.json, yarn.lock
Fixes vulnurability: https://security.snyk.io/vuln/SNYK-JS-SERIALIZEJAVASCRIPT-6147607
=> Bump serialize-javascript to 6.0.2

package.json, src/containers/NdlaFilm/filmUtil.ts, src/containers/SearchPage/components/form/SearchForm.tsx, src/containers/WelcomePage/hooks/savedSearchHook.ts, src/modules/audio/audioApi.ts, src/modules/audio/audioQueries.ts, src/modules/concept/conceptApi.ts, src/modules/concept/conceptQueries.ts, src/modules/image/imageApi.ts, src/modules/image/imageQueries.ts, src/modules/search/searchApi.ts, src/modules/search/searchQueries.ts, yarn.lock
Depends on https://github.com/NDLANO/backend/pull/479 :heavy_check_mark: 
Ideelt sett så syns jeg hele søkesiden burde skrives om til å ikke være så veldig tett koblet sammen :sweat_smile: 
Dette gjør egentlig bare at alt fungerer som tidligere med at vi håndterer `sort` som en streng i frontenden selvom backend-typen sier at det er enums.
Gjør det ved å lage en generisk type som wrapper alle backend-typer som bytter ut hva-enn `sort` er med `sort?: string`.
Syns ikke det er det kuleste i verden, men det fungerer :shrug:
=> Work around sort being different types for different apis

src/containers/WelcomePage/components/GoToSearch.tsx, src/containers/WelcomePage/styles.tsx
Mellom ca 981 og ca 1249 pixler bredde, blir knappene på Revisjon seende slik ut:
Det er jo ikke så pent. Så nå wrapper en etter en knapp fra toppen istedet, fortsatt høyrejustert, slik at det heller blir seende slik ut:
=> Wrap header controls på welcome page

src/containers/ConceptPage/EditConcept.tsx
fixes https://github.com/NDLANO/Issues/issues/4053
Ser ut som vi ikke tok hensyn til at htmlContent er separat fra text. La til `content.htmlContent` som et field i concept som skulle bli translated, tok samtidig og forandret `content.content` typen til å kun være tekst.
=> Added htmlContent to be translated also

src/containers/Masthead/components/Navigation.tsx
fixes https://github.com/NDLANO/Issues/issues/4054
Dette ble en mer generell fiks som gjør at vi viser rød warning modal etter man har gjort endringer i artikkel og prøver å navigere vekk via logo.
=> Show content changed warning modal on logo navigation

src/components/SlateEditor/plugins/link/utils.ts
Om du klikka på lenke knappen når du markerte en lenke fikk du opp dialog for insetting av ny lenke. Tenker at det er mer logisk å fjerne lenken som andre editorer gjør.
=> Added return when unwrapping link

src/components/SlateEditor/RichTextEditor.tsx
Kjapp bugfix for å sikre at tab virker i tabeller igjen.
=> Allow tab in tables to not escape editor

src/components/SlateEditor/plugins/codeBlock/CodeBlockEditor.tsx
Fixes https://github.com/NDLANO/Issues/issues/4108
Var ikke helt samme fremgangsmåte som de andre to, sida denne ikke bruker RichTextEditor-komponenten. Men sida tab registreres som den skal i tekstfeltet, holder det å stanse propagering dersom Tab er trykket, inntil videre.
=> Stop propagation of tab keypress from codeblock editor

src/components/SlateEditor/plugins/comment/inline/SlateCommentInline.tsx
Ser ut som relatert til samme issue som dette: https://github.com/NDLANO/Issues/issues/4036
Dette ser ut til å fikse bugen BM meldte om: 
man ser feilen i for eksempel denne: https://ed.test.ndla.no/subject-matter/learning-resource/38686/edit/nb, hvis man i den prøver å trykke på kommentarer i de forskjellige tekstboksene så ser man at det plutselig scrolles til en annen kommentar uten at den åpnes.
Stjålet fiksen til @MaPoKen fra [her](https://github.com/NDLANO/editorial-frontend/pull/2382) og [her](https://github.com/NDLANO/frontend-packages/pull/2261), fremstår litt hacky, men ser ut til å fungere! Fint om flere verifiserer
=> Fix autoscroll issue for inline comments

src/components/SlateEditor/plugins/comment/CommentForm.tsx, src/containers/ArticlePage/FrontpageArticlePage/components/FrontpageArticleFormContent.tsx
Ble visst aldri vist i blockpicker for frontpage articles, denne fikser! setter også makshøyde på kommentar input-feltet
=> Show block comments in blockpicker for frontpage articles

src/components/SlateEditor/plugins/toolbar/toolbarState.ts
fixes https://github.com/NDLANO/Issues/issues/4179
Fikser at toolbar state håndteringen fungerer som den skal i henhold til toolbar reglene. Regler som: Ikke lov med inlines i definition term og description
=> Fetch single node at lowest if there is only 1 fragment

src/components/SlateEditor/plugins/image/ImageEmbedForm.tsx
Fjerning av bildetekst gir samme effekt som flagg. Flagget kan fjernes fra validation i etterkant.
=> Ignore handing of hide-caption

src/components/SlateEditor/plugins/concept/block/BlockWrapper.tsx, src/components/SlateEditor/plugins/concept/inline/InlineWrapper.tsx
Er en ganske stor jobb å kvitte seg med Modal og sånt her, så tar det senere. Dette er fint i første omgang.
=> refactor: reduce emotion usage in Slate concept

src/components/SlateEditor/plugins/grid/SlateGrid.tsx, src/components/SlateEditor/plugins/grid/SlateGridCell.tsx
Dette fikser også et overflow-problem som oppstår med nye accordions (tror jeg).
=> refactor: use primitives in SlateGrid

src/server/api.ts, src/server/contentSecurityPolicy.ts, src/server/server.ts
Oppdaterer ut csp-rapportering. Kunne sikkert delt kode mellom funksjonene.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-to
=> Support both report-uri and report-to in csp

src/components/SlateEditor/plugins/details/Details.tsx, src/components/SlateEditor/plugins/details/render.tsx
Chromium-based browsers do not allow for selection of more than one element when we use `details` and `summary` directly. This could either be intended, or it could be a bug with details/contenteditable. Either way, we render divs instead.
=> fix: ensure details content can be selection in chromium.

package.json, src/components/SlateEditor/plugins/related/RelatedArticleBox.tsx, src/components/SlateEditor/plugins/related/index.tsx, src/util/__tests__/__snapshots__/embedTagHelpers-test.ts.snap, src/util/__tests__/embedTagHelpers-test.ts, yarn.lock
Ref https://trello.com/c/OQEMgdd0/1062-relatert-innhold-feil-visning-i-ed
Bruker punycode siden dette kjører i klient.
=> Viser fram url-domain på ekstern relatert artikkel

src/server/server.ts
This fixes an issue with the `nynorsk-robot` that includes `charset` directive with its `content-type` header.
This patch also introduces a TODO with a `ts-ignore` since it seems that the `req.is()` function isn't defined in the typescript type definition.
=> Use `req.is()` to check content-type rather than a simple string compare

src/components/SlateEditor/plugins/blockPicker/actions.tsx
Fikser https://trello.com/c/7YQw2beV/1084-fjern-innsettingsvalg-for-forklaringsblokk
Kan tenkes går i beina på det @MaPoKen jobber med. Kan kanskje også være lurt å skrive litt om plugin, men siden gloss kan settes inn som blokk er eg usikker på kor masse.
=> Fjerner mulighet for å sette inn forklaring som blokk.

src/components/H5PElement/H5PElement.tsx
The `H5PElement` component assumes the `url` parameter in a `https://h5p.ndla.no/oembed?url=...` URL isn't URL-encoded. While currently true, this will change after the H5P API is reimplemented.
This PR solves the issue by using appropriate functions for reading query params, and is compatible with both new and old implementations of the H5P API.
=> handle encoded oembed_url

src/server/server.ts
Vet ikke om dette er beste måten å gjøre det på jeg, men det er vel bittelitt bedre enn en `@ts-ignore` i alle fall.
=> Cast request to express request to allow `is()`

src/containers/App/SearchPage.tsx, src/modules/search/searchQueries.ts, src/queryKeys.ts
Flytter ut logikken som håndterer custom filtrering av favoritt-/da-/lma-/sa-fag, så kan vi bruke en helt clean search-hook ellers!
=> Create a separate search hook which handles custom subject filtering

e2e/specs/status_change.spec.ts, package.json, src/components/SlateEditor/EditorFooter.tsx, src/containers/FormikForm/components/PrioritySelect.tsx, src/containers/FormikForm/components/ResponsibleSelect.tsx, src/containers/FormikForm/components/StatusSelect.tsx, yarn.lock
Skriver om alt bruk av ndla/select i EditorFooter til å bruke vår nye select. Resultatet av dette er at ansvarlig ikke lenger er like "søkbar". Det skal dog sies at man kan hoppe i listen ved å skrive som en vanligvis gjør.
=> refactor: remove remaining ndla/select usage

src/components/QualityEvaluation/AverageQualityEvaluation.tsx, src/components/QualityEvaluation/QualityEvaluation.tsx, src/components/QualityEvaluation/QualityEvaluationForm.tsx, src/components/QualityEvaluation/qualityEvaluationOptions.ts, src/containers/StructurePage/NodeItem.tsx, src/containers/StructurePage/resourceComponents/QualityEvaluationGrade.tsx, src/containers/StructurePage/resourceComponents/Resource.tsx, src/containers/StructurePage/resourceComponents/SubjectBanner.tsx, src/containers/StructurePage/resourceComponents/TopicResourceBanner.tsx
Mistenker at dette kommer til å være den kjipeste radio-knappen å kvitte seg med, så tenkte det var like greit å starte med den. Er vel Katrine som har rørt mest med dette, så setter hun som eneste reviewer.
=> refactor: redesign quality evaluation

src/components/SlateEditor/plugins/audio/SlateAudio.tsx, src/components/SlateEditor/plugins/embed/FigureButtons.tsx, src/components/SlateEditor/plugins/h5p/EditH5PModal.tsx, src/components/SlateEditor/plugins/h5p/SlateH5p.tsx, src/components/SlateEditor/plugins/video/SlateVideo.tsx
Add new components h5p. Fix bug where h5p isn't removed on onClose without selecting
=> Refactor h5p and remove h5p when no item selected

package.json, src/components/FormField.tsx, src/components/SlateEditor/PlainTextEditor.tsx, yarn.lock
Fjerner `useFormControl` fra `PlainTextEditor` inntil videre. Vi bruker ikke `FormControl` lenger, og ikke helt sikker på hvordan vi skal få integrert `Field` med `contenteditable`
=> chore: drop forms

src/components/SlateEditor/plugins/table/matrixNormalizer.ts
Fjerner normaliserings feilmeldinger i konsollet.
Fikser at title/caption ikke slutter å funke ved toggle rad headers
=> Adjust scope checks

src/components/SlateEditor/plugins/codeBlock/CodeBlock.tsx
Fjerner codeblock når alertdialog blir lukket
=> Use onOpenChange with extra argument to skip state check

src/components/SlateEditor/plugins/concept/inline/InlineWrapper.tsx
fixes https://github.com/NDLANO/Issues/issues/4208
Bruker metoder som var der fra før. Hvorfor problemet var kun når du markerte fra venstre gir ikke mening.
=> Use onclose method instead of onExitCOmplete logic

src/containers/SearchPage/components/form/GenericSearchForm.tsx
Kan gjøre styling-endringer når vi endrer søkesiden.
=> refactor: use primitives button in GenericSearchForm

src/components/Taxonomy/TaxonomyBlockNode.tsx
Ikke like pent, men funksjonelt. Tenker vi burde kvitte oss med knapp før vi skriver om alle struktur-komponenter :')
=> refactor: use primitives Button in TaxonomyBlockNode

src/containers/ArticlePage/LearningResourcePage/components/LearningResourceFootnotes.tsx
Halvhjerta. Dette brukes vel egentlig ikke lenger. Søk "footnote" for å finne artikler som bruker de.
=> refactor: use panda in footnotes

src/components/SlateEditor/plugins/toolbar/toolbarState.ts
fixes https://github.com/NDLANO/Issues/issues/4226
Trengte visst å oppdatere filtreringen her etter [denne](https://github.com/NDLANO/editorial-frontend/pull/2455) ble tatt inn
=> Toolbar: prevent inline insertion when multiple paragraph blocks are selected

src/components/SlateEditor/plugins/mark/index.tsx, src/components/SlateEditor/plugins/noop/index.tsx, src/components/SlateEditor/plugins/paragraph/index.tsx, src/components/SlateEditor/plugins/span/index.tsx, src/components/SlateEditor/plugins/table/index.tsx, src/util/articleContentConverter.tsx, src/util/compareHTMLHelpers.tsx
Mer linting-fikser. Vi burde nok egentlig endre typen for dette globalt, men mistenker at det kommer til å kreve endring av serialiseringslogikken vår.
=> refactor: ignore fragment warnings where they cannot be avoided. Return a JSX.Element where possible

src/components/Taxonomy/Breadcrumb.tsx
Feil oppstår om man prøver å opprette en emnetilknytning til et fag
=> Add support for subject as topic article connection

src/containers/StructurePage/resourceComponents/Resource.tsx, src/containers/StructurePage/resourceComponents/SubjectBanner.tsx, src/containers/StructurePage/resourceComponents/TopicResourceBanner.tsx
Gamle urler fører til redirect og dermed mistes queryparam.
Legger også til lenke til frontend på fag
=> Use pretty urls in structure links

src/containers/ArticlePage/LearningResourcePage/components/taxonomy/TaxonomyBlock.tsx
Feil brødsmulesti genereres når man legger til emnetilknytninger/emneplassering før man har lagret taksonomi, denne fikser!
=> Fix breadcrumb generation in taxonomy block

src/components/SlateEditor/plugins/toolbar/toolbarState.ts
Fikser opp i at inline kommentar var disablet for definisjonsliste i framed content
eksempel her: `/subject-matter/learning-resource/39023/edit/nb`
=> Allow inline comments in definition-list

src/components/SlateEditor/plugins/copyright/__tests__/serializer-test.ts, src/components/SlateEditor/plugins/copyright/index.ts
fixes https://github.com/NDLANO/Issues/issues/4250
Added copyright serialization tests. Add hotfix for escaping " quotes in stringified html
=> Fixes copyright serialization

src/components/SlateEditor/plugins/image/ImageEmbedForm.tsx, src/containers/VisualElement/VisualElementSearch.tsx
Første del av https://github.com/NDLANO/Issues/issues/4248
Nye bilder som settes inn i artikkel skal skjule byline som default.
=> Set hideByline if not copyrighted

src/components/SlateEditor/EditorFooter.tsx
https://trello.com/c/ULzcb6Dl/1176-spr%C3%A5kvelger-i-ed-footer-legger-seg-bak-knappene-prioritert-og-ansvarlig-i-artikkelvisning-p%C3%A5-dashboard-funker-det-fint
Denne fungerer med selects, comboboxer, venstre/høyre-plasserte bilder, tror ikke det skal brekke andre ting heller utifra det jeg har testet, men fint med dobbeltsjekk!
=> Fix editor footer z index to prevent content appearing behind

src/containers/ImageEditor/ImageEditor.tsx
Dersom du har satt align=right og så skrur det av ved å klikke på align=right, så settes undefined som verdi og dermed slettes feltet. Då feiler lagringa fordi valideringa forventer en data-align, sjølv om denne kan være tom.
=> Handle val=undefined if same align button is pressed

src/components/SlateEditor/plugins/mark/index.tsx, src/util/articleContentConverter.tsx
Fixes https://github.com/NDLANO/Issues/issues/4262
Sikkert lurt å teste dette ___uhyre___ nøye, men ser ut til å funke ganske så greit!
Vi kunne vurdert å bytte ut "escape-html" med "he" i samme slengen for å spare en liten kb på bundle, men da vil vi begynne å encode bokstaver som f.eks "æøå". Vet ikke hva dere tenker
=> fix: properly escape children

.github/workflows/release.yml, package.json, src/containers/FormikForm/GrepCodesField.tsx, yarn.lock
Viser maks 10 koder slik det er i dag.
=> Display all greps even if more than 10

src/phrases/phrases-en.ts, src/phrases/phrases-nb.ts, src/phrases/phrases-nn.ts
Fra Johannes:
> Ledeteksten i lenkeinnsetting bør endres. Riktig tekst blir “interne ressurser vises med lilla bakgrunn og eksterne lenker med blå” slik det er nå på test…
=> Update link description

src/containers/StructurePage/resourceComponents/StructureResources.tsx, src/modules/nodes/nodeApi.ts, src/modules/nodes/nodeApiTypes.ts, src/modules/nodes/nodeQueries.ts
isVisible defaulter til true, og dermed filtreres disse bort ved henting av noder. Men i struktur ønsker vi at alle kontekster skal vises og derfor må vi sende isVisible=false for å få til det.
Øverste fagstoff har to kontekster men en er usynlig så derfor vises ikkje advarsel om fleire kontekster: https://ed.test.ndla.no/structure/urn:subject:644e5655-75e5-49c3-9f5a-e2a98271bb3d/urn:topic:cc9689b4-94c3-40cd-8876-7f8111678b2e/urn:topic:2ad32cb8-c350-4680-bb03-a4c56c0c3f0c
På https://editorial-frontend-pr-2835.vercel.app/structure/urn:subject:644e5655-75e5-49c3-9f5a-e2a98271bb3d/urn:topic:cc9689b4-94c3-40cd-8876-7f8111678b2e/urn:topic:2ad32cb8-c350-4680-bb03-a4c56c0c3f0c så vises den med advarsel.
=> Send isVisible to not filter invisible contexts for resources

src/components/SlateEditor/plugins/campaignBlock/CampaignBlockForm.tsx, src/components/SlateEditor/plugins/campaignBlock/SlateCampaignBlock.tsx, src/components/SlateEditor/plugins/comment/block/SlateCommentBlock.tsx, src/components/SlateEditor/plugins/concept/ConceptModalContent.tsx, src/components/SlateEditor/plugins/concept/block/BlockWrapper.tsx, src/components/SlateEditor/plugins/concept/inline/InlineWrapper.tsx, src/components/SlateEditor/plugins/contactBlock/ContactBlockForm.tsx, src/components/SlateEditor/plugins/contactBlock/SlateContactBlock.tsx, src/components/SlateEditor/plugins/keyFigure/KeyFigureForm.tsx, src/components/SlateEditor/plugins/keyFigure/SlateKeyFigure.tsx, src/containers/ConceptPage/ConceptForm/ConceptForm.tsx, src/containers/ConceptPage/ConceptForm/ConceptFormFooter.tsx, src/containers/GlossPage/components/GlossForm.tsx
Ettersom onClose tidligere bare har blitt kjørt når man trykker på "Avbryt" så skjedde det ofte at slate-elementet faktisk ikke ble fjernet fra editor. Dette ser man ved å inspecte htmlen etter man har trykket på et av elementene i block picker også lukke dialogen ved å trykke utenfor. Denne fikser sånn at elementet alltid fjernes helt når dialogen lukkes!
=> Bug fix: Properly remove slate elements on exit

src/components/SlateEditor/plugins/blockPicker/SlateBlockPicker.tsx
Dette løser de tilfeldige buggene hvor om du lagrer så kræsjer editoren.
Ser ut som koden er redundant da den ble introdusert i [denne](https://github.com/NDLANO/editorial-frontend/pull/2301) og det fungerer selv etter koden er slettet. 
Linje 310 skulle være med i en annen PR men den gjør bare at du setter fokus inn i grid når du setter inn en gridblock som er mer logisk. Så den kan stå.
=> Remove redundant keyboard logic for blockpicker

src/components/SlateEditor/plugins/audio/SlateAudio.tsx, src/components/SlateEditor/plugins/campaignBlock/SlateCampaignBlock.tsx, src/components/SlateEditor/plugins/codeBlock/CodeBlock.tsx, src/components/SlateEditor/plugins/comment/CommentPopoverPortal.tsx, src/components/SlateEditor/plugins/comment/block/SlateCommentBlock.tsx, src/components/SlateEditor/plugins/concept/block/BlockWrapper.tsx, src/components/SlateEditor/plugins/contactBlock/SlateContactBlock.tsx, src/components/SlateEditor/plugins/external/SlateExternal.tsx, src/components/SlateEditor/plugins/file/SlateFileList.tsx, src/components/SlateEditor/plugins/grid/SlateGrid.tsx, src/components/SlateEditor/plugins/h5p/SlateH5p.tsx, src/components/SlateEditor/plugins/image/SlateImage.tsx, src/components/SlateEditor/plugins/keyFigure/SlateKeyFigure.tsx, src/components/SlateEditor/plugins/pitch/SlatePitch.tsx, src/components/SlateEditor/plugins/related/RelatedArticleBox.tsx, src/components/SlateEditor/plugins/uuDisclaimer/SlateDisclaimer.tsx, src/components/SlateEditor/plugins/video/SlateVideo.tsx
Liten improvment for å returnere fokus mer "riktig" i editoren. Nå setter jeg slik at blokkene returnerer fokus rett etter blokkene på insert og på remove så settes den til pathen der elementet skulle vært.
=> Standardises on remove logic to focus editor after editor transformation

src/components/SlateEditor/plugins/grid/SlateGridCell.tsx
fixes https://github.com/NDLANO/Issues/issues/4285
=> Grid: Adjust z-index to prevent overlapping block picker menu button

src/components/SlateEditor/plugins/aside/index.tsx, src/components/SlateEditor/plugins/audio/index.tsx, src/components/SlateEditor/plugins/campaignBlock/index.tsx, src/components/SlateEditor/plugins/codeBlock/index.tsx, src/components/SlateEditor/plugins/comment/block/index.tsx, src/components/SlateEditor/plugins/concept/block/index.tsx, src/components/SlateEditor/plugins/contactBlock/index.tsx, src/components/SlateEditor/plugins/copyright/index.ts, src/components/SlateEditor/plugins/definitionList/index.tsx, src/components/SlateEditor/plugins/details/index.tsx, src/components/SlateEditor/plugins/embed/index.tsx, src/components/SlateEditor/plugins/external/index.ts, src/components/SlateEditor/plugins/file/index.tsx, src/components/SlateEditor/plugins/framedContent/index.tsx, src/components/SlateEditor/plugins/grid/index.tsx, src/components/SlateEditor/plugins/h5p/index.tsx, src/components/SlateEditor/plugins/image/index.ts, src/components/SlateEditor/plugins/keyFigure/index.tsx, src/components/SlateEditor/plugins/linkBlockList/index.tsx, src/components/SlateEditor/plugins/pitch/index.tsx, src/components/SlateEditor/plugins/related/index.tsx, src/components/SlateEditor/plugins/span/index.tsx, src/components/SlateEditor/plugins/table/index.tsx, src/components/SlateEditor/plugins/uuDisclaimer/index.ts, src/components/SlateEditor/plugins/video/index.ts, src/components/SlateEditor/utils/defaultNormalizer.ts
Tilgi meg for alle filene, dette legger også til rette for at vi kan ta i bruk `defaultBlockNormalizer` med nye slate-plugins. 
Har egentlig ikke endret på logikken i `defaultBlockNormalizer`, jeg har bare forkortet koden litt. Når vi begynner å skrive våre gamle plugins om til `createPlugin` vil `defaultBlockNormalizer` logge mer og mer!
=> feat: add logging to defaultBlockNormalizer

package.json, src/modules/video/nrkApi.ts, src/server/auth.ts, src/util/apiHelpers.ts, yarn.lock
Vi kjører vel ny nok node-versjon til at vi ikke trenger cross-fetch lenger.
=> chore: drop cross-fetch

src/containers/FormikForm/components/ResponsibleSelect.tsx
fikser opp i:
>  En liten greie jeg så er at når man endrer status til publisert så må man refreshe siden for at ansvarlig-combobox skal oppdatere seg riktig
=> Responsible combobox: Fallback to empty list when responsible does not exist

src/components/SlateEditor/EditorFooter.tsx, src/constants.ts, src/containers/ArticlePage/FrontpageArticlePage/components/FrontpageArticleForm.tsx, src/containers/ArticlePage/FrontpageArticlePage/components/FrontpageArticleFormContent.tsx, src/containers/ArticlePage/LearningResourcePage/components/LearningResourceContent.tsx, src/containers/ArticlePage/LearningResourcePage/components/LearningResourceForm.tsx, src/containers/ArticlePage/TopicArticlePage/components/TopicArticleContent.tsx, src/containers/ArticlePage/TopicArticlePage/components/TopicArticleForm.tsx, src/containers/ArticlePage/articleTransformers.ts, src/containers/FormikForm/IngressField.tsx, src/containers/FormikForm/articleFormHooks.ts, src/util/useDebouncedCallback.ts
Dette er nok den største ytelsesforbedringen vi kan få i editoren. Debouncer `onChange`-kallet i 200ms, som tar en del arbeid av både valideringslogikken og formik. Ulempen med dette er at man i teorien kan lagre før verdien er flushet til formik. Vi kunne alternativt lagret et promise, og deretter ventet på at det resolvet før vi lagret? Hva tenker dere? Det er en ganske merkbar ytelsesforskjell på store artikler, f.eks http://localhost:3000/subject-matter/learning-resource/34220/edit/nb
=> perf: debounce RichTextEditor onChange call

src/components/HeaderWithLanguage/CloneImageDialog.tsx, src/components/HeaderWithLanguage/HeaderInformation.tsx, src/containers/ImageUploader/components/ImageContent.tsx, src/containers/ImageUploader/components/ImageUploadFormElement.tsx, src/modules/image/imageApi.ts, src/modules/image/imageMutations.ts, src/phrases/phrases-en.ts, src/phrases/phrases-nb.ts, src/phrases/phrases-nn.ts
Fixes https://github.com/NDLANO/Issues/issues/4290
Depends on https://github.com/NDLANO/backend/pull/619
Legger til en liten knapp i toppen av header for bilder på samme måte som for artikler.
Denne knappen åpner en ~~modal~~ dialog som lar deg laste opp et bilde med samme informasjon som bildet du står i.
=> feat: add copy image functionality

src/containers/VisualElement/__tests__/transformUrlIfNeeded-test.ts, src/containers/VisualElement/urlTransformers.ts
Test ved å sette inn https://www.gapminder.org/tools/#$model$markers$line$data$filter$dimensions$geo$/$or@$geo$/$in@=nga&=ind&=jpn&=nor;;;;;;;;&encoding$selected$data$filter$markers@=nga;;;;&y$data$concept=pop&space@=geo&=time;;&scale$type:null&domain:null&zoomed:null;;&frame$value=1827;;;;;&chart-type=linechart&url=v2 i ressurs fra lenke
=> Adds pasting gapminder url and get embeddable version

src/containers/SearchPage/components/form/SearchContentForm.tsx
fixes https://github.com/NDLANO/Issues/issues/4235
=> Correctly initialize hasPublished at page load

src/components/HeaderWithLanguage/DeleteLanguageVersion.tsx, src/components/HeaderWithLanguage/SimpleLanguageHeader.tsx, src/containers/NdlaFilm/components/NdlaFilmForm.tsx
Fixes the navigation after deleting a language from a subject page, when there are other supported languages. Also fixes the language picker for the NDLA film frontpage, such that only Bokmål, Nynorsk and English is available.
=> Fix delete language navigation and language picker

e2e/specs/math.spec.ts, e2e/specs/toolbar.spec.ts
Seks timer tok det å komme hit. Fikk forskjellige resultater på e2e, e2e:headless, e2e med prod-bygg og e2e:headless med prod-bygg. 
Virker som at playwright virkelig ikke liker at vi viser editoren med en gang slate har lastet inn.
=> fix: make e2e tests more resilient

src/components/SlateEditor/plugins/details/Details.tsx
Drastisk økning i ytelse i alle artikler som bruker details
=> perf: use static slate instance when transforming details

src/containers/Masthead/components/MastheadSearch.tsx
Fikser opp i to greier:
- Sørger for unike values i masthead search, så slipper vi feks:
- Filtrerer ikke søkeresultater basert på casing
=> Small fixes masthead search

package.json, src/__tests__/vitest.setup.ts, src/components/SlateEditor/interfaces.ts, src/components/SlateEditor/plugins/aside/__tests__/normalizer-test.ts, src/components/SlateEditor/plugins/codeBlock/__tests__/normalizer-test.ts, src/components/SlateEditor/plugins/definitionList/__tests__/normalizer-test.ts, src/components/SlateEditor/plugins/details/__tests__/normalizer-test.ts, src/components/SlateEditor/plugins/embed/__tests__/normalizer-test.ts, src/components/SlateEditor/plugins/file/__tests__/normalizer-test.ts, src/components/SlateEditor/plugins/framedContent/__tests__/normalizer-test.ts, src/components/SlateEditor/plugins/grid/__tests__/normalizer-test.ts, src/components/SlateEditor/plugins/heading/__tests__/normalizer-test.ts, src/components/SlateEditor/plugins/id/__tests__/id-operations-test.ts, src/components/SlateEditor/plugins/id/idPlugin.ts, src/components/SlateEditor/plugins/id/idTypes.ts, src/components/SlateEditor/plugins/link/__tests__/normalizer-test.ts, src/components/SlateEditor/plugins/list/__tests__/normalizer-test.ts, src/components/SlateEditor/plugins/mark/__tests__/normalizer-test.ts, src/components/SlateEditor/plugins/paragraph/__tests__/normalizer-test.ts, src/components/SlateEditor/plugins/related/__tests__/normalizer-test.ts, src/components/SlateEditor/plugins/section/__tests__/normalizer-test.ts, src/components/SlateEditor/plugins/span/__tests__/normalizer-test.ts, src/components/SlateEditor/plugins/table/__tests__/normalizer-test.ts, src/components/SlateEditor/utils/makeNodeId.ts, src/containers/ArticlePage/FrontpageArticlePage/components/frontpagePlugins.ts, src/containers/ArticlePage/LearningResourcePage/components/learningResourcePlugins.ts, src/containers/ArticlePage/TopicArticlePage/components/topicArticlePlugins.ts, yarn.lock
Denne gjør egentlig ingenting på egenhånd, så den er kanskje litt vanskelig å teste. Hovedmåten å teste på blir kanskje å se hvordan `editor.children` ser ut mens man gjør rare ting i editoren, men sliter litt med å brekke den. 
Brorparten av endringene har med testene våre å gjøre. Node-ID'er er generert dynamisk. Tanken var i utgangspunktet å mocke de, men det ble veldig fort veldig komplekst når man tok normalisering med i bildet. Vurderte også å modifisere`toEqual` til å ignorere ID'er når man sammenlignet to slate-noder, men såpass mye rekursjon kommer nok med en ytelsespris. CI trenger ikke å bli tregere :')
Endte opp med å asserte at ID eksisterer på alle noder, men sjekker aldri hvilken verdi det er. PDD sjekker vi bare at det er en string, og at den finnes på objektet. En fin …
=> feat: unique IDs for slate block nodes

src/containers/Masthead/components/MastheadSearch.tsx
Fikk beskjed om at innliming av urler i søkefeltet med "subject" i seg ikkje funka. Etter å ha testa med urlene 
* https://test.ndla.no/r/engelsk-1/subject-verb-agreement-concord/bb49e99178
* https://test.ndla.no/subject:1:aeaf8fcc-9ad2-4f23-a2cf-d764194f5380/topic:5:1c484b3e-7f3d-4a81-8c24-c8ffc95d421d/resource:720fdfee-9bd4-40ce-ac6a-b17b287efa2c
har eg justert sjekken litt slik at det fungerer bedre.
=> Handle url paste correct

src/components/SlateEditor/plugins/blockPicker/actions.tsx
https://trello.com/c/85u92rNg/1335-gj%C3%B8re-uu-advarsel-tilgjengelig-for-standardbruker
=> remove limitation on disclaimer

src/components/SlateEditor/plugins/comment/inline/SlateCommentInline.tsx
Fixes an issue where the `onOpenChange` handler would be called twice if the user has focused the popover (e.g. by clicking on it), and then interacted outside in order to close it.
=> Avoid double invocation of `onOpenChange` in comment popover

src/components/SlateEditor/plugins/audio/SlateAudio.tsx, src/components/SlateEditor/plugins/details/Details.tsx, src/components/SlateEditor/plugins/framedContent/SlateFramedContent.tsx
Fixes https://trello.com/c/fENK4KvC/1349-ed-h%C3%B8yrestilt-bilde-kommer-over-knappene-til-ekspanderende-boks
=> fix: ensure buttons are placed above floated image

src/components/SlateEditor/RichTextEditor.tsx, src/containers/FormikForm/TitleField.tsx
Synes dette er en ganske mye mer "lesbar" måte å håndtere dette tilfellet på. Hele greia er bare at man skal disable enter i tittel-feltet.
=> refactor: use a plugin to disable enter key in TitleField instead of extending editor

src/components/SlateEditor/helpers.ts, src/components/SlateEditor/plugins/blockPicker/SlateBlockPicker.tsx, src/components/SlateEditor/plugins/blockPicker/actions.tsx, src/components/SlateEditor/plugins/external/SlateExternal.tsx, src/components/SlateEditor/plugins/external/__tests__/serializer-test.ts, src/components/SlateEditor/plugins/external/index.ts, src/components/SlateEditor/plugins/external/queries.ts, src/components/SlateEditor/plugins/external/render.tsx, src/components/SlateEditor/plugins/external/types.ts, src/components/SlateEditor/plugins/external/utils.ts, src/components/SlateEditor/utils/normalizationHelpers.ts, src/containers/ArticlePage/FrontpageArticlePage/components/FrontpageArticleFormContent.tsx, src/containers/ArticlePage/FrontpageArticlePage/components/frontpagePlugins.ts, src/containers/ArticlePage/LearningResourcePage/components/LearningResourceContent.tsx, src/containers/ArticlePage/LearningResourcePage/components/learningResourcePlugins.ts, src/containers/VisualElement/VisualElement.tsx, src/util/articleContentConverter.tsx
Lagt `IFRAME_ELEMENT_TYPE` de fleste stedene vi kun hadde `EXTERNAL_ELEMENT_TYPE` før. De burde vel strengt tatt behandles ganske så likt?
=> refactor: split external plugin into externalPlugin and iframePlugin.

src/components/abstractions/Combobox.tsx, src/containers/StructurePage/plannedResource/AddExistingResource.tsx
Det er vanskelig å søke etter nye læringsstier, og om du forsøker å søke på sti-id så vil du kunne få både sti og artikkel med samme id i lista. Disse lar seg ikkje skille i dag og kun den første lar seg velge. 
Denne koden gjør det _litt_ enklere å finne læringsstier i dette søket.
Test: søk etter 3305 i felt for å legge til ny ressurs i struktur. Sjå at du kan skille mellom disse to:
=> Skill på søketrefftype ved ny ressurs i struktur

src/containers/ArticlePage/components/commentToolbarUtils.ts
Vi rendrer div, så vi burde inkludere pluginen også!
=> fix: add missing div plugin to commentToolbarUtils

src/containers/ArticlePage/LearningResourcePage/components/LearningResourcePanels.tsx, src/containers/ArticlePage/LearningResourcePage/components/LearningResourceTaxonomy.tsx, src/containers/ArticlePage/LearningResourcePage/components/taxonomy/TaxonomyBlock.tsx, src/containers/ArticlePage/TopicArticlePage/components/TopicArticleAccordionPanels.tsx, src/containers/ArticlePage/TopicArticlePage/components/TopicArticleForm.tsx, src/containers/ArticlePage/TopicArticlePage/components/TopicArticleTaxonomy.tsx, src/containers/ArticlePage/TopicArticlePage/components/TopicTaxonomyBlock.tsx
Bør deployes sammen med [denne](https://github.com/NDLANO/taxonomy-api/pull/285)
Fjerner notater som oppdateres pga endringer i struktur siden disse nå oppdateres direkte fra taxonomy-api.
=> fix: remove redundant taxonomy note update

src/config.ts, src/containers/VisualElement/urlTransformers.ts
La det bak et flagg for å kunne koordinere med deploy av migreringer.
=> Strip obsolete part of norgesfilm url

package.json, src/components/LastUpdatedLine/LastUpdatedLine.tsx, src/containers/ArticlePage/components/InputComment.tsx, src/containers/ArticlePage/components/RevisionNotes.tsx, src/containers/FormikForm/components/InlineDatePicker.tsx, src/containers/StructurePage/resourceComponents/ApproachingRevisionDate.tsx, src/containers/WelcomePage/components/Revisions.tsx, src/util/formatDate.ts, yarn.lock
ark bruker det, så tenker det er like greit at vi gjør det samme. Virker som et godt nok bibliotek.
=> refactor: replace date-fns with `@internationalized/date`

src/components/SlateEditor/plugins/paste/index.ts, src/components/SlateEditor/plugins/paste/types.ts, src/components/SlateEditor/plugins/uuDisclaimer/DisclaimerForm.tsx, src/containers/ArticlePage/FrontpageArticlePage/components/frontpagePlugins.ts, src/containers/ArticlePage/LearningResourcePage/components/LearningResourcePanels.tsx, src/containers/ArticlePage/LearningResourcePage/components/learningResourcePlugins.ts, src/containers/ArticlePage/TopicArticlePage/components/topicArticlePlugins.ts, src/containers/ArticlePage/components/commentToolbarUtils.ts, src/containers/AudioUploader/components/AudioManuscript.tsx, src/containers/FormikForm/IngressField.tsx, src/containers/FormikForm/InlineField.tsx, src/containers/FormikForm/TitleField.tsx
Første utkast av et paste-plugin. Inntil videre gjør denne bare en sjekk på om den nåværende editoren støtter alle elementer en prøver å lime inn. Dersom editoren ikke støtter alt vil den heller lime inn det hele som plaintext. 
Mangler:
- Lime inn flere blokker samtidig
- Sjekke hvorvidt et mark er støttet
=> feat: disallow invalid pastes

tsconfig.json
Dette fikser at vi får en million typefeil når man linker inn med frontend-packages
=> fix: properly resolve types when linking during dev

src/phrases/phrases-en.ts, src/phrases/phrases-nb.ts, src/phrases/phrases-nn.ts, src/util/__tests__/taxonomyHelpers-test.ts, src/util/__tests__/taxonomyMocks.ts, src/util/searchHelpers.ts, src/util/taxonomyHelpers.ts
Fikser slik at om du velger læringssti i nedtrekk så søkes det på type og ikkje ressurstype, tilsvarende som forklaring.
=> Handle learningpaths same as concepts to find paths without context

src/components/SlateEditor/plugins/span/index.tsx
Fikser språkmarkering inni inline forklaring/glose. Synes det ser veldig rart ut da, så spørs om vi egentlig ønsker dette?
=> Add concept-inline to allowed parents of span plugin

src/components/SlateEditor/EditorFooter.tsx
Fixes https://trello.com/c/kqkn1Xva/1453-feil-url-i-nynorsk-url-nederst-i-ed
=> fix: double basename in language button

e2e/specs/blockpicker_learning_resource.spec.ts, src/components/HeaderWithLanguage/CloneImageDialog.tsx, src/components/MetaImagePicker.tsx, src/components/SlateEditor/plugins/blockPicker/SlateVisualElementPicker.tsx
https://trello.com/c/79rWHmeJ/1471-modal-kan-lukkes-uten-lagring-advarsel-med-tapt-data-som-resultat-mulig-%C3%A5-unng%C3%A5
=> Prevents dialogclose for image-dialogs
