NDLANO/editorial-frontend

package.json
src/util/authHelpers.js
yarn.lock

Fix auth0 logout

---

src/util/authHelpers.js

Fixes problem with renewal of auth tokens. The problem was that the `renewAuth` function did not return the promise to the await, hence the await resolved way to early.

Fixes bug with renewal of auth

---

src/components/DisplayEmbedTag/DisplayExternal.jsx
src/components/H5PSearch/H5PSearch.jsx
src/components/SlateEditor/plugins/embed/SlateFigure.jsx
src/containers/VisualElement/VisualElementSearch.jsx
src/phrases/phrases-en.js
src/phrases/phrases-nb.js
src/phrases/phrases-nn.js

closes https://github.com/NDLANO/Issues/issues/1025

Improved H5P handling

---

src/containers/Masthead/components/SessionContainer.jsx
src/modules/session/__tests__/sessionReducer-test.js
src/modules/session/session.js
src/util/authHelpers.js

resolves https://github.com/NDLANO/Issues/issues/1068
Should resolve the problem with users getting stuck as logged in and not have the possibility to log out.

Adds fix for personal tokens logout problem #1068

---

src/components/SlateEditor/plugins/embed/EditRelated.jsx
src/components/SlateEditor/plugins/embed/RelatedArticleBox.jsx
src/containers/Masthead/MastheadContainer.jsx
src/modules/article/articleApi.js

Check list for bug fix pullrequest:

Fixes related article bug

---

package.json
src/client.jsx
src/components/DisplayEmbedTag/__tests__/__snapshots__/DisplayOembed-test.jsx.snap
src/containers/StructurePage/__tests__/__snapshots__/AddResourceModal-test.js.snap
src/containers/StructurePage/__tests__/__snapshots__/ConnectFilters-test.js.snap
src/containers/StructurePage/__tests__/__snapshots__/EditFilters-test.js.snap
src/containers/StructurePage/__tests__/__snapshots__/InlineAddButton-test.js.snap
src/containers/StructurePage/__tests__/__snapshots__/InlineEditField-test.js.snap
src/containers/StructurePage/__tests__/__snapshots__/ResourceItems-test.js.snap
src/containers/StructurePage/__tests__/__snapshots__/StructurePage-test.js.snap
yarn.lock

HMR now works without reloading page, but state is still not preserved

module.hot.accept()

---

src/components/SlateEditor/schema.jsx

resolves https://github.com/NDLANO/Issues/issues/1084

Readd data to defaultEmbedBlock

---

src/config.js

Needed to resolve H5P issue in environment `brukertest` and others

H5P default to prod env

---

src/phrases/phrases-nb.js
src/phrases/phrases-nn.js
src/style/link-menu.css

Partially resolves https://github.com/NDLANO/Issues/issues/1099
- Fixes link tooltip in asides
- Minor spelling fixes

Aside fix: Usable link tooltip in sidebar. Spelling fixes

---

package.json
src/containers/StructurePage/StructurePage.jsx
src/containers/StructurePage/StructureResources.jsx
src/containers/StructurePage/__tests__/ConnectFilters-test.js
src/containers/StructurePage/__tests__/__snapshots__/ConnectFilters-test.js.snap
src/containers/StructurePage/__tests__/__snapshots__/StructurePage-test.js.snap
src/containers/StructurePage/components/ConnectFilters.jsx
src/containers/StructurePage/components/EditLinkButton.jsx
src/containers/StructurePage/components/FilterView.jsx
src/containers/StructurePage/components/FolderItem.jsx
src/containers/StructurePage/components/InlineDropdown.jsx
src/containers/StructurePage/components/SubjectSettingsItems.jsx
src/containers/StructurePage/components/TopicSettingItems.jsx
src/modules/taxonomy/index.js
src/modules/taxonomy/subjects/index.js
src/modules/taxonomy/topics/index.js
src/phrases/phrases-en.js
src/phrases/phrases-nb.js
src/phrases/phrases-nn.js
src/style/overlay.css
src/style/taxonomy.css
src/util/jsPlumbHelpers.js
src/util/taxonomyHelpers.js
yarn.lock

Taxonomy editor filter topics

---

src/containers/AudioUploader/components/AudioForm.jsx
src/containers/ImageUploader/components/ImageForm.jsx
src/containers/LearningResourcePage/components/LearningResourceForm.jsx
src/containers/TopicArticlePage/components/TopicArticleForm.jsx
src/util/formHelper.js

Resolves https://github.com/NDLANO/Issues/issues/1162

Remove default session user as processor on new items

---

src/util/convertFromHTML.js

Removed method for wrapping nodes that have text and block children. We already check for that with "invalidTextWrapper", and the method outputs an invalid slate tree in some articles.

Remove unnecessary code

---

src/containers/App/App.jsx
src/containers/App/SubjectMatterPage.jsx
src/containers/Form/FormCopyright.jsx
src/containers/Form/FormWorkflow.jsx
src/containers/LearningResourcePage/components/LearningResourceContent.jsx
src/containers/LearningResourcePage/components/LearningResourceForm.jsx
src/containers/LearningResourcePage/components/LearningResourceMetadata.jsx
src/containers/LearningResourcePage/components/LearningResourceTaxonomy.jsx
src/containers/TopicArticlePage/components/TopicArticleContent.jsx
src/containers/TopicArticlePage/components/TopicArticleForm.jsx
src/containers/TopicArticlePage/components/TopicArticleMetadata.jsx

• Use Accordion PR: https://github.com/NDLANO/frontend-packages/pull/318
• Clean up components using old <Accordion> to be stateless if possible
NOTE: Uses ndla-accordion and ndla-core. Causes Travis error?

use Accordion from ndla-accordion

---

src/components/SlateEditor/plugins/embed/EditImage.jsx
src/components/SlateEditor/plugins/embed/EditVideo.jsx
src/components/SlateEditor/plugins/related/EditRelated.jsx
src/containers/SearchPage/components/results/SearchAudio.jsx

Check that images, video and related articles stay correctly in place in article when editing them

Fix css when editing image

---

src/util/__tests__/__snapshots__/slateHelpers-test.js.snap
src/util/slateHelpers.js

- Removes bug where `th` was replaced by `td`

Adds fix for th that dissapears on seralizing #1333

---

src/components/SlateEditor/plugins/related/RelatedArticleBox.jsx
src/util/__tests__/articleContentConverter-test.js
src/util/articleContentConverter.js
src/util/formHelper.js

Fixes bug with dirty in articles when loaded

---

src/components/SlateEditor/plugins/aside/SlateAside.jsx
src/components/SlateEditor/plugins/aside/SlateRightAside.jsx
src/phrases/phrases-en.js
src/phrases/phrases-nb.js
src/phrases/phrases-nn.js
src/style/content-block.css

Adds possiblity to move right aside content out in the editor #1358

---

src/components/PreviewDraft/PreviewDraftLightbox.jsx
src/components/PreviewDraft/PreviewLanguage.jsx
src/components/PreviewDraft/PreviewLightboxContent.jsx
src/components/PreviewDraft/PreviewProduction.jsx
src/containers/Form/components/FormQualityAssurance.jsx
src/containers/LearningResourcePage/components/LearningResourceForm.jsx
src/containers/TopicArticlePage/components/TopicArticleForm.jsx
src/phrases/phrases-en.js
src/phrases/phrases-nb.js
src/phrases/phrases-nn.js
src/style/preview-draft.css
src/util/articleUtil.js
src/util/formatDate.js

Adds support for preview on different languages #1354

---

src/containers/AgreementPage/components/AgreementFields.jsx
src/containers/Form/components/FormLicense.jsx

Resolves https://github.com/NDLANO/Issues/issues/1397
Test procedure:
- Check that `agreement/new` and edit works

fix: spelling error causing app to crash

---

cypress/integration/Editor/rich_block_text_editor_spec.js
src/components/SlateEditor/plugins/blockPicker/SlateBlockPicker.jsx
src/containers/AudioUploader/components/AudioForm.jsx
src/containers/Form/FormCopyright.jsx
src/containers/ImageUploader/components/ImageForm.jsx
src/containers/LearningResourcePage/components/LearningResourceForm.jsx
src/containers/TopicArticlePage/components/TopicArticleForm.jsx

Fixes some bugs where the lower accordion tabs couldn't be clicked, and some closed content suddenly showing up.

Dont render closed accordion content

---

src/containers/Masthead/components/MastheadSearchForm.jsx

Resolves https://github.com/NDLANO/Issues/issues/1456
Test Procedure for MastheadSearchForm # node redirect:

feat: node id forwarding to supported language

---

src/containers/LearningResourcePage/components/LearningResourceMetadata.jsx
src/containers/TopicArticlePage/components/TopicArticleMetadata.jsx

Added placeholder for metadescription

Added placeholder for metadescription

---

src/components/FileUploader/FileUploader.jsx
src/components/SlateEditor/plugins/file/EditFile.jsx
src/components/SlateEditor/plugins/file/Filelist.jsx
src/shapes.js

Removes alt text in files #1468

---

src/util/__tests__/embedTagHelpers-test.js
src/util/embedTagHelpers.js

Make it possible to edit videos.

Remove caption validation for video

---

src/server/contentSecurityPolicy.js

New embeds for naturfag. Links to NDLANO/issues#1508

Added new embeds

---

src/components/SlateEditor/plugins/SlateToolbar/ToolbarButton.jsx

Adds icon for alphabetical lists. 
@gunnarvelle Is this what you ment with the issue 1478?

Adds icon for alphebetical list

---

src/containers/StructurePage/__tests__/__snapshots__/ConnectFilters-test.js.snap
src/containers/StructurePage/folderComponents/ConnectFilters.jsx
src/containers/StructurePage/folderComponents/EditFilters.jsx
src/style/taxonomy-lightbox.css

- taxonomy lightbox overflow on small screens
- Delete warning confirm now works again

Taxonomy editor bug fixes

---

src/components/Contributors/Contributors.jsx
src/components/validateSchema.js
src/containers/ImageUploader/components/ImageForm.jsx

Removes requirement about creators

---

src/containers/TopicArticlePage/components/TopicArticleMetadata.jsx

Make metadata component equal to standardarticle.

Simplified metadata page

---

src/components/SlateEditor/plugins/bodybox/SlateBodyBox.jsx

Add missing classname

---

src/containers/Form/FormWorkflow.jsx
src/containers/TopicArticlePage/EditTopicArticle.jsx
src/containers/TopicArticlePage/components/TopicArticleForm.jsx

Connects to NDLANO/issues#1577

Fix publishing topic article

---

src/articleSchema.js
src/components/DeleteButton.jsx
src/components/DisplayEmbedTag/DisplayEmbedTag.jsx
src/components/DisplayEmbedTag/DisplayImageTag.jsx
src/containers/TopicArticlePage/components/TopicArticleForm.jsx
src/containers/TopicArticlePage/components/TopicArticleVisualElement.jsx

Fixes: 
- Issue 1570. Change visual element by deleting and selecting new
- Issue 1579. Show all validation errors when submitting topic article

Fix change topic article image

---

src/config.js
src/server/contentSecurityPolicy.js

Guttorm vil ha dette aktiv i staging.

Added GA to staging

---

src/articleSchema.js
src/containers/TopicArticlePage/components/TopicArticleForm.jsx
src/containers/TopicArticlePage/components/TopicArticleVisualElement.jsx

Fixes caption and alt text on visual element not saving

Use correct names

---

src/containers/LearningResourcePage/components/LearningResourceForm.jsx
src/modules/draft/draftSagas.js

1. Find and article in search.
2. Open the article.
3. Click back in the browser.
4. Open the article in a new tab (CTRL/CMD click).
5. Edit something in the article and save changes.
6. Open the article again from the tab with the search result.
7. Check that the changes made in  **step 4** is visible.

Always fetch draft from the server

---

package.json
src/components/SlateEditor/editorSchema.jsx
src/components/SlateEditor/plugins/detailsbox/index.js
src/components/SlateEditor/renderNode.js
src/containers/LearningResourcePage/components/LearningResourceContent.jsx
src/containers/TopicArticlePage/components/TopicArticleContent.jsx
yarn.lock

Fixes bug where plus sign don't show after exiting list.
- Includes this commit from list-plugin: https://github.com/NDLANO/slate-edit-list/commit/82b12cd156bf2a6445b70979cd9fba77f666d251
- Remove unused schema rules, and adds stricter rules for nodes in section (wrapping inline nodes in paragraph). 
- Put renderNode and renderMark in seperate file

Fix validation schema

---

src/components/ObjectSelector.jsx
src/containers/SearchPage/components/form/SearchContentForm.jsx

Only search when selecting a dropdownitem

fix: duplicate search on onBlur

---

cypress/integration/Editor/rich_block_text_editor_spec.js
package.json
src/components/Dropdown/asyncDropdown/AsyncDropdown.jsx
src/components/Dropdown/common/DropdownActionButton.jsx
src/components/Dropdown/common/DropdownInput.jsx
src/components/SlateEditor/plugins/related/EditRelated.jsx
src/components/SlateEditor/plugins/related/RelatedArticle.jsx
src/components/SlateEditor/plugins/related/RelatedArticleBox.jsx
src/components/SlateEditor/plugins/related/__tests__/RelatedArticleBox-test.js
src/components/SlateEditor/plugins/related/__tests__/__snapshots__/RelatedArticleBox-test.js.snap
src/components/SlateEditor/utils/relatedArticleMapping.js
src/containers/StructurePage/__tests__/__snapshots__/AddResourceModal-test.js.snap
src/containers/StructurePage/folderComponents/menuOptions/MenuItemDropdown.jsx
src/style/content-block.css
yarn.lock

- Fixes show more / less button
- fixes correct icons and colors
- Improve styling, use emotion
- Fix placeholder in search
- Add search icon button
- open new in edit mode

Improve related articles

---

run-editorial-frontend.sh

connects to NDLANO/Issues#1575

#1575: Stop fetching s3 secrets if in kubernetes environment

---

src/components/SlateEditor/plugins/aside/SlateFactAside.jsx
src/components/SlateEditor/plugins/aside/SlateRightAside.jsx
src/components/SlateEditor/plugins/bodybox/SlateBodyBox.jsx
src/components/SlateEditor/plugins/detailsbox/DetailsBox.jsx
src/components/SlateEditor/plugins/embed/SlateImage.jsx
src/containers/StructurePage/__tests__/__snapshots__/AddResourceModal-test.js.snap

- Fix bug where parent set to inline breaks styling
- FIx bug where buttons in slate didn't work

Factbox bugs

---

src/containers/Form/FormHeader.jsx
src/phrases/phrases-en.js
src/phrases/phrases-nb.js
src/phrases/phrases-nn.js

Connects to NDLANO/issues#1599

Added support for sami articles.

---

cypress/integration/Editor/toolbar_spec.js
src/components/SlateEditor/editorSchema.jsx
src/components/SlateEditor/plugins/SlateToolbar/ToolbarButton.jsx
src/components/SlateEditor/plugins/externalPlugins.js
src/components/SlateEditor/renderNode.js
src/util/__tests__/__snapshots__/slateHelpers-test.js.snap
src/util/__tests__/slateHelpers-test.js
src/util/slateHelpers.js

Removes two column list #1608

---

src/containers/Form/components/FormNotes.jsx

Sånn det er no så sendes System til auth0 og du får ingenting tilbake.

Do not send system to auth0, but show it in table

---

src/containers/Form/FormWorkflow.jsx
src/containers/LearningResourcePage/components/LearningResourceForm.jsx
src/phrases/phrases-en.js
src/phrases/phrases-nb.js
src/phrases/phrases-nn.js

Add button to save copy as a new article

Save as copy

---

cypress/integration/Editor/toolbar_spec.js
src/components/SlateEditor/plugins/link/EditLink.jsx
src/components/SlateEditor/plugins/link/Link.jsx
src/components/SlateEditor/plugins/link/LinkForm.jsx
src/phrases/phrases-en.js
src/phrases/phrases-nb.js
src/phrases/phrases-nn.js
src/shapes.js

Removes title from link

---

src/containers/Masthead/components/MastheadSearchForm.jsx
src/modules/taxonomy/taxonomyApi.js

Connects to NDLANO/Issues#1628

#1628: Make urls searchable

---

src/components/SlateEditor/plugins/blockPicker/SlateVisualElementPicker.jsx
src/components/SlateEditor/plugins/file/Filelist.jsx

Send url with path key
Trello: https://trello.com/c/pRMZZGAA/150-filer-feil-ved-visning-i-ed

fixed path for files (url)

---

src/containers/LearningResourcePage/EditLearningResource.jsx
src/containers/LearningResourcePage/components/LearningResourceForm.jsx
src/containers/TopicArticlePage/EditTopicArticle.jsx
src/modules/draft/__tests__/draftSelectors-test.js
src/modules/draft/draft.js

Adds fix for switching language in form

---

src/components/IconButton.jsx

Fix css color

---

src/components/SlateEditor/plugins/detailsbox/index.js
src/components/SlateEditor/plugins/embed/index.js
src/components/SlateEditor/plugins/file/index.js
src/components/SlateEditor/plugins/related/index.js
src/components/SlateEditor/plugins/table/schema.js
src/components/SlateEditor/utils/schemaHelpers.js

Wrap normalizing in withoutSaving

FIx save warning

---

src/components/reformed.js
src/containers/Form/FormMetaImageSearch.jsx
src/containers/LearningResourcePage/components/LearningResourceForm.jsx
src/containers/TopicArticlePage/components/TopicArticleForm.jsx

Adds fix for reset form

---

src/client.jsx

Fixes problem with changing language.

Adds fix for basename bug #1673

---

src/containers/LearningResourcePage/components/LearningResourceForm.jsx
src/util/__tests__/formHelper-test.js
src/util/articleContentConverter.js
src/util/formHelper.js
src/util/resolveJsonOrRejectWithError.js

Fixes bug with form dirty check of content arrays

---

package.json
yarn.lock

Updates `@ndla/editor` package to fix following things:

Updates ndla editor to fix filelist problems #1723

---

src/containers/FormikForm/FormikWorkflow.jsx
src/containers/FormikForm/components/FormikNotes.jsx

Delete language is now part of the header

Remove delete lang from workflow

---

src/components/SlateEditor/HeaderWithLanguage.jsx

• Fix header bug for Images and Audio.

Bug fix header

---

src/components/SaveButton.jsx
src/containers/LearningResourcePage/components/LearningResourceTaxonomy.jsx
src/modules/taxonomy/resources/index.js

Fixes bug where taxonomy fetched data based on article id undefined

fix prop names in taxonomy

---

src/util/slateHelpers.js

Fixes bug with undefined childnode mark

---

src/util/embedTagHelpers.js

Correct order of related embed data attributes

---

src/components/SlateEditor/plugins/SlateToolbar/SlateToolbar.jsx
src/components/SlateEditor/plugins/aside/SlateFactAside.jsx

Adds h2 and h3 to aside. Removes h1

---

src/containers/VisualElement/VisualElementUrlPreview.jsx
src/containers/VisualElement/__tests__/__snapshots__/transformUrlIfNeeded-test.js.snap
src/containers/VisualElement/__tests__/transformUrlIfNeeded-test.js
src/containers/VisualElement/visualElementApi.js
src/server/contentSecurityPolicy.js
src/util/htmlHelpers.js

Adds helper for nrk embeds which makes embedding from nrk urls work

---

src/containers/LearningResourcePage/components/LearningResourceTaxonomy.jsx
src/containers/LearningResourcePage/components/taxonomy/ResourceTypeSelect.jsx

removes learningpath as content type

---

jest.config.js
package.json
src/client.jsx
src/containers/AgreementPage/components/AgreementForm.jsx
src/containers/App/App.jsx
src/containers/AudioUploader/components/AudioForm.jsx
src/containers/FormikForm/components/FormikAbortButton.jsx
src/containers/FormikForm/index.js
src/containers/ImageUploader/components/ImageForm.jsx
src/containers/LearningResourcePage/components/LearningResourceForm.jsx
src/containers/TopicArticlePage/components/TopicArticleForm.jsx
yarn.lock

Fixes bug where first load on forms made the abort button not show the warning modal.

Fixes problem with form submission when first loaded on page

---

src/containers/StructurePage/resourceComponents/Resource.jsx
src/containers/StructurePage/resourceComponents/ResourceItemLink.jsx

Connects to NDLANO/Issues#1828

Fix links for learningpaths

---

.travis.yml

Unngå `JavaScript heap out of memory` issues på Travis.

Add node options to env

---

src/util/diffHTML.js
src/util/formHelper.js
src/util/slateHelpers.js

Fix articles that appear dirty when using soft line breaks inside marks

Allow wrapping of break tag

---

.babelrc
package.json
src/containers/TopicArticlePage/components/TopicArticleTaxonomy.jsx
yarn.lock

Fix bug where the wrong api method was changed somehow. Also cleans up handle submit function and adds optional chaining

fix add new topic to tax bug, add optional chaining!

---

src/components/HeaderWithLanguage/HeaderInformation.jsx
src/components/HeaderWithLanguage/HeaderWithLanguage.jsx
src/containers/ImageUploader/components/ImageContent.jsx
src/containers/LearningResourcePage/components/LearningResourceForm.jsx
src/containers/TopicArticlePage/components/TopicArticleForm.jsx

Viser tittel på innhold ved siden av typen. Gjør det litt enklere å ha oversikt om innholdsfana legges ned.

Add title to header.

---

src/components/SlateEditor/plugins/blockPicker/actions.js

Remove solutionbox from editor

---

src/containers/ConceptPage/components/ConceptForm.jsx
src/containers/ConceptPage/components/ConceptMetaData.jsx
src/phrases/phrases-en.js
src/phrases/phrases-nb.js
src/phrases/phrases-nn.js

Lagring av kilde funka ikkje. Men no gjør det det.

Fixes saving source.

---

src/components/SlateEditor/plugins/link/Link.jsx

Fix show link edit when pressed

ref after attributes

---

src/containers/SearchPage/components/form/SearchContentForm.jsx

Tar høgde for at ndla_id kan begynne med en -

Uses quotes for user search

---

src/components/HeaderWithLanguage/HeaderInformation.jsx
src/containers/FormikForm/formikDraftHooks.js
src/containers/LearningResourcePage/EditLearningResource.jsx
src/containers/TopicArticlePage/EditTopicArticle.jsx

- fixes bug where content don't show after copy article
- also fixes same bug when you paste an ndla.no url into search
- adds spinner when you click on copy article

Fix copy article images missing

---

src/containers/FormikForm/VersionAndNotesPanel.jsx

Fetch names for all notes

---

src/components/SaveButton.jsx
src/components/SlateEditor/EditorFooter.tsx
src/components/SlateEditor/RichBlockTextEditor.jsx
src/components/SlateEditor/plugins/embed/FigureInput.jsx
src/components/SlateEditor/plugins/embed/SlateImage.jsx
src/containers/LearningResourcePage/components/LearningResourceContent.jsx
src/containers/LearningResourcePage/components/LearningResourceForm.jsx
src/style/index.css

- Disable save button on formik errors
- Disable save image alt-text or caption if alt-text is empty
- Show outline around embeds without alt-text

Improve  validation

---

cypress/integration/Taxonomy/resource_spec.js
cypress/integration/Taxonomy/topic_spec.js
package.json
src/containers/StructurePage/StructureContainer.jsx
src/containers/StructurePage/__tests__/__snapshots__/StructurePage-test.js.snap
src/containers/StructurePage/folderComponents/FolderItem.jsx
src/containers/StructurePage/folderComponents/SettingsMenu.jsx
src/containers/StructurePage/resourceComponents/StructureResources.jsx
src/util/taxonomyHelpers.js
yarn.lock

Relates to https://github.com/NDLANO/frontend-packages/pull/541

Sort topics

---

src/components/SlateEditor/plugins/blockPicker/SlateBlockPicker.jsx
src/components/SlateEditor/plugins/blockPicker/SlateVisualElementPicker.jsx
src/components/SlateEditor/plugins/embed/EditAudio.jsx
src/components/SlateEditor/plugins/embed/FigureButtons.jsx
src/components/SlateEditor/plugins/embed/SlateAudio.jsx
src/components/SlateEditor/plugins/embed/SlateFigure.jsx
src/components/SlateEditor/plugins/embed/SlateImage.jsx
src/components/SlateEditor/plugins/embed/index.js
src/containers/AudioUploader/EditAudio.jsx
src/containers/FormikForm/FormikMetaImageSearch.jsx
src/containers/LearningResourcePage/components/LearningResourceContent.jsx
src/containers/StructurePage/__tests__/__snapshots__/StructurePage-test.js.snap
src/containers/VisualElement/VisualElementSearch.jsx
src/containers/VisualElement/visualElementApi.js
src/modules/image/imageApi.js

Benytter artikkelens språk for å sette inn bilder og lyder for å få metainformasjonen på det korrekte språket.

Use article language for fetching images and audio

---

src/components/SlateEditor/plugins/embed/EditAudio.jsx
src/components/SlateEditor/plugins/embed/SlateAudio.jsx

Make sure audiotype is saved. Depends on PR in validation.

Save audiotype

---

src/containers/LearningResourcePage/components/LearningResourceTaxonomy.jsx
src/containers/TopicArticlePage/components/TopicArticleTaxonomy.jsx
src/modules/taxonomy/resourcetypes/index.js
src/modules/taxonomy/topics/index.js
src/util/apiHelpers.js

- Adds resource-type dropdown in topic-article taxonomy
- Disables cache for all requests

#1921: Add taxonomy dropdown for resourcetype on topic-articles

---

src/components/Taxonomy/Breadcrumb.tsx

Legger til urler til strukturredigering.

Show urls to structure

---

package.json
src/containers/AgreementPage/components/AgreementForm.jsx
src/containers/AudioUploader/components/AudioForm.jsx
src/containers/ConceptPage/components/ConceptForm.jsx
src/containers/FormikForm/components/FormikLicense.jsx
src/containers/ImageUploader/components/ImageForm.jsx
src/containers/LearningResourcePage/components/LearningResourceForm.jsx
src/containers/TopicArticlePage/components/TopicArticleForm.jsx
src/phrases/phrases-en.js
src/phrases/phrases-nb.js
src/phrases/phrases-nn.js
yarn.lock

Ref https://trello.com/c/zxCm2s0Z/299-bilder-skal-ikke-ha-default-lisens

Force choose license.

---

src/components/SlateEditor/plugins/file/Filelist.jsx
src/containers/FormikForm/articleFormHooks.js
src/containers/LearningResourcePage/components/LearningResourceForm.jsx
src/modules/draft/draftApi.js
src/phrases/phrases-en.js
src/phrases/phrases-nb.js
src/phrases/phrases-nn.js

Depends on https://github.com/NDLANO/frontend-packages/pull/563

#1948: Delete remote files on remove from article

---

src/components/SlateEditor/plugins/SlateToolbar/SlateToolbar.jsx
src/containers/TopicArticlePage/components/TopicArticleContent.jsx

Stops plugins to be initialized on every render.

Fix slate problem in topic editor

---

src/containers/SearchPage/SearchContainer.jsx
src/containers/SearchPage/components/form/SearchConceptForm.jsx
src/containers/SearchPage/components/form/SearchContentForm.jsx
src/containers/SearchPage/components/results/SearchConcept.jsx
src/containers/SearchPage/components/results/SearchList.jsx
src/containers/SearchPage/components/results/SearchResult.jsx

Uses subjects as parameters for concept search.

Search for subjects

---

src/components/HeaderWithLanguage/HeaderInformation.jsx
src/components/HeaderWithLanguage/HeaderStatusInformation.jsx
src/components/HeaderWithLanguage/HeaderWithLanguage.jsx
src/phrases/phrases-en.js
src/phrases/phrases-nb.js
src/phrases/phrases-nn.js

Add check icon for published articles.

Add icon for published

---

src/components/SlateEditor/plugins/concept/ConceptModal.jsx

Uten subjects feiler innsettinga.

Fix concept add

---

src/components/SlateEditor/plugins/link/EditLink.jsx
src/components/SlateEditor/plugins/link/__tests__/EditLink-test.js

Lenker til fag må behandles som reine lenker.

Make possible to link to subject

---

src/containers/FormikForm/FormikMetaTagSearch.tsx
src/containers/FormikForm/FormikMetadata.jsx
src/modules/draft/draftApi.js

Vet ikke helt hvordan vi ønsker å ha strukturen på typescript filer, skal vi ha interfaces inn i .tsx filer som jeg gjorde eller skal vi ha de definert i egne filer i en eller annen folder?

added async tag-search in draft-articles, and introducing typescript

---

src/components/Dropdown/MultiSelectDropdown.jsx
src/containers/ConceptPage/components/ConceptMetaData.jsx

Kan forenkles hvis det alltid skal søkes på første bokstav.

Subject searches on first letter in concept metadata

---

src/components/Dropdown/MultiSelectDropdown.jsx

NDLA ønsker at søk skal starte med det som skrives inn.

Only show hits starting with

---

src/modules/grep/grepApi.tsx
src/phrases/phrases-en.js
src/phrases/phrases-nb.js
src/phrases/phrases-nn.js
src/util/__tests__/articleUtil-test.js
src/util/articleUtil.js

[#2016](https://github.com/NDLANO/Issues/issues/2016)

added TT to competences

---

cypress/integration/Editor/toolbar_spec.js
src/components/SlateEditor/plugins/SlateToolbar/SlateToolbar.jsx

https://trello.com/c/3KP7sq45/366-fjerne-mulighet-for-understreking-i-br%C3%B8dtekst

Remove underline from editor

---

src/components/SlateEditor/plugins/blockPicker/SlateBlockPicker.jsx
src/components/SlateEditor/plugins/blockPicker/actions.js
src/components/SlateEditor/plugins/blockPicker/index.js
src/containers/LearningResourcePage/components/LearningResourceContent.jsx

Remove section from menu.

---

src/containers/ConceptPage/components/ConceptForm.jsx
src/containers/ConceptPage/components/ConceptMetaData.jsx
src/containers/FormikForm/FormikMetaImageSearch.jsx
src/containers/FormikForm/FormikMetadata.jsx
src/containers/FormikForm/components/FormikMetaImage.jsx
src/containers/LearningResourcePage/components/LearningResourceForm.jsx
src/containers/TopicArticlePage/components/TopicArticleForm.jsx
src/phrases/phrases-en.js
src/phrases/phrases-nb.js
src/phrases/phrases-nn.js
src/util/articleUtil.js

https://github.com/NDLANO/Issues/issues/2011

added remove button for metaImage

---

cypress/integration/Taxonomy/topic_spec.js
src/components/RoundIcon.jsx
src/containers/StructurePage/StructureContainer.jsx
src/containers/StructurePage/folderComponents/SettingsMenuDropdownType.jsx
src/containers/StructurePage/folderComponents/menuOptions/CopyResources.tsx
src/containers/StructurePage/folderComponents/menuOptions/MenuItemDropdown.jsx
src/containers/StructurePage/folderComponents/menuOptions/PublishTopic.tsx
src/containers/StructurePage/resourceComponents/StructureResources.jsx
src/interfaces.ts
src/phrases/phrases-en.js
src/phrases/phrases-nb.js
src/phrases/phrases-nn.js
src/util/retriveBreadCrumbs.ts

Jeg vet ikke hva som gir mest mening på rekkefølgen i dropdown-menyen, men lå denne til nederst.

2028 copy resources

---

src/util/formHelper.js

https://github.com/NDLANO/Issues/issues/2044

quickfix for wrong error message

---

src/containers/FormikForm/FormikGrepCodes.tsx
src/containers/FormikForm/FormikGrepCodesContent.tsx
src/containers/LearningResourcePage/components/LearningResourceForm.jsx
src/containers/LearningResourcePage/components/LearningResourcePanels.jsx
src/containers/TopicArticlePage/components/TopicArticleAccordionPanels.jsx
src/containers/TopicArticlePage/components/TopicArticleForm.jsx
src/interfaces.ts
src/modules/draft/draftApi.js
src/modules/grep/grepApi.tsx
src/phrases/phrases-en.js
src/phrases/phrases-nb.js
src/phrases/phrases-nn.js
src/util/__tests__/articleUtil-test.js
src/util/articleUtil.js
src/util/formHelper.js

https://github.com/NDLANO/Issues/issues/2039

renamed competences to grepCodes

---

src/components/PreviewDraft/PreviewDraft.tsx

[Issue #2043](https://github.com/NDLANO/Issues/issues/2043)

renderMarkdown in PreviewDraft

---

src/containers/StructurePage/resourceComponents/Resource.jsx
src/containers/StructurePage/resourceComponents/StructureResources.jsx

Use same rules for published icon as article

---

src/modules/translate/translateApi.js
src/server/contentSecurityPolicy.js

Fixes NDLANO/Issues#2079
Bruker ny adresse på oversettelsesrobot.

Use official translate address

---

src/containers/StructurePage/folderComponents/menuOptions/CopyResources.tsx
src/containers/StructurePage/resourceComponents/Resource.jsx
src/containers/StructurePage/resourceComponents/ResourceItems.jsx
src/interfaces.ts
src/modules/taxonomy/index.js
src/modules/taxonomy/resources/index.js

2046 topic filter on copied resources

---

src/phrases/phrases-en.js
src/phrases/phrases-nb.js
src/phrases/phrases-nn.js

Etter tilbakemelding fra Knut Inge.

change some labels

---

src/containers/SearchPage/components/form/SearchConceptForm.jsx
src/modules/search/searchApi.js
src/style/search.css
src/util/constants/ConceptStatus.js

Fixes NDLANO/Issues#2085
Filteringen vil ikke fungere før https://github.com/NDLANO/concept-api/pull/46 er deployet
Er ikke helt sikker på hva som er penest/best mtp design, men det er kanskje ikke så farlig ¯\_(ツ)_/¯

#2085: Concept status filtering in search

---

src/components/SlateEditor/plugins/table/schema.js
src/style/content-block.css
src/style/table.css

fixing row/colspan, font style, and th uppercase

---

src/components/SlateEditor/plugins/related/EditRelated.jsx

Ved innsetting av relaterte artikler.

Returning search result makes number of hits in dropdown correct.

---

src/components/SlateEditor/plugins/pasteHandler/index.js
src/components/SlateEditor/plugins/table/schema.js
src/containers/LearningResourcePage/components/LearningResourceContent.jsx
src/util/embedTagHelpers.js
src/util/slateHelpers.js

2090 pasting text in ed uses break tags should be paragraph

---

src/containers/Login/LoginFailure.js
src/containers/Login/LoginSuccess.js
src/modules/session/__tests__/__snapshots__/sessionReducer-test.js.snap
src/modules/session/session.js
src/modules/session/sessionSagas.js
src/phrases/phrases-en.js
src/phrases/phrases-nb.js
src/phrases/phrases-nn.js
src/util/authHelpers.js

https://github.com/NDLANO/Issues/issues/2070

prevent unauthorized user from logging into ed

---

src/components/SlateEditor/plugins/mathml/EditMath.js
src/server/Html.jsx

Update mathjx and fix math editor

---

src/components/DisplayEmbed/__tests__/__snapshots__/DisplayExternal-test.js.snap
src/components/SlateEditor/plugins/embed/FigureButtons.jsx

Add type button to external

---

src/modules/session/__tests__/sessionSagas-test.js
src/modules/session/sessionSagas.js
src/server/server.js
src/util/authHelpers.js

Bruk gjerne litt tid på testing for jeg er ikke 1000% sikker på hvorfor vi trengte dette i utgangspunktet, men det ser ut til å fungere for meg ¯\_(ツ)_/¯

Remove get_token endpoint and m2m token fetcing

---

src/components/HeaderWithLanguage/HeaderActions.jsx
src/components/HeaderWithLanguage/HeaderWithLanguage.jsx
src/components/HeaderWithLanguage/TranslateNbToNn.jsx
src/containers/FormikForm/FormikAlertModalWrapper.jsx
src/containers/LearningResourcePage/EditLearningResource.jsx
src/containers/LearningResourcePage/components/LearningResourceForm.jsx
src/containers/TopicArticlePage/EditTopicArticle.jsx
src/containers/TopicArticlePage/components/TopicArticleForm.jsx

2135 prevent nn overwrite

---

src/components/FileUploader/FileUploader.jsx

NDLANO/Issues#2112
Tvinger opplaster til å godkjenne nye filtyper.

Added new filetypes to fileuploader

---

src/components/DisplayEmbed/DisplayExternalVisualElement.jsx
src/components/SlateEditor/plugins/embed/SlateVideo.jsx
src/containers/TopicArticlePage/components/TopicArticleVisualElement.jsx
src/containers/VisualElement/DisplayVisualElement.jsx

Define visual element language

---

cypress/integration/Film/film_spec.js
src/containers/NdlaFilm/components/MovieListItem.jsx

Add film link

---

cypress/support/index.js
src/containers/FormikForm/preventWindowUnloadHook.js
src/containers/LearningResourcePage/components/LearningResourceForm.jsx
src/containers/TopicArticlePage/components/TopicArticleForm.jsx

Prevent close of unsaved article

---

cypress/integration/Taxonomy/filter_spec.js
cypress/integration/Taxonomy/resource_spec.js
cypress/integration/Taxonomy/subject_spec.js
cypress/integration/Taxonomy/topic_spec.js
package.json
src/containers/LearningResourcePage/components/LearningResourceTaxonomy.jsx
src/containers/StructurePage/StructureContainer.jsx
src/containers/StructurePage/__tests__/StructurePage-test.js
src/containers/StructurePage/folderComponents/menuOptions/AddExistingToTopic.jsx
src/containers/StructurePage/folderComponents/menuOptions/CopyResources.tsx
src/containers/StructurePage/resourceComponents/StructureResources.jsx
src/containers/TopicArticlePage/components/TopicArticleTaxonomy.jsx
src/modules/learningpath/learningpathApi.js
src/modules/taxonomy/subjects/index.js
yarn.lock

Fixes NDLANO/Issues#2136
Send med språk i alle apikall for å sikre at det som vises er konsistent.

2136 locale in api parameter

---

src/containers/ConceptPage/components/ConceptForm.jsx

https://github.com/NDLANO/Issues/issues/2128

added old save button when editing concept in modal

---

cypress/integration/Search/search_spec.js
src/constants.js
src/containers/SearchPage/components/form/SearchConceptForm.jsx
src/containers/SearchPage/components/form/SearchContentForm.jsx
src/modules/auth0/auth0Api.js
src/server/auth.js
src/server/server.js

https://github.com/NDLANO/Issues/issues/2107

2107 sok etter forklaringer etter bruker

---

src/components/SlateEditor/plugins/embed/SlateImage.jsx
src/containers/ImageEditor/ImageCropEdit.jsx
src/containers/ImageEditor/ImageFocalPointEdit.jsx
src/containers/ImageEditor/ImageTransformEditor.jsx

https://github.com/NDLANO/Issues/issues/2122

added minimum width for images

---

cypress/integration/Editor/editorRoutes.js
src/containers/NdlaFilm/NdlaFilmEditor.jsx
src/containers/NdlaFilm/components/DropdownSearch.jsx
src/modules/taxonomy/resources/index.js

Relates to NDLANO/Issues#2145
Bytter ut bruk av query endepunkt med parameter på vanlige endepunkt.

Uses new endpoints for queries

---

src/components/SlateEditor/RichTextEditor.jsx
src/style/content-block.css
src/style/index.css

Change editor content font to serif

---

src/containers/StructurePage/StructureContainer.jsx

Legger tilbake en await for at sida skal rendre korrekt med statuser, og for at pubiser alt skal funke. Deployer fra branch til ff.

Adding await to fix publish all

---

src/containers/StructurePage/resourceComponents/StructureResources.jsx
src/containers/StructurePage/resourceComponents/TopicDescription.jsx
src/modules/learningpath/learningpathApi.js

Fikser publisering av alt. 
For å patche ff med dette, sjekker eg ut commiten som blei deploya, cherrypicker det som trengs og lager branch for det. Deployer deretter branch til ff.

Fixes publishing all

---

src/util/__tests__/routeHelpers-test.js
src/util/routeHelpers.js

Fixes NDLANO/Issues#2163
For å kunne legge til eksisterende ressurs til emne må vi kunne hente ut id på både gammelt og nytt format.

Expanded regexp to support uuids in id

---

src/config.js
src/containers/NdlaFilm/NdlaFilmEditor.jsx
src/containers/NdlaFilm/components/DropdownSearch.jsx

depends on NDLANO/deploy/pull/249

use env variable

---

src/containers/StructurePage/__tests__/__snapshots__/StructurePage-test.js.snap
src/containers/TopicArticlePage/components/TopicArticleConnections.jsx
src/containers/TopicArticlePage/components/TopicArticleTaxonomy.jsx

Opprette nye emner i taksonomi har feila etter at locale blei lagt inn som parameter på en del kall. Her var det et hull som eg no har tetta.

Fixes creating topic from article.

---

src/components/DisplayEmbed/DisplayExternal.jsx
src/components/DisplayEmbed/DisplayExternalVisualElement.jsx
src/components/DisplayEmbed/__tests__/__snapshots__/DisplayExternal-test.js.snap
src/components/H5PElement/H5PElement.jsx
src/components/SlateEditor/plugins/embed/SlateFigure.jsx
src/config.js
src/containers/VisualElement/DisplayVisualElement.jsx
src/containers/VisualElement/VisualElementSearch.jsx

https://github.com/NDLANO/Issues/issues/2146
Det er en liten feil i draft-api og article-api som gjør at lenka fra backenden får en ekstra `/`
```
data-url="https://h5p-test.ndla.no//resource/ea9bd951-c422-4a64-b057-1bb0075e5b76"
```
Fixed: https://github.com/NDLANO/draft-api/pull/210

2146 endre lagring av h5p ressurser i artikler

---

src/containers/NdlaFilm/NdlaFilmEditor.jsx
src/phrases/phrases-en.js
src/phrases/phrases-nb.js
src/phrases/phrases-nn.js

Added title to ndla-film

---

src/server/server.js

Versjon av ed som redirecter alle kall til ff-adresser til tilsvarende adresser i prod.

Redirect ff to prod

---

src/containers/StructurePage/folderComponents/menuOptions/DeleteTopic.jsx

https://github.com/NDLANO/Issues/issues/2162
* La til metode som arkiverer emne artikkel når emne blir slettet

2162 Sletting av emne i taksonomi burde arkivere emneartikkel

---

src/containers/FormikForm/FormikAlertModalWrapper.jsx
src/containers/ImageUploader/CreateImage.jsx
src/containers/ImageUploader/components/ImageForm.jsx

https://github.com/NDLANO/Issues/issues/2169
* Fixed bug continue button on alertmodal didn't continue/crashed site
* Fixed bug where alertmodal(notsaved) popped up when creating new image

fixed add image bug 

---

src/components/EditMarkupLink.js
src/containers/SearchPage/components/results/SearchContent.jsx
src/style/search.css

Fixes https://github.com/NDLANO/Issues/issues/2188
- Separerer link til å kun wrappe title teksten og ikke både html button og contentbadge.

Made title and button to link instead of entire div

---

src/constants.js
src/server/contentSecurityPolicy.js

Added support for molview embeds

---

package.json
yarn.lock

Søk etter youtubevideoer har slutta å fungere pga en nullpointer i frontendpackages.

Bump to fix youtube search

---

src/containers/StructurePage/folderComponents/FolderItem.jsx
src/containers/StructurePage/folderComponents/SettingsMenu.jsx
src/containers/StructurePage/folderComponents/SettingsMenuDropdown.jsx
src/containers/StructurePage/folderComponents/SettingsMenuDropdownType.jsx
src/containers/StructurePage/folderComponents/menuOptions/CopyResources.tsx
src/interfaces.ts
src/modules/draft/draftApi.js
src/modules/learningpath/learningpathApi.js
src/modules/taxonomy/index.js
src/modules/taxonomy/resources/index.js
src/phrases/phrases-en.js
src/phrases/phrases-nb.js
src/phrases/phrases-nn.js

https://github.com/NDLANO/Issues/issues/2199
How to test the new functionality: 
1. Menu -> Structure -> click on a Subject -> click on a Topic -> click on the Gear icon -> Copy resources from topic -> choose a Topic to copy resources from.
2. Check that the new Taxonomy-resources have different id from the one old ones
3. Check that the new Resources have different id from the old ones
4. Check that the new Taxonomy-resources filterId is the same as the Topic filterId you are copying to
5. Check that the new Taxonomy-resources fields are the same as the old ones (besides filterId, see 4.)

taxonomy resources are no longer shared after being copied

---

src/components/SlateEditor/plugins/embed/EditVideo.jsx
src/components/SlateEditor/plugins/embed/EditVideoTime.tsx
src/components/SlateEditor/plugins/embed/SlateVideo.jsx

Lifting youtube start/stop time state from EditVideoTime to SlateVideo

---

src/components/SlateEditor/plugins/link/Link.jsx
src/containers/FormikForm/articleFormHooks.js

2198 speed up article save

---

cypress/integration/Taxonomy/resource_spec.js
src/containers/StructurePage/StructureContainer.jsx
src/containers/StructurePage/__tests__/__snapshots__/ResourceItems-test.js.snap
src/containers/StructurePage/folderComponents/menuOptions/EditGrepCodes.tsx
src/containers/StructurePage/folderComponents/menuOptions/ToggleVisibility.tsx
src/containers/StructurePage/resourceComponents/Resource.jsx
src/containers/StructurePage/resourceComponents/ResourceItemLink.jsx
src/containers/StructurePage/resourceComponents/TopicDescription.jsx
src/modules/taxonomy/index.js
src/modules/taxonomy/subjects/index.js
src/modules/taxonomy/topics/index.js
src/shapes.js

Fixes NDLANO/Issues#2194
Oppdaterer metadata rekursivt. Viser også synlighet på ressursnivå ved å gråe ut teksten og ha den i kursiv.

Update metadata recursively

---

src/components/DisplayEmbed/DisplayExternalVisualElement.jsx
src/components/SlateEditor/plugins/embed/EditVideo.jsx
src/components/SlateEditor/plugins/embed/SlateFigure.jsx
src/containers/EditSubjectFrontpage/components/SubjectpageAbout.tsx
src/containers/FormikForm/components/FormikVisualElement.jsx
src/containers/TopicArticlePage/components/TopicArticleContent.jsx
src/containers/TopicArticlePage/components/TopicArticleForm.jsx
src/containers/VisualElement/DisplayVisualElement.jsx
src/containers/VisualElement/VisualElement.jsx
src/util/ndlaFilmHelpers.js

https://github.com/NDLANO/Issues/issues/2217

2217-Setting av youtube som visuelt element funker ikkje

---

src/containers/WelcomePage/components/SavedSearch.tsx

Add username to saved search

---

src/components/Dropdown/asyncDropdown/AsyncSearchTags.tsx

Fixes NDLANO/Issues#2227
Fikser nøkkelord. Ser ut som resten av metadataene ikke skiller mellom språk.

2227 update metadata on language change

---

src/containers/StructurePage/folderComponents/menuOptions/AddExistingToTopic.jsx

Unngår feilmelding ved flytting av emne.

Add filter to moved topic if filter not present.

---

src/components/SlateEditor/plugins/embed/SlateAudio.tsx

Fix audio dnd

---

src/containers/FormikForm/formikSubjectpageHooks.ts

#2254: Pass editorsChoices correctly when creating subjectpages as well as updating

---

src/components/Dropdown/asyncDropdown/AsyncSearchTags.tsx

#2267: Set tags to an empty list rather than undefined

---

.travis.yml
src/components/SlateEditor/plugins/embed/SlateAudio.tsx
src/components/SlateEditor/plugins/embed/SlateFigure.tsx

Add figure buttons to audio element

---

src/containers/FormikForm/FormikAlertModalWrapper.jsx

Fixes NDLANO/Issues#2311
Fjerner ekstra eventhander som kun kjører i prod.

Remove extra windowunload

---

src/components/H5PElement/H5PElement.jsx
src/components/Lightbox.jsx
src/components/SlateEditor/plugins/blockPicker/SlateVisualElementPicker.jsx

Justerer h5p-editoren til å få litt meir plass på sidene.

Give h5p-editor some more space

---

src/components/DisplayEmbed/DisplayExternal.jsx
src/components/H5PElement/H5PElement.jsx
src/components/H5PElement/h5pApi.js
src/components/HeaderWithLanguage/HeaderInformation.jsx
src/components/SlateEditor/RichBlockTextEditor.jsx
src/containers/H5PPage/H5PPage.jsx
src/containers/VisualElement/VisualElementSearch.jsx
src/phrases/phrases-en.js

NDLANO/Issues#2337
Sender språkinfo til h5p. Gjør at om du har norsk locale i ed så vises h5p-editoren på norsk.
Bruker artikkelspråk for å vise h5p i vanlig artikkel.
Fikser også emneikon og feil i engelsk phrases.

Add locale to h5p. Fix icon and title in en.

---

src/containers/VisualElement/__tests__/transformUrlIfNeeded-test.js
src/containers/VisualElement/visualElementApi.js
src/server/contentSecurityPolicy.js

Fixes NDLANO/Issues#2342
Test.
Lag artikkel og sett inn ressurs fra lenke: https://www.nrk.no/skole?mediaId=23224

fix adding nrk-skole urls to article

---

src/containers/WelcomePage/components/LastUsedContent.tsx

Eneste jeg lurer på her er om det er noe hokus pokus med locale som jeg burde ha håndtert annerledes
Tips: Om du skriver Fixes NDLANO/Issues#2333 så lukkes issuet når PR lukkes.

Tok i bruk EditMarkupLink i LastUsedContent

---

package.json
yarn.lock

Fixes NDLANO/Issues#2351
Også i ed

Bumped packages to get bash as language

---

src/components/Contributors/Contributors.jsx
src/components/DisplayEmbed/DisplayExternal.jsx
src/components/DisplayEmbed/DisplayExternalVisualElement.jsx
src/components/HeaderWithLanguage/HeaderActions.jsx
src/components/SlateEditor/plugins/embed/SlateAudio.tsx
src/components/SlateEditor/plugins/embed/SlateFigure.tsx
src/components/SlateEditor/plugins/embed/SlateVideo.tsx
src/components/SlateEditor/plugins/mathml/BlockMenu.jsx
src/components/SlateEditor/plugins/mathml/MathEditor.jsx
src/containers/AgreementPage/components/AgreementFields.jsx
src/containers/ConceptPage/components/ConceptForm.jsx
src/containers/ConceptPage/components/ConceptMetaData.jsx
src/containers/FormikForm/components/FormikDatePicker.jsx
src/containers/FormikForm/components/FormikLicense.jsx
src/containers/LearningResourcePage/components/LearningResourceContent.jsx
src/containers/LearningResourcePage/components/LearningResourceFootnotes.jsx
src/containers/Masthead/components/Navigation.jsx
src/containers/Masthead/components/SessionContainer.jsx
src/containers/SelectLocale/SelectLocale.jsx
src/containers/StructurePage/resourceComponents/AddResourceModal.tsx

Rydder i t-props, fikser noen warnings og fjerner redux fra dei enkleste komponentene.

Cleaning t props and other fixes

---

src/containers/WelcomePage/components/SaveSearchUrl.tsx

Sjekker om du har token før du prøver å gjøre fetch av user-data.
Bare en feilmelding etter deploy/build, men på dev-serveren så får du en sånn stor feilmelding over hele sida som jeg ikke likte :smile:

Fix crash when not logged in on WelcomePage

---

src/components/Taxonomy/Breadcrumb.tsx
src/containers/StructurePage/folderComponents/menuOptions/CopyResources.tsx
src/containers/TopicArticlePage/components/TopicArticleConnections.jsx
src/containers/TopicArticlePage/components/TopicArticleTaxonomy.jsx
src/util/retriveBreadCrumbs.ts

Fixes NDLANO/Issues#2361
Legger til mulighet for å plassere emneartikkel fleire plasser i taksonomi. 
Legger også til visning av emnesynlighet på brødsmulestier i taksonomikomponenten.

2361 add topic article to multiple topics

---

src/components/Dropdown/asyncDropdown/AsyncDropdown.jsx
src/containers/FormikForm/FormikGrepCodesContent.tsx
src/containers/LearningResourcePage/components/LearningResourceForm.jsx
src/phrases/phrases-en.js
src/phrases/phrases-nb.js
src/phrases/phrases-nn.js

Fixes NDLANO/Issues#2368
- Fikset en del console-warnings (fortsatt noen igjen, holder på med dem)
- Lagt til mulighet for å legge til grep-koder med enter
- Lagt til mulighet for å legge til flere grep-koder på en linje separert med komma
- Viser error ved feilformatert eller ikke-eksisterende grep-kode

2368 enklere innlegging av grep koder

---

src/modules/grep/grepApi.tsx
src/phrases/phrases-en.js
src/phrases/phrases-nb.js
src/phrases/phrases-nn.js

NDLANO/issues#2371
Vis kompetansemålkoder på bokmål i ed som standard. Bruk default om kun den varianten finnes.

Show grep-text on nob

---

src/components/SlateEditor/plugins/embed/EditImage.tsx

https://github.com/NDLANO/Issues/issues/2408

Setter size til fullbredde om du endrer alignment til center

---

cypress/integration/Editor/versions_spec.js
src/modules/article/articleApi.ts

Fixes NDLANO/Issues#2423
Depends on https://github.com/NDLANO/article-converter/pull/219
Sender ekstra parameter til article-converter.

Add preview-parameter

---

src/containers/SearchPage/components/results/SearchConcept/ConceptForm.tsx

https://github.com/NDLANO/Issues/issues/2427

Validering i inline form

---

src/components/SlateEditor/plugins/concept/ConceptModal.jsx
src/containers/ConceptPage/CreateConcept.jsx
src/containers/FormikForm/FormikConcepts.tsx
src/containers/FormikForm/formikDraftHooks.js
src/modules/concept/conceptApi.ts

https://github.com/NDLANO/Issues/issues/2428

InitialValues for articles må være en tom liste

---

src/containers/EditSubjectFrontpage/components/SubjectpageForm.tsx

https://github.com/NDLANO/Issues/issues/2429

default value på visualElement skapte problemer

---

src/components/Dropdown/MultiSelectDropdown.jsx
src/containers/ConceptPage/components/ConceptMetaData.jsx
src/containers/SearchPage/components/results/SearchConcept/ConceptForm.tsx

Fix footnote author bug

---

src/components/HelpMessage.jsx
src/components/MonacoEditor/MonacoEditor.jsx
src/components/MonacoEditor/editorActions.js
src/containers/EditMarkupPage/EditMarkupPage.jsx
src/phrases/phrases-en.js
src/phrases/phrases-nb.js
src/phrases/phrases-nn.js

Adding saving in html-editor.

---

src/components/SlateEditor/plugins/mathml/EditMath.jsx

Fixes NDLANO/Issues#2476
Plasserer markør i matteeditoren når den åpnes

Place caret in math editor

---

src/components/SlateEditor/plugins/blockPicker/SlateBlockPicker.jsx
src/components/SlateEditor/plugins/blockPicker/options.js
src/components/SlateEditor/plugins/details/index.tsx
src/components/SlateEditor/utils/schemaHelpers.js
src/containers/LearningResourcePage/components/LearningResourceContent.jsx

Gjør det mulig å sette inn embeds i tekstbokser.

Plus-menu in boxes

---

src/components/Dropdown/asyncDropdown/AsyncDropdown.jsx
src/components/Dropdown/asyncDropdown/AsyncSearchTags.tsx

Fixes NDLANO/Issues#2478
Test:
* Gå til nøkkelord under metadata
Ting som skal fungere:
* Skrive inn nøkkelord og legge til med enter
* Skrive inn flere nøkkelord separert med komma og legge dem til med enter
* Navigere nedover lista med piltastene og velge med enter
* Markøren skal holde seg i feltet etter at man har trykket enter

2478 keyword field improvements

---

src/components/SlateEditor/plugins/aside/SlateFactAside.jsx
src/components/SlateEditor/plugins/details/Details.tsx
src/components/SlateEditor/plugins/details/index.tsx
src/components/SlateEditor/utils/schemaHelpers.js

Legger til støtte for filer i bokser samt passer på at bilder ikkje tar større plass enn boksen.
Test: Det skal være mulig å legge til filer i bokser, samt at bilder/video ikkje skal være breiere enn boksen.

Embed in box fixes

---

src/components/Dropdown/asyncDropdown/AsyncSearchTags.tsx

Fjerner støtte for kommaseparering.
Test:
Innliming av tekst skal no gi en ny tag sjølv om den har komma i seg. Funksjonaliteten er no at du kan skrive inn nøkkelord, og velge disse med piltaster. Om et nøkkelord ikkje finnes kan du opprette det med enter.
Funker alle plasser der du kan sette inn nøkkelord.

Remove duplicates by using Set

---

cypress/integration/Search/search_spec.js
src/containers/SearchPage/components/form/SearchContentForm.jsx
src/containers/SearchPage/components/form/SearchForm.jsx
src/containers/WelcomePage/components/SavedSearch.tsx

Fikser problem med at status-valget resettes ved endring av query.

Fix resetting of status when changing other parameters.

---

src/components/H5PElement/H5PElement.jsx
src/containers/H5PPage/H5PPage.jsx
src/containers/VisualElement/VisualElementSearch.jsx

Ref https://trello.com/c/PsP5nEUk/1014-lukk-edlib-2
Legger til håndtering av h5p-lukk event i ny h5p-editor.
Test:
Ny X-knapp i h5p-editor skal lukke dialogen ved innsetting av h5p.

Add event hander for h5p close button

---

src/components/HeaderWithLanguage/HeaderWithLanguage.jsx
src/components/HeaderWithLanguage/LearningpathConnection.tsx
src/containers/ArticlePage/LearningResourcePage/components/LearningResourceForm.jsx
src/containers/EditSubjectFrontpage/Subjectpage.tsx
src/containers/EditSubjectFrontpage/components/SubjectpageForm.tsx
src/containers/EditSubjectFrontpage/components/SubjectpageMetadata.tsx

fikk api feil ved ny læringssti fordi id var null

Fikser feil ved ny læringssti

---

cypress/fixtures/draft-12173.json
cypress/integration/Editor/rich_block_text_editor_spec.js
src/components/Contributors/Contributors.jsx

https://github.com/NDLANO/Issues/issues/2523

Gjør alle opphavstyper til lowercase

---

src/components/SlateEditor/plugins/concept/SlateConceptPreview.tsx

Viser markdown i forklaringer i artikler.
Test: Legg inn forklaring med markdown i artikkel og sjekk at den vises rendra.

Rendering markdown

---

package.json
src/components/DisplayEmbed/helpers/DisplayExternalModal.jsx
src/components/H5PElement/H5PElement.tsx
src/components/Lightbox.jsx
src/containers/H5PPage/H5PPage.jsx
yarn.lock

Forsøk på css-versjon av Gunnar sin pr: 
https://github.com/NDLANO/editorial-frontend/pull/965:
> fixing NDLANO/Issues#2542
> 
> Test:
> Åpne pr-installasjon og velg Rediger H5P i menyen. Edlib skal ta opp heile høgda på skjermen - header.
> Innsetting og redigering av h5p i artikkel skal fremdels funke greit.

Setting height on edlib-iframe dynamically

---

src/components/DisplayEmbed/DisplayExternal.jsx
src/containers/SearchPage/components/form/SearchAudioForm.tsx

DisplayExternal krever src og type

default props static

---

src/components/SlateEditor/slateRendering.jsx

https://github.com/NDLANO/Issues/issues/2549
editor er nå konsekvent med preview

paragrafer som er midtstilt, vises nå som midtstilt i editor

---

src/config.js
src/constants.ts
src/containers/FormikForm/components/ElementListItem.tsx
src/containers/NdlaFilm/NdlaFilmEditor.jsx
src/containers/NdlaFilm/components/SlideshowEditor.tsx
src/containers/NdlaFilm/components/ThemeEditor.tsx
src/util/routeHelpers.js

Fjerner bruk av emne for ndla-film i test. Fikser slik at lenker til filmene er til artikkel og ikkje læringssti på grunn av manglende articleType.
Test:
Åpne NDLA Film-redigering og sjekk at allen filmlenkene går til korrekte artikler.

Removing custom article-type from ndla-film. Fix urls to articles.

---

src/style/index.css

https://github.com/NDLANO/Issues/issues/2548

Setter display flex på c-figure

---

src/components/Dropdown/asyncDropdown/AsyncSearchTags.tsx
src/containers/AudioUploader/components/AudioForm.tsx
src/containers/ImageUploader/components/ImageForm.tsx

Test:
- Sjekk at tags fungerer på alle plasser (lyd, bilde, artikkel?), både ny og eksisterende

Use tags from values rather than props to prevent resetting initial tags in AsyncSearchTags

---

src/style/index.css

https://github.com/NDLANO/Issues/issues/2548
Dette ser ut til å funke med både h5p og video
http://localhost:3000/subject-matter/learning-resource/30636/edit/nb
Jeg brukte denne for å teste
Forsøk å fjern h5p og bytt den ut med forskjellige andre elementer

Forsøker med en annen display type

---

src/containers/H5PPage/H5PPage.jsx
src/containers/Masthead/components/NavigationMenu.jsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Kunne sikkert gjort dette meir elegant ved at HeaderInformation og NavigationMenu brukte en komponent som hadde oversikt over ikoner.
Test:
Ikon skal vises ved åpning av meny.

Added icons in meny

---

src/containers/ArticlePage/LearningResourcePage/CreateLearningResource.jsx
src/containers/ArticlePage/TopicArticlePage/CreateTopicArticle.jsx
src/containers/FormikForm/GrepCodesFieldContent.tsx

https://github.com/NDLANO/Issues/issues/2559

Setter grepCodes: [] utenfor formet i nye artikler

---

cypress/integration/Editor/concept_spec.js
cypress/integration/Editor/editorRoutes.js
cypress/integration/Editor/full_resource_spec.js
cypress/integration/Editor/rich_block_text_editor_spec.js
cypress/integration/Editor/slate_block_picker_spec.js
cypress/integration/Editor/status_handling_spec.js
cypress/integration/Editor/table_spec.js
cypress/integration/Editor/toolbar_spec.js
cypress/integration/Editor/topic_article_spec.js
cypress/integration/Editor/versions_spec.js
cypress/integration/Film/film_spec.js
cypress/integration/Search/search_audios_spec.js
cypress/integration/Search/search_concept_spec.js
cypress/integration/Search/search_content_spec.js
cypress/integration/Search/search_images_spec.js
cypress/integration/Taxonomy/filter_spec.js
cypress/integration/Taxonomy/resource_spec.js
cypress/integration/Taxonomy/subject_spec.js
cypress/integration/Taxonomy/topic_spec.js
cypress/support/index.js

Testing some other stuff.

---

src/components/FormikField/FormikFieldHelp.tsx
src/components/SlateEditor/EditorFooter.tsx
src/containers/ConceptPage/ConceptForm/ConceptForm.tsx
src/containers/ConceptPage/ConceptForm/FormFooter.tsx
src/containers/ConceptPage/ConceptPage.jsx
src/containers/ConceptPage/CreateConcept.jsx
src/containers/ConceptPage/components/ConceptContent.tsx
src/containers/ConceptPage/conceptUtil.ts
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

https://github.com/NDLANO/Issues/issues/2573

Disabler save knappen helt om man har feil

---

src/containers/ArticlePage/LearningResourcePage/EditLearningResource.jsx
src/containers/ArticlePage/TopicArticlePage/EditTopicArticle.jsx
src/containers/ConceptPage/EditConcept.jsx
src/containers/FormikForm/translateFormHooks.ts
src/containers/Podcast/EditPodcast.tsx
src/modules/translate/translateApi.js
tsconfig.json

Unngår å sende inn data fleire gonger. Sender heller med liste med felt som skal oversettes.

Send inn list of fields to translate.

---

src/containers/AudioUploader/components/AudioContent.tsx
src/containers/VisualElement/VisualElement.tsx

Fixes NDLANO/Issues#2581
Fikser også denne: https://knowitobjectnet.slack.com/archives/C0XP13QV8/p1620638240003200

2581 prevent unnecessary audio fetches

---

src/constants.ts
src/containers/StructurePage/StructureContainer.jsx

Fixes NDLANO/Issues#2591
Test
Har du valgt å vise favoritter en gang, skal favoritter vises.

Remembering users favourite subjects.

---

src/containers/PodcastSeries/components/PodcastSeriesForm.tsx
src/containers/PodcastSeries/components/PodcastSeriesMetaData.tsx
src/modules/audio/audioApiInterfaces.ts
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts
src/util/audioHelpers.ts

Test: Sjekk at det går å legge til en beskrivelse for serier :^)

#2599: Adds formik field for description of podcast series

---

cypress/integration/Editor/concept_spec.js
cypress/integration/Editor/table_spec.js
cypress/integration/Editor/toolbar_spec.js
cypress/integration/Editor/topic_article_spec.js
cypress/integration/Search/search_audios_spec.js
cypress/integration/Search/search_concept_spec.js
cypress/integration/Search/search_content_spec.js
cypress/integration/Search/search_images_spec.js
cypress/integration/Taxonomy/subject_spec.js
cypress/integration/Taxonomy/topic_spec.js
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Noen endringer etter ønske fra NDLA. Gjør det tydeligere at det er snakk om episoder.

Some changes in wording

---

src/containers/SearchPage/components/results/SearchConcept/ConceptForm.tsx
src/containers/SearchPage/components/results/SearchConcept/SearchConcept.jsx

Endret ConceptForm til å rerendre alt innhold når språk endres.
Fikset en typing error i ContentView når et Concept oppdateres.

2620 hurtigredigering forklaring bruker kun nb

---

src/containers/ConceptPage/components/ConceptContent.tsx

Fixes https://github.com/NDLANO/Issues/issues/2589
Kan sjekkes ved å gå inn på ed og søke på sko. Se om dato i oversikt er lik skjemaet. 
Screenshot:

Replace created with updated in concept form

---

src/components/SlateEditor/plugins/embed/EditImage.tsx

Fixes https://github.com/NDLANO/Issues/issues/2632
Store bilder kan no lagrast både med og uten byline.

Lagt til hide-byline for store bilder

---

src/containers/StructurePage/__tests__/__snapshots__/AddResourceModal-test.jsx.snap
src/containers/StructurePage/resourceComponents/AddResourceModal.tsx
src/containers/StructurePage/resourceComponents/AllResourcesGroup.tsx
src/containers/StructurePage/resourceComponents/ResourceGroup.jsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts
src/util/resolveJsonOrRejectWithError.ts

Fixes NDLANO/Issues#2659
La til en custom-feilemelding for duplikat.
Denne vil også fikse visning av feilmeldinger dersom requesten feiler av andre grunner (var en typo).

#2659: Handle duplicate resources on sturcturepage

---

src/config.ts

NDLANO/Issues#2656
Gjør det mulig å kjøre ed med andre verdier.

Added possibility to override ndla values

---

now.json
src/config.ts

Fjerner miljøvariabel som gjør at now-installasjoner går mot auth0 prod.'
Test: Sjekk at now-installasjonen funker og lar seg logge inn i.

Fjerner miljøvariabel fra now-instans.

---

src/containers/StructurePage/StructureContainer.jsx
src/util/taxonomyHelpers.ts

https://github.com/NDLANO/Issues/issues/2658
Pga flatering av struktur har ikke topics subtopics, så subtopics måtte finnes ved å sjekke på parents

manglende subtopics måtte finnes

---

src/components/SlateEditor/plugins/details/index.tsx

Fixes NDLANO/Issues#2674
Fikser også en error vi fikk hvis vi brukte backspace i ekspanderende boks

2674 expanding box fixes

---

src/components/SlateEditor/plugins/table/handleKeyDown.ts
src/components/SlateEditor/plugins/table/helpers.ts
src/components/SlateEditor/plugins/table/index.tsx
src/components/SlateEditor/plugins/table/matrix.ts
src/components/SlateEditor/plugins/table/utils.ts

Har ryddet en del opp i koden for slate table plugin for å gjøre den mer lesbar. Har opprettet noen nye hjelpefunksjoner

Upgrade slate refactor table

---

src/containers/ArticlePage/TopicArticlePage/components/TopicArticleConnections.tsx

Show all subjects if no favorites

---

src/components/DisplayEmbed/DisplayExternal.jsx

Fixes NDLANO/Issues#2720,
sammen med https://github.com/NDLANO/graphql-api/pull/183

Add missing error message

---

src/components/HeaderWithLanguage/EmbedInformation/EmbedConnection.tsx
src/components/HeaderWithLanguage/HeaderStatusInformation.jsx
src/components/HeaderWithLanguage/HeaderStatusInformation.tsx
src/components/HeaderWithLanguage/LearningpathConnection.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Add connection for concepts

---

src/containers/SearchPage/SearchContainer.tsx
src/containers/SearchPage/SearchSaveButton.tsx
src/containers/WelcomePage/components/SaveSearchUrl.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts
src/style/search.css
src/util/htmlHelpers.ts

Fixes NDLANO/Issues#2729
Liste over ting som er fikset:
1. (Forsiden) Det skal nå være mulig å lagre lenker med locale. Feks https://ed.test.ndla.no/en/search/content?page=1&page-size=10&query=&sort=-lastUpdated
2. (Søkeside) lagt til knapp for å lagre søk.
3. (Søkeside). Ved forsøk på nytt søk via Masthead resulterte det i at formen på søkesiden ble endret, men det ble ikke faktisk gjort et nytt søk. Dette er nå fikset.

2729 fix save search with language

---

cypress/integration/Editor/slate_block_picker_spec.js
src/containers/VisualElement/VisualElementSearch.jsx

Fixes https://github.com/NDLANO/Issues/issues/2733

Remove YouTube from video search

---

src/containers/SearchPage/components/results/SearchConcept/SearchConcept.jsx
src/containers/SearchPage/components/results/SearchContent.jsx

Fixes https://github.com/NDLANO/Issues/issues/2747.

Added image width parameters to concept and content search results

---

src/components/DisplayEmbed/DisplayExternal.jsx
src/components/SlateEditor/plugins/DND/index.ts
src/components/SlateEditor/plugins/blockPicker/SlateBlockPicker.tsx
src/components/SlateEditor/plugins/details/Details.tsx

Har fikset et par feil:
- (Artikkel editor) Ressurs fra lenke skal nå kunne redigeres etter innsetting (endre url).
- Drag and drop skal fungere mer likt som i master. Ved markering av deler av en liste så vil nå hele listen flyttes.
- Fjern-knappen i ekspanderende boks er nå plassert i høyre hjørne og ikke utenfor boksen

Slate upgrade bugfixes

---

src/components/HeaderWithLanguage/DeleteLanguageVersion.tsx

Fixes NDLANO/Issues#2753
Hvordan teste:
Se at det går an å slette en språkversjon i artikkel.

Bugfix: Delete article version now works

---

src/modules/article/articleApi.ts

Viser visuelt element ved preview av emneartikkel.
Avhenger av https://github.com/NDLANO/article-converter/pull/275

Sender parameter for å vise visuelt element.

---

src/components/ArticlePreview.tsx

Fixes https://github.com/NDLANO/Issues/issues/2756

2756 Added image width property to ArticlePreview

---

src/constants.ts
src/server/contentSecurityPolicy.ts

Fixes https://github.com/NDLANO/Issues/issues/2740
Test:
* Åpne en artikkel (funker både for emner og læringsressurser)
* Velg `ressurs fra lenke`
* Lim inn lenke fra Trinket.io (f.eks https://trinket.io/python3/6afe18902f )
* Sjekk at både validation fungerer og at det går an å lagre artikkelen

add trinket as new embed type

---

package.json
src/components/PreviewConcept/PreviewConcept.tsx
yarn.lock

Fixes NDLANO/Issues#2774
Avhengig av https://github.com/NDLANO/frontend-packages/pull/883
Hvordan teste:
1. Åpne feks /concept/2879/edit/nb og forhåndsvis. Teksten skal plasseres under bildet. Bildet skal være sentrert.
2. På https://liste.test.ndla.no/nb/concepts/2879 plasseres teksten til høyre for bildet.

2774 bugfix concept layout

---

src/containers/SearchPage/components/results/SearchConcept/FormView.tsx

Fixes https://github.com/NDLANO/Issues/issues/2797

Only update search result if the currently displayed language is updated

---

cypress/integration/Editor/toolbar_spec.js
src/components/SlateEditor/helpers.ts
src/components/SlateEditor/plugins/DND/index.ts
src/components/SlateEditor/plugins/blockPicker/SlateBlockPicker.tsx
src/components/SlateEditor/plugins/blockPicker/options.js
src/components/SlateEditor/plugins/concept/EditSlateConcept.tsx
src/components/SlateEditor/plugins/concept/SlateConceptPreview.tsx
src/components/SlateEditor/plugins/list/__tests__/normalizer-test.ts
src/components/SlateEditor/plugins/list/__tests__/serializer-test.ts
src/components/SlateEditor/plugins/list/handlers/onBackspace.ts
src/components/SlateEditor/plugins/list/handlers/onEnter.ts
src/components/SlateEditor/plugins/list/handlers/onTab.ts
src/components/SlateEditor/plugins/list/index.tsx
src/components/SlateEditor/plugins/list/types.ts
src/components/SlateEditor/plugins/list/utils/defaultBlocks.ts
src/components/SlateEditor/plugins/list/utils/getListItemType.ts
src/components/SlateEditor/plugins/list/utils/hasListItem.ts
src/components/SlateEditor/plugins/list/utils/isList.ts
src/components/SlateEditor/plugins/list/utils/isSelectionOnlyOfType.ts
src/components/SlateEditor/plugins/list/utils/toggleList.ts
src/components/SlateEditor/plugins/paragraph/index.tsx
src/components/SlateEditor/plugins/toolbar/SlateToolbar.tsx
src/components/SlateEditor/plugins/toolbar/handleMenuClicks.ts
src/util/articleContentConverter.tsx
src/util/convertFromHTML.ts

Unwrap block element children in paragraph

---

src/server/contentSecurityPolicy.ts

Gjør det mulig å kjøre applikasjonen i lokal docker. Lettere å teste fullt oppsett lokalt.

Run locally

---

cypress/integration/Editor/slate_block_picker_spec.js
cypress/integration/Editor/table_spec.js
cypress/integration/Editor/toolbar_spec.js

Fortsatt ikke feilfritt, men slate-specsene har nå vært stabile fire kjøringer på rad.

update slate block picker spec

---

src/components/HeaderWithLanguage/HeaderActions.tsx
src/components/HeaderWithLanguage/SimpleLanguageHeader.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

NDLANO/Issues#1637
Viser språkkode und dersom den kjem fra api.

Add support for showing language code und.

---

cypress/integration/Editor/versions_spec.js
cypress/integration/Film/film_spec.js
src/components/Dropdown/asyncDropdown/AsyncDropdown.tsx
src/components/SlateEditor/plugins/embed/AudioPlayerMounter.tsx

Fixes https://github.com/NDLANO/Issues/issues/2839

2839 Change figureLicenseDialogId to avoid querySelector crash in articleScripts

---

src/containers/AudioUploader/EditAudio.tsx
src/containers/Podcast/EditPodcast.tsx
src/phrases/phrases-en.ts

Fikse manglende oversettelser av audios.

Send subfield to translator.

---

src/components/HeaderWithLanguage/HeaderActions.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Enable northern sami

---

src/containers/SearchPage/components/results/SearchList.tsx

Fixes https://github.com/NDLANO/Issues/issues/2852

2852 Make SearchResult component key composite

---

src/components/validators.ts

Fixes https://github.com/NDLANO/Issues/issues/2849

2849 Fixed isEmpty Slate function to handle embed edge case

---

src/containers/PreviewDraftPage/LanguageSelector.tsx
src/containers/PreviewDraftPage/PreviewDraftPage.tsx

Reintroduserte "label", som på et eller annet tidspunkt har blitt fjernet.

Preview Draft to ts

---

src/containers/ImageUploader/EditImage.tsx
src/containers/ImageUploader/components/ImageContent.tsx
src/containers/ImageUploader/components/ImageForm.tsx
src/containers/ImageUploader/imageTransformers.ts
src/modules/image/imageApi.ts

Bildefil sendes nå med ved oppdatering av bilde.
Hvordan teste:
1. Åpne eksisterende bildefil.
2. Fjern bilde og last opp et nytt.
3. Lagre
4. Bilde skal oppdateres som forventet.

Image file is now sent on patch

---

src/constants.ts
src/containers/VisualElement/__tests__/transformUrlIfNeeded-test.js
src/containers/VisualElement/urlTransformers.ts
src/server/contentSecurityPolicy.ts

Fixes NDLANO/Issues#2857
Legger til codepen.io som embed.

Add codepen to resource from url.

---

src/containers/VisualElement/__tests__/transformUrlIfNeeded-test.js
src/containers/VisualElement/urlTransformers.ts

Håndterer både bruker og team i codepen urler.

Simpler transform code

---

src/containers/EditSubjectFrontpage/components/SubjectpageAbout.tsx
src/containers/EditSubjectFrontpage/components/SubjectpageForm.tsx
src/containers/NdlaFilm/components/NdlaFilmForm.tsx
src/util/__tests__/ndlaFilmHelpers-test.ts
src/util/ndlaFilmHelpers.ts

Fixes NDLANO/Issues#2880
Fikser en feil der tittel i ndlafilm og fagforside? ikke gjorde at formen ble markert som dirty selv om tittelen var redigert.
Hvordan teste:
1. Apne fagforside fra strukturredigering eller ndla film.
2. Begynn å endre tittel og bekreft at lagreknapp blir blå.

Change title in subjectpage and ndlafilm to Slate

---

src/server/Html.tsx
src/style/index.css

Nyeste mathjax. Samme fiks som i ndla-frontend for å få matte til å sjå best mulit ut.

Bump mathjax and adjust styling.

---

cypress/integration/Editor/slate_block_picker_spec.js
cypress/integration/Editor/table_spec.js
package.json
yarn.lock

Bumper for å få inn https://github.com/NDLANO/Issues/issues/2889

Bumped editor to fix plus button

---

src/containers/ArticlePage/TopicArticlePage/components/TopicArticleAccordionPanels.tsx

Fixes NDLANO/Issues#2910
Test:
* Sjekk at du kan sette lisens N/A på emneartikler og at dette kan vises i frontend.

2910 enable licese na

---

src/containers/ArticlePage/TopicArticlePage/components/TopicArticleTaxonomy.tsx

Fixes https://github.com/NDLANO/Issues/issues/2898
Hvordan teste:
1. Opprett et nytt emne. Plasser det under et emne i taksonomien. Det skal være markert som ikke synlig i struktur.
2. Plasser et publisert emne i taksonomien. Det skal være markert som synlig i struktur.
3. Plasser et tidligere publisert emne i taksonomi. Det skal være markert som synlig i struktur.

#2898 Update visibility to false if a topic has never been published

---

package.json
src/components/SlateEditor/plugins/related/RelatedArticle.tsx
src/components/SlateEditor/plugins/related/RelatedArticleBox.tsx
src/containers/FormikForm/VersionAndNotesPanel.tsx
src/util/resourceHelpers.ts
yarn.lock

Forstår ikke hvorfor disse har ikke har fått pipelinen til å krasje, men nå skal de hvertfall være fikset. Bumpet ndla-ui for å få med en optional prop på Figure.

Fixed some type errors that only appeared locally

---

src/containers/ArticlePage/LearningResourcePage/EditLearningResource.tsx
src/containers/ArticlePage/TopicArticlePage/EditTopicArticle.tsx

Oversettelse funker ikkje for artikler på grunn av endringer i skjema.
Test
* Forsøk å oversett en artikkel til nynorsk
* Sjekk at innhold oversettes.

Fix translate robot for article.

---

src/modules/article/articleApi.ts

Depends on NDLANO/article-converter/pull/299
Test:
* Kjør denne sammen med article-converter med `start-with-local-converter' 
* Lag en artikkel med lenke til anna artikkel
* Forhåndsvis artikkel og sjekk at lenka peiker på test.ndla.no

Add parameter for absolute url.

---

src/components/SlateEditor/utils/defaultNormalizer.ts

Fixes NDLANO/Issues#2942
Det skal nå være mulig å toggle lister (og sikkert andre elementer) i en boks når det kun er ett element der.
Problemet oppsto pga dette hendelsesforløpet:
1. Boks inneholder kun en paragraf med tekst.
2. Brukeren endrer paragrafen til en liste
3. Normaliseringen ønsket at første element alltid skal være en paragraf eller header. I stedet for å sette inn en tom paragraf som første element endret den heller listen tilbake til en paragraf.
Hvordan teste:
1. Åpne en artikkel.
2. Sett inn en boks (ekspanderende, faktaboks, tekst i ramme).
3. Marker tekst eller bruk hotkeys til å sette inn liste. Dette skal nå være mulig selv om det bare er en paragraf i boksen.

Rewrite defaultNormalizer to better handle first, last and nodes normalization

---

src/components/HeaderWithLanguage/HeaderWithLanguage.tsx
src/containers/ArticlePage/LearningResourcePage/EditLearningResource.tsx
src/containers/ArticlePage/LearningResourcePage/components/LearningResourceForm.tsx
src/containers/ArticlePage/LearningResourcePage/components/LearningResourcePanels.tsx
src/containers/ArticlePage/LearningResourcePage/components/LearningResourceTaxonomy.tsx
src/containers/ArticlePage/TopicArticlePage/EditTopicArticle.tsx
src/containers/ArticlePage/TopicArticlePage/components/TopicArticleAccordionPanels.tsx
src/containers/ArticlePage/TopicArticlePage/components/TopicArticleForm.tsx
src/containers/ArticlePage/TopicArticlePage/components/TopicArticleTaxonomy.tsx
src/containers/FormikForm/formikDraftHooks.ts

Fixes https://github.com/NDLANO/Issues/issues/2941

2941 Reintrodusere varsel for artikler med mer enn en oppføring i taksonomi.

---

src/containers/FormikForm/__tests__/FormikAvailability-test.tsx
src/containers/FormikForm/components/AvailabilityField.tsx
src/interfaces.ts
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Partially fikses https://github.com/NDLANO/Issues/issues/2926

removed Student/Elev status from Availability

---

cypress/integration/Editor/full_resource_spec.js

Oppdatering av fixtures fikset full_resource_spec for meg lokalt.
Krysser fingrene for at det også går bra i PR.

Update cypress fixtures relevant to full_resource_spec

---

src/containers/VisualElement/VisualElementUrlPreview.tsx

Det skal nå være mulig å sette inn Ressurs fra lenke i blokk-meny i Slate.

External embed plugin now inserts block on save

---

src/containers/ArticlePage/LearningResourcePage/EditLearningResource.tsx
src/containers/ArticlePage/TopicArticlePage/EditTopicArticle.tsx
src/containers/ConceptPage/EditConcept.tsx
src/containers/Podcast/EditPodcast.tsx

Får form til å være dirty når ny språkversjon legges til.
Test:
* Rediger artikkel og legg til ny språkversjon.
* Lagreknappen skal være blå. I test er den grå.

Gjøre form dirty ved ny språkversjon

---

src/components/SlateEditor/plugins/concept/ConceptModal.tsx

Fixes https://github.com/NDLANO/Issues/issues/2981
Hvordan teste: Skriv noe tekst i en lærringsressurs og marker det. Velg deretter forklaring i toolbox. Skru på slow 3g-throttling og søk etter noe. Mens spinner-ikonet er aktivt, søk på noe helt urelatert. Hvis alt fungerer som tiltenkt vil resultatene til det originale søket ditt først vises, etterfulgt av resultatet av det siste søket ditt. Query-parameteret skal aldri endre seg uten at du selv velger at det skal endres ved å skrive mer.

Improved debounce usage for concept query search when inserting a concept into an article

---

src/containers/VisualElement/__tests__/__snapshots__/transformUrlIfNeeded-test.js.snap
src/containers/VisualElement/__tests__/transformUrlIfNeeded-test.js
src/containers/VisualElement/urlTransformers.ts

Fixes https://github.com/NDLANO/Issues/issues/2997
Hvordan teste: 
Hent en embed-url fra https://www.nrk.no/skole/ og legg den til som "ressurs fra lenke" i ed. Sjekk at forhåndsvisning og innsetting fungerer.

Rewrote nrk-skole transformer to new spec

---

src/containers/ArticlePage/components/ContentField.tsx
src/containers/FormikForm/components/ElementList.tsx
src/containers/FormikForm/components/ElementListItem.tsx
src/containers/FormikForm/components/ElementListLink.tsx
src/util/resourceHelpers.ts

Mer eller mindre prikk lik som to komponter jeg tok i frontend-packages tidligere i dag, så tenkte jeg kunne ta denne mens det var ferskt i minnet.
Den brukes 10 forskjellige steder, og kan testes ved å legge til, slette og flytte på elementer de ti forskjellige stedene.

ElementList to TypeScript

---

src/constants.ts
src/containers/App/App.tsx
src/containers/Masthead/components/NavigationMenu.tsx
src/containers/StructurePageBeta/Fade.tsx
src/containers/StructurePageBeta/MakeDNDList.tsx
src/containers/StructurePageBeta/NodeItem.tsx
src/containers/StructurePageBeta/RootNode.tsx
src/containers/StructurePageBeta/StructureContainer.tsx
src/containers/StructurePageBeta/StructurePage.tsx
src/containers/StructurePageBeta/folderComponents/StructureErrorIcon.tsx
src/modules/nodes/nodeApi.ts
src/modules/nodes/nodeApiTypes.ts
src/modules/nodes/nodeMutations.ts
src/modules/nodes/nodeQueries.ts
src/modules/nodes/nodeUtil.ts
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts
src/queryKeys.ts
src/util/apiHelpers.ts
src/util/taxonomyHelpers.ts

Har begynt å plukke ting fra https://github.com/NDLANO/editorial-frontend/pull/1222/. Inntil videre har jeg lagt inn alt av queries, mutations og API-kall, selv om ikke alt brukes. Tenkte å få skrevet tester allerede nå, så vi har et litt bedre grunnlag enn på nåværende struktur. Følgende PR'er vil bli mindre inkrementer med funksjonalitet, mest sannsynligvis.

Initial Beta Structure

---

src/containers/StructurePageBeta/NodeItem.tsx
src/containers/StructurePageBeta/folderComponents/FolderItem.tsx
src/containers/StructurePageBeta/folderComponents/SettingsMenu.tsx
src/containers/StructurePageBeta/folderComponents/SettingsMenuDropdownType.tsx
src/containers/StructurePageBeta/folderComponents/sharedMenuOptions/ToggleVisibility.tsx
src/containers/StructurePageBeta/folderComponents/sharedMenuOptions/components/MenuItemButton.tsx
src/interfaces.ts
src/modules/nodes/nodeMutations.ts

Tenker å legge til en og en funksjonalitet inntil videre, inntil options-lista er fullverdig igjen.
Hvordan teste: Sjekk at rotnoder blir hentet på nytt når du endrer synligheten på en rotnode. Sjekk at barnenoder blir hentet på nytt når du endrer synligheten til en barnenode.

Added FolderItem and visibility toggle option to structure beta

---

src/containers/ImageEditor/ImageEditor.tsx

Dersom et bilde har satt crop eller fokal så vil knappene vises utheva i bilderedigeringa.

Viser knapp som aktiv dersom embed har verdier.

---

src/modules/article/articleApi.ts

Fixes NDLANO/Issues#3008
Sender ekstra param for å vise alt-tekst for bilder.

Add previewAlt param

---

src/components/HeaderWithLanguage/HeaderActions.tsx
src/components/HeaderWithLanguage/SimpleLanguageHeader.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts
src/util/resourceHelpers.ts

Fixes https://github.com/NDLANO/Issues/issues/3030

Added new language option

---

src/containers/Podcast/components/PodcastForm.tsx

Av en eller annen grunn har jeg ikke lagt til warnings på Podcast episoder, legger de til nå.

adding warning labels on podcast episodes

---

src/config.ts
src/containers/Masthead/components/NavigationMenu.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Fant berre ut at dette var praktisk å ha.

Add menu for brightcove

---

src/containers/ArticlePage/articleTransformers.ts
src/util/formHelper.ts

Fixes https://github.com/NDLANO/Issues/issues/3017

ingress no longer fallbacks when empty, it stays empty

---

src/constants.ts
src/containers/SearchPage/components/results/SearchConcept/ContentView.tsx

Remove liste from embeds.
Fixes NDLANO/Issues#3047
Lar alle redigere forklaringer i søkeresultatet.

Let all edit concepts inline.

---

cypress/fixtures/draftEN.json
cypress/integration/Editor/editorRoutes.js
cypress/integration/Editor/full_resource_spec.js

Gått grønt tre ganger nå, regner med at det er greit.

Fix cypress flake for published date test

---

src/containers/AudioUploader/EditAudio.tsx
src/containers/AudioUploader/components/AudioForm.tsx
src/containers/ImageUploader/EditImage.tsx
src/containers/ImageUploader/components/ImageForm.tsx
src/containers/PodcastSeries/EditPodcastSeries.tsx
src/containers/PodcastSeries/components/PodcastSeriesForm.tsx

Fixes https://github.com/NDLANO/Issues/issues/3035

Enable save button for images, audio and series when creating a new language version

---

src/components/HeaderWithLanguage/HeaderActions.tsx
src/components/PreviewDraft/PreviewDraftLightbox.tsx
src/containers/ArticlePage/LearningResourcePage/components/LearningResourcePanels.tsx
src/containers/ArticlePage/TopicArticlePage/components/TopicArticleAccordionPanels.tsx
src/containers/EditMarkupPage/EditMarkupPage.tsx
src/containers/FormikForm/VersionActionButtons.tsx
src/containers/FormikForm/VersionAndNotesPanel.tsx

Fixes https://github.com/NDLANO/Issues/issues/3048
Krasjen var forårsaket av at vi prøvde å hente ut formikContext et sted den ikke var tilgjengelig. Denne må vel nesten være med dersom vi skal master til test.

3048 Fikse EditMarkupPage

---

src/containers/ArticlePage/LearningResourcePage/components/LearningResourceForm.tsx
src/containers/ArticlePage/TopicArticlePage/components/TopicArticleForm.tsx
src/containers/FormikForm/articleFormHooks.ts

Fixes https://github.com/NDLANO/Issues/issues/3039

Reset warnings when handleSubmit succeeds

---

src/modules/nodes/nodeQueries.ts

Dette fører til en reduksjon på N kall hver gang man trykker på en ny rotnode. I nåværende løsning gjøres det ti API-kall dersom rotnoden har ti barn. I denne gjøres det ett.

Make use of /drafts instead of individually attempting to fetch every draft when checking articleType

---

src/containers/StructurePageBeta/folderComponents/SettingsMenuDropdownType.tsx
src/containers/StructurePageBeta/folderComponents/subjectMenuOptions/AddNodeTranslation.tsx
src/containers/StructurePageBeta/folderComponents/subjectMenuOptions/ChangeNodeName.tsx
src/modules/nodes/nodeApi.ts
src/util/yupHelpers.ts

Sjekkliste:
* Alle rotnoder skal hentes på nytt når du oppdaterer listen med oversettelser. 
* Dersom du endrer oversettelsen til det nåværende språket skal rotnoden umiddelbart oppdateres til å ta i bruk det nye navnet.
* Formet skal bli dirty når du oppdaterer og sletter.

Re-implemented name changes for subjects in Structure Beta

---

src/containers/StructurePageBeta/StructureContainer.tsx

Kjapp fiks. Sjekk at favorite-valget ditt holder seg gjennom page reloads.

Fix for remembering favorite toggle

---

src/components/FormikField/FormikField.tsx
src/components/SlateEditor/plugins/link/EditLink.tsx
src/components/SlateEditor/plugins/link/Link.tsx
src/components/SlateEditor/plugins/link/LinkForm.tsx
src/components/SlateEditor/plugins/link/__tests__/EditLink-test.ts
src/components/SlateEditor/plugins/link/utils.ts
src/containers/App/SubjectMatterPage.tsx
src/util/routeHelpers.ts

Fixes https://github.com/NDLANO/Issues/issues/3053
Åssen sjekke:
1. Åpne en artikkel (enten learning-resource eller topic-article)
2. Sett inn lenke (dobbelttrykk på et ord og velg `link` fra context menyen)
3. Sjekk at lenker med locale f.eks `https://ed.ndla.no/nb/subject-matter/learning-resource/33243/edit/nn` blir formatert riktig -> `https://ed.test.ndla.no/subject-matter/learning-resource/33243/edit`.
eksempel på feil formatert lenke: `https://ed.ndla.no/subject-matter/learning-resource/learning-resource/edit`

3053 problemer med a lenke til andre artikler

---

src/containers/ArticlePage/components/ResourceTypeSelect.tsx
src/containers/StructurePage/resourceComponents/AddResourceModal.tsx
src/containers/StructurePageBeta/resourceComponents/AddResourceModal.tsx
src/containers/StructurePageBeta/resourceComponents/AllResourcesGroup.tsx
src/containers/StructurePageBeta/resourceComponents/ResourceGroup.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Endte opp med å skrive om `AddResourceModal`, da det skjedde mye rart der inne. Kunne sikkert lent meg mer på react-query, men da måtte jeg ha laget en ny `AsyncDropdown` for hooks. Det får eventuelt komme senere. Fant også ut av at `ResourceTypeSelect` ble brukt feil i `ResourceGroup` og `AllResourcesGroup`. Endte derfor opp med å endre litt på den også.
Sjekk at du kan legge til læringsstier og artikler både når ressurser er gruppert og ugruppert. Sjekk også at man kan legge til en artikkel ved å lime inn en gyldig lenke fra test.ndla.no

Added ability to add node resources in structure beta

---

src/containers/ArticlePage/articleTransformers.ts
src/util/formHelper.ts

Fixes NDLANO/Issues#3057
Fikk kontra på møte på tirsdag om at vi ikkje lenger skal gjøre dette.
Test:
* Ingress fra en språkversjon skal vises for nye språkversjoner som endå ikkje har ingress.

Reset ignoring introduction changes.

---

now.json

Oppdaterer deprecated pakke her også for å unngå at deploy feiler igjen

Update deprecated now package

---

src/containers/SearchPage/components/results/SearchConcept/ConceptForm.tsx
src/containers/SearchPage/components/results/SearchConcept/FormView.tsx

Fjerner forfatter fra inline form før frislipp av funksjonalitet.

Fjerner forfatter fra inlineform.

---

src/modules/taxonomy/resources/index.ts

Stringify body

---

src/containers/TaxonomyVersions/components/Version.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Er bare en lenke som lenker til `ndla.no?versionHash=abcd`

Added link for opening a specific taxonomy version on ndla.no

---

src/containers/StructurePageBeta/RootNode.tsx
src/containers/StructurePageBeta/folderComponents/subjectMenuOptions/ChangeNodeName.tsx
src/containers/StructurePageBeta/folderComponents/topicMenuOptions/GroupTopicResources.tsx
src/containers/StructurePageBeta/resourceComponents/AddResourceModal.tsx
src/containers/StructurePageBeta/resourceComponents/Resource.tsx
src/containers/StructurePageBeta/resourceComponents/ResourceItems.tsx
src/modules/nodes/nodeMutations.ts
src/modules/nodes/nodeQueries.ts

https://github.com/NDLANO/Issues/issues/3076
Kan testes ved å sjekke at all funksjonalitet i struktur-beta og node-diff fungerer som tiltenkt. Kan for eksempel gjøres ved å opprette en testversjon blunk blunk.

More rigid keys for nodes

---

src/containers/NdlaFilm/components/ThemeMovies.tsx
src/modules/frontpage/filmMutations.ts
src/modules/frontpage/filmQueries.ts

Query key functions for film queries

---

src/modules/draft/draftQueries.ts
src/modules/grep/grepQueries.ts
src/modules/search/searchQueries.ts
src/modules/taxonomy/subjects/subjectsQueries.ts

Fixes https://github.com/NDLANO/Issues/issues/3076
Småplukk.

Finishing touches for query key functions. Make all parameter objects partial and create key for grepCodes

---

src/containers/EditMarkupPage/EditMarkupPage.tsx

Fixes https://github.com/NDLANO/Issues/issues/3085
Det er lagt inn en liten feilmelding under HTML-skjemaet. Skal jeg fjerne den?

3085 Show validation error messages in an AlertModal in EditMarkupPage

---

src/components/SlateEditor/plugins/concept/ConceptModal.tsx
src/containers/ConceptPage/ConceptForm/ConceptForm.tsx

Fixes https://github.com/NDLANO/Issues/issues/3088
Hvordan teste: Lag en ny forklaring inline fra en eksisterende artikkel og lagre artikkelen. Den fullverdige forklaringen skal forbli.

Fixed adding a new concept from inside a form

---

src/config.ts
src/containers/App/App.tsx
src/containers/Masthead/components/NavigationMenu.tsx
src/containers/StructurePageBeta/StructureContainer.tsx
src/containers/StructurePageBeta/folderComponents/SettingsMenuDropdownType.tsx

Måtte endre måten denne var definert på grunn av at secrets i k8s er strenger.
Branch er deploya i prod.

Disable versioning

---

src/containers/StructurePage/resourceComponents/AllResourcesGroup.tsx
src/containers/StructurePageBeta/resourceComponents/AllResourcesGroup.tsx

Remove unused topic resources BEM class instances

---

src/containers/ImageEditor/ImageEditor.tsx

Removed unused BEM helper for image-editor

---

src/containers/ArticlePage/LearningResourcePage/components/LearningResourceContent.tsx
src/containers/ArticlePage/TopicArticlePage/components/TopicArticleContent.tsx

Fixes https://github.com/NDLANO/Issues/issues/3096

Add space-between for Byline in topic and learning resource forms

---

src/containers/NodeDiff/NodeDiff.tsx
src/containers/NodeDiff/NodeDiffContainer.tsx
src/containers/NodeDiff/diffUtils.ts
src/containers/PublishRequests/PublishRequestsContainer.tsx
src/containers/StructurePageBeta/StickyVersionSelector.tsx
src/containers/StructurePageBeta/folderComponents/sharedMenuOptions/RequestNodePublish.tsx
src/containers/TaxonomyVersions/TaxonomyVersionsPage.tsx
src/containers/TaxonomyVersions/components/Version.tsx
src/containers/TaxonomyVersions/components/VersionForm.tsx
src/modules/taxonomy/versions/versionApi.ts
src/modules/taxonomy/versions/versionApiTypes.ts
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Fixes https://github.com/NDLANO/Issues/issues/3101
Fixes https://github.com/NDLANO/Issues/issues/3094
Forklaring kommer.

Move node tree publish to Diff.

---

src/containers/NodeDiff/DiffOptions.tsx
src/containers/NodeDiff/NodeDiffContainer.tsx
src/containers/PublishRequests/PublishRequestsContainer.tsx
src/containers/StructurePageBeta/StickyVersionSelector.tsx
src/containers/TaxonomyVersions/TaxonomyVersionsPage.tsx
src/containers/TaxonomyVersions/components/Version.tsx
src/containers/TaxonomyVersions/components/VersionForm.tsx
src/modules/taxonomy/versions/versionApi.ts
src/modules/taxonomy/versions/versionMutations.ts
src/modules/taxonomy/versions/versionQueries.ts
src/util/apiHelpers.ts

Ignoreres, og trengs derfor ikke.

Remove version-hash parameter from version API calls

---

src/constants.ts

Add gapminder

---

src/components/Taxonomy/nodeStyles.tsx

Fixes https://github.com/NDLANO/Issues/issues/3126
Dette vil bare gjelde for struktur-beta. Hvis det skal fikses for vanlig struktur må vi endre frontend-packages.

Remove left-margin on itemTitleLinked

---

src/components/SlateEditor/plugins/aside/SlateFactAside.jsx
yarn.lock

Veldig straightforward. Brukes kun her, og har ingen korresponderende CSS.

Remove slate aside bem stuff. Not used

---

src/components/SlateEditor/plugins/embed/EditVideo.tsx
src/components/SlateEditor/plugins/embed/SlateFigure.tsx
src/components/SlateEditor/plugins/embed/SlateVideo.tsx
yarn.lock

Ser ut til å fungere som tidligere, men jeg tør ikke være sikker.

Use emotion instead of plain css for Slate figures

---

src/components/PreviewConcept/PreviewConcept.tsx

Fixes https://github.com/NDLANO/Issues/issues/3067?
Dropper 'bruk bildet'-knappen da det ser ut til å være litt arbeid å få den inn. Dekker denne alle krav?

Show alt text and license information when previewing concepts

---

src/components/ObjectSelector.tsx
src/containers/TaxonomyVersions/components/VersionSourceField.tsx

Fixes https://github.com/NDLANO/Issues/issues/3136
La inn noen keys i ObjectSelector for å slippe unna noen warnings også.

Add optgroup separation for taxonomy version source ID field

---

src/components/DisplayEmbed/__tests__/__snapshots__/DisplayExternal-test.jsx.snap
src/components/Overlay.tsx
src/components/SlateEditor/plugins/embed/EditAudio.tsx
src/components/SlateEditor/plugins/embed/EditVideo.tsx
src/components/SlateEditor/plugins/embed/FigureButtons.tsx
src/components/SlateEditor/plugins/embed/SlateImage.tsx
src/components/SlateEditor/plugins/embed/SlateVideo.tsx
src/components/SlateEditor/plugins/related/__tests__/__snapshots__/RelatedArticleBox-test.tsx.snap
src/containers/StructurePage/__tests__/__snapshots__/AddResourceModal-test.tsx.snap
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Closes https://github.com/NDLANO/Issues/issues/3130
Kan sammenignes med: https://ed.test.ndla.no/subject-matter/learning-resource/10239/edit/nb dersom man går inn i redigeringsmodus på videoen eller et bilde.

Prevent editing of text when editing video

---

src/containers/FormikForm/AddRevisionDateField.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Closes https://github.com/NDLANO/Issues/issues/3152

Add message to republish article when marked as revised

---

src/components/MetaInformation.tsx
src/components/SlateEditor/plugins/blockPicker/SlateVisualElementPicker.tsx
src/containers/ConceptPage/components/InlineImageSearch.tsx
src/containers/FormikForm/MetaImageSearch.tsx
src/containers/FormikForm/components/MetaImageField.tsx
src/containers/Podcast/components/PodcastForm.tsx

Closes https://github.com/NDLANO/Issues/issues/3128
Kan sjekkes ved å gå til https://ed.test.ndla.no/concept/2494/edit/nb og bytte metabilde.

Reset alt-text when switching meta image

---

src/containers/ArticlePage/LearningResourcePage/components/LearningResourcePanels.tsx
src/containers/ArticlePage/TopicArticlePage/components/TopicArticleAccordionPanels.tsx
src/containers/ArticlePage/components/RevisionNotes.tsx
src/containers/FormikForm/articleFormHooks.ts
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts
src/util/formHelper.ts

Closes https://github.com/NDLANO/Issues/issues/3148
Kan sjekkes ved å opprette en ny læringsressurs og se at det kreves å fylle inn revisjonsdato.

Make revision mandatory when creating articles

---

src/components/SlateEditor/plugins/conceptList/ConceptTagPicker.tsx

Closes https://github.com/NDLANO/Issues/issues/3157

Add sorting to fetched tags

---

src/containers/VisualElement/VisualElementUrlPreview.tsx

Legger på sjekk slik at ny visning av ressurs fra lenke kan fases inn gradvis.

Hide fullscreen checkbox for other than admin

---

src/components/SlateEditor/plugins/blockPicker/actions.tsx

Release fra denne branch er deploya til staging.

Make concept-list admin-only

---

package.json
yarn.lock

Fixes NDLANO/Issues#3173
Laget PR asap bare for å få PR-instans så fort som mulig

Update ndla editor. Fixing checkbox toggling in file editor

---

src/containers/ArticlePage/LearningResourcePage/components/LearningResourceTaxonomy.tsx
src/modules/taxonomy/taxonomyApiInterfaces.ts

Mikroendring tilsvarende https://github.com/NDLANO/graphql-api/pull/256

Rename parentTopics to parents.

---

src/components/SlateEditor/plugins/span/LanguageSelector.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Add es language code for word encoding.

---

cypress/integration/Editor/slate_block_picker_spec.js
package.json
src/components/ControlledImageSearchAndUploader.tsx
src/components/ImageSearchAndUploader.tsx
src/modules/image/imageApiInterfaces.ts
yarn.lock

Gjør at du kan søke opp bilder for innsetting i artikkel og få korrekt forhåndsvisning.
Test:
* I artikkel med nb og nn versjoner
* Sett inn bilde 54559 i begge versjonene og sjå at forhåndsvisninga og innsatt bilde er likt.

Bruker språk + fallback ved søk etter bilder.

---

src/components/HeaderWithLanguage/HeaderStatusInformation.tsx
src/containers/SearchPage/components/results/SearchListOptions.tsx

Fixes NDLANO/Issues#3196 and Fixes NDLANO/Issues#3183
Endrer antall treff. Lenker til /article i publisert ikon
Test:
* Sjekk at søketreff-sida endres i henhold til bytte av antall treff.
* Sjekk at url til publisert artikkel er /article

Changing number of hits

---

src/components/SlateEditor/plugins/embed/EditImage.tsx
src/components/SlateEditor/plugins/embed/SlateImage.tsx
src/constants.ts
src/containers/ImageEditor/ImageCropEdit.tsx
src/containers/ImageEditor/ImageEditor.tsx
src/containers/ImageEditor/ImageFocalPointEdit.tsx
src/containers/ImageEditor/ImageTransformEditor.tsx
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts
src/server/contentSecurityPolicy.ts

NDLANO/Issues#3171
Slik det er no så brukes nb-bildet for redigering av bilde sjølv om nn versjonen er satt i artikkelen. 
Test:
* Sett inn bilde 54559 i nb og nn artikkel.
* Forsøk å redigere bildet, både vanlig men også ved å sette utsnitt og fokalpunkt. 
* Sjekk at samme bildet brukes over alt. Sammenlign med oppførsel i test.

Legger til language som parameter for bilderedigering.

---

src/components/DisplayEmbed/DisplayExternal.tsx
src/containers/VisualElement/VisualElementUrlPreview.tsx

NDLANO/Issues#3195
Legger til støtte for fullskjerm på external-embed.
Test:
* Sjekk at du får redigert feks ted-embeds og satt metabilde, tittel og innhold. Lagring fungerer ikkje enda, men kjem i egen pr.

Legger til støtte for fullscreen.

---

src/containers/TaxonomyVersions/TaxonomyVersionsPage.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Fixes https://github.com/NDLANO/Issues/issues/3202

Add title to taxonomy versions page

---

src/containers/NodeDiff/NodeDiffContainer.tsx
src/containers/StructurePageBeta/resourceComponents/Resource.tsx

Fixes https://github.com/NDLANO/Issues/issues/3203

Default to default version instead of originalHash

---

src/containers/StructurePageBeta/NodeItem.tsx
src/containers/StructurePageBeta/RootNode.tsx
src/containers/StructurePageBeta/StickyVersionSelector.tsx
src/containers/StructurePageBeta/StructureContainer.tsx
src/containers/StructurePageBeta/resourceComponents/StructureResources.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Fixes https://github.com/NDLANO/Issues/issues/3201
Det oppsto tidligere en race-condition mellom kall med den gamle taksonomiversjonen og den nye. Nå fjerner vi alle queries som ligger inne med den gamle taksonomiversjonen.

3201 ungrouped tas ikkje hensyn til i strukturbeta

---

src/components/SlateEditor/plugins/mathml/MathEditor.tsx
src/components/SlateEditor/plugins/mathml/MathML.tsx

Fixes https://github.com/NDLANO/Issues/issues/3189

Double click to open Math Editor

---

src/util/searchHelpers.ts

Fixes https://github.com/NDLANO/Issues/issues/3207
Kan testes ved å lagre et søk med meg som bruker!

Escape users ID search

---

src/containers/StructurePageBeta/folderComponents/SettingsMenuDropdownType.tsx
src/containers/StructurePageBeta/folderComponents/sharedMenuOptions/components/NodeSearchDropdown.tsx
src/containers/StructurePageBeta/folderComponents/sharedMenuOptions/components/SearchDropdown.tsx
src/containers/StructurePageBeta/folderComponents/topicMenuOptions/SwapTopicArticle.tsx
src/containers/StructurePageBeta/folderComponents/topicMenuOptions/SwapTopicResource.tsx
src/interfaces.ts
src/modules/nodes/nodeApi.ts
src/modules/nodes/nodeMutations.ts
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Fixes https://github.com/NDLANO/Issues/issues/2948

Add the ability to swap out a topic resource for another

---

src/components/H5PElement/__tests__/h5pApi-test.ts
src/components/H5PElement/h5pApi.ts
src/containers/VisualElement/VisualElementSearch.tsx

Legg til sending av fleire språkkoder til h5p api.

Send more language codes to h5p

---

src/containers/StructurePage/NodeItem.tsx
src/containers/StructurePage/folderComponents/topicMenuOptions/SwapTopicArticle.tsx
src/modules/draft/draftApi.ts

Fixes https://github.com/NDLANO/Issues/issues/3248

Update selected node when switching topic articles

---

src/components/HeaderWithLanguage/HeaderActions.tsx
src/components/HeaderWithLanguage/SimpleLanguageHeader.tsx
src/components/SlateEditor/plugins/span/LanguageSelector.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts
src/util/resourceHelpers.ts

Fixes NDLANO/Issues#3262
Legger til tysk og spansk som mulige språk for innhold. Legger til nn og nb som mulige markeringer av ord.

Added de and es to languages.

---

src/containers/NodeDiff/DiffOptions.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Gir hint til bruker om at emnet er oppdatert i bakgrunnen.
Test:
* Finn et emne i struktur og bytt emneartikkel. Sjekk at melding inkluderer hint om å laste på nytt. 
* Last sida på nytt og sjekk at nytt navn er på plass.

Update messages after updating topic article.

---

src/containers/StructurePage/NodeItem.tsx
src/containers/StructurePage/StructureContainer.tsx
src/containers/StructurePage/folderComponents/StructureErrorIcon.tsx
src/modules/nodes/nodeQueries.ts
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

NDLANO/Issues#3275 
Sikkert litt hacky, men viser advarsel til bruker om at emnet ikkje er publisert.
Test:
* /structure/urn:subject:846c7a59-c870-4aa3-a68d-633300e6669c har emner uten publisert emneartikkel.

Vis alert-ikon dersom artikkel ikkje er publisert.

---

src/containers/EditSubjectFrontpage/components/SubjectpageForm.tsx
src/util/subjectHelpers.ts

NDLANO/Issues#3272
Endrer du tittel på fagforside, så endres også navnet som vises i toppen.

Oppdaterer name med title for fagforsider.

---

src/modules/draft/draftApi.ts
src/modules/nodes/nodeQueries.ts

…in one subject?
Bruker nytt ids endepunkt i draft-api.

Use fetchDrafts-function. 

---

src/components/Taxonomy/ActiveTopicConnection.tsx

Lar alle sette primærkobling for ressurser.

Enable primary connection for all users

---

package.json
yarn.lock

Fikser https://github.com/NDLANO/editorial-frontend/security/dependabot/77
En senere versjon brukes indirekte av en annen dep, men den brukes aldri av oss.

Remove unused and vulnerable wait-on dep

---

package.json
razzle.config.js
src/server/server.tsx
yarn.lock

Samme som ble gjort her https://github.com/NDLANO/ndla-frontend/pull/1193
La inn to type assertions for å unngå TS-feil i server.ts
Fikser https://github.com/NDLANO/editorial-frontend/security/dependabot/38
Fikser https://github.com/NDLANO/editorial-frontend/security/dependabot/39
Fikser https://github.com/NDLANO/editorial-frontend/security/dependabot/17
Fikser https://github.com/NDLANO/editorial-frontend/security/dependabot/42
Fikser https://github.com/NDLANO/editorial-frontend/security/dependabot/58
Fikser https://github.com/NDLANO/editorial-frontend/security/dependabot/59
Fikser https://github.com/NDLANO/editorial-frontend/security/dependabot/57

Bump webpack-dev-server to most recent version

---

Dockerfile

Fikser https://github.com/NDLANO/Issues/issues/3337

Removes pm2 from Dockerfile

---

package.json
yarn.lock

I bunn og grunn en deduplicate.

Bump react-focus-trap to remove peer dep warning

---

src/constants.ts
src/server/contentSecurityPolicy.ts

https://github.com/NDLANO/Issues/issues/3363
La til støtte for jeopardylabs url'er i ressurs fra link

Added jeopardylabs support for links

---

src/components/SlateEditor/plugins/link/__tests__/serializer-test.ts
src/components/SlateEditor/plugins/link/index.tsx

Depends on https://github.com/NDLANO/backend/pull/156
Kan testes ved å se at lenke oppretting (og redigering) funker som forventet :^)

Support ndlaembed content-link children

---

src/config.ts
src/server/contentSecurityPolicy.ts

La merke til at zendesk-auth feila, samt et par cors feil i prodlogger.

Fix zendesk auth error

---

src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Gjør beskrivelse av publisering litt tydeligere.

Change phrasing for publishing

---

src/modules/draft/draftApi.ts

Deploya fra branch til staging.

Hotfix: Add fallback to ids

---

src/components/HeaderWithLanguage/HeaderActions.tsx
src/containers/ImageUploader/EditImage.tsx
src/containers/PodcastSeries/EditPodcastSeries.tsx

Fixes https://github.com/NDLANO/Issues/issues/3411

Add translate to nn for image and podcast series

---

src/constants.ts
src/containers/PublishRequests/PublishRequestsContainer.tsx

Fixes NDLANO/Issues#3413
Legger på spinner for å vise at en publisering er starta.

Viser spinner for publiseringsforespørsler som er starta

---

src/containers/NodeDiff/NodeDiffContainer.tsx
src/containers/NodeDiff/TreeNode.tsx

Fixes https://trello.com/c/Ed89GawV/111-sammenligning-av-nodetr%C3%A6r-tar-ikkje-nok-hensyn-til-kun-ressurser

Account for resourcesChanged diff on root node for tree view

---

src/containers/ImageUploader/components/ImageForm.tsx

Fixes NDLANO/Issues#3377
Fjerner krav om billedtekst.

Fjerner krav om billedtekst i bildeskjema

---

cypress/e2e/Search/search_concept_spec.js

Added query paramteres to url in search

---

src/components/PreviewConcept/PreviewConcept.tsx
src/components/PreviewDraft/PreviewLightboxContent.tsx

Fixes https://github.com/NDLANO/Issues/issues/3357
Prøvde å gå over til `ConceptNotion`, men det er en vanskelig komponent og ble altfor mye jobb.

Fix svg sizing in preview concept

---

src/containers/NodeDiff/NodeDiff.tsx
src/containers/NodeDiff/__tests__/diffTestData.ts
src/containers/NodeDiff/diffUtils.ts
src/modules/nodes/nodeApi.ts
src/modules/nodes/nodeApiTypes.ts
src/modules/nodes/nodeMutations.ts
src/modules/nodes/nodeQueries.ts

Depends on https://github.com/NDLANO/taxonomy-api/pull/170
Er ikke tusen-prosent sikker på alle stedene som må fikses, men her er et forslag som ser ut til å fungere lokalt :shrug:

Handle resources as nodes in structure

---

src/components/NodeIconType.tsx
src/containers/StructurePage/AddSubjectModal.tsx
src/containers/StructurePage/folderComponents/topicMenuOptions/SwapTopicArticle.tsx
src/modules/nodes/nodeApi.ts
src/modules/nodes/nodeApiTypes.ts
src/modules/nodes/nodeQueries.ts

Bedre variant av #1673.
Endringer i ressurser skal vises i diffvisning.

Resources are missing in diff view after tax changes.

---

src/containers/PublishRequests/PublishRequestsContainer.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

fixes https://github.com/NDLANO/Issues/issues/3438

Added breadcrumb,  safelink button, and request counter

---

src/constants.ts
src/containers/NdlaFilm/components/ThemeEditor.tsx
src/containers/NdlaFilm/components/ThemeNameModal.tsx
src/containers/StructurePage/folderComponents/subjectMenuOptions/ChangeNodeName.tsx
src/i18n2.ts

Legger til støtte for samiske språkkoder for fagnavn.

Legger til støtte for fagnavn på sør og nordsamisk

---

src/components/FormWrapper.tsx
src/constants.ts
src/containers/Masthead/components/NavigationMenu.tsx
src/containers/PodcastSeries/components/PodcastSeriesForm.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Fixes https://github.com/NDLANO/Issues/issues/3334
Trenger vi å vise frem en feilmelding?

Disable podcast series creation and editing when not admin

---

src/components/SlateEditor/EditorFooter.tsx
src/containers/PublishRequests/PublishRequestsContainer.tsx

Sjekk at du kan sette artikkel til sletta uten å måtte sette ansvarlig.

Treng ikkje ansvarlig for status sletta.

---

src/components/AlertModal/AlertModal.tsx
src/components/HeaderWithLanguage/DeleteLanguageVersion.tsx
src/components/SlateEditor/plugins/codeBlock/EditCodeBlockModal.tsx
src/components/SlateEditor/plugins/mathml/EditMathModal.jsx
src/containers/FormikForm/AlertModalWrapper.tsx
src/containers/Messages/Messages.tsx
src/containers/Messages/__tests__/Messages-test.tsx
src/containers/Messages/__tests__/__snapshots__/Messages-test.tsx.snap
src/containers/Messages/__tests__/useMessages-test.tsx
src/containers/NodeDiff/NodeDiffContainer.tsx
src/containers/StructurePage/folderComponents/sharedMenuOptions/CopyRevisionDate.tsx
src/containers/StructurePage/folderComponents/sharedMenuOptions/DeleteNode.tsx
src/containers/StructurePage/folderComponents/topicMenuOptions/CopyNodeResources.tsx
src/containers/StructurePage/folderComponents/topicMenuOptions/PublishChildNodeResources.tsx
src/containers/StructurePage/folderComponents/topicMenuOptions/SetResourcesPrimary.tsx
src/containers/StructurePage/resourceComponents/AddResourceModal.tsx
src/containers/StructurePage/resourceComponents/ResourceItems.tsx
src/containers/TaxonomyVersions/components/Version.tsx
src/containers/TaxonomyVersions/components/VersionForm.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Fixes https://github.com/NDLANO/Issues/issues/3468
En lite skritt på vei til å fjerne Lightbox. Er en del snapshot-endringer, men annet enn det skal dette være ganske straight-forward.

Use Modal instead of Lightbox for Alert modals

---

src/components/SlateEditor/plugins/footnote/EditFootnote.tsx
src/components/SlateEditor/plugins/footnote/Footnote.tsx

Kan f.eks testes med http://localhost:3000/subject-matter/learning-resource/31293/edit/nb

Convert footnote form to Modal V2

---

src/containers/WelcomePage/components/LastUsedItems.tsx

Hvis man går rett til ed.test.ndla.no står det at "sist redigert"-lista er tom. Den dukker først opp hvis du går til en annen side, for så å gå tilbake til forsiden. Forenkler også koden litt mens jeg er i gang.

Fix bug where last edited does not appear on first render

---

src/containers/WelcomePage/components/SaveSearchUrl.tsx

Fixes https://github.com/NDLANO/Issues/issues/3470

Remove add search on welcome page

---

src/containers/StructurePage/NodeItem.tsx
src/containers/StructurePage/RootNode.tsx
src/containers/StructurePage/StructureContainer.tsx
src/containers/StructurePage/folderComponents/FolderItem.tsx
src/containers/StructurePage/folderComponents/SettingsMenu.tsx
src/containers/StructurePage/folderComponents/SettingsMenuDropdownType.tsx

Remove unused structure prop

---

src/containers/StructurePage/RootNode.tsx

fixes https://github.com/NDLANO/Issues/issues/3478
Kan testes ved å sjekke at DND ikke lenger returnerer 400 for emner i tax

Fix DND in tax for subjects

---

src/components/SlateEditor/plugins/blockPicker/SlateBlockPicker.tsx

Fixes https://github.com/NDLANO/Issues/issues/3383
Mitt første slate-issue!

Fix issue where you type backwards after closing block picker with ESC

---

src/containers/TaxonomyVersions/TaxonomyVersionsPage.tsx
src/containers/TaxonomyVersions/components/DeletePublishRequests.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Fixes https://trello.com/c/tZA2p6QB/88-valg-for-%C3%A5-slette-alle-publiseringsforesp%C3%B8rsler

Add option to delete all publish requests

---

src/containers/WelcomePage/components/worklist/ConceptListTabContent.tsx
src/containers/WelcomePage/components/worklist/WorkList.tsx
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Litt småfikser til arbeidsliste:
- Øker antall som fetches til 100
- Oppdaterer tittel i tabs-tittel
- Oppdaterer count som vises til å hentes fra totalCount felt

Work list fixes

---

src/containers/SearchPage/components/form/GenericSearchForm.tsx

Fixes NDLANO/Issues#3490
Test:
* Skriv noe i søkefelt og trykk på enter. Teksten skal ikkje slettes.

Setter submit på riktig knapp for at ikkje form skal tømmes

---

src/containers/WelcomePage/WelcomePage.tsx
src/containers/WelcomePage/components/worklist/ConceptListTabContent.tsx
src/containers/WelcomePage/components/worklist/SubjectDropdown.tsx
src/containers/WelcomePage/components/worklist/WorkList.tsx
src/containers/WelcomePage/components/worklist/WorkListTabContent.tsx

fixes https://github.com/orgs/NDLANO/projects/2/views/9?pane=issue&itemId=22864092
Oppdatert for både artikler og forklaringer i arbeidsliste

Remove favorite subjects from dropdown in worklist

---

src/components/Taxonomy/OptGroupVersionSelector.tsx
src/containers/PublishRequests/PublishRequestsContainer.tsx
src/containers/TaxonomyVersions/components/VersionForm.tsx
src/modules/taxonomy/versions/versionApiTypes.ts
src/phrases/phrases-en.ts
src/phrases/phrases-nb.ts
src/phrases/phrases-nn.ts

Fixes NDLANO/Issues#3502
Plukker enten nyeste beta eller publisert versjon for diffvisning. Derom ingen av disse finnes, brukes første i lista.

Bruker nyeste oppretta betaversjon som utgangspunkt for diff

---

src/config.ts
src/util/apiHelpers.ts

Fjerner gamle ubrukte verdier.

---

src/containers/PublishRequests/PublishRequestsContainer.tsx
src/containers/WelcomePage/components/worklist/ConceptListTabContent.tsx

fixes https://github.com/NDLANO/Issues/issues/3504

Add language to searchNodes concepts worklist

---

src/components/SlateEditor/EditorFooter.tsx
src/containers/ConceptPage/ConceptForm/ConceptForm.tsx
src/containers/ConceptPage/conceptTransformers.ts

fixes https://trello.com/c/Hy0yuu90/38-automatisk-sette-seg-selv-som-default-ansvarlig-n%C3%A5r-man-oppretter-ny-ressurs
Testes ved å sjekke at du selv settes som default ansvarlig når man oppretter ressurs

Set current user as default responsible on new article/concept

---

src/components/SlateEditor/EditorFooter.tsx
src/containers/FormikForm/components/ResponsibleSelect.tsx
src/containers/PublishRequests/PublishRequestsContainer.tsx

fixes https://trello.com/c/sUJETQgF/39-ikke-nullstill-ansvarlig-n%C3%A5r-status-endres
Nullstiller nå kun ansvarlig når status endres til PUBLISHED

Only reset responsible when status changes to PUBLISHED

---

src/components/SlateEditor/plugins/embed/utils.ts

Iframe-embeds vises ikkje i editor i prod. Dette fikser det. Lager release av denne og deployer til staging.

Add iframe to check.

---

src/containers/StructurePage/StructureContainer.tsx

fixes https://github.com/NDLANO/Issues/issues/3513

Fix scroll into view bug in taxonomy when navigating from article

---

package.json
yarn.lock

Fixes https://github.com/NDLANO/editorial-frontend/security/dependabot/97

Bump start-server-and-test

---

src/containers/Messages/MessagesProvider.tsx
src/util/authHelpers.ts

Fixes https://github.com/NDLANO/Issues/issues/3479
Ble endelig logget ut av Auth0, så nå hadde jeg muligheten til å fikse den. Dette vil ikke fikse det overordnede problemet, men det fikser problemet for akkurat innlogging. Vi har ikke en måte å skape deterministiske ID'er på, så legger inn en hardkodet ID for akkurat dette. Hvis vi er avhengige av unike ID'er i loggly vil dette ikke funke.

Fix duplicate auth0 login error modals

---

src/containers/WelcomePage/components/LastUsedItems.tsx
src/containers/WelcomePage/components/Revisions.tsx
src/containers/WelcomePage/components/worklist/WorkList.tsx
src/modules/draft/draftApi.ts

Oppdateringer med language-parameter i requests på dashboard
- Legger til på en del requests sånn at vi får oversetting på feks fag

Dashboard: updates language parameter

---

package.json
src/modules/article/articleGqlQueries.ts
yarn.lock

Brukes bare ett sted, og ser ut til å funke greit der.

Bump graphql-request. Fix types after bump

---

src/containers/WelcomePage/components/Revisions.tsx

- Fjerner publisert markering i revisjons-blokk
- Snur default sortering

Updates revision-block
